Article : retour sur les journées R d'Avignon
geotribu/website pull request #1001
Opened 2023-10-26 10:38 UTC by KazeNoOni

2023-10-29 19:56 UTC, Guts commented
Allez go @geotribu/relecture !

:information_source: **Aux relecteur/ices**

Merci d'utiliser autant que possible le mode Suggestion de la review : https://docs.github.com/fr/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request#starting-a-review

![image](https://github.com/geotribu/website/assets/1596222/4d081e97-7290-48c4-b1ff-587a8920b508)

2023-11-10 10:00 UTC, Guts requested changes
Il ne reste qu'à changer la date cf suggestions dans le texte.

Pour renommer le fichier : https://github.com/KazeNoOni/website_geotribu/edit/article/Retour_R_Avignon/content/articles/2023/2023-11-03_retour-conference-journees-R-2023.md?pr=%2Fgeotribu%2Fwebsite%2Fpull%2F1001

![image](https://github.com/geotribu/website/assets/1596222/1891d925-c1ba-4538-a3af-33fe842d1a87)

2023-11-10 10:00 UTC, Guts commented on content/articles/2023/2023-11-03_retour-conference-journees-R-2023.md
> +date: "2023-11-3 10:30"
```suggestion
date: "2023-11-10 14:30"
```

2023-11-10 10:00 UTC, Guts commented on content/articles/2023/2023-11-03_retour-conference-journees-R-2023.md
> +:calendar: Date de publication initiale : 3 novembre 2023
```suggestion
:calendar: Date de publication initiale : 10 novembre 2023
```

2023-11-10 15:33 UTC, merged

2023-11-10 22:10 UTC, Michael-cd30 commented on content/articles/2023/2023-11-10_retour-conference-journees-R-2023.md
> +Ingénieure agronome, elle a été recrutée au CNRS après sa thèse en écologie/statistiques, notamment grâce à ses compétences en R. Son travail au quotidien s'articule autour du soutien à la recherche
Faut-il considérer "doctorant" comme un adjectif de public ? Ne serait-il pas mieux d'écrire d'un public de doctorants tRaumatisés ?

2023-11-10 22:10 UTC, Michael-cd30 commented on content/articles/2023/2023-11-10_retour-conference-journees-R-2023.md
> +C'est de cette expérience de terrain qu'est né son [blog Ratique](https://perso.ens-lyon.fr/lise.vaudor/) et la création de contenus visant à démocratiser R. Un contenu qu'elle a voulu illustré, avec
antisècheS

2023-11-10 22:10 UTC, Michael-cd30 commented on content/articles/2023/2023-11-10_retour-conference-journees-R-2023.md
> +L'engagement était aussi écologique : les goodies venaient des environs. La bière, brassée spécialement pour l'occasion, était locale, tout comme le jus de fruit. Nous avions de la verrerie aux coule
fruitS

2023-11-10 22:10 UTC, Michael-cd30 commented on content/articles/2023/2023-11-10_retour-conference-journees-R-2023.md
> +L'engagement était aussi écologique : les goodies venaient des environs. La bière, brassée spécialement pour l'occasion, était locale, tout comme le jus de fruit. Nous avions de la verrerie aux coule
je suppose "les informations pratiques" et non "les informatiques pratiques"

2023-11-24 15:14 UTC, Guts commented
Diffusé sur Mastodon : https://mapstodon.space/deck/@geotribu/111466171153182352

2023-11-24 15:46 UTC, Guts commented
Diffusé sur Twitter https://twitter.com/geotribu/status/1728077671731499163