Ajout de l'article DuckDB et les données spatiales
geotribu/website pull request #1016
Opened 2023-12-04 20:14 UTC by florentfgrs

# Amorcer une nouvelle revue de presse

- [ ] nommer cette _Pull Request_ de façon claire et lisible. Exemple : `GeoRDP du JJ MM AAAA`
- [ ] partir du modèle disponible (copier/coller) [sur Github](https://github.com/geotribu/website/blob/master/content/rdp/templates/template_rdp.md?plain=1) ou [sur le pad](https://geotripad.herokuapp.com/DCBQirjYSp6sqxPd5JYqLg?both)
- [ ] changer la date dans les métadonnées :
    - [ ] `date` : au format `AAAA-MM-JJ HH-MM` - mais laisser l'heure sur 14h20 c'est historique
    - [ ] `title` : correspond à ce qui est affiché dans le menu de navigation, l'onglet du navigateur et le SEO. Bien **indiquer l'année** pour améliorer le référencement et en prévision d'une refonte du moteur de rendu.
- [ ] changer la date du titre principal (en début de contenu). Idem, **indiquer l'année**.

## Encourager les contributions

- [ ] informer l'équipe que la prochaine RDP a été initiée en publiant le lien de la PR sur [le canal `#revues-de-presse` de Slack](https://geotribu.slack.com/archives/C010DD7FMEX)
- [ ] tweeter le lien du fichier de la RDP. Voici ci-dessous un modèle dans lequel :

- remplacer `XXXXXXXXXX` par le lien vers le fichier de la GeoRDP dans la branche créée (par exemple : <https://github.com/geotribu/website/blob/rdp/2021-02-26/content/rdp/2021/rdp_2021-02-26.md?plain=1>)
- insérer cette image dans le tweet <https://cdn.geotribu.fr/img/internal/contribution/geotribu_contribuer_rdp_github_edit.png>

```txt
Ce vendredi c'est #GeoRDP !

💡 Une idée de news ? Une envie de parler de #carte ? d'outil #SIG ? de relayer un article, un tutoriel  sur la #géographie ou la #géomatique ?

C'est par ici 👉 XXXXXXXXXX 👈
(icône 🖍️)

Modèle de news ici : https://github.com/geotribu/website/blob/master/content/rdp/templates/template_rdp_news.md
```

Exemple de [tweet](https://twitter.com/geotribu/status/1364625815099613185) :

![tweet geordp](https://cdn.geotribu.fr/img/internal/contribution/geotribu_rdp_tweet_incitation.png)

----

## Check-list de publication

### Qualité

- [ ] les news sont bien réparties dans les bonnes sections
- [ ] les sections vides sont supprimées
- [ ] vérifier le rendu de la syntaxe markdown (cf. linter)
- [ ] chasse aux coquilles orthographiques et dyslexiques

### Images

- [ ] les images téléversées sur le CDN n'ont pas de caractère spécial dans leur nom de fichier (espace, accent, etc.) et n'excédent pas 1000px de largeur
- [ ] les images sont hébergées sur des sites sécurisés (HTTPS)
- [ ] chaque news a une vignette
- [ ] les images (sauf les vignettes) ont l'attribut `loading` défini sur `lazy` (cf. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading) et [guide material-mkdocs](https://squidfunk.github.io/mkdocs-material/reference/images/#image-lazy-loading))
- [ ] accessibilité : chaque image a un texte de remplacement (entre les crochets) et un titre lisible par les outils d'assistance. Bref, qui respecte la [syntaxe générale](https://contribuer.geotribu.fr/guides/image/#syntaxe-generale)

### SEO

- [ ] `image` pointe vers l'URL d'une des images de la revue de presse
- [ ] `description` contient les mots-clés et grandes lignes du contenu (par exemple, la reprise de l'intro)

----

## Publier

1. S'assurer que la branche soit à jour par rapport à la branche principale. Le cas échéant, utiliser le bouton `Update branch` en bas.
2. S'assurer que les éléments de la check-list ci-dessus soient tous remplis
3. Fusionner (_merge_) en utilisant un _merge commit_ ou un _rebase_, mais **surtout pas un squash**.

----

## Diffuser

### Twitter

Une fois le déploiement effectué (~ 5 minutes), diffuser a minima sur Twitter :

- avec le hashtag `#GeoRDP`, en citant les contributeur/ices avec leur éventuel compte
- si possible en intégrant quelques hastags des personne, organisations ou logiciels cités dans la revue de presse
- de préférence via le compte `@geotribu` en utilisant Tweetdeck.

### LinkedIn

La diffusion sur LinkedIn est à faire avec un compte personnel. Exemple de structure :

```txt
🗞 La #GeoRDP est en ligne :

👥 Contributeur/ices : @XXXX

🌍 #Geotribu #veille #géomatique #YYYY @ZZZZ
```

2023-12-04 21:24 UTC, Guts commented
Salut @florentfgrs et merci pour la proposition d'article 🙏 !

J'ai intégré le message automatique à la description de cette PR avec différentes informations à lire attentivement et à remplir. Merci !

Il y a par contre au moins 2 éléments bloquants avant de lancer la relecture :

- il manque le fichier auteur
- il y a des liens mal formatés ou cassés dans ton contenu (comme celui-ci https://github.com/geotribu/website/blob/35a71f72ccb4e7f4933524a0d4e833e848454ab3/content/articles/2023/2023-12-04_duckdb-donnees-spatiales.md?plain=1#L83 signalé par les contrôles automatisés)

## 👓 Relecture

Pour la relecture, nous la réalisons de préférence via [le mode Review de GitHub](https://docs.github.com/fr/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews).

Si tu n'es pas à l'aise avec ce mode de travail, ne pas hésiter à nous le dire, soit pour former rapidement, accompagner ou trouver un autre moyen.

A noter que nous nous permettons de modifier directement ce qui est de l'ordre des règles de contribution (syntaxe Markdown, images, etc.), sans jamais toucher au fond (formulation, structure de l'article, etc.) sans commentaire.

## Ressources

Pour info, voici quelques extraits de notre guide de contribution :

- [comprendre et compléter l'en-tête](https://contribuer.geotribu.fr/guides/metadata_yaml_frontmatter/)
- [intégrer une image](https://contribuer.geotribu.fr/guides/image/)
- [choisir une licence](https://contribuer.geotribu.fr/guides/licensing/)
- [signer un article](https://contribuer.geotribu.fr/guides/authoring/)

2023-12-06 13:27 UTC, Guts commented
Super, ça a levé les points bloquants et la preview est donc générée.

Rapidement, avant que je fasse une passe complète, il y a des soucis de syntaxe au moins sur  les blocs de code : 

![image](https://github.com/geotribu/website/assets/1596222/94aef4ad-e425-41c0-a198-8b3d25f7cb48)

A moins que ce soit le rendu attendu ?

De même, il y a bcp de commentaires Markdown pour désactiver/réactiver le linter Markdown (https://contribuer.geotribu.fr/internal/markdown_linter/#gerer-les-faux-positifs-du-linter) mais qui semblent inutiles non ?

2023-12-06 13:34 UTC, Guts requested changes

2023-12-06 13:34 UTC, Guts commented on content/articles/2023/2023-12-06_duckdb-donnees-spatiales.md
> +
Pour rester cohérent avec les autres contenus, on met le bouton des commentaires à la fin du paragraphe d'intro

```suggestion
![logo DuckDB](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/duckdb_spatial/DuckDB_Logo.png){: .img-thumbnail-left }

Si depuis quelques semaines, vous voyez passer beaucoup de chose sur des sujets comme DuckDB, les fichiers parquet ou encore les données d’Ouverture Maps, mais sans trop comprendre de quoi il s’agit, vous êtes au bon endroit !

[Commenter cet article :fontawesome-solid-comments:](#__comments){: .md-button }
{: align=middle }
```

2023-12-06 13:34 UTC, Guts commented on content/articles/2023/2023-12-06_duckdb-donnees-spatiales.md
> +```
````suggestion
```sh
````

2023-12-06 13:34 UTC, Guts commented on content/articles/2023/2023-12-06_duckdb-donnees-spatiales.md
> +D
?

2023-12-06 13:35 UTC, Guts commented on content/articles/2023/2023-12-06_duckdb-donnees-spatiales.md
> +date: "2023-12-06 14:20"
Penser à changer également en ligne 24 et dans le nom du fichier.

Le mardi 19 semble raisonnable

2023-12-08 07:02 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +```
````suggestion
=== ":snake: Python”

    ```python
    con.sql("INSTALL spatial; LOAD spatial ; LOAD httpfs ;")
    ```

=== "▶️ CLI”

    ```sh
    D INSTALL spatial ;
    D LOAD spatial ;
    D LOAD httpfs ;
    ```
````

2023-12-08 07:11 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +```
Correction syntaxe

````suggestion
=== ":snake: Python”

    ```python
    con.sql("CREATE TABLE airports AS FROM read_csv_auto('[https://davidmegginson.github.io/ourairports-data/airports.csv](https://davidmegginson.github.io/ourairports-data/airports.csv)', HEADER=True, DELIM=',') ;")
    con.sql("ALTER TABLE airports ADD COLUMN the_geom GEOMETRY ;")
    con.sql("UPDATE airports SET the_geom = ST_POINT(longitude_deg, latitude_deg) ;")
    ```

=== "▶ CLI”

    ```sh
    D CREATE TABLE airports AS FROM read_csv_auto('[https://davidmegginson.github.io/ourairports-data/airports.csv](https://davidmegginson.github.io/ourairports-data/airports.csv)', HEADER=True, DELIM=',') ;
    D ALTER TABLE airports ADD COLUMN the_geom GEOMETRY ;
    D UPDATE airports SET the_geom = ST_POINT(longitude_deg, latitude_deg) ;
    ```
````

2023-12-09 18:39 UTC, lbartoletti reviewed
Super article Flo,

Quelques remarques sur la forme. Sur le fond, rien à dire, hormis quelques demandes pour ajouter du contexte. Je ne connais pas très bien le sujet et je suis intéressé 😄

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Au niveau des performances, DuckDB est particulièrement adapté pour traiter avec une grande efficacité les gros volumes de données. La ou DuckDB se démarque, c’est que contrairement au système de bas
```suggestion
Au niveau des performances, DuckDB est particulièrement adapté pour traiter avec une grande efficacité les gros volumes de données. Au niveau des performances, DuckDB est particulièrement adapté pour traiter avec une grande efficacité les gros volumes de données. DuckDB se distingue par son approche différente : contrairement à des systèmes de base de données tels que PostgreSQL ou MySQL qui adoptent un traitement par ligne, DuckDB repose sur une architecture en colonne. Selon [le site officiel de DuckDB](https://duckdb.org/why_duckdb.html#duckdbisfast) :
```

Proposition de tournure de phrase plus légère, selon moi.

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Concrètement, cela permet donc de traiter uniquement les colonnes utiles à la requête et donc d’accélérer le temps de réponse.
```suggestion
Concrètement, cela permet donc de traiter uniquement les colonnes utiles à la requête, et ainsi accélérer le temps de réponse.```

Ajout d'une virgule avant le "et" et synonyme de "donc" qui était deux fois dans la phrase.

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Au niveau des performances, DuckDB est particulièrement adapté pour traiter avec une grande efficacité les gros volumes de données. La ou DuckDB se démarque, c’est que contrairement au système de bas
Ça me manque presqu'une explication de la différence entre colonne et ligne. Ça change quoi ? Pourquoi "c'est mieux" ? Dans quel cadre ?

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Tout d’abord le support est mufti plateforme, ce que je vais dire est valable pour Windows, Linux et MacOS. DuckDB est utilisable de plusieurs façons et [les installations sont bien documentées](http
```suggestion
Tout d’abord, le support est multiplateforme ; ce que j'écris est valable pour Windows, Linux et MacOS. DuckDB est utilisable de plusieurs façons et [les installations sont bien documentées](https://duckdb.org/docs/installation/). Il y a tout d’abord un CLI si vous êtes un adepte du terminal. Mais également de nombreux langages, parmi lesquels Python, C++, R, Node.js ou encore Rust. Si vous n’êtes pas très familier avec ces environnements et que vous êtes plus à l’aise avec les gestionnaires de base de données avec interface graphique, [DBeaver](https://dbeaver.io/) propose le [support](https://duckdb.org/docs/guides/sql_editors/dbeaver.html) des bases de données DuckDB.
```

Bon, on n'est pas soumis à la règle des 3 marques. Tant qu'à faire, soit en ajouter un ou deux autres comme DataGrip de JetBrains, soit dire que c'est un parmi (tant) d'autres.

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Bien sûr, au-delà de la manière donc vous utilisez DuckDB, le langage pour utiliser DuckDB est le SQL. Dans la suite dans cet article, lors des exemples pratiques, je détaillerais les commandes en ut
```suggestion
Bien sûr, au-delà de la manière dont vous utilisez DuckDB, le langage pour utiliser DuckDB est le SQL. Dans la suite de cet article, lors des exemples pratiques, je détaillerais les commandes en utilisant le CLI ou bien le paquet Python.
```

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Les fonctions spatiales de DuckDB sont une [extension](https://duckdb.org/docs/extensions/spatial.html). La plupart des fonctions spatiales sont issus de la librairie [GEOS](https://libgeos.org/). Se
```suggestion
Les fonctions spatiales de DuckDB sont dans une [extension](https://duckdb.org/docs/extensions/spatial.html). La plupart de ces fonctions sont issues de la librairie [GEOS](https://libgeos.org/). Seulement certaines sont implémentées nativement dans le cœur de DuckDB. Si vous êtes un habitué des fonctions spatiales de PostGIS vous ne serez pas dépaysé en utilisant les fonctions spatiales du canard : la syntaxe et le nom des fonctions sont extrêmement proches.
```

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Une bonne soixantaine de fonctions spatiales sont disponibles parmi par exemple la star de la jointure spatiale `ST_Intersects(GEOMETRY, GEOMETRY)`
```suggestion
Une bonne soixantaine de fonctions spatiales sont disponibles, parmi, par exemple, la star de la jointure spatiale `ST_Intersects(GEOMETRY, GEOMETRY)`
```

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Ces fonctions spatiales ne sont donc pas nativement présente. Il faut donc la première fois faire un `INSTALL spatial` pour installer cette extension. Pour faire une analogie assez connue du monde de
```suggestion
Ces fonctions spatiales ne sont donc pas nativement présentes. Par conséquent, vous devez faire un `INSTALL spatial` pour installer cette extension. Pour faire une analogie assez connue du monde de la géomatique (ou des sigistes à votre guise) c’est un peu l’équivalent d’un `CREATE EXTENSION postgis` dans PostgreSQL pour obtenir l’extension spatiale PostGIS.```

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Au niveau des formats, là aussi, il y a du choix. Une cinquantaine de formats sont supportés pour lire ou importer des données spatiales. On trouve par exemples les classiques Shapefile, GeoJSON, GPX
```suggestion
Au niveau des formats, là aussi, il y a du choix. Une cinquantaine de formats sont supportés pour lire ou importer des données spatiales. On trouve, par exemple, les classiques Shapefile, GeoJSON, GPX ou encore KML. Mais également des formats de base de données spatiales comme Spatialite ou GeoPackage. Pour finir sur les formats, si vous êtes un OSM addict, le support est encore en mode expérimental, mais DuckDB est capable de lire et intégrer des fichiers [PBF](https://wiki.openstreetmap.org/wiki/PBF_Format) (`.osm.pbf`) via une fonction nommée `ST_ReadOSM()`.
```

C'est supporté directement dans le code de DuckDB ou via GDAL ou autres ?

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Une des particularités de colonne de géométrie sur DuckDB spatial, est qu’une colonne n’a pas de type de géométrie défini (comme sur PostGIS par exemple). Une même colonne de géométrie peut contenir
```suggestion
Une des particularités de la colonne de géométrie sur DuckDB spatial, est qu’elle ne possède pas de géométrie définie ; comme sur PostGIS par exemple. Une même colonne de géométrie peut contenir aussi bien des points, des lignes, des polygones, etc.
```

Le retour à la mapinfo !

C'est considéré comme du GeometryCollection ?
Tu fais comment pour l'intégrer dans QGIS ? Split entre les différents types comme avec le GPX ?

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Il y a quand même un hic à tout ça, à l’heure où j’écris ces lignes (peut-être que cela sera prochainement implémenté), une colonne de géométrie ne porte pas de système de projection. Il n’y a donc p
```suggestion
Il y a quand même un hic à tout ça, à l’heure où j’écris ces lignes (peut-être que cela sera prochainement implémenté), une colonne de géométrie ne porte pas de système de projection. Il n’y a donc pas de fonction de reprojection. Lors de l’export d’une couche géographique, cette couche ne portera pas de projection. Lors d’une lecture dans un SIG, QGIS par exemple, il faudra définir manuellement la projection de votre couche.
```

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +[Parquet](https://parquet.apache.org/) est un format de fichier open source poussé par la fondation Apache créé en juillet 2013. Et qui a la particularité de pouvoir stocker avec une grande efficacit
```suggestion
[Parquet](https://parquet.apache.org/) est un format de fichier open source poussé par la fondation Apache, créé en juillet 2013, qui a la particularité de pouvoir stocker avec une grande efficacité des données. Il utilise… une architecture en colonne. Tiens, tiens, cette histoire de colonne, ça ne vous dit pas quelque chose ? Il est notamment utilisé pour des données « big data »… Les « parquet files », comme ils sont souvent nommés sur la toile, sont uniquement des fichiers utilisés pour s’échanger des données et non pour travailler dessus.
```

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +De nombreux outils existent pour traiter et requêter ce type de fichier, parmi un est particulièrement performant, et devinez quoi, il s’agit de DuckDB (quelle surprise hein ?)
```suggestion
De nombreux outils existent pour traiter et requêter ce type de fichier, parmi lesquels un est particulièrement performant, et devinez quoi, il s’agit de DuckDB (quelle surprise hein ?)
```

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +De nombreux outils existent pour traiter et requêter ce type de fichier, parmi un est particulièrement performant, et devinez quoi, il s’agit de DuckDB (quelle surprise hein ?)
J'ai l'impression que la façon de formuler dans le texte n'est pas forcément claire.

DuckDB, c'est une base de données ou un outil pour parquet ?

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Sur ce [répertoire Github](https://github.com/davidgasquez/awesome-duckdb) est maintenu une liste de projets, outils, ou ressource développée autour de DuckDB. Petit coup de ❤️ pour [Harlequin](https
```suggestion
Sur ce [répertoire Github](https://github.com/davidgasquez/awesome-duckdb) est maintenu une liste de projets, outils ou ressources développées autour de DuckDB. Petit coup de ❤️ pour [Harlequin](https://harlequin.sh/), qui est un IDE pour terminal destiné à l’utilisation de DuckDB et simple d'installation.```

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +- L’exécutable DuckDB pour utiliser le CLI
```suggestion
- L’exécutable DuckDB pour utiliser la CLI :
```

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +- Un environnement Python avec le [paquet duckdb](https://pypi.org/project/duckdb/) d’installer (DuckDB utilise de nombreuses dépendances, il est donc conseiller d’utiliser un environnement virtuel p
```suggestion
- Un environnement Python avec le [paquet duckdb](https://pypi.org/project/duckdb/) déjà installé. DuckDB utilise de nombreuses dépendances, il est donc conseillé d’utiliser un environnement virtuel pour éviter les conflits de dépendances.
```

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +### Création d’une de données (ou l’ouvrir si elle existe déjà)
```suggestion
### Création d’une de données, ou l’ouvrir si elle existe déjà
```

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +La fonction `read_csv_auto` nous permet de pouvoir importer un CSV sans avoir à créer la table au préalable, cette fonction détecte automatiquement la structure du CSV.
```suggestion
La fonction `read_csv_auto` nous permet de pouvoir importer un CSV sans avoir à créer la table au préalable. Cette fonction détecte automatiquement la structure du CSV.
```

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Dans cet exemple on récupère 100 bâtiments aléatoirement (environ 1 minute de traitement chez moi)
```suggestion
Dans cet exemple, on récupère 100 bâtiments aléatoirement ; environ une minute de traitement chez moi.
```

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +:warning: Attention cette extension est encore expérimentales, il faut donc bien cocher ce paramètres dans le gestionnaire des extensions de QGIS.
```suggestion
:warning: Attention, cette extension est encore expérimentale, il faut donc bien cocher ce paramètre dans le gestionnaire des extensions de QGIS.
```

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Un des atouts de DuckDB n'est pas seulement d’intégrer des données pour les traiter dans la base. Mais cela peut servir d’outils de conversion pour des données parquets. Exemple, on me donne des donn
```suggestion
Un des atouts de DuckDB n'est pas seulement d’intégrer des données pour les traiter dans la base. Mais, cela peut servir d’outils de conversion pour des données parquets. Exemple, on me donne des données en parquet. Pourtant, je souhaite les avoir en GeoJSON. Grâce à DuckDB, on peut les convertir sans créer de table ni de base.
```

2023-12-09 18:39 UTC, lbartoletti commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +:bulb: Également possible d'exporter en Shapefile, pour cela il faut remplacer les deux dernières lignes par celles-ci :
```suggestion
:bulb: Également possible d'exporter en Shapefile, pour cela, il faut remplacer les deux dernières lignes par celles-ci :
```

2023-12-09 18:39 UTC, lbartoletti commented on content/team/ffou.md
> +Géographe et Géomatacien de formation  issus du Master [SIGAT](https://formations.univ-rennes2.fr/fr/formations/master-37/master-mention-geomatique-parcours-systeme-d-information-geographique-et-anal
```suggestion
Géographe et Géomatacien de formation issu du Master [SIGAT](https://formations.univ-rennes2.fr/fr/formations/master-37/master-mention-geomatique-parcours-systeme-d-information-geographique-et-analyse-des-territoires-sigat-JEOC8L9A.html). J'ai commencé ma carrière professionnelle comme géomaticien dans un bureau d'études où je travaillais sur des projets de fibre optique, la partie SIG étant très présente dans ce secteur. Désormais, je travaille chez [Oslandia](https://oslandia.com/) en tant que développeur SIG.
```

2023-12-09 18:39 UTC, lbartoletti commented on content/team/ffou.md
> +Passionné de géographie, de sport et d'informatique, j'aime jouer avec les données géographiques (open source si possible) pour les traiter et les représenter. Je suis actif sur [X](https://twitter.c
```suggestion
Passionné de géographie, de sport et d'informatique, j'aime jouer avec les données géographiques (open source si possible) pour les traiter et les représenter. Je suis actif sur [X](https://twitter.com/florent1foug) et [Linkedin](https://www.linkedin.com/in/florent-foug%C3%A8res-083597b8/).
```

2023-12-10 10:12 UTC, florentfgrs commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +```
Je ne comprends pas ce souci, quel est le problème ?

2023-12-11 10:14 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +```
cf https://github.com/geotribu/website/pull/1016#issuecomment-1842877469

2023-12-11 10:53 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +image:
Je suggère d'utiliser le logo de DuckDB comme icône de l'article (utilisée dans la navigation de droite et l'image générée pour les cartes de partage)

```suggestion
description: "Présentation de DuckDB et surtout de ses fonctions spatiales. Comment les exploiter et les mettres en liens avec des données parquet."
icon: simple/duckdb
image:
```

2023-12-13 11:44 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +image: https://cdn.icon-icons.com/icons2/3914/PNG/512/duckdb_logo_icon_248992.png
Ré-ajout de l'icône et suppression du logo car inadapté à l'image d'en-tête

```suggestion
description: "Présentation de DuckDB et surtout de ses fonctions spatiales. Comment les exploiter et les mettres en liens avec des données parquet."
icon: simple/duckdb
image:
```

2023-12-13 11:48 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +title: "DuckDB et les données spatiales"
pas besoin de double-quoter sauf s'il y a un caractère spécial au regard du YAML

```suggestion
title: DuckDB et les données spatiales
```

2023-12-13 11:49 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +description: "Présentation de DuckDB et surtout de ses fonctions spatiales. Comment les exploiter et les mettres en liens avec des données parquet."
```suggestion
description: Présentation de DuckDB et surtout de ses fonctions spatiales. Comment les exploiter et les mettre en lien avec des données (géo)parquet.
```

2023-12-13 11:49 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +    - duckdb
```suggestion
    - DuckDB
```

2023-12-13 11:50 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +    - database
```suggestion
    - base de données
```

2023-12-13 11:50 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +    - spatial
```suggestion
```

2023-12-13 11:52 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +=== "▶️ CLI”
```suggestion
=== ":material-console: CLI”
```

2023-12-13 11:52 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +=== "▶️ CLI”
```suggestion
=== ":material-console: CLI”
```

2023-12-13 11:53 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +=== "▶ CLI”
```suggestion
=== ":material-console: CLI”
```

2023-12-13 11:53 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +=== "▶️ CLI”
```suggestion
=== ":material-console: CLI”
```

2023-12-13 11:53 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +=== "▶️ CLI”
```suggestion
=== ":material-console: CLI”
```

2023-12-13 11:53 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +=== "▶️ CLI”
```suggestion
=== ":material-console: CLI”
```

2023-12-18 09:03 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +[DuckDB](https://duckdb.org/) est un SGBD (système de gestion de base de données) relationnel principalement écrit en C++ et [open source](https://github.com/duckdb/duckdb) publié sous licence MIT. L
Lien vers la [licence MIT](https://fr.wikipedia.org/wiki/Licence_MIT)

2023-12-18 09:14 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +La particularité de ce système de base de données est qu'à l’instar des bases GeoPackage, File GeoDatabe d'ESRI ou encore Access MDB, les bases de données sont des fichiers portables. Ce qui permet u
Proposition : Ce SGBD a la particularité d'être sous forme de **fichier portable** (comme les bases GeoPackage, File GeoDatabase d'ESRI ou encore Access MDB) ce qui simplifie les échanges. Cette portabilité présente cependant un défaut : la **non rétrocompatibilité** entre les différentes versions de DuckDB : un fichiers produit avec une version de DuckDB ne peut actuellement pas être lu avec une autre version de DuckDB.

2023-12-18 09:25 UTC, Guts commented on content/team/ffou.md
> +Géographe et Géomatacien de formation issu du Master [SIGAT](https://formations.univ-rennes2.fr/fr/formations/master-37/master-mention-geomatique-parcours-systeme-d-information-geographique-et-analys
```suggestion
Géographe et Géomaticien de formation issu du Master [SIGAT](https://formations.univ-rennes2.fr/fr/formations/master-37/master-mention-geomatique-parcours-systeme-d-information-geographique-et-analyse-des-territoires-sigat-JEOC8L9A.html), j'ai commencé ma carrière professionnelle dans un bureau d'études sur des projets de fibre optique, les besoins en SIG étant fortement présents dans ce secteur.  
Désormais, je travaille chez [Oslandia](https://oslandia.com/) en tant que développeur SIG.
```

2023-12-18 09:25 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +![logo DuckDB](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/duckdb_spatial/DuckDB_Logo.png){: .img-thumbnail-left }
Utilisation du logo carré déposé dans le bon dossier :

```suggestion
![logo DuckDB](https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/duckdb.png){: .img-thumbnail-left }
```

2023-12-18 09:27 UTC, Guts commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +[Parquet](https://parquet.apache.org/) est un format de fichier open source poussé par la fondation Apache, créé en juillet 2013, qui a la particularité de pouvoir stocker avec une grande efficacité
Ajout logo du format Parquet

```suggestion

![logo Parquet](https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/parquet.png){: .img-thumbnail-left }

[Parquet](https://parquet.apache.org/) est un format de fichier open source poussé par la fondation Apache, créé en juillet 2013, qui a la particularité de pouvoir stocker avec une grande efficacité des données. Il utilise… une architecture en colonne. Tiens, tiens, cette histoire de colonne, ça ne vous dit pas quelque chose ? Il est notamment utilisé pour des données « big data »… Les « parquet files », comme ils sont souvent nommés sur la toile, sont uniquement des fichiers utilisés pour s’échanger des données et non pour travailler dessus.
```

2023-12-18 09:46 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Au niveau des performances, DuckDB est particulièrement adapté pour traiter avec une grande efficacité les gros volumes de données. Au niveau des performances, DuckDB est particulièrement adapté pour
Au niveau des performances, DuckDB est particulièrement adapté au traitement des gros volumes de données. Son architecture diffère d'ailleurs sensiblement de SGBDs comme PostgreSQL ou MySQL qui attaquent majoritairement les données par ligne, car DuckDB traite les données en colonnes. La finalité permise : _un grand lot de valeurs est traité en une seule opération_ rapporte le [le site officiel de DuckDB](https://duckdb.org/why_duckdb.html#duckdbisfast).

2023-12-18 09:48 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Concrètement, cela permet donc de traiter uniquement les colonnes utiles à la requête, et ainsi accélérer le temps de réponse.
Concrètement, seules les colonnes utiles à la requête sont traitées et cela accélère et optimise le temps de réponse.

2023-12-18 09:53 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Tout d’abord le support est multi-plateforme, ce que je vais dire est valable pour Windows, Linux et MacOS. DuckDB est utilisable de plusieurs façons et [les installations sont bien documentées](http
Le support est multi-plateforme (Windows, Linux et MacOS) et DuckDB est utilisable de plusieurs façons via [des installations bien documentées](https://duckdb.org/docs/installation/). Il y a un CLI si vous êtes un adepte du terminal, et de nombreux langages peuvent l'utiliser (parmi lesquels Python, C++, R, Node.js ou encore Rust). Si vous êtes plus à l’aise avec les gestionnaires de base de données avec interface graphique, [DBeaver](https://dbeaver.io/) propose lui aussi le [support](https://duckdb.org/docs/guides/sql_editors/dbeaver.html) des bases de données DuckDB.

2023-12-18 09:57 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Bien sûr, au-delà de la manière dont vous utilisez DuckDB, le langage pour utiliser DuckDB est le SQL. Dans la suite de cet article, lors des exemples pratiques, je détaillerais les commandes en util
Enfin, indépendamment du client de votre choix, DuckDB fonctionne en SQL. Dans la suite de cet article, mes exemples reposeront sur des commandes en utilisant le CLI ou le paquet Python.

2023-12-18 09:59 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Les fonctions spatiales de DuckDB sont une [extension](https://duckdb.org/docs/extensions/spatial.html). La plupart des fonctions spatiales sont issues de la librairie [GEOS](https://libgeos.org/). N
Les fonctions spatiales de DuckDB sont rassemblées dans une [extension](https://duckdb.org/docs/extensions/spatial.html), et sont pour la plupart issues de la librairie [GEOS](https://libgeos.org/). Néanmoins, toutes ne sont pas implémentées nativement dans le cœur de DuckDB. Si vous êtes un habitué des fonctions spatiales de PostGIS vous ne serez pas dépaysé en utilisant les fonctions spatiales du canard, la syntaxe et le nom des fonctions est extrêmement proche.

2023-12-18 10:01 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Une bonne soixantaine de fonctions spatiales sont disponibles, parmi, par exemple, la star de la jointure spatiale `ST_Intersects(GEOMETRY, GEOMETRY)`
On retrouve ainsi une bonne soixantaine de fonctions dont la **star de la jointure spatiale** `ST_Intersects(GEOMETRY, GEOMETRY)`

2023-12-18 10:04 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Ces fonctions spatiales ne sont donc pas nativement présentes. Il faut donc la première fois faire un `INSTALL spatial` pour installer cette extension. Pour faire une analogie assez connue du monde d
Ces fonctions ne sont donc pas natives mais s'implémentent avec un simple `INSTALL spatial`, qui équivaut (coucou les géomaticien.ne.s) à un `CREATE EXTENSION postgis` pour obtenir l’extension spatial PostGIS dans PostgreSQL.

2023-12-18 10:31 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Au niveau des formats, là aussi, il y a du choix. Une cinquantaine de formats sont supportés pour lire ou importer des données spatiales. On trouve par exemple les classiques Shapefile, GeoJSON, GPX
Au niveau des formats de données spatiales, beaucoup de choix également. Une cinquantaine sont supportés en lecture ou import dont les classiques Shapefile, GeoJSON, GPX ou encore KML, ainsi quedes formats de base de données spatiales comme Spatialite ou GeoPackage. Enfin, pour les OSM addicts, en mode expérimental, DuckDB est capable de lire et intégrer des fichiers [PBF](https://wiki.openstreetmap.org/wiki/PBF_Format) (`.osm.pbf`) via une fonction nommée `ST_ReadOSM()`.

2023-12-18 10:39 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +## Les colonnes de géométries
## Les colonnes de géométries et la non prise en charge des projections

2023-12-18 11:18 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +[DuckDB](https://duckdb.org/) est un SGBD (système de gestion de base de données) relationnel principalement écrit en C++ et [open source](https://github.com/duckdb/duckdb) publié sous licence MIT. L
```suggestion
[DuckDB](https://duckdb.org/) est un SGBD (système de gestion de base de données) relationnel principalement écrit en C++ et [open source](https://github.com/duckdb/duckdb) publié sous[ licence MIT](https://fr.wikipedia.org/wiki/Licence_MIT). Le projet a débuté en 2018 et vit beaucoup. Il fait l'objet de releases fréquentes (13 300 étoiles sur GitHub le 09/12/23) et en est à la version 0.9.2.
```
```suggestion
[DuckDB](https://duckdb.org/) est un SGBD (système de gestion de base de données) relationnel principalement écrit en C++ et [open source](https://github.com/duckdb/duckdb) publié sous licence MIT. Le projet est assez récent, il a débuté en 2018, mais le projet vit beaucoup et les releases sont fréquentes, notamment grâce à une communauté très active (13 300 étoiles sur Github en date du 09/12/2023). Actuellement, le projet est en version 0.9.2.
```

2023-12-18 11:19 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +La particularité de ce système de base de données est qu'à l’instar des bases GeoPackage, File GeoDatabe d'ESRI ou encore Access MDB, les bases de données sont des fichiers portables. Ce qui permet u
```suggestion
Ce SGBD a la particularité d'être sous forme de fichier portable (comme les bases GeoPackage, File GeoDatabase d'ESRI ou encore Access MDB) ce qui simplifie les échanges. Cette portabilité présente cependant un défaut : la non rétrocompatibilité entre les différentes versions de DuckDB : un fichiers produit avec une version de DuckDB ne peut actuellement pas être lu avec une autre version de DuckDB.
```

2023-12-18 11:21 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Au niveau des performances, DuckDB est particulièrement adapté pour traiter avec une grande efficacité les gros volumes de données. Au niveau des performances, DuckDB est particulièrement adapté pour
```suggestion
Au niveau des performances, DuckDB est particulièrement adapté au traitement des gros volumes de données. Son architecture diffère d'ailleurs sensiblement de SGBDs comme PostgreSQL ou MySQL qui attaquent majoritairement les données par ligne, car DuckDB traite les données en colonnes. La finalité permise : un grand lot de valeurs est traité en une seule opération rapporte le [le site officiel de DuckDB](https://duckdb.org/why_duckdb.html#duckdbisfast) : on traite seulement les colonnes utiles à la requête et cela accélère et optimise le temps de réponse.
```

2023-12-18 11:21 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +> “Un grand lot de valeurs est traité en une seule opération"
```suggestion
```

2023-12-18 11:21 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Concrètement, cela permet donc de traiter uniquement les colonnes utiles à la requête, et ainsi accélérer le temps de réponse.
```suggestion
```

2023-12-18 11:22 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Tout d’abord le support est multi-plateforme, ce que je vais dire est valable pour Windows, Linux et MacOS. DuckDB est utilisable de plusieurs façons et [les installations sont bien documentées](http
```suggestion
Le support est multi-plateforme (Windows, Linux et MacOS) et DuckDB est utilisable de plusieurs façons via [des installations bien documentées](https://duckdb.org/docs/installation/). Il y a un CLI si vous êtes un adepte du terminal, et de nombreux langages peuvent l'utiliser (parmi lesquels Python, C++, R, Node.js ou encore Rust). Si vous êtes plus à l’aise avec les gestionnaires de base de données avec interface graphique, [DBeaver](https://dbeaver.io/) propose lui aussi le [support](https://duckdb.org/docs/guides/sql_editors/dbeaver.html) des bases de données DuckDB.
```

2023-12-18 11:23 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Bien sûr, au-delà de la manière dont vous utilisez DuckDB, le langage pour utiliser DuckDB est le SQL. Dans la suite de cet article, lors des exemples pratiques, je détaillerais les commandes en util
```suggestion
Enfin, indépendamment du client de votre choix, DuckDB fonctionne en SQL. Dans la suite de cet article, mes exemples reposeront sur des commandes en utilisant le CLI ou le paquet Python.
```

2023-12-18 11:23 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Les fonctions spatiales de DuckDB sont une [extension](https://duckdb.org/docs/extensions/spatial.html). La plupart des fonctions spatiales sont issues de la librairie [GEOS](https://libgeos.org/). N
```suggestion
Les fonctions spatiales de DuckDB sont rassemblées dans une [extension](https://duckdb.org/docs/extensions/spatial.html), et sont pour la plupart issues de la librairie [GEOS](https://libgeos.org/). Néanmoins, toutes ne sont pas implémentées nativement dans le cœur de DuckDB. Si vous êtes un habitué des fonctions spatiales de PostGIS vous ne serez pas dépaysé en utilisant les fonctions spatiales du canard, la syntaxe et le nom des fonctions est extrêmement proche.
```

2023-12-18 11:23 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Une bonne soixantaine de fonctions spatiales sont disponibles, parmi, par exemple, la star de la jointure spatiale `ST_Intersects(GEOMETRY, GEOMETRY)`
```suggestion
On retrouve ainsi une bonne soixantaine de fonctions dont la star de la jointure spatiale ST_Intersects(GEOMETRY, GEOMETRY)
```

2023-12-18 11:24 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Ces fonctions spatiales ne sont donc pas nativement présentes. Il faut donc la première fois faire un `INSTALL spatial` pour installer cette extension. Pour faire une analogie assez connue du monde d
```suggestion
Ces fonctions ne sont donc pas natives mais s'implémentent avec un simple INSTALL spatial, qui équivaut (coucou les géomaticien.ne.s) à un CREATE EXTENSION postgis pour obtenir l’extension spatial PostGIS dans PostgreSQL. À chaque utilisation, cette extension s'appelle par la commande LOAD spatial.
```

2023-12-18 11:26 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Au niveau des formats, là aussi, il y a du choix. Une cinquantaine de formats sont supportés pour lire ou importer des données spatiales. On trouve par exemple les classiques Shapefile, GeoJSON, GPX
```suggestion
Au niveau des formats de données spatiales, beaucoup de choix également. Une cinquantaine sont supportés en lecture ou import dont les classiques Shapefile, GeoJSON, GPX ou encore KML, ainsi quedes formats de base de données spatiales comme Spatialite ou GeoPackage. Enfin, pour les OSM addicts, en mode expérimental, DuckDB est capable de lire et intégrer des fichiers [PBF](https://wiki.openstreetmap.org/wiki/PBF_Format) (.osm.pbf) via une fonction nommée ST_ReadOSM().
```

2023-12-18 11:26 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Puis lors de chaque utilisation sur une base de données, il faut charger cette extension via un `LOAD spatial`
```suggestion
```

2023-12-18 11:26 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +## Les colonnes de géométries
```suggestion
## Les colonnes de géométries et la non prise en charge des projections
```

2023-12-18 11:30 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Une des particularités de colonne de géométrie sur DuckDB spatial, est qu’une colonne n’a pas de type de géométrie défini (comme sur PostGIS par exemple). Une même colonne de géométrie peut contenir
```suggestion
Une des particularités des colonnes de géométrie sur DuckDB spatial est l'absence de définition du type de géométrie (contrairement à PostGIS par exemple). Une même colonne de géométrie contiendra aussi bien des points, des lignes, des polygones, etc.
```

2023-12-18 11:33 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Il y a quand même un hic à tout ça, à l’heure où j’écris ces lignes (peut-être que cela sera prochainement implémenté), il n'est pas possible de définir une projection comme contrainte pour une colon
```suggestion
Il y a quand même un hic dans tout ça : la définition d'une projection comme contrainte pour une colonne n'est actuellement pas implémentée. Il n’y a pas non plus de fonction de reprojection. De même qu'une couche n'a pas de projection attribuée lors d'un export. Il vous faudra définir manuellement cette projection en dehors de DuckDB, ce qui implique une certaine rigueur : toutes vos données devront donc être dans la même projection.

Si cette réflexion tombe sous le sens du point de vue "administrateur de données", les utilisateurs moins avertis peuvent avoir quelques surprises en mélangeant des projections.
```

2023-12-18 11:42 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +[Parquet](https://parquet.apache.org/) est un format de fichier open source poussé par la fondation Apache, créé en juillet 2013, qui a la particularité de pouvoir stocker avec une grande efficacité
```suggestion
[Parquet](https://parquet.apache.org/) est un format de fichier open source poussé par la fondation Apache depuis 2013, qui a la particularité de stocker des données avec efficacité... via une architecture en colonne 😉. Il est notamment utilisé pour le big data. À la base, ces « parquet files » étaient utilisés pour l'échange de données et non pour travailler dessus mais les schémas de compression et de codage de données qu'ils mobilisent les rendent très performants pour la gestion massive de données complexes.
```

2023-12-18 11:43 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +De nombreux outils existent pour traiter et requêter ce type de fichier, parmi lesquels un est particulièrement performant, et devinez quoi, il s’agit de DuckDB (quelle surprise hein ?)
```suggestion
```

2023-12-18 11:46 UTC, Gab-OPenIG commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Un des atouts de DuckDB n'est pas seulement d’intégrer des données pour les traiter dans la base. Mais, cela peut servir d’outils de conversion pour des données parquets. Exemple, on me donne des don
```suggestion
Un des atouts de DuckDB est qu'en plus d’intégrer des données pour les traiter en base, il peut servir d’outil de conversion pour des données parquets. Exemple : Si on me donne des données en parquet et je souhaite des GeoJSON, DuckDB peut les convertir sans créer de table ni de base !
```

2023-12-18 12:32 UTC, florentfgrs commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +[Parquet](https://parquet.apache.org/) est un format de fichier open source poussé par la fondation Apache, créé en juillet 2013, qui a la particularité de pouvoir stocker avec une grande efficacité
Repris dans ce [commit](1442a0950163fd446dd9902463799b63c609e2ba) pour également prendre en compte la reprise de @Gab-OPenIG

2023-12-18 12:32 UTC, florentfgrs commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +[Parquet](https://parquet.apache.org/) est un format de fichier open source poussé par la fondation Apache, créé en juillet 2013, qui a la particularité de pouvoir stocker avec une grande efficacité
Repris dans ce [commit](1442a0950163fd446dd9902463799b63c609e2ba) pour également prendre en compte l'ajout du logo parquet proposé par @Guts

2023-12-18 13:05 UTC, florentfgrs commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Une des particularités de colonne de géométrie sur DuckDB spatial, est qu’une colonne n’a pas de type de géométrie défini (comme sur PostGIS par exemple). Une même colonne de géométrie peut contenir
Si tu parles du plugin QGIS, le multi geom dans une couche n'est actuellement pas géré.

2023-12-18 13:08 UTC, florentfgrs commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Tout d’abord le support est mufti plateforme, ce que je vais dire est valable pour Windows, Linux et MacOS. DuckDB est utilisable de plusieurs façons et [les installations sont bien documentées](http
DataGrip ajouté :)

2023-12-18 13:09 UTC, florentfgrs commented on content/articles/2023/2023-12-19_duckdb-donnees-spatiales.md
> +Au niveau des formats, là aussi, il y a du choix. Une cinquantaine de formats sont supportés pour lire ou importer des données spatiales. On trouve par exemples les classiques Shapefile, GeoJSON, GPX
Je ne connais pas la réponse à cette question. Il faudrait que je cherche.

2023-12-19 10:26 UTC, Guts approved these changes

2023-12-19 10:30 UTC, merged

2023-12-21 15:16 UTC, Guts commented
LinkedIn : https://www.linkedin.com/feed/update/urn:li:share:7143620095523655680/

2023-12-21 15:51 UTC, florentfgrs commented
X : https://x.com/florent1foug/status/1737863328431513614?s=20

2023-12-21 17:37 UTC, Guts commented
Mastodon : https://mapstodon.space/@geotribu/111619137229616980