article création de cartes avec Blender
geotribu/website pull request #1107
Opened 2024-04-07 10:46 UTC by thomas-szczurek

Traduction et adaptation qgis / full open source de l'article initialement paru ici : https://somethingaboutmaps.wordpress.com/2017/11/16/creating-shaded-relief-in-blender/ sur les techniques permettant de réaliser des cartes de relief avec Blender en échange d'un sticker geotribu aux journées qgis 2024.

L'auteur initial a été contacté et j'ai sa permission de traduire / changer le texte.

par contre je n'ai pas bien comprit comment signer en étant pas membre de l'équipe. J'espère avoir tout fait comme il faut ! (sinon je suis joignable : thomas.szczurek@gmail.com pour rectifier)

2024-04-13 09:49 UTC, thomas-szczurek commented
Salut ! Merci ! Désolé j'ai eu une semaine assez chargée. J'essaye de rectifier les quelques fautes de frappe qu'il reste et de fignoler ça comme il faut ce WE.

2024-04-14 13:34 UTC, thomas-szczurek commented
Et voilà, ajout de la signature, correction de coquilles/quelques ajustments/corrections/photo de preview fait !

j'espère que ça va comme ça !

2024-04-16 08:18 UTC, thomas-szczurek commented
@gounux je me permet de te pinger car j'ai mis un peu de temps à répondre !

2024-04-16 08:25 UTC, Guts commented
Merci @thomas-szczurek pour la proposition d'article 🙏 !

J'ai modifié la description de ta PR avec le message type que je t'invite à consulter et dont il faut compléter certaines parties.

@geotribu/relecture c'est à vous !

2024-04-16 08:27 UTC, thomas-szczurek commented
J'essaye de regarder ça ce soir !

2024-04-16 08:32 UTC, Guts requested changes
Première passe très rapide !
Je continue plus tard !

2024-04-16 08:32 UTC, Guts commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +image: https://github.com/thomas-szczurek/images/blob/main/title.png
Toutes les images doivent être uploadées sur notre CDN (sauf si elles sont trop lourdes) et celle pour l'en-tête doit respecter un certain ratio de dimensions.

Voir :

- https://contribuer.geotribu.fr/guides/metadata_yaml_frontmatter/#syntaxe pour les consignes sur l'image d'en-tête
- https://contribuer.geotribu.fr/guides/cdn-images-hebergement/

Je t'envoie les accès au CDN par mail.

2024-04-16 08:32 UTC, Guts commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +image: https://github.com/thomas-szczurek/images/blob/main/title.png
Tu peux aussi ne rien mettre dans ce champ, une image sera alors automatiquement généréé. C'est ce que je te suggère ici (mais c'est à ta convenance) :

```suggestion
image:
```

2024-04-16 08:32 UTC, Guts commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +authors:
Pour info, tu peux ajouter un court sous-titre qui apparaît dans la barre de navigation de gauche, dans l'image d'en-tête si auto-générée, la liste des articles...

```suggestion
title: "Réaliser des cartes avec Blender"
subtitle: 
authors:
```

2024-04-16 08:32 UTC, Guts commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +cd C:\\\Users\nabuchodonosor\Documents (Windows)
Ajouter les balises de code :

```suggestion

- sur Linux : `cd /home/nabuchodonosor/Documents`
- sur Windows : `cd C:\\\Users\nabuchodonosor\Documents`
```

2024-04-16 08:32 UTC, Guts commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +![exemple fichier tuile](https://github.com/thomas-szczurek/images/blob/main/img2_tuiles.png)
Ajouter les balises de centrage et chargement optimisé (cf https://contribuer.geotribu.fr/guides/image/)

```suggestion
![exemple fichier tuile](https://github.com/thomas-szczurek/images/blob/main/img2_tuiles.png){: .img-center loading=lazy }
```

2024-04-16 08:35 UTC, Guts commented
> J'essaye de regarder ça ce soir !

Ne te mets pas la pression, c'est du bénévolat donc il n'y a de deadline que celle que l'on s'impose pour éviter de ne jamais publier.

C'est déjà énorme d'avoir fait cet effort !

2024-04-18 11:04 UTC, Guts requested changes
Nouvelle passe de corrections !

@thomas-szczurek as-tu vu mon mail avec les accès au CDN et une proposition de visio pour t'éviter de la friction sur la review ?

2024-04-18 12:21 UTC, thomas-szczurek commented
> Nouvelle passe de corrections !
> 
> @thomas-szczurek as-tu vu mon mail avec les accès au CDN et une proposition de visio pour t'éviter de la friction sur la review ?

@Guts Désolé, j'ai vu passé l'info ici sur l'hergement CDN, mais pas le mail avec les accès et il ne me semble pas le trouver :( (j'avoue avoir un nom et donc un mail prompt aux erreurs haha)

2024-04-18 12:49 UTC, Guts commented
> @Guts Désolé, j'ai vu passer l'info ici sur l'hergement CDN, mais pas le mail avec les accès et il ne me semble pas le trouver :( (j'avoue avoir un nom et donc un mail prompt aux erreurs haha)

Pourtant il est bien dans le dossier Envoyés :

![image](https://github.com/geotribu/website/assets/1596222/b7aef6a0-9197-4324-bd95-5f045490c818)

Il me semble avoir copié collé ton adresse. Tu peux check sur la capture stp ?

2024-04-18 12:51 UTC, thomas-szczurek commented
> > @Guts Désolé, j'ai vu passer l'info ici sur l'hergement CDN, mais pas le mail avec les accès et il ne me semble pas le trouver :( (j'avoue avoir un nom et donc un mail prompt aux erreurs haha)
> 
> Pourtant il est bien dans le dossier Envoyés :
> 
> ![image](https://private-user-images.githubusercontent.com/1596222/323608318-b7aef6a0-9197-4324-bd95-5f045490c818.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDQ4NzYsIm5iZiI6MTcxMzQ0NDU3NiwicGF0aCI6Ii8xNTk2MjIyLzMyMzYwODMxOC1iN2FlZjZhMC05MTk3LTQzMjQtYmQ5NS01ZjA0NTQ5MGM4MTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MThUMTI0OTM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDIwMDM0MzFjNTM5OTQ0ZDFkZWQ5NDNkODBkNDJiZWU4YmFhNWU4ZWQxOGI3YjZjYWU4ZWFhMWMyMGNlNGMzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.nC9bzaUFDoaaq3wJ8We4WwKRW-1V1yihHg3IycT9_Rc)
> 
> Il me semble avoir copié collé ton adresse. Tu peux check sur la capture stp ?

Ok c'est bon, il était arrivé dans mes spams, je check ça dès que je peux !

2024-04-18 12:54 UTC, Guts commented
> Ok c'est bon, il était arrivé dans mes spams, je check ça dès que je peux !

Argh ça sent pas bon ça. Si tu as moyen d'indiquer à gmail que ce compte est un compte de confiance, ça nous arrange ! :pray: 

No souci, no pression sauf pour qu'on boira pour fêter la publication !

2024-04-19 09:51 UTC, thomas-szczurek reviewed
On est bon là non ?

2024-04-19 09:51 UTC, thomas-szczurek commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +subtitle:
je laisse les calembours aux spécialistew !

2024-04-19 14:18 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Cet article se base sur celui initialement paru en anglais sur [somethingaboutmaps](https://somethingaboutmaps.wordpress.com/2017/11/16/creating-shaded-relief-in-blender/), dont on remerciera l'auteu
Éventuellement citer le nom de l'auteur original du tuto? (Daniel Huffman) 
Ça personnifie l'histoire, et ça lui donne un peu plus de visibilité :)

2024-04-19 14:19 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Je vais ici utiliser le  MNT à 1 mètre issus du [RGE ALTI](https://geoservices.ign.fr/rgealti) de l'IGN sur le département des Pyrennées Atlantiques, ce qui permettra d'avoir et du relief (ce qui ren
```suggestion
Je vais ici utiliser le  MNT à 1 mètre issus du [RGE ALTI](https://geoservices.ign.fr/rgealti) de l'IGN sur le département des Pyrénées-Atlantiques, ce qui permettra d'avoir du relief (ce qui rend bien avec cette technique) et de la mer (sacro-sainte règle des effets de manche pour avoir la classe : mettez de la flotte).
```

2024-04-19 14:20 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Il y a plusieurs étapes de préparation des données et l'une d'entre elle nécessite obligatoirement l'utilisation de GDAL en lignes de commande. Restez ici ! Rien de bien compliqué et on vous explique
```suggestion
Il y a plusieurs étapes de préparation des données et l'une d'entre elles nécessite obligatoirement l'utilisation de GDAL en ligne de commande. Restez ici ! Rien de bien compliqué et on vous explique tout (et on va profiter de cet article pour essayer de faire tout les pré-traitements raster en lignes de commande pour s'y familiariser. Au cazou j'indiquerai aussi comment faire avec QGIS).
```

2024-04-19 14:21 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Ceci implique d'avoir accès à GDAL. Sur windows ça passe en se rendant dans votre répertoire d'installation de Qgis et ensuite en démarrant OSGeo4W.bat. Je considère que les linuxiens sont assez agué
```suggestion
Ceci implique d'avoir accès à GDAL. Sur Windows, ça se passe en se rendant dans votre répertoire d'installation de QGIS, puis en démarrant OSGeo4W.bat. Je considère que les linuxiens sont assez aguerris pour se débrouiller (au pire faites-vous un environnement [mamba](https://mamba.readthedocs.io/en/latest/) qui va bien (miniconda réécrit en c/c++)) et je refuse par principe de parler aux apple-iens (sauf à ma cheffe de service car je suis bien obligé).
```

J'ai remplacé appeliens par apple-iens, ça me semblait un peu plus lisible du premier coup!

2024-04-19 14:25 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Après récupération du jeu de données, chargez une des dalles au format asc dans qgis. Le format asc ne gère pas les projections et Qgis essayera par défaut de les positionner en WGS 84 (ne vous inqui
```suggestion
Après récupération du jeu de données, chargez une des dalles au format ASC dans qgis. Le format ASC ne gère pas les projections et QGIS essayera par défaut de les positionner en WGS84 (ne vous inquiétez pas, les coordonnées sont les bonnes). Vous pouvez repositionner l'image en cliquant sur la petite icône de l'image ci-dessous et en spécifiant ce bon vieux Lambert 93.
```

2024-04-19 14:25 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +![Ca arrive même aux meilleurs](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/gdal_qgis_blender/img1_lign.png){: .img-center loading=lazy }
```suggestion
![Ça arrive même aux meilleurs](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/gdal_qgis_blender/img1_lign.png){: .img-center loading=lazy }
```

2024-04-19 14:26 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Sur ces considérations on chargera plutôt la couche "dalles" [dans le format dont il ne faut pas prononcer le nom](http://switchfromshapefile.org/) située dans le dossier "3_SUPPLEMENTS_LIVRAISON" de
```suggestion
Sur ces considérations on chargera plutôt la couche "dalles" [dans le format dont il ne faut pas prononcer le nom](http://switchfromshapefile.org/) située dans le dossier "3_SUPPLEMENTS_LIVRAISON" de l'archive. On active ensuite un fond de plan OpenStreetMap sous "xyz tiles" de l'explorateur de QGIS histoire de se repérer.
```

2024-04-19 14:26 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +- Dans Qgis, on sélectionne les dalles de la région (rectangulaire) que l'on souhaite cartographier et on exporte la sélection au format csv qu'on nommera select.csv.
```suggestion
- Dans QGIS, on sélectionne les dalles de la région (rectangulaire) que l'on souhaite cartographier et on exporte la sélection au format CSV qu'on nommera select.csv.
```

2024-04-19 14:28 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +- On tire la formule et on remplace par les valeurs "en dur " avec un collage spécial
Qu'est ce que tu veux dire par "on tire la formule"?

2024-04-19 14:30 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +- Enfin on change à la brutasse l'extension du fichier en .txt ce qui nous donne une fois ouvert :
```suggestion
- Enfin on change à la brutasse l'extension du fichier en TXT ce qui nous donne une fois ouvert :
```
NB: 'harmonise le format typographique des types d'extensions pour être cohérent sur l'ensemble de l'article: j'ai choisi de les indiquer en majuscule et sans point devant (ASC, TXT) mais ce n'est pas forcément ce format là qu'il faut retenir :)

2024-04-19 14:30 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +- On déplace ce fichier directement dans le répertoire contenant les tuilles asc téléchargées.
```suggestion
- On déplace ce fichier directement dans le répertoire contenant les tuiles ASC téléchargées.
```

2024-04-19 14:31 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Pour les non initiés à la ligne de commande, on se déplace dans un répertoire avec la commande cd (pour change directory). On peut soit passer un repertoire situé dans le repertoire courant, soit une
```suggestion
Pour les non-initiés à la ligne de commande, on se déplace dans un répertoire avec la commande cd (pour _change directory_). On peut soit passer un répertoire situé dans le repertoire courant, soit une adresse complète.
```

2024-04-19 14:31 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Sur windows pour changer de lecteur juste indiquer la lettre et les deux points, sans cd (exemple `D:`).
```suggestion
Sur Windows, pour changer de lecteur, juste indiquer la lettre et les deux points, sans cd (exemple `D:`).
```

2024-04-19 14:33 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Vous vous souvenez de ces gens relous qui vous demandent des noms de dossiers/fichiers juste en alphanumériques et sans espaces mais avec des _ ? C'est pour ça.
Il n'y a pas un balisage pour faire un encadré façon "tips" ou "le saviez-vous"? Ce serait drôle d'encadrer cette phrase de cette manière :)

2024-04-19 14:33 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Vous vous souvenez de ces gens relous qui vous demandent des noms de dossiers/fichiers juste en alphanumériques et sans espaces mais avec des _ ? C'est pour ça.
```suggestion
Vous vous souvenez de ces gens relous qui vous demandent des noms de dossiers/fichiers juste en alphanumériques et sans espaces mais avec des _ ? C'est pour ça.
```

Il n'y a pas un balisage pour faire un encadré façon "tips" ou "le saviez-vous"? Ce serait drôle d'encadrer cette phrase de cette manière :)

2024-04-19 14:33 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +On se déplace dans le dossier contenant les images ex :
```suggestion
On se déplace dans le dossier contenant les images. Exemple :
```

2024-04-19 14:36 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Et maitenant on va utiliser [GDAL_merge.py](https://GDAL.org/programs/GDAL_merge.html), le programme de GDAL permettant de fusionner des images.
```suggestion
Et maitenant on va utiliser [GDAL_merge.py](https://GDAL.org/programs/GDAL_merge.html), le programme de GDAL permettant de fusionner des images.
```

Peut-être transformer cette phrase qui commence par "Et maintenant" (comme celle de la ligne 63): Autant la changer en titre, non? Ça fera respirer et ça structure le texte

2024-04-19 14:37 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +L'option`-o` permet de spécifier le nom du fichier de sortie (c'est donc obligatoire). On ne caressera jamais assez dans le sens du poil les gens derrière GDAL donc on dit que c'est très fort et ça r
```suggestion
- L'option`-o` permet de spécifier le nom du fichier de sortie (c'est donc obligatoire). On ne caressera jamais assez dans le sens du poil les gens derrière GDAL donc on dit que c'est très fort et ça reconnait le type de fichier désiré juste avec l'extension.
```
Pareil ici, structuration du contenu pour ajouter de la respiration :)

2024-04-19 14:37 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +`-co` correspond aux options spécifiques non pas du programme mais du driver du type de fichier (ici geotiff). BIGTIFF permet de faire des tif de plus de 4gb. Ce n'est pas mon cas ici mais ça ne cout
```suggestion
`- -co` correspond aux options spécifiques non pas du programme mais du driver du type de fichier (ici geotiff). BIGTIFF permet de faire des tif de plus de 4gb. Ce n'est pas mon cas ici mais ça ne coute rien de passer la commande par sécurité.
```

2024-04-19 14:38 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Il faut ensuite normalement spécifier un par un les noms de fichiers à fusionner ce qui serait fastidieux, mais l'option `--optfile` nous permet de passer un fichier contenant une liste, d'où les éta
```suggestion
Il faut ensuite normalement spécifier un par un les noms de fichiers à fusionner, ce qui serait fastidieux, mais l'option `--optfile` nous permet de passer un fichier contenant une liste, d'où les étapes précedentes !
```

2024-04-19 14:38 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Dans le repertoire vous trouverez votre geotiff mosaic.tif que je vous encourage à déplacer ailleurs pour s'y retrouver.
```suggestion
Dans le répertoire, vous trouverez votre geotiff mosaic.tif que je vous encourage à déplacer ailleurs pour vous y retrouver.
```

2024-04-19 14:39 UTC, mapperfr reviewed
Hop, une revue essentiellement coquilles/orthographes sur les 100 premières lignes du texte. Je continue sur les suivantes!

2024-04-19 14:42 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +On va maintenant reprojeter (vous vous souvenez des fichiers asc ?) notre image avec [GDALwarp](https://GDAL.org/programs/GDALwarp.html) le programme servant à ... reprojeter.
```suggestion
On va maintenant reprojeter (vous vous souvenez des fichiers ASC ?) notre image avec [GDALwarp](https://GDAL.org/programs/GDALwarp.html) le programme servant à... reprojeter.
```

2024-04-19 14:43 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Dans ~~l'interface graphique de GDAL~~ Qgis cette étape est faisable via le menu raster -> Divers -> fusion (il faut au préalable charger l'ensemble des tuiles voulues dans qgis).
```suggestion
Dans ~~l'interface graphique de GDAL~~ QGIS cette étape est faisable via le menu raster -> Divers -> fusion (il faut au préalable charger l'ensemble des tuiles voulues dans QGIS).
```

2024-04-19 14:43 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +- L'option `-t_srs` sert à indiquer le srid de sortie.
```suggestion
- L'option `-t_srs` sert à indiquer le SRID de sortie.
```

2024-04-19 14:44 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +- `-r` permet de spécifier la méthode de rééchantillonage. Le choix dépasse le cadre de cet article mais sachez que des methodes avancées comme cubicspline ou lanczos peuvent donner des résultats "fl
```suggestion
- `-r` permet de spécifier la méthode de rééchantillonnage. Le choix dépasse le cadre de cet article mais sachez que des methodes avancées comme `cubicspline` ou `lanczos` peuvent donner des résultats "floutés" car modifiant la valeur des pixels selon des courbes. On va donc rester sur la méthode par défaut : `nearest neighbour` (plus proche voisin) pour éviter ceci.
```

2024-04-19 14:45 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Pour celles et ceux à l'aise avec GDAL, vous pouvez compresser les images pour réduire la taille des fichiers de sortie au moins en deflate (pour les autres, ça se fait en passant une seconde option
```suggestion
Pour celles et ceux à l'aise avec GDAL, vous pouvez compresser les images pour réduire la taille des fichiers de sortie au moins en `deflate` (pour les autres, ça se fait en passant une seconde option pour le driver de type de fichier : `-co COMPRESS=methode`, la plus couramment utilisée étant `-co COMPRESS=DEFLATE` pour s'assurer de la compatibilité avec tous les systèmes / logiciels).
```

2024-04-19 14:45 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Sinon, ça se fait avec raster -> Projection -> Assigner une projection dans Qgis.
```suggestion
Sinon, dans QGIS, ça se fait avec Raster -> Projection -> Assigner une projection.
```

2024-04-19 14:46 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Oui. Nous allons commettre ceci. Ne sortez pas les bidons d'essence tout de suite s'il vous plait. Pour ce que nous allons en faire, Blender n'accepte que les images en entier 16 bits non signés (UIn
```suggestion
Oui. Nous allons commettre ceci. Ne sortez pas les bidons d'essence tout de suite s'il vous plaît. Pour ce que nous allons en faire, Blender n'accepte que les images en entier 16 bits non signés (UInt16, on y reviendra), donc une plage de valeur pour les pixels comprise entre 0 et 65 535. Mais sans virgules, ce que contient notre raster initial donc on perdrait du détail. L'idée est donc de réattribuer aux pixels de notre image des valeurs sur l'ensemble de cette plage, ceci pour bénéficier de l'entièreté de cette finesse.
```

2024-04-19 14:48 UTC, mapperfr reviewed
Deuxième passe!

2024-04-19 14:48 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +On fait ça avec [GDAL_calc.py](https://GDAL.org/programs/GDAL_calc.html) mais on peut aussi rester simple et faire ça avec la calculatrice raster de Qgis.
```suggestion
On fait ça avec [GDAL_calc.py](https://GDAL.org/programs/GDAL_calc.html) mais on peut aussi rester simple et faire ça avec la calculatrice raster de QGIS.
```

2024-04-19 14:49 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Tout d'abord, on normalise notre raster car certaines valeurs peuvent êtres en dessous de 0 (notamment quand il y a de l'eau). On va donc les mettres à 0.
```suggestion
Tout d'abord, on normalise notre raster car certaines valeurs peuvent êtres en dessous de 0 (notamment quand il y a de l'eau). On va donc les mettre à 0.
```

2024-04-19 14:49 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Avec GDAL_calc.py les maths doivent être "[numpy](https://numpy.org/) style".
```suggestion
Avec `GDAL_calc.py`, les maths doivent être "[numpy](https://numpy.org/) style".
```

2024-04-19 14:50 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Ou dans qgis : raster -> calculatrice raster puis
```suggestion
Ou dans QGIS : raster -> calculatrice raster puis
```

2024-04-19 14:50 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +- `--calc` la formule de calcul, entourée de "".
```suggestion
- `--calc` la formule de calcul, entourée de `""`.
```

2024-04-19 15:06 UTC, mapperfr reviewed
Troisième passe, a priori que des modifs de forme ici aussi.

2024-04-19 15:06 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Enfin, on va convertir notre raster en UInt16 pour l'import dans Blender. C'est cette opération qui n'est pas réalisable dans Qgis sans circonvolutions. Donc on sort [GDAL_translate](https://GDAL.org
```suggestion
Enfin, on va convertir notre raster en UInt16 pour l'importer dans Blender. C'est cette opération qui n'est pas réalisable dans QGIS sans circonvolutions. Donc on sort [gdal_translate](https://GDAL.org/programs/GDAL_translate.html), le programme qui sert à faire des conversions.
```

2024-04-19 15:06 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Faire le tour de Blender serait bien sur beaucoup trop ambiteux ici, mais voici quelques indications de base pour celles et ceux qui n'ont jamais ouvert le logiciel.
```suggestion
Faire le tour de Blender serait bien sûr beaucoup trop ambiteux ici, mais voici quelques indications de base pour celles et ceux qui n'ont jamais ouvert le logiciel.
```

2024-04-19 15:06 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Blender fonctionne sur un principe d'environnement en fonction de la tache que vous êtes en train de réaliser (modéliser, travailler sur les textures ...). Pour passer de l'un à l'autre, on clique ic
```suggestion
Blender fonctionne sur un principe d'environnement en fonction de la tâche que vous êtes en train de réaliser (modéliser, travailler sur les textures ...). Pour passer de l'un à l'autre, on clique ici :
```

2024-04-19 15:06 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +![La](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/gdal_qgis_blender/img6_viewports.png){: .img-center loading=lazy }
```suggestion
![Là](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/gdal_qgis_blender/img6_viewports.png){: .img-center loading=lazy }
```

2024-04-19 15:06 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +3D Viewport est la vue 3d par défaut.
```suggestion
3D Viewport est la vue 3D par défaut.
```

2024-04-19 15:06 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Les boutons situés ici permettent de changer le mode d'affichage des objets 3d (fil de fer, materiaux, rendu ...).
```suggestion
Les boutons situés ici permettent de changer le mode d'affichage des objets 3D (fil de fer, materiaux, rendu...).
```

2024-04-19 15:06 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +(vous pouvez essayer avec le cube présent par défaut).
```suggestion
(Vous pouvez essayer avec le cube présent par défaut).
```

2024-04-19 15:06 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +![La](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/gdal_qgis_blender/img7_render.png){: .img-center loading=lazy }
```suggestion
![Là](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/gdal_qgis_blender/img7_render.png){: .img-center loading=lazy }
```

2024-04-19 15:06 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +![La](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/gdal_qgis_blender/img8_engine.png){: .img-center loading=lazy }
```suggestion
![Là](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/gdal_qgis_blender/img8_engine.png){: .img-center loading=lazy }
```

2024-04-19 15:06 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +En fonction de votre carte graphique, vous pouvez aussi faire un tour par le menu edit -> preferences -> system et choisir en fonction de votre crémerie ce qui sera utilisé par Cycles. Choisir [OptiX
```suggestion
En fonction de votre carte graphique, vous pouvez aussi faire un tour par le menu edit -> preferences -> system et choisir en fonction de votre crémerie ce qui sera utilisé par Cycles. Choisir [OptiX](https://fr.wikipedia.org/wiki/OptiX) chez Nvidia / [HIP](https://rocm.docs.amd.com/projects/HIP/en/latest/index.html) chez AMD si votre configuration matérielle le supporte (hey, vous venez sur un tuto 3D, il faut s'attendre à ce genre de phrases !).
```

2024-04-19 15:06 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +![La](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/gdal_qgis_blender/img9_sampling.png){: .img-center loading=lazy }
```suggestion
![Là](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/gdal_qgis_blender/img9_sampling.png){: .img-center loading=lazy }
```

2024-04-19 15:06 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +En descendant vous verez Sampling. Ces options permettent de configurer le nombre de passages qu'effectuera le moteur de rendu en changeant la valeur max samples. Je vous conseille de configurer View
```suggestion
En descendant vous verrez "Sampling". Ces options permettent de configurer le nombre de passages qu'effectuera le moteur de rendu en changeant la valeur `max samples`. Je vous conseille de configurer Viewport (quand vous serez en train de travailler mais en affichant quelque chose proche du rendu) avec une valeur basse pour gagner du temps, et Render avec une valeur haute pour avoir un beau rendu final. Activer l'option Denoise dans les deux cas qui permet d'enlever du "bruit" sur les rendus. Sur l'image vous verrez ma proposition de paramétrage.
```

2024-04-19 15:06 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Enfin la chose la plus importante, Blender fonctionne beaucoup avec les raccourcis clavier. Pour ajouter un objet : `shift + A`.
```suggestion
Enfin la chose la plus importante, Blender fonctionne beaucoup avec les raccourcis clavier. Pour ajouter un objet : `Shift + A`.
```

2024-04-20 20:27 UTC, thomas-szczurek commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +- On tire la formule et on remplace par les valeurs "en dur " avec un collage spécial
Appliquer la formule sur l'ensemble de la colonne concernée, je rends ça plus clair !

2024-04-20 20:30 UTC, thomas-szczurek commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Vous vous souvenez de ces gens relous qui vous demandent des noms de dossiers/fichiers juste en alphanumériques et sans espaces mais avec des _ ? C'est pour ça.
!!! tip  semble t-il (pouvez pas synchro vos languages histoire de toujours avoir les mêmes balises pour faire ça :P )

2024-04-20 20:38 UTC, thomas-szczurek commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Et maitenant on va utiliser [GDAL_merge.py](https://GDAL.org/programs/GDAL_merge.html), le programme de GDAL permettant de fusionner des images.
Yep, j'ai reformulé

2024-04-24 09:58 UTC, mapperfr reviewed
Hop - je place une passe de plus et trace - à plus.

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Je vous ai déjà parlé de mon amour de GDAL ? Et bien on ve le ressortir avec encore une fois la commande `GDALinfo`. En effet maintenant on va donner à notre plan les dimensions de notre raster d'ele
```suggestion
Je vous ai déjà parlé de mon amour de GDAL ? Et bien on ve le ressortir avec encore une fois la commande `gdalinfo`. En effet maintenant on va donner à notre plan les dimensions de notre raster d'elevation.
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Toujours dans ce panneau de Blender, on modifie `scale` pour faire correspondre. Indiquer x 8000 / y 7000 (mon cas) donnerai un plan beaucoup trop grand, l'important est de garder le ratio. J'indique
```suggestion
Toujours dans ce panneau de Blender, on modifie `scale` pour faire correspondre. Indiquer x 8000 / y 7000 (mon cas) donnerait un plan beaucoup trop grand, l'important est de garder le ratio. J'indique donc x 0.8 et y 0.7 comme valeur pour scale.
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Toujours dans ce panneau de Blender, on modifie `scale` pour faire correspondre. Indiquer x 8000 / y 7000 (mon cas) donnerai un plan beaucoup trop grand, l'important est de garder le ratio. J'indique
```suggestion
Toujours dans ce panneau de Blender, on modifie `scale` pour faire correspondre. Indiquer x 8000 / y 7000 (mon cas) donnerai un plan beaucoup trop grand, l'important est de garder le ratio. J'indique donc x 0.8 et y 0.7 comme valeur pour `scale`.
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Je ne répeterai pas cette information mais pensez à sauvegarder ! File -> save as et enregistrez votre espace de travail au format `.blend.`
```suggestion
Je ne répeterai pas cette information mais pensez à sauvegarder ! `File > Save as`, puis enregistrez votre espace de travail au format `.blend.`
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Dans le monde réel, les substances telles que le bois, la roche, le verre ... semblent différentes les unes des autres car elles ont des couleurs, des textures, une rugosité différentes. Blender est
```suggestion
Dans le monde réel, les substances telles que le bois, la roche, le verre ... semblent différentes les unes des autres car elles ont des couleurs, des textures, une rugosité différentes. Blender est conçu pour simuler ces variations en permettant d'attribuer des propriétés reflétant ceci aux `matériaux` attribués aux objets. Les moteurs de rendus calculent ensuite l'apparence des objets ainsi que la dispersion et les rebonds de la lumière en fonction de ces `matériaux`.
```

C'est `matériaux`ou `materiaux` dans Blender? (Oui, je coupe les cheveux en quatre)

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Pour l'instant, notre plan ne possèque aucun matériau, ce pourquoi il apparait gris mat. Si vous effectuez un rendu en cliquant sur render -> render image, ou en choissant le mode de visualisation "r
```suggestion
Pour l'instant, notre plan ne possèque aucun matériau, ce pourquoi il apparaît gris mat. Si vous effectuez un rendu en cliquant sur `Render -> Render image`, ou en choissant le mode de visualisation "Rendu" dans le 3D view port, vous vous en rendrez compte.
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Pour affecter un matériau au plan, selectionnez le puis cliquez sur cette icone :
```suggestion
Pour affecter un matériau au plan, selectionnez-le puis cliquez sur cette icone :
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Puis cliquez sur `New`. Blendez créera alors un nouveau materiau nommé Material.001. Vous pouvez le renommer si vous le désirez.
```suggestion
Puis cliquez sur `New`. Blendez créera alors un nouveau matériau nommé `Material.001`. Vous pouvez le renommer si vous le désirez.
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +- Il y a beaucoup d'options pour ce `shader` : la rugosité, l'incide de refraction, la couleur ... mais pour le moment nous voulons un plan plat et réaliste, donc on touche à rien. On y reviendra plu
```suggestion
- Il y a beaucoup d'options pour ce `shader` : la rugosité, l'incide de refraction, la couleur ... mais pour le moment nous voulons un plan plat et réaliste, donc on ne touche à rien. On y reviendra plus tard.
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Les `matériaux` ne servent pas qu'à assigner une couleur ou une interaction avec la lumière. Ils peuvent aussi posséder un `displacement` / `déplacement`. Soit une déformation de leur surface. Et c'e
```suggestion
Les `matériaux` ne servent pas qu'à assigner une couleur ou une interaction avec la lumière. Ils peuvent aussi posséder un `displacement` / `déplacement`, soit une déformation de leur surface. C'est comme ça que nous allons transformer notre plan en un modèle de relief réaliste.
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Changez l'environnement de travail pour passer de "3D View port" à "Shader editor" (voir la petite présentation de Blender plus haut pour voir comment faire).
```suggestion
Changez l'environnement de travail pour passer de "3D Viewport" à "Shader Editor" (voir la petite présentation de Blender plus haut pour voir comment faire).
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Cette interface permet de régler les paramètres du `matériau` comme précédemment, mais bien plus encore. Faites bien attention à bien sélectionner votre plan en cliquant là :
```suggestion
Cette interface permet de régler les paramètres du `matériau` comme précédemment, mais bien plus encore. Faîtes bien attention à bien sélectionner votre plan en cliquant là :
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +La manière dont est rendu votre matériau est présentée sous forme d'un diagramme. Vous pouvez cliquer sur chacune des boites pour les déplacer, ainsi que vous déplacer dans la vue comme dans le 3D Vi
```suggestion
La manière dont est rendu votre matériau est présentée sous forme d'un diagramme. Vous pouvez cliquer sur chacune des boîtes pour les déplacer, ainsi que vous déplacer dans la vue comme dans le 3D View Port.
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Chaque boite est un `node` et vous verrez une ligne reliant Principle BSDF à la "Surface" de notre `matériau` final, indiquant qu'il est utilisé pour déterminer son apparence. Vous verrez que vous po
```suggestion
Chaque boîte est un `node` et vous verrez une ligne reliant "Principle BSDF" à la "Surface" de notre `matériau` final, indiquant qu'il est utilisé pour déterminer son apparence. Vous verrez que vous pouvez aussi relier quelque chose qui donnera à la surface un `displacement`.
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Depuis la barre de menu située au dessus de l'écran, choisissez Add -> Texture -> Image texture.
```suggestion
Depuis la barre de menu située au dessus de l'écran, choisissez `Add > Texture > Image Texture`.
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Une nouvelle boite apparait, positionnez la où bon vous semble. Dans le language de Blender une `texture` est une image ou un motif qui sera appliqué aux `matériaux` pour changer leur apparence. On p
```suggestion
Une nouvelle boite apparait. Positionnez-la où bon vous semble. Dans le language de Blender, une `texture` est une image ou une motif qui sera appliquée aux `matériaux` pour changer leur apparence. On pourrait ainsi charger une image de grain de bois pour faire ressembler notre plan à du bois. Mais ces texture peuvent aussi être utilisées pour générer un `displacement`.
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +- Cliquez sur `Open` dans cette boite et indiquez votre mnt.tif.
```suggestion
- Cliquez sur `Open` dans cette boite et indiquez votre `mnt.TIF`.
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Vous pouvez faire un essai de rendu en cliquant sur Render -> render image dans le menu tout en haut.
```suggestion
Vous pouvez faire un essai de rendu en cliquant sur `Render -> Render Image` dans le menu tout en haut.
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Pour repprendre les mots de l'auteur originel "Tout ceci est bâti sur un mensonge". Pour le moment Blender ne fait que **simuler** la déformation en utilisant une technique nommée _bump mapping_. C'e
```suggestion
Pour reprendre les mots de l'auteur originel : "Tout ceci est bâti sur un mensonge". Pour le moment Blender ne fait que **simuler** la déformation en utilisant une technique nommée _bump mapping_. C'est plus rapide à calculer mais pas aussi réaliste. Cette technique ne fait que donner une _apparence_ de profondeur, mais elle n'est pas réelle : aucune ombre n'est projetée et la lumière n'interagit pas avec.
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Pour l'instant ces derniers ne sont pas utilsés, Blender n'a fait que _peindre_ le relief sur le plan avec des nuances de gris. On pourrait ajouter des `vertices` à la main mais on va utiliser une au
```suggestion
Pour l'instant ces derniers ne sont pas utilisés, Blender n'a fait que _peindre_ le relief sur le plan avec des nuances de gris. On pourrait ajouter des `vertices` à la main, mais on va utiliser une autre astuce. Les `modificateurs`.
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +- Retournez dans le 3D View Port
```suggestion
- Retournez dans le `3D Viewport`
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +- Toujours bien penser à sélectionner le plan et cliquez sur l'icone en forme de clef à molette.
### 
```suggestion
- Toujours bien penser à sélectionner le plan et cliquer sur l'icône en forme de clef à molette.
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +- Et maintenant cliquez sur "Add modifier"
```suggestion
- Et maintenant, cliquer sur "Add Modifier"
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +Apparemant la communauté Blender surnomme ce modificateur "subsurf" ou "subdiv". Ne me demandez pas. Il est très utilisé et permet de dire à Blender d'ajouter du détail à un objet (ainsi il permet de
```suggestion
Apparemment, la communauté Blender surnomme ce modificateur `subsurf` ou `subdiv`. Ne me demandez pas. Il est très utilisé et permet de dire à Blender d'ajouter du détail à un objet (ainsi il permet de faire des objets très arrondies en travaillant avec des `mesh` simples).
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +- Si vous avez bien écouté au fond de la salle, vous verrez un bouton "adaptive subdivision" qu'il faut activer, sinon retournez sur la partie de présentation / configuration de Blender pour passez l
```suggestion
- Si vous avez bien écouté au fond de la salle, vous verrez un bouton "adaptive subdivision" qu'il faut activer, sinon retournez sur la partie de présentation / configuration de Blender pour passez le feature set de `Cycles` à `Expérimental`. Vous savez, celle ou j'avais indiqué "important". En gras.
```

2024-04-24 09:58 UTC, mapperfr commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +- Ce `modificateur` est non destructif, il ne modifie par réellement l'objet. C'est une pile qui s'ajoute _par dessus_ alors qu'il est toujours constitué de quatre `vertices`. Blender ne subdivisera
```suggestion
- Ce `modificateur` est non-destructif, il ne modifie par réellement l'objet. C'est une pile qui s'ajoute _par dessus_ alors qu'il est toujours constitué de quatre `vertices`. Blender ne subdivisera le plan que temporairement lors du rendu.
```

2024-04-24 14:39 UTC, thomas-szczurek commented
> Salut @thomas-szczurek! Juste pour te signaler que la review n'est pas terminée. Ça prend un peu de temps, on cale ça dans les plannings comme on peut :) Merci pour ta patience, ça va faire un bel article!

Pas de soucis @mapperfr ! j'essaye d'être réactif de mon côté  car connaissant bien l'animal je me laisserai vite envahir par la flemme ce qui aurait pour conséquence dramatique d'aboutir à un truc qui trainerait pendant des mois  mais prends/prennez le temps qu'il faut :) (oui, ça fait un beau morceau ! j'apprécie l'approche de l'auteur de ne pas juste dire "cliquez là", mais d'expliquer pourquoi on clique)

2024-05-14 09:15 UTC, Guts commented
Salut @thomas-szczurek ,

Désolé, la France était en pause sous les ponts de mai et Geotribu n'échappe pas à la règle (même en Corse wink wink).

Entre-temps, on a fait évoluer les pages auteurs et la façon d'intégrer le bloc de signature : https://contribuer.geotribu.fr/guides/authoring/.  
Pas de panique, j'ai adapté pour toi directement vu que ça ne touche pas le fond de ton article. Voilà ce que ça donne : https://preview-pullrequest-1107--geotribu-preprod.netlify.app/team/thomas-szczurek-gayant/



Pour parler de ton article justement, je pense que ce serait mieux de le scinder en 2 voire 3 parties. Qu'en penses-tu ?

2024-05-21 06:19 UTC, arno974 reviewed
Suggestions

2024-05-21 06:19 UTC, arno974 commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +![réglages lumière](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/gdal_qgis_blender//img35_light4.png){: .img-center loading=lazy }
Bizarre car cette image (et la suivante) sur le site de preview ne s'affiche pas.
Pourtant elles sont bien sur le CDN

2024-05-21 06:19 UTC, arno974 commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +# Réaliser des cartes avec Blender
Attention au poids des images dans l'articles. Elles sont souvent > à 1.5mo

2024-05-21 06:19 UTC, arno974 commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +![Là](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/gdal_qgis_blender/img6_viewports.png){: .img-center loading=lazy }
Suggestion, plutôt que de mettre des flèches à la "Paint", peut utiliser libre office ou power point pour coller l'image et faire des flèches plus sympas...

2024-05-21 07:25 UTC, thomas-szczurek commented
> Salut @thomas-szczurek ,
> 
> Désolé, la France était en pause sous les ponts de mai et Geotribu n'échappe pas à la règle (même en Corse wink wink).
> 
> Entre-temps, on a fait évoluer les pages auteurs et la façon d'intégrer le bloc de signature : https://contribuer.geotribu.fr/guides/authoring/. Pas de panique, j'ai adapté pour toi directement vu que ça ne touche pas le fond de ton article. Voilà ce que ça donne : https://preview-pullrequest-1107--geotribu-preprod.netlify.app/team/thomas-szczurek-gayant/
> 
> Pour parler de ton article justement, je pense que ce serait mieux de le scinder en 2 voire 3 parties. Qu'en penses-tu ?

Salut !
J’étais en pause moi aussi :) Ça peut se couper en deux effectivement, par exemple la première partie sur gdal qui est déjà longue en soit et prête. Par contre j’aurai dans ce cas besoin d’un peu d’aide pour annuler la pull request !

2024-05-21 07:28 UTC, thomas-szczurek commented on content/articles/2024/2024-04-14_creer_carte_blender.md
> +![Là](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/gdal_qgis_blender/img6_viewports.png){: .img-center loading=lazy }
> Suggestion, plutôt que de mettre des flèches à la "Paint", peut utiliser libre office ou power point pour coller l'image et faire des flèches plus sympas...

Salut !
Je peux peut-être regarder pour faire ça mais à condition que j'arrive à retoucher les images déjà crées car je ne possède plus les versions d'origine sans flèches et j'ai moyennement envie de me refaire les plus de 40 captures ;) (mais ça pourrai être l'occasion de voir cette question de poids des images)

2024-05-21 16:33 UTC, igeofr reviewed
Merci pour cet article @thomas-szczurek.
Juste une remarque générale, j'aurai tendance à mettre un peu plus en avant les chemins ou les variables en utilisant le rendu "code". J'ai proposé quelques modifications.

2024-05-23 08:06 UTC, Guts commented
> ut !
> J’étais en pause moi aussi :) Ça peut se couper en deux effectivement, par exemple la première partie sur gdal qui est déjà longue en soit et prête. Par contre j’aurai dans ce cas besoin d’un peu d’aide pour annuler la pull request

Salut @thomas-szczurek,

Si tu veux, on peut se prévoir un créneau en visio pour que je te guide sur les opérations git. Je préfère que tu fasses toi-même plutôt que de faire à ta place :).

Prépare donc les 2 fichiers Markdown séparés. Le mieux étant de splitter après avoir intégré les dernières remarques.

Dispo ce midi.

Concernant les images, voici les recommandations :

- maximum 1000 pixels sauf besoin spécifique (sujet de l'image peu lisible, trop grande résolution...)
- un format optimisé pour le web (.webp a la cote)

Comme dit par @igeofr https://github.com/geotribu/website/pull/1107#discussion_r1608605468, tinypng facilite grandement la vie avec compression, optimisation et conversion de format. Par contre, faut avoir redimensionné avant.

Pour redimensionner tu peux essayer d'utiliser le CLI Geotribu si t'es chaud (https://cli.geotribu.fr/usage/examples.html#optimiser-des-images-pour-le-cdn-geotribu). Par exemple pour installer le CLI dans ton dossier temporaire (je te file les commandes sur Ubuntu 20.04) :

```sh
cd /tmp
mkdir geotribu-cli
cd geotribu-cli
python3 -m venv .venv
. .venv/bin/activate
python -m pip install -U pip setuptools wheel
python -m pip install -U geotribu[img-local]
```

Puis tu lances :

```sh
geotribu images optimize {chemin dossier des images}
```

2024-05-25 10:41 UTC, thomas-szczurek commented
Ok, on va y arriver ! (oui, j'avoue être dans la période où il faut que je me force pour finir)

J'ai validé les derniers commit et me suis occupé des images (effectivement, j'avais oublié avoir fais les screens sur un écran en 2500*1400, plus tinypng ça change pas mal), et j'ai fais ce que j'ai pu pour les flèches.

J'essaye de couper l'artcle en deux avant la fin du we

2024-05-26 08:28 UTC, Guts commented
@thomas-szczurek oui on va y arriver, publions le premier article ce mardi 28 !

En séparant l'article en deux, essaie de conserver l'historique git des modifications faites ici.

2024-05-26 12:46 UTC, closed without merging