Article : création de cartes avec Blender partie 2 (traduction)
geotribu/website pull request #1132
Opened 2024-05-26 15:51 UTC by thomas-szczurek

# Amorcer une nouvelle revue de presse

- [ ] nommer cette _Pull Request_ de façon claire et lisible. Exemple : `GeoRDP du JJ MM AAAA`
- [ ] partir du modèle disponible (copier/coller) [sur Github](https://github.com/geotribu/website/blob/master/content/rdp/templates/template_rdp.md?plain=1) ou [sur le pad](https://geotripad.herokuapp.com/DCBQirjYSp6sqxPd5JYqLg?both)
- [ ] changer la date dans les métadonnées :
    - [ ] `date` : au format `AAAA-MM-JJ HH-MM` - mais laisser l'heure sur 14h20 c'est historique
    - [ ] `title` : correspond à ce qui est affiché dans le menu de navigation, l'onglet du navigateur et le SEO. Bien **indiquer l'année** pour améliorer le référencement et en prévision d'une refonte du moteur de rendu.
- [ ] changer la date du titre principal (en début de contenu). Idem, **indiquer l'année**.

## Encourager les contributions

- [ ] informer l'équipe que la prochaine RDP a été initiée en publiant le lien de la PR sur [le canal `#revues-de-presse` de Slack](https://geotribu.slack.com/archives/C010DD7FMEX)
- [ ] tweeter le lien du fichier de la RDP. Voici ci-dessous un modèle dans lequel :

- remplacer `XXXXXXXXXX` par le lien vers le fichier de la GeoRDP dans la branche créée (par exemple : <https://github.com/geotribu/website/blob/rdp/2021-02-26/content/rdp/2021/rdp_2021-02-26.md?plain=1>)
- insérer cette image dans le tweet <https://cdn.geotribu.fr/img/internal/contribution/geotribu_contribuer_rdp_github_edit.png>

```txt
Ce vendredi c'est #GeoRDP !

💡 Une idée de news ? Une envie de parler de #carte ? d'outil #SIG ? de relayer un article, un tutoriel  sur la #géographie ou la #géomatique ?

C'est par ici 👉 XXXXXXXXXX 👈
(icône 🖍️)

Modèle de news ici : https://github.com/geotribu/website/blob/master/content/rdp/templates/template_rdp_news.md
```

Exemple de [tweet](https://twitter.com/geotribu/status/1364625815099613185) :

![tweet geordp](https://cdn.geotribu.fr/img/internal/contribution/geotribu_rdp_tweet_incitation.png)

----

## Check-list de publication

### Qualité

- [ ] les news sont bien réparties dans les bonnes sections
- [ ] les sections vides sont supprimées
- [ ] vérifier le rendu de la syntaxe markdown (cf. linter)
- [ ] chasse aux coquilles orthographiques et dyslexiques

### Images

- [ ] les images téléversées sur le CDN n'ont pas de caractère spécial dans leur nom de fichier (espace, accent, etc.) et n'excédent pas 1000px de largeur
- [ ] les images sont hébergées sur des sites sécurisés (HTTPS)
- [ ] chaque news a une vignette
- [ ] les images (sauf les vignettes) ont l'attribut `loading` défini sur `lazy` (cf. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading) et [guide material-mkdocs](https://squidfunk.github.io/mkdocs-material/reference/images/#image-lazy-loading))
- [ ] accessibilité : chaque image a un texte de remplacement (entre les crochets) et un titre lisible par les outils d'assistance. Bref, qui respecte la [syntaxe générale](https://contribuer.geotribu.fr/guides/image/#syntaxe-generale)

### SEO

- [ ] `image` pointe vers l'URL d'une des images de la revue de presse
- [ ] `description` contient les mots-clés et grandes lignes du contenu (par exemple, la reprise de l'intro)

----

## Publier

1. S'assurer que la branche soit à jour par rapport à la branche principale. Le cas échéant, utiliser le bouton `Update branch` en bas.
2. S'assurer que les éléments de la check-list ci-dessus soient tous remplis
3. Fusionner (_merge_) en utilisant un _merge commit_ ou un _rebase_, mais **surtout pas un squash**.

----

## Diffuser

### Twitter

Une fois le déploiement effectué (~ 5 minutes), diffuser a minima sur Twitter :

- avec le hashtag `#GeoRDP`, en citant les contributeur/ices avec leur éventuel compte
- si possible en intégrant quelques hastags des personne, organisations ou logiciels cités dans la revue de presse
- de préférence via le compte `@geotribu` en utilisant Tweetdeck.

### LinkedIn

La diffusion sur LinkedIn est à faire avec un compte personnel. Exemple de structure :

```txt
🗞 La #GeoRDP est en ligne :

👥 Contributeur/ices : @XXXX

🌍 #Geotribu #veille #géomatique #YYYY @ZZZZ
```

2024-05-27 07:15 UTC, Guts commented
@thomas-szczurek j'ai MAJ la description des 2 PRs et passé celle-ci en draft pour éviter les gestes trop rapides.

2024-05-28 11:38 UTC, Guts commented
@geotribu/relecture @thomas-szczurek maintenant que la partie 1, ne traînons pas sur la finalisation de la partie 2.

j'ai fait une première passe pour corriger des typos, ajouter les liens mutuels entre les 2 parties, tunner les raccourcis claviers pour suivre https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd entre autres choses.

2024-05-28 11:42 UTC, thomas-szczurek commented
> @geotribu/relecture @thomas-szczurek maintenant que la partie 1, ne traînons pas sur la finalisation de la partie 2.
> 
> j'ai fait une première passe pour corriger des typos, ajouter les liens mutuels entre les 2 parties, tunner les raccourcis claviers pour suivre https://developer.mozilla.org/en-US/docs/Web/HTML/Element/kbd entre autres choses.

Ca marche merci ! J'essaye de relire ça aussi de mon côté rapidement car il doit évidemment rester queslques %§@sds!? coquilles

2024-06-18 09:51 UTC, Guts commented
:wave: Coucou @mapperfr et @thomas-szczurek !

C'est le jour J ! Tout est prêt ?

2024-06-18 10:11 UTC, mapperfr commented
Hello, dans l'ensemble c'est top, à part quelques coquilles encore (crèmerie -> crêmerie, and -> et). Pas du tout le temps de faire la review aujourd'hui, j'essaye de faire un tour de correction après publi d'ici quelques jours. Bravo et merci @thomas-szczurek pour cette super ressource!

2024-06-18 10:34 UTC, Guts requested changes

2024-06-18 10:34 UTC, Guts commented on content/articles/2024/2024-06-11_carte-relief-ombre-avec-blender-partie-2-modelisation-reglages-cartographie.md
> +date: 2024-06-11
```suggestion
date: 2024-06-18
```

Penser à renommer aussi le fichier. C'est faisable via l'interface web de github.

2024-06-18 10:34 UTC, Guts commented on content/articles/2024/2024-06-11_carte-relief-ombre-avec-blender-partie-2-modelisation-reglages-cartographie.md
> +description: "Réaliser des cartes de relief avec le logiciel libre 3D Blender. Partie 2 : préparer les données avec GDAL et/ou QGIS."
Description de la partie 2 incorrecte

2024-06-18 11:13 UTC, thomas-szczurek commented
> Hello, dans l'ensemble c'est top, à part quelques coquilles encore (crèmerie -> crêmerie, and -> et). Pas du tout le temps de faire la review aujourd'hui, j'essaye de faire un tour de correction après publi d'ici quelques jours. Bravo et merci @thomas-szczurek pour cette super ressource!

Merci ! @mapperfr , les deux coquilles signalées sont corrigées

2024-06-18 11:14 UTC, thomas-szczurek commented
Nom du fichier et description corrigée @Guts + correction des deux coquilles signalées

2024-06-18 11:17 UTC, Guts commented on content/articles/2024/2024-05-28_carte-relief-ombre-avec-blender-partie-1-preparation-donnes-avec-qgis-et-gdal.md
> +[Lire la deuxième partie :fontawesome-solid-forward:](2024-06-11_carte-relief-ombre-avec-blender-partie-2-modelisation-reglages-cartographie.md "Réaliser des cartes avec Blender - Partie 2"){: .md-bu
```suggestion
[Lire la deuxième partie :fontawesome-solid-forward:](2024-06-18_carte-relief-ombre-avec-blender-partie-2-modelisation-reglages-cartographie.md "Réaliser des cartes avec Blender - Partie 2"){: .md-button }
```

2024-06-18 11:21 UTC, Guts approved these changes
OK alors en avant.

2024-06-18 11:22 UTC, merged