Article: De la tolérance en SIG
geotribu/website pull request #1151
Opened 2024-06-26 19:43 UTC by lbartoletti

J'ouvre cette première pour faire une première relecture globale. Il devra être séparé en plusieurs parties pour la publication.

Merci à vous @geotribu/relecture :pray:

2024-06-28 11:50 UTC, Guts requested changes

2024-06-28 11:50 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Toutes les données utilisées sont disponibles sur [mon GitHub](), et pour simplifier la compréhension et la transposition de ces données dans différents SIG, j'utiliserai les formats WKB et WKT[^1].
Il manque le lien vers le Github

2024-06-28 11:50 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +<autopromo> Pour ceux qui veulent en savoir plus sur ces formats, pensez à suivre ou aimer pour être informé du prochain article dédié. </autopromo>
opter pour un encart (admonition) ?

```suggestion
!!! tip "autopromo"
    Pour ceux qui veulent en savoir plus sur ces formats, pensez à suivre ou aimer pour être informé du prochain article dédié.
```

2024-06-28 12:00 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +/assets/2024_intersection_intersects/data/processing/grass_line_overlay_points.svg)
Syntaxe pétée qui fait crasher le build

```suggestion
![grass_line_overlay_points](https://github.com/lbartoletti/lbartoletti.github.io/blob/main/assets/2024_intersection_intersects/data/processing/grass_line_overlay_points.svg)
```

2024-06-28 12:10 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Depuis quelques versions, il n'est plus possible d'avoir les traitements de SAGA directement depuis QGIS. Il faut installer le plugin [SAGA NG](lien du plugin) mais il a quelques limitations m'empêch
Manque le lien et ça fait crasher le validateur


```suggestion
Depuis quelques versions, il n'est plus possible d'avoir les traitements de SAGA directement depuis QGIS. Il faut installer le plugin [SAGA NG](https://plugins.qgis.org/plugins/processing_saga_nextgen/) mais il a quelques limitations m'empêchant de l'utiliser pour l'article.
```

2024-06-29 10:35 UTC, gounux reviewed
Salut @lbartoletti et merci de t'être donné, c'est super intéressant !

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +- **WKT (Well-Known Text)** : Le WKT est un format texte utilisé pour représenter des objets géométriques de manière lisible par l'homme. Il est souvent utilisé pour le partage et l'affichage de donn
```suggestion
- **WKT (Well-Known Text)** : Le WKT est un format texte utilisé pour représenter des objets géométriques de manière lisible par l'humain. Il est souvent utilisé pour le partage et l'affichage de données géographiques.
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Ici, j'ai utilisé `\` pour que la commande soit sur plusieurs lignes afin de simplifier la lecture de la commande ; vous pouvez évidemment tout faire sur une ligne.
Pourrait être mis dans un encart / admonition ?

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Le WKT est plus lisible, mais il a l'inconvénient de ne pas avoir toujours la même représentation. QGIS nous retourne 17 décimales et GEOS : 10 ; ce qui, dans tous les cas, est déjà trop pour du proj
```suggestion
Le WKT est plus lisible, mais il a l'inconvénient de ne pas avoir toujours la même représentation. QGIS nous retourne 17 décimales et GEOS : 10 ; ce qui, dans tous les cas, est déjà trop pour du projeté, on en reparlera plus tard.
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Ici, nous avons la représentation d'un multipoint, où les coordonnées peuvent se retrouver dans ces parties :
Je ne comprends pas la phrase

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +[<img src="https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/example_grid_line.png?raw=true" alt="Example points along line" width="349" heig
```suggestion
![Example points along line](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/example_grid_line.png?raw=true)
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Pour ceux intéressés, je reviendrai sur l'importance du calcul dans la partie algorithme.
Quid de celles intéressées ? :wink:

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Si [SAGA](https://fr.wikipedia.org/wiki/Saga_(personnage)) est le plus puissant des chevaliers du zodiaque, [SAGA GIS](https://saga-gis.sourceforge.io/en/index.html) est malheureusement bien souvent
:D

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +[<img src="https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/saga_load_shapes.png?raw=true" alt="Load shapes" width="349" height="203">](http
```suggestion
![Load shapes](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/saga_load_shapes.png?raw=true)
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +[<img src="https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/saga_map_base_line.png?raw=true" alt="Map base line" width="349" height="203">](
```suggestion
![Map base line](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/saga_map_base_line.png?raw=true)
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +[<img src="https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/saga_line_crossing.png?raw=true" alt="Line Crossing" width="349" height="203">](
```suggestion
![Line Crossing](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/saga_line_crossing.png?raw=true)
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +[<img src="https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/saga_map_crossing.png?raw=true" alt="Map crossing" width="349" height="203">](ht
```suggestion
![Map crossing](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/saga_map_crossing.png?raw=true)
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +[<img src="https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/saga_select_crossing_base.png?raw=true" alt="Select crossing base" width="349" h
```suggestion
![Select crossing base](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/saga_select_crossing_base.png?raw=true
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +<insérer images/saga_select_crossing_base.png>
```suggestion

```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +[<img src="https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/saga_select_crossing_base_error.png?raw=true" alt="Select crossing base error" w
```suggestion
![Select crossing base error](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/saga_select_crossing_base_error.png?raw=true)
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +[<img src="https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/saga_select_crossing_base_poly.png?raw=true" alt="Select crossing base poly" wid
```suggestion
![Select crossing base poly](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/saga_select_crossing_base_poly.png?raw=true)
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +[<img src="https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/saga_select_base_test_line.png?raw=true" alt="Select base test line" width="349"
```suggestion
![Select base test line](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/saga_select_base_test_line.png?raw=true)
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +< insérer image avec break>
ah

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +< insérer gif>
manque gif

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +<insérer image>
manque image

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +<insérer image>
manque image

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +![](https://github.com/lbartoletti/lbartoletti.github.io/blob/e2a7c896516af05da86d079c589edda415471e83/assets/2024_intersection_intersects/data/processing/qgis_segments_azimuth.svg?raw=true)
manque le alt-text

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +> Les coordonnées des géométries ont une représentation en nombre rationnel exact et peuvent être en 2D ou en 3D.
Pourquoi pas dans un encart / admonition ?

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +![](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/fme_test_intersects.png?raw=true)
manque le alt-text

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +- MultiPoint ((1981640.78490000218153 5199258.02210000157356262),(1981583.62060000002384186 5199333.30189999938011169))
```suggestion
- `0104000000020000000101000000e034efc8c83c3e4120166a8166d55341010100000040a4df9e8f3c3e416054525379d55341`
- `MultiPoint ((1981640.78490000218153 5199258.02210000157356262),(1981583.62060000002384186 5199333.30189999938011169))`
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Les ordinateurs utilisent majoritairement une représentation en [virgule flottante](https://fr.wikipedia.org/wiki/Virgule_flottante) pour stocker des nombres réels. C'est même, la norme pour les coor
```suggestion
Les ordinateurs utilisent majoritairement une représentation en [virgule flottante](https://fr.wikipedia.org/wiki/Virgule_flottante) pour stocker des nombres réels. C'est même la norme pour les coordonnées de nos géométries. Ce fameux double que l'on retrouve de partout. Toutefois son utilisation peut introduire des erreurs d'arrondi. J'ai indiqué une opération en introduction, 0.1 + 0.2 != 0.3. Comme 0.3 ne peut pas être représenté exactement cela conduit à des approximations. C'est un problème connu des informaticiens, au point d'avoir [son propre site](https://0.30000000000000004.com/).
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +### l'accumulation d'erreurs
```suggestion
### L'accumulation d'erreurs
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Des solutions comme GEOS ou Clipper (pour SAGA), repose sur des calculs bien plus robuste que notre exemple ; d'ailleurs, elles passent également par des entiers. Le calcul de l'intersection va être
```suggestion
Des solutions comme GEOS ou Clipper (pour SAGA), repose sur des calculs bien plus robustes que notre exemple ; d'ailleurs, elles passent également par des entiers. Le calcul de l'intersection va être juste - à la précision du float.
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Une solution, qui n'est pas élégante et donc pas encore implémentée, serait d'avoir des fonctions qui s'enchaînent et ne fasse pas continuellement des va et vient entre les nombres. Avec une fonction
```suggestion
Une solution, qui n'est pas élégante et donc pas encore implémentée, serait d'avoir des fonctions qui s'enchaînent et ne fassent pas continuellement des va et vient entre les nombres. Avec une fonction CG_IntersectsIntersection comme suit, le résultat dans PostGIS sera juste.
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Plus généralement, vous pouvez exécuter ce [mini script python](https://github.com/lbartoletti/lbartoletti.github.io/blob/e2a7c896516af05da86d079c589edda415471e83/assets/2024_intersection_intersects/
```suggestion
Plus généralement, vous pouvez exécuter ce [mini script python](https://github.com/lbartoletti/lbartoletti.github.io/blob/e2a7c896516af05da86d079c589edda415471e83/assets/2024_intersection_intersects/data/intersects_intersection_numbers.py) qui résume ce que l'on a vu.
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Tout d'abord, rendons à César ce qui est à César, cette suite d'articles, n'est qu'une explication illustrée de la [FAQ](https://locationtech.github.io/jts/jts-faq.html) de JTS ; qui est à l'origine
```suggestion
Tout d'abord, rendons à César ce qui est à César, cette suite d'articles, n'est qu'une explication illustrée de la [FAQ](https://locationtech.github.io/jts/jts-faq.html) de JTS ; qui est à l'origine de GEOS. Mais, comme personne ne lit la documentation :wink: autant remettre le lien [ici](https://locationtech.github.io/jts/jts-faq.html#D8).
```

2024-06-29 10:35 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +J'espère que cette série d'articles vous a intéressés. D'autres sur la comparaison entre les outils devraient venir.
```suggestion
J'espère que cette série d'articles vous a intéressé. D'autres sur la comparaison entre les outils devraient venir.
```

2024-07-02 04:56 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Ces questions reflètent des préoccupations courantes parmi les utilisateurs de SIG, qui s'attendent à une exactitude et à une précision rigoureuses. Mais, les 3 R : rigueur, rigueur, rigueur, cher à
@gounux en relisant, je préfère presque mettre les 3 rigueurs entre guillements, et écrire : cette citation chère à ...

Tu en penses quoi ?

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +subtitle: Fenêtre ou ne pas fenêtre, telle est la question
oups. C'est obligé le sous-titre ?

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Toutes les données utilisées sont disponibles sur [mon GitHub](), et pour simplifier la compréhension et la transposition de ces données dans différents SIG, j'utiliserai les formats WKB et WKT[^1].
```suggestion
Toutes les données utilisées sont disponibles sur [mon GitHub](https://github.com/lbartoletti/lbartoletti.github.io/tree/master/assets/2024_intersection_intersects), et pour simplifier la compréhension et la transposition de ces données dans différents SIG, j'utiliserai les formats WKB et WKT[^1].
```

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +![](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/fr_line_snap_intersects_base.png?raw=true)
```suggestion
![line snap intersects base](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/fr_line_snap_intersects_base.png?raw=true)
```

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +![](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/selected_line_snap.png?raw=true)
```suggestion
![selected line snap](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/selected_line_snap.png?raw=true)
```

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Ici, j'ai utilisé `\` pour que la commande soit sur plusieurs lignes afin de simplifier la lecture de la commande ; vous pouvez évidemment tout faire sur une ligne.
La partie shell ?

Tu peux me rappeler la syntaxe stp ?

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Ici, nous avons la représentation d'un multipoint, où les coordonnées peuvent se retrouver dans ces parties :
Est-ce que cette phrase est plus compréhensible ?
```suggestion
Ce WKB est la représentation d'un multipoint. On peut en extraire les coordonnées des deux points suivants :
```

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Pour ceux intéressés, je reviendrai sur l'importance du calcul dans la partie algorithme.
Je pense globalement avoir écrit de façon neutre, mais je n'utiliserai pas d'écritures inclusives, mais OK pour ajouter le féminin comme il se doit 😉 

```suggestion
Pour celles et ceux que cela intéresse, je reviendrai sur l'importance du calcul dans la partie algorithme.
```

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +< insérer image >
```suggestion
![GRASS line overlay](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/data/processing/grass_line_overlay_points.svg?raw=true)
```

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +< insérer image avec break>
```suggestion
```suggestion
![GRASS line overlay clean](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/data/processing/grass_select_line_clean_points.svg?raw=true)
```
```

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +< insérer image avec break>
J'ai ajouté les SVG du processing. Bon, l'export de QGIS n'est pas excellent :/
à voir pour faire une copie d'écran à la place.

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +< insérer gif>
```suggestion
```

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +< insérer gif>
En fait, il n'y en a pas ici

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +<insérer image>
```suggestion
```

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +<insérer image>
```suggestion
```

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +<insérer image>
Pareil, pas d'image finalement

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +<insérer image>
pareil

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +![](https://github.com/lbartoletti/lbartoletti.github.io/blob/e2a7c896516af05da86d079c589edda415471e83/assets/2024_intersection_intersects/data/processing/qgis_segments_azimuth.svg?raw=true)
```suggestion
![QGIS segments azimuth](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/data/processing/qgis_segments_azimuth.svg?raw=true)
```

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +> Les coordonnées des géométries ont une représentation en nombre rationnel exact et peuvent être en 2D ou en 3D.
Je te laisse voir ce qui est le mieux pour la lecture :)

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +![](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/fme_test_intersects.png?raw=true)
```suggestion
![FME test intersects](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/images/fme_test_intersects.png?raw=true)
```

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Et voilà, "l'imprécision" des doubles nous donne ce mauvais résultat.
```suggestion
Et, voilà, « l'imprécision » des doubles nous donne ce mauvais résultat.
```

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +![Canvas select transect](https://github.com/lbartoletti/lbartoletti.github.io/blob/40c1b2bf53b7842b3a86eb009525578fe492efd8/assets/2024_intersection_intersects/selected_transect_left_right.png?raw=t
```suggestion
![Canvas select transect](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/selected_transect_left_right.png?raw=true)
```

2024-07-02 05:25 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +- [Le constat : les calculs ne sont pas bons](https://pad.oslandia.net/wa9nxItyS3S9IJMUD2KVDw) ;
Ici, c'est lien vers mon brouillon interne.

Je propose de supprimer les liens. On peut rajouter les liens à chaque parution de partie ? @Guts @gounux

2024-07-02 05:44 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +
```suggestion
| cg_intersects | cg_intersects |      cg_distance       |     cg_distance      |
|---------------|---------------|------------------------|----------------------|
|  f            | f             | 3.0508500689910857e-10 | 1.72344247851053e-10 |

```

2024-07-02 06:09 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +- [Le constat : les calculs ne sont pas bons](https://pad.oslandia.net/wa9nxItyS3S9IJMUD2KVDw) ;
Bien sûr.

2024-07-02 06:19 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +subtitle: Fenêtre ou ne pas fenêtre, telle est la question
Pas obligatoire je crois, mais si t'as un jeu de mot ou une ref en tête :wink: 

![image](https://github.com/geotribu/website/assets/40383801/9d44de7b-1131-434c-a5cd-a29365cdd6db)

2024-07-02 06:20 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Ces questions reflètent des préoccupations courantes parmi les utilisateurs de SIG, qui s'attendent à une exactitude et à une précision rigoureuses. Mais, les 3 R : rigueur, rigueur, rigueur, cher à
J'en pense pas moins

2024-07-02 06:22 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Ici, j'ai utilisé `\` pour que la commande soit sur plusieurs lignes afin de simplifier la lecture de la commande ; vous pouvez évidemment tout faire sur une ligne.
```suggestion
Ici, j'ai utilisé `\` pour que la commande soit sur plusieurs lignes afin de simplifier la lecture de la commande ; vous pouvez évidemment tout faire sur une ligne.

!!! tip
    Ici, j'ai utilisé `\` pour que la commande soit sur plusieurs lignes afin de simplifier la lecture de la commande ; vous pouvez évidemment tout faire sur une ligne.
```

Tout est documenté sur geotribu !
https://contribuer.geotribu.fr/guides/admonition/

2024-07-02 06:29 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +subtitle: Fenêtre ou ne pas fenêtre, telle est la question
D'ailleurs si tu le souhaites c'est sympa aussi de choisir une petite icône

https://contribuer.geotribu.fr/guides/icone_page/

2024-07-02 06:29 UTC, gounux commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +icon:
D'ailleurs c'est sympa aussi de choisir une petite icône

https://contribuer.geotribu.fr/guides/icone_page/

2024-07-02 06:54 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +subtitle: Fenêtre ou ne pas fenêtre, telle est la question
[La vraie tolérance consiste à voir large sans perdre la mesure.](https://citations.ouest-france.fr/citation-anne-barratin/vraie-tolerance-consiste-voir-large-106909.html) irait très bien et ce n'est pas du barratin mais du Barratin ! #désolé

2024-07-02 07:35 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Ces questions reflètent des préoccupations courantes parmi les utilisateurs de SIG, qui s'attendent à une exactitude et à une précision rigoureuses. Mais, les 3 R : rigueur, rigueur, rigueur, cher à
```suggestion
Ces questions reflètent des préoccupations courantes parmi les utilisateurs de SIG, qui s'attendent à une exactitude et à une précision rigoureuses. La maxime "rigueur, rigueur, rigueur", si chère à l'un de mes anciens chefs, n'est pas toujours… de rigueur sur nos ordinateurs.
```

2024-07-02 07:35 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +- [La conclusion : comment arrêter de trop penser et vivre une vie meilleure !](https://pad.oslandia.net/Y_3yENWdR6GL63LDPlYmnQ)
```suggestion
- Le constat : les calculs ne sont pas bons ;
- Fonctionnement Interne de QGIS et GEOS : comment ces outils gèrent-ils les données et les opérations géométriques ;
- Et les autres SIG Open Source ? Comparaisons avec GRASS et SAGA ;
- Et dans les bases de données ? Comparaisons de SQL Server, Oracle et PostGIS ;
- Utilisation de la Topologie : est-ce que la topologie peut nous sauver ? ;
- Approche alternative : exploration de méthodes alternatives telles que l'utilisation de SFCGAL pour des calculs plus robustes ;
- Et chez la concurrence, ça se passe comment ? ;
- Algorithmes et Code : comment cela fonctionne-t-il ? Cette partie sera optionnelle, pour ceux ne voulant pas voir de code ;
- La conclusion : comment arrêter de trop penser et vivre une vie meilleure !
```

2024-07-02 07:49 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +subtitle: Fenêtre ou ne pas fenêtre, telle est la question
```suggestion
subtitle: La vraie tolérance consiste à voir large sans perdre la mesure (c) Barratin
```

2024-07-03 18:55 UTC, Guts commented
J'ai optimisé les images et les ai déposées dans ce dossier : https://cdn.geotribu.fr/tinyfilemanager.php?p=articles-blog-rdp%2Farticles%2F2024%2Fgeometrie_tolerance_sig (accès en lecture : https://contribuer.geotribu.fr/guides/cdn-images-recherche/)

J'entame l'édition de l'article pour adapter les chemins puis je ferai le découpage. Pfiou...

2024-07-06 15:18 UTC, Michael-cd30 reviewed
Je termine une première review sachant que je vais attaquer la lecture du test avec les BDD.
Quelques remarques, rien de bien méchant.

Super intéressant jusque là.

2024-07-06 15:18 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +La couche `base` est une polyligne fermée, elle sera utilisée pour être convertie en polygone. Pour les puristes, on regardera que les coordonnées du WKB sont bien identiques entre le linestring et l
```suggestion
La couche `base` est une polyligne fermée, elle sera utilisée pour être convertie en polygone. Pour les puristes, on regardera que les coordonnées du WKB sont bien identiques entre le linestring et le (multi)polygone. Il y a plusieurs façons de procéder, mais, pour rendre accessible à tous, nous allons utiliser GRASS via QGIS, j'utilise les premières conversions dans QGIS ; ensuite, nous utiliserons uniquement les outils de GRASS.
```

2024-07-06 15:18 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +On remarque que nos points d'origines sont dans les deux cas :
Je remarque qu'ici tu mets un "s" à origines mais pas plus bas...je ne sais pas s'il le faut...

2024-07-06 15:18 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +En effet, on retrouve bien les coordonnées d'origine :
origineS ?

2024-07-06 15:18 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Très bien. Est-ce que le point intersecte ou touche une des géométries d'origine ?
origineS ?

2024-07-06 15:18 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +D'ailleurs, demandons à GEOS où se trouvent les points sur nos géométries d'origine.
origineS ?

2024-07-06 15:18 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Comme pour les autres, nous allons réaliser les points d'intersection entre `line` et `base`, puis tester si ceux-ci intersectent les géométries d'origine et également, combien de lignes de `test_lin
origineS ?

2024-07-06 15:18 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Oui, celui que l'on attend ! Enfin ! Tant sur la `base` que sur la `line`, les points d'intersection intersectent bien les géométries d'origine !
origineS ?

2024-07-06 15:18 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Les nouveaux segments ne sont pas « alignés » comme le segment d'origine. De rien du tout, en vrai, car si on convertit ces angles en degrés, on obtient 4 valeurs, identiques à nos segments d'origine
origineS ?

2024-07-06 15:18 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Première étape, vérifier, le calcul d'intersection. Dans le vocabulaire de SAGA, l'intersection entre lignes, s'appelle "Crossing".
```suggestion
Première étape, vérifier le calcul d'intersection. Dans le vocabulaire de SAGA, l'intersection entre lignes s'appelle "Crossing".
```

2024-07-06 15:18 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +L'algorithme de SAGA, qui rappelons-le, n'utilisant pas GEOS retourne le même résultat. Très bien !
```suggestion
L'algorithme de SAGA qui, rappelons-le, n'utilise pas GEOS retourne le même résultat. Très bien !
```

2024-07-06 21:52 UTC, Michael-cd30 reviewed
Seconde partie de review...j'ai eu un peu plus de mal à suivre.

Peut-être est-ce l'heure tardive mais j'ai trouvé cela un peu plus confus, notamment sur la partie qui évoque la topologie. Je comprends que l'édition topologique ajoute des sommets pour faire coïncider les géométries (une sorte de ST_SNAP) mais je trouve que ce n'est pas explicitement dit. Peut-être faudrait-il ajouter des illustrations de base vs base_topology vues sous QGIS.

Me reste à faire la review de SFCGAL à la fin.

2024-07-06 21:52 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Si vous avez bien suivi les parties précédentes, vous savez que PostGIS va utiliser GEOS pour réaliser la plupart de ses opérations.
Lorsque l'article sera découpé, il pourrait être intéressant de mettre un lien vers la partie qui parle de ça, j'imagine qu'il est fait référence à l'illustration CrunchyData

2024-07-06 21:52 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> + SELECT ST_Intersection(base, line) FROM ST_GeomFromWKB(decode('0102000000050000007997c6b68d3c3e4139eb62c260d55341ac9ea7316a3c3e41cbeb40e073d55341403e0bfbc33c3e41b3fc06f380d55341387a2a800c3d3e41f256b
Peut-être mettre cette requête (et les suivantes) sur plusieurs lignes ?

2024-07-06 21:52 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Le résultat d'intersects est faux, et pourtant pour un des cas, la distance est égale à 0. Intéressant, est-ce vraiment un zéro ou tellement proche de 0, que ça retourne 0 ? Sinon, le second, est éga
```suggestion
Le résultat d'intersects est faux, et pourtant pour un des cas, la distance est égale à 0. Intéressant, est-ce vraiment un zéro ou tellement proche de 0, que ça retourne 0 ? Sinon, le second, est égal à celui de GEOS : 2.3283064365386963e-10
```

2024-07-06 21:52 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Je vais légèrement adapter la requête, grâce à des CTE, pour plus de lisibilité par la suite.
```suggestion
Je vais légèrement adapter la requête, grâce à des [CTE](https://www.postgresql.org/docs/current/queries-with.html), pour plus de lisibilité par la suite.
```

2024-07-06 21:52 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +`"{2005,null,null,{1,1,2},{1981583.62057374,5199333.30187808,1981640.78490601,5199258.0220884}}",
Difficile de faire le lien entre la requête et le résultat. Ne pourrais-tu pas utiliser une représentation en tableau comme cela est fait en première partie ?

2024-07-06 21:52 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Je ne vais pas m'étendre sur le WKB qui est « étrange », il est en Big Endian, alors que jusqu'à présent, je n'ai eu que du Little Endian ; encore une fois plus d'explications dans l'article sur le W
Un petit hyperlien vers une description de Big/Little Endian ?

2024-07-06 21:52 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Je ne vais pas m'étendre sur le WKB qui est « étrange », il est en Big Endian, alors que jusqu'à présent, je n'ai eu que du Little Endian ; encore une fois plus d'explications dans l'article sur le W
De mon point de vue la même phrase...et accord de lié avec différences.

```suggestion
Je ne vais pas m'étendre sur le WKB qui est « étrange », il est en Big Endian, alors que jusqu'à présent, je n'ai eu que du Little Endian ; encore une fois plus d'explications dans l'article sur le WKB/WKT. Néanmoins, on a quelques différences entre ceux-ci, sans-doute liées à la précision du résultat ; n'étant pas expert ORACLE, il me manque des éléments de compréhension et des tests à mener.
```

2024-07-06 21:52 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Pour utiliser la topologie, nous allons faire l'union de nos deux lignes de `base` et `line` pour ensuite nettoyer celles-ci.
Je ne comprends pas ce que l'on entend par "nettoyer"...ce qui revient à poser la question, mais que fait v.clean ?

2024-07-06 21:52 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +QGIS est spaghetti. Les données sont toutes dans ce plat de pâtes : les entités géographiques sont stockées individuellement sans relations topologiques explicites. Mais, bien que QGIS utilise un mod
Est-ce vraiment QGIS qui est spaghetti ou le stockage ? Il se passerait quoi si je manipulais sous QGIS un fichier TopoJSON...si tant est que ce soit possible.

2024-07-06 21:52 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +- sommets plus importants ;
```suggestion
- nombre de sommets plus important ;
```

2024-07-06 21:52 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Dans la première partie, j'ai écrit que le point que la distance du point par rapport à la géométrie d'origine était proche de zéro, mais pas exactement 0.
```suggestion
Dans la première partie, j'ai écrit que la distance du point par rapport à la géométrie d'origine était proche de zéro, mais pas exactement 0.
```

2024-07-08 04:12 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +On remarque que nos points d'origines sont dans les deux cas :
```suggestion
On remarque que nos points d'origine sont dans les deux cas :
```

il ne faut pas de 's'

2024-07-08 04:14 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Si vous avez bien suivi les parties précédentes, vous savez que PostGIS va utiliser GEOS pour réaliser la plupart de ses opérations.
Oui, c'est bien ça

2024-07-08 04:17 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +`"{2005,null,null,{1,1,2},{1981583.62057374,5199333.30187808,1981640.78490601,5199258.0220884}}",
C'est vrai qu'ici, il n'y a pas de tableau, mais chaque ligne du select a sa ligne de résultat ; hormis les deux dernières.

La première ligne où tu as fait le commentaire, c'est vraiment la ligne du point d'intersection avec la représentation interne d'Oracle, qui est surprenante quand on est habitué, comme moi, à PostGIS.

2024-07-08 04:20 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Je ne vais pas m'étendre sur le WKB qui est « étrange », il est en Big Endian, alors que jusqu'à présent, je n'ai eu que du Little Endian ; encore une fois plus d'explications dans l'article sur le W
Où une note de bas de page ? Est-ce que cela te va : 

Big et Little Endian, ou en Français, gros- et petit-boutisme, sont l'ordre dans lequel les octets sont placés. Pour plus d'informations, je vous invite à regarder la page [Wikipedia](https://fr.wikipedia.org/wiki/Boutisme)

2024-07-08 04:28 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Pour utiliser la topologie, nous allons faire l'union de nos deux lignes de `base` et `line` pour ensuite nettoyer celles-ci.
L'utilisation de l'outil "break" de` v.clean `dans ce cas précis sert à "nettoyer" les données en réalisant une opération topologique :

Que fait la fonction "break" ?

- Cela découpe les lignes à leurs points d'intersection.
- Cela crée de nouveaux nœuds aux endroits où les lignes se croisent.

On parle de nettoyage, car, initialement, les lignes de 'base' et 'line' se croisent sans être réellement connectées topologiquement. Le "nettoyage" consiste à établir une véritable connexion topologique à ces intersections.

Dans notre cas, en appliquant "break" après l'union des lignes, on force GRASS à reconnaître et à matérialiser les points d'intersection ; cela transforme de simples croisements géométriques en nœuds topologiques explicites.

Cela permet d'exploiter ensuite la structure topologique de GRASS pour identifier facilement ces points d'intersection.

2024-07-08 04:29 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +QGIS est spaghetti. Les données sont toutes dans ce plat de pâtes : les entités géographiques sont stockées individuellement sans relations topologiques explicites. Mais, bien que QGIS utilise un mod
Aujourd'hui ce n'est pas possible.

QGIS va savoir fait de l'édition topologique, mais en effet, c'est plutôt le stockage qui est spaghetti.

2024-07-08 04:31 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +- Le constat : les calculs ne sont pas bons ;
C'est mon conservatisme de la ligue du retour des ";"

Cela dit, ici, j'ai fait une erreur. Si j'utilise les ";", il ne doit pas y avoir de majuscule au début des tirets.

source https://dictionnaire.lerobert.com/guide/enumeration-quelles-sont-les-regles-de-ponctuation

2024-07-08 04:32 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +- La conclusion : comment arrêter de trop penser et vivre une vie meilleure !
```suggestion
- Le constat : les calculs ne sont pas bons.
- Fonctionnement Interne de QGIS et GEOS : comment ces outils gèrent-ils les données et les opérations géométriques.
- Et les autres SIG Open Source ? Comparaisons avec GRASS et SAGA.
- Et dans les bases de données ? Comparaisons de SQL Server, Oracle et PostGIS.
- Utilisation de la Topologie : est-ce que la topologie peut nous sauver ?
- Approche alternative : exploration de méthodes alternatives telles que l'utilisation de SFCGAL pour des calculs plus robustes.
- Et chez la concurrence, ça se passe comment ?
- Algorithmes et Code : comment cela fonctionne-t-il ? Cette partie sera optionnelle, pour ceux ne voulant pas voir de code.
- La conclusion : comment arrêter de trop penser et vivre une vie meilleure !
```

2024-07-08 07:56 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +line\_snap:
corrigé, merci

2024-07-09 20:30 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +`"{2005,null,null,{1,1,2},{1981583.62057374,5199333.30187808,1981640.78490601,5199258.0220884}}",
En fait ce sont ces accolades qui perturbent la lecture....je n'arrivais pas à identifier le séparateur de champ et je viens de comprendre que c'est la virgule.
Peut-être que cela aiderait d'aller à la ligne après chaque virgule juste pour rendre le truc plus lisible.

2024-07-09 20:32 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Pour utiliser la topologie, nous allons faire l'union de nos deux lignes de `base` et `line` pour ensuite nettoyer celles-ci.
C'est plus clair et je pense que ce serait un plus de proposer cette explication dans l'article.

2024-07-09 21:17 UTC, Michael-cd30 reviewed
Me reste à faire la partie code et la conclusion.

2024-07-09 21:17 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Ce qu'il faut comprendre, c'est que SFCGAL peut donner le résultat correct, à condition de rester dans sa numérotation ou d'avoir des nombres qui sont finis ou dans la plage de valeur des doubles.
Je ne pense pas que le terme numérotation soit adapté, je propose "modèle de représentation des nombres" mais si quelqu'un trouve mieux...

2024-07-09 21:17 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Il existerait une façon de rendre le calcul correct dans PostGIS avec SFCGAL, mais ce n'est pas encore implémenté.
Quid de l'intérêt de SFCGAL dans PostGIS ?

2024-07-09 21:17 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +On ne va pas tous les faire, mais seulement deux un peu connus et installé parfois à côté de QGIS :wink:
```suggestion
On ne va pas tous les faire, mais seulement deux un peu connus et installés parfois à côté de QGIS :wink:
```

2024-07-09 21:17 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Sauf erreur de ma part, ArcGis ne sait pas ouvrir les fichiers GeoPackage. Qu'importe, nous utiliserons le bon vieux ShapeFile qui sera importé dans une GeoDatabase.
ArcGis
![Au bûcher](https://kaamelott-gifboard.fr/gifs/au-bucher.gif) !

2024-07-09 21:17 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +- 01040000000200000001010000008016d99e8f3c3e416054525379d553410101000000e034efc8c83c3e4120166a8166d55341
```suggestion
- `01040000000200000001010000008016d99e8f3c3e416054525379d553410101000000e034efc8c83c3e4120166a8166d55341`
```

2024-07-09 21:17 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +- MultiPoint ((1981583.62049999833106995 5199333.30189999938011169),(1981640.78490000218153 5199258.02210000157356262))
```suggestion
- `MultiPoint ((1981583.62049999833106995 5199333.30189999938011169),(1981640.78490000218153 5199258.02210000157356262))`
```

2024-07-09 21:17 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +- MultiPoint ((1981640.78490600734949112 5199258.02208840474486351),(1981583.6205737441778183 5199333.30187807604670525))
```suggestion
- `MultiPoint ((1981640.78490600734949112 5199258.02208840474486351),(1981583.6205737441778183 5199333.30187807604670525))`
```

2024-07-09 21:17 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +- 0104000000020000000101000000a099efc8c83c3e417ce5698166d553410101000000c0ebdd9e8f3c3e416cf8515379d55341
```suggestion
- `0104000000020000000101000000a099efc8c83c3e417ce5698166d553410101000000c0ebdd9e8f3c3e416cf8515379d55341`
```

2024-07-10 04:50 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Ce qu'il faut comprendre, c'est que SFCGAL peut donner le résultat correct, à condition de rester dans sa numérotation ou d'avoir des nombres qui sont finis ou dans la plage de valeur des doubles.
```suggestion
Ce qu'il faut comprendre, c'est que SFCGAL peut donner le résultat correct, à condition de rester dans son modèle de représentation des nombres ou d'avoir des nombres qui sont finis ou dans la plage de valeur des doubles.
```

2024-07-10 04:50 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Ce qu'il faut comprendre, c'est que SFCGAL peut donner le résultat correct, à condition de rester dans sa numérotation ou d'avoir des nombres qui sont finis ou dans la plage de valeur des doubles.
Bonne idée, merci.

2024-07-10 04:51 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Il existerait une façon de rendre le calcul correct dans PostGIS avec SFCGAL, mais ce n'est pas encore implémenté.
Ici, c'est pour forcer le trait. Cela peut très bien se passer dans certains cas. Mais, le gros avantage de SFCGAL dans PostGIS, ce sont les algorithmes 2D avancés et 3D que ne possède pas et ne possèdera pas GEOS/PostGIS de base.

2024-07-13 13:38 UTC, Guts commented
Hop hop hop, grâce à @sylvainbeo on a une illustration pour la série d'été : https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/geometrie_tolerance_sig/splash_serie_geometrie_annonce.png

2024-07-13 16:06 UTC, lbartoletti commented
> Hop hop hop, grâce à @sylvainbeo on a une illustration pour la série d'été : https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/geometrie_tolerance_sig/splash_serie_geometrie_annonce.png

Merci @sylvainbeo, elle est juste parfaite 😍

2024-07-14 13:33 UTC, igeofr reviewed
J'ai relu en diagonal et fait quelques propositions sur la forme mais je tiens à te remercier pour la qualité de cet article @lbartoletti 👏

Ton article m'a aussi rappelé certaines divergences auxquelles j'avais été confronté il y a quelques années en faisant des conversions tab/shp 😉

2024-07-14 13:33 UTC, igeofr commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Le titre donne directement la conclusion, mais c'était déjà annoncé.
```suggestion
### PostGIS, même résultat que GEOS

![logo PostGIS](https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/postgis.jpg){: .img-thumbnail-left }

Le titre donne directement la conclusion, mais c'était déjà annoncé.
```

2024-07-14 13:33 UTC, igeofr commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +La syntaxe SQL Server est différente de celle de PostGIS, mais assez lisible. La « grosse » différence est l'ajout du « 0 x » dans le WKB d'entrée. Il s'agit en fait de sa représentation hexadécimale
```suggestion
### Microsoft SQL Server

![logo MS SQL Server](https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/microsoft_sql_server.png){: .img-thumbnail-left }

La syntaxe SQL Server est différente de celle de PostGIS, mais assez lisible. La « grosse » différence est l'ajout du « 0 x » dans le WKB d'entrée. Il s'agit en fait de sa représentation hexadécimale ; plus d'informations dans le prochain article.
```

2024-07-14 13:33 UTC, igeofr commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +ORACLE va nous donner des éléments intéressants. Passons directement à la requête :
```suggestion
### ORACLE Spatial

![logo ORACLE](https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/oracle.png){: .img-thumbnail-left }

ORACLE va nous donner des éléments intéressants. Passons directement à la requête :
```

2024-07-14 13:33 UTC, igeofr commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Pour FME, pas de blabla. J'insère les WKB, je fais une test d'intersection et je regarde si les points intersectent `line` et `base`.
```suggestion
### FME

![logo FME](https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/FME.png){: .img-thumbnail-left }

Pour FME, pas de blabla. J'insère les WKB, je fais une test d'intersection et je regarde si les points intersectent `line` et `base`.
```

2024-07-14 13:33 UTC, igeofr commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Comme pour QGIS, nous allons tester notre problème de deux façons : par les traitements via une couche SIG et directement avec le WKB.
```suggestion
### ESRI ArcGis Pro

![logo ArcGis Pro](https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/arcgis_pro.png){: .img-thumbnail-left }

Comme pour QGIS, nous allons tester notre problème de deux façons : par les traitements via une couche SIG et directement avec le WKB.
```

2024-07-14 13:33 UTC, igeofr commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Disclaimer : Cet article s'adresse à tous les géomaticiens, quel que soit leur niveau de compétence. Cependant, ceux qui sont déjà familiers avec les erreurs comme 0.1 + 0.2 != 0.3 ne trouveront peut
```suggestion
## Algorithmes et Code : comment cela fonctionne-t-il ?

![logo console terminal](https://cdn.geotribu.fr/img/logos-icones/divers/ligne_commande.png){: .img-thumbnail-left }

Disclaimer : Cet article s'adresse à tous les géomaticiens, quel que soit leur niveau de compétence. Cependant, ceux qui sont déjà familiers avec les erreurs comme 0.1 + 0.2 != 0.3 ne trouveront peut-être pas de nouvelles informations ici. Encore une fois, j'essaie de vulgariser. Si une version plus détaillée vous intéresse, je peux essayer d'en faire une.
```

2024-07-14 13:33 UTC, igeofr commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +On a souvent ces interrogations sur les « irrégularités » rencontrées lors des opérations courantes dans les SIG : pourquoi les accrochages dans QGIS ne se positionnent-ils pas toujours exactement su
```suggestion
## Comment arrêter de trop penser et vivre une vie meilleure !

![Globe cerveau](https://cdn.geotribu.fr/img/internal/icons-rdp-news/mentale.png){: .img-thumbnail-left }

On a souvent ces interrogations sur les « irrégularités » rencontrées lors des opérations courantes dans les SIG : pourquoi les accrochages dans QGIS ne se positionnent-ils pas toujours exactement sur la géométrie ? Pourquoi les calculs de superposition manquent-ils de précision ? Et pourquoi les résultats peuvent-ils être incohérents ?
```

2024-07-14 13:33 UTC, igeofr commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +En lien avec le nombre de chiffres après la virgule, vous pouvez également ajouter une tolérance. En France, les gestionnaires de réseaux savent qu'on les caractérise suivant 3 classes : A, B ou C. 1
```suggestion
En lien avec le nombre de chiffres après la virgule, vous pouvez également ajouter une tolérance. En France, les gestionnaires de réseaux savent qu'on les caractérise suivant 3 classes : A, B ou C. 10 cm, 40 cm, etc. Une bonne pratique est de se demander si le point n'est pas à une distance d'environ X cm. Sur PostGIS, cela va se caractériser par l'utilisation de `ST_DWithin` plutôt qu'un `ST_Intersects`.
```

2024-07-14 20:24 UTC, Michael-cd30 reviewed
Et voilà lecture terminée.
Gros GROS **GROS** taff.
Bravo !

2024-07-14 20:24 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Il existe d'autres nombres sur des ordinateurs. Vous avez pu voir que 1 + 2 est bien égale à 3. Tandis que 0.1 + 0.2 n'est pas égale à 0.3.
```suggestion
Il existe d'autres nombres sur des ordinateurs. Vous avez pu voir que 1 + 2 est bien égal à 3. Tandis que 0.1 + 0.2 n'est pas égal à 0.3.
```

2024-07-14 20:24 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +C'est plus ou moins ce qui est fait par d'autres bibliothèques de calculs. On pensera notamment à SFCGAL, mais comme on l'a vue, cela ne fait pas tout. L'enregistrement se faisant en double, la conve
Dans ce cas, je ne sais pas exactement à quoi se réfère le "l'" or c'est ce qui doit déterminer l'accord de "vu(e)".

```suggestion
C'est plus ou moins ce qui est fait par d'autres bibliothèques de calculs. On pensera notamment à SFCGAL, mais comme on l'a vu, cela ne fait pas tout. L'enregistrement se faisant en double, la conversion va introduire des erreurs ; on détaillera cela plus bas.
```

2024-07-14 20:24 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Lors de calculs complexes, ces petites erreurs d'arrondi peuvent s'accumuler et devenir significatives.
Pas sûr mais je dirais ça.

```suggestion
Lors de calculs complexes, ces petites erreurs d'arrondis peuvent s'accumuler et devenir significatives.
```

2024-07-14 20:24 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Pour une étude plus approfondie, je vous encourage à lire l'article[Comparing Two Floating-Point Numbers
```suggestion
Pour une étude plus approfondie, je vous encourage à lire l'article [Comparing Two Floating-Point Numbers
```

2024-07-14 20:24 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Dans notre requête, on calcul le point d'intersection avec CG_Intersection. A la fin de son traitement, elle va convertir sa géométrie, et ses nombres, en [double PostGIS](https://github.com/postgis/
```suggestion
Dans notre requête, on calcule le point d'intersection avec CG_Intersection. A la fin de son traitement, elle va convertir sa géométrie, et ses nombres, en [double PostGIS](https://github.com/postgis/postgis/blob/d29ba84cb05988ab0aa1b2da3eef90108dfae1db/sfcgal/lwgeom_sfcgal.c#L559). Cette étape est la cause du problème. Cette conversion revient à cela en Python :
```

2024-07-14 20:24 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Une solution, qui n'est pas élégante et donc pas encore implémentée, serait d'avoir des fonctions qui s'enchaînent et ne fassent pas continuellement des va et vient entre les nombres. Avec une foncti
```suggestion
Une solution, qui n'est pas élégante et donc pas encore implémentée, serait d'avoir des fonctions qui s'enchaînent et ne fassent pas continuellement des va-et-vient entre les nombres. Avec une fonction CG_IntersectsIntersection comme suit, le résultat dans PostGIS sera juste.
```

2024-07-14 20:24 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +QGIS
```suggestion

QGIS
```

2024-07-14 20:24 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Derrière cette expression « putaclic », voici en réalité quelques conseils ou expériences que j'ai pu rencontrer sur différents projets.
On a eu quelques échanges ici sur le mot "putaclic" et quelques propositions.
https://x.com/tetranos/status/1707469248002503017

J'aime bien incitaclic.

2024-07-14 20:24 UTC, Michael-cd30 commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +_Utilisez des tolérances appropriées dans vos calculs pour minimiser les effets des erreurs d'arrondi. Définissez des tolérances adaptées à l’échelle et aux objectifs de votre projet._
Comme la question se pose à nouveau j'ai cherché et je trouve les deux orthographes...donc arrondi or arrondis, that is the question!

2024-07-15 04:34 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Lors de calculs complexes, ces petites erreurs d'arrondi peuvent s'accumuler et devenir significatives.
Ici, il faut bien garder arrondi au singulier.

2024-07-15 04:36 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Derrière cette expression « putaclic », voici en réalité quelques conseils ou expériences que j'ai pu rencontrer sur différents projets.
Je n'ai plus twitter et donc plus accès aux réponses.

Mais, j'aime beaucoup incitaclic !

```suggestion
Derrière cette expression « incitaclic », voici en réalité quelques conseils ou expériences que j'ai pu rencontrer sur différents projets.
```

2024-07-15 04:40 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +_Utilisez des tolérances appropriées dans vos calculs pour minimiser les effets des erreurs d'arrondi. Définissez des tolérances adaptées à l’échelle et aux objectifs de votre projet._
Ici, arrondi, est un complément d'erreurs et non un pluriel. Comme, des frais de port, des coups de poing (même en y mettant les deux poings contre l'ordi), des points de vue, etc.

2024-07-15 04:45 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +   - \( $\overrightarrow{AB}$ = (x_B - x_A, y_B - y_A) \)
Oui, j'avais commencé sur [hedgedoc](https://hedgedoc.org/), notre outil de pad à Oslandia, qui a le support LaTeX dans markdown.

2024-07-15 05:07 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +```python title="Exemple d'utilisation avec des points colinéaires"
En effet, j'ai fait le copier-coller de mon script, sans ajouter les réponses. Quelle est votre préférence dans l'affichage du résultat @Michael-cd30 @Guts @igeofr @gounux ?

Le résultat en commentaire : 

```python
print(0.1 + 0.2)
# 0.30000000000000004
```

Une phrase explicative

```python
print(0.1 + 0.2)
```

Le résultat sera 0.30000000000000004 et non 0.3 comme attendu,

Une autre réponse ?

2024-07-15 05:23 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Pour utiliser la topologie, nous allons faire l'union de nos deux lignes de `base` et `line` pour ensuite nettoyer celles-ci.
Ajouté.

2024-07-15 05:26 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +QGIS est spaghetti. Les données sont toutes dans ce plat de pâtes : les entités géographiques sont stockées individuellement sans relations topologiques explicites. Mais, bien que QGIS utilise un mod
Légèrement réécrit

2024-07-15 05:28 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Si vous avez bien suivi les parties précédentes, vous savez que PostGIS va utiliser GEOS pour réaliser la plupart de ses opérations.
Ajout de l'image

2024-07-15 05:47 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> + SELECT ST_Intersection(base, line) FROM ST_GeomFromWKB(decode('0102000000050000007997c6b68d3c3e4139eb62c260d55341ac9ea7316a3c3e41cbeb40e073d55341403e0bfbc33c3e41b3fc06f380d55341387a2a800c3d3e41f256b
:white_check_mark:

2024-07-15 05:49 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +(Source : <https://www.crunchydata.com/blog/performance-improvements-in-geos>)
Ah si, c'est bon ! La pré visualisation n'était pas encore bonne.

2024-07-15 05:52 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +![QGIS segments azimuth](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/data/processing/qgis_segments_azimuth.svg){: .img-center loading=lazy }
@Guts ici, le svg n'est pas bon et il n'est pas dans le CDN de GeoTribu

2024-07-15 05:59 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Il existerait une façon de rendre le calcul correct dans PostGIS avec SFCGAL, mais ce n'est pas encore implémenté.
Hop, j'ai ajouté un petit commentaire pour dire que SFCGAL c'est bien :)

2024-07-15 06:03 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +[^1] - **WKB (Well-Known Binary)** : Le WKB est un format binaire utilisé pour représenter des objets géométriques de manière compacte et efficace, couramment utilisé dans les bases de données géospa
```suggestion
[^1]:
 - **WKB (Well-Known Binary)** : Le WKB est un format binaire utilisé pour représenter des objets géométriques de manière compacte et efficace, couramment utilisé dans les bases de données géospatiales pour le stockage et l'échange de données géographiques.
```

2024-07-15 06:18 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +[^1]:
ici, le pré-commit semble casser la note de bas de page cc @Guts

2024-07-15 06:22 UTC, lbartoletti commented
Merci à vous @gounux @Michael-cd30 @igeofr @Guts pour les relectures et messages :blush: 

Je pense avoir pris en compte toutes les remarques. Pour ce tour, il manque : 

- une note de bas de page récalcitrante https://github.com/geotribu/website/pull/1151#pullrequestreview-2176924479 ;
- un SVG à refaire/intégrer dans le CDN https://github.com/geotribu/website/pull/1151#pullrequestreview-2176898327 ;
- une solution pour le LaTeX (extension pour GeoTribu ?) https://github.com/geotribu/website/pull/1151#discussion_r1677306745 ;
- un style pour les réponses dans du code python https://github.com/geotribu/website/pull/1151#discussion_r1677315729.

2024-07-15 10:23 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +[^1]:
Je m'en occupons.

2024-07-15 10:30 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +![QGIS segments azimuth](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/data/processing/qgis_segments_azimuth.svg){: .img-center loading=lazy }
Envoie moi ton SVG @lbartoletti

2024-07-15 10:30 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +```python title="Exemple d'utilisation avec des points colinéaires"
mode repl ?

```python
>>> print(0.1 + 0.2)
0.30000000000000004
```

2024-07-15 10:31 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +   - \( $\overrightarrow{AB}$ = (x_B - x_A, y_B - y_A) \)
Si besoin, je peux faire l'intégration de Math et KateX https://squidfunk.github.io/mkdocs-material/reference/math/

2024-07-15 10:51 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +[^1]:
Problème trouvé : il y a plusieurs notes de bas de page mais les références ne sont incrémentales. Par exemple [en ligne ](https://github.com/geotribu/website/blob/1566c1b66616461d7561b27676782831fcc9eb03/content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md?plain=1#L491).

Je corrige et push.

2024-07-15 12:33 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +[^1]:
Corrigé.

2024-07-15 12:37 UTC, Guts commented
Derniers changements appliqués sur ma pause ce midi :

- correction des notes de bas de page
- ajout de l'image de @sylvainbeo dans l'en-tête et le corps du billet d'annonce.
- internalisation de l'image du diagramme GEOS
- MAJ par rapport à la branche principale
- ajout d'icônes à certains tags :

  ![image](https://github.com/user-attachments/assets/d0d8a21a-c97d-44f2-96a3-1055ea40e858)

2024-07-15 19:37 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +![QGIS segments azimuth](https://github.com/lbartoletti/lbartoletti.github.io/blob/master/assets/2024_intersection_intersects/data/processing/qgis_segments_azimuth.svg){: .img-center loading=lazy }
Corrigé.

2024-07-15 19:39 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +   - \( $\overrightarrow{AB}$ = (x_B - x_A, y_B - y_A) \)
Fait. 

À gauche rendu Geotribu, à droite rendu hedgedoc :

![image](https://github.com/user-attachments/assets/7f184c01-0ef0-47b7-a764-e76eb523009a)


Par contre @lbartoletti il semble y avoir des erreurs de syntaxe.


Reste à voir si ça ne pète pas par ailleurs dans un autre contenu... ça va augmenter la probabilité de faire une connerie de syntaxe. Mais bon c'est plutôt cool.

2024-07-16 05:07 UTC, Guts requested changes

2024-07-16 05:07 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +On utilisera SFCGAL de deux façons, pour comparer leurs résultats, avec Python et avec PostGIS.
Suite de cette discussion : https://github.com/geotribu/website/pull/1151/files#r1659741524

Il y a un peu trop d'IA de traduction de la doc là-dedans non (majuscules mal placées, bibliothèque enveloppe, autres expressions littérales...) ? :smirk: 

Vu qu'il s'agit plutôt d'introduire, je pense qu'il faut rester en texte simple :

```suggestion
## Approche alternative : utilisation de SFCGAL pour des calculs plus robustes

Dans les parties précédentes, nous avons montré que le « intersects » d'une intersection, était faux, sauf avec la topologie ou la tolérance.

Nous allons maintenant utiliser une « approche alternative » dans les calculs. Promis, je garde le code pour une autre partie à la lecture optionnelle.

Pour cela, laissez-moi introduire [SFCGAL](https://sfcgal.gitlab.io/SFCGAL/).

Il s'agit d'une bibliothèque logicielle C++ sous licence [LGPL2+](https://www.gnu.org/licenses/old-licenses/lgpl-2.0.html) construite comme une surcouche de [CGAL](https://www.cgal.org/) avec pour objectif de supporter l'[ISO 19107:2013](https://www.iso.org/fr/standard/26012.html) et la norme OGC [Simple Features Access](www.opengeospatial.org/standards/sfa) 1.2 de l'OGC pour les opérations en 3D.

Concrètement, SFCGAL fournit des types de géométries et des opérations conformes aux normes, auxquels on accède via ses API [C](https://sfcgal.gitlab.io/SFCGAL/doxygen/group__capi.html) ou [C++](https://sfcgal.gitlab.io/SFCGAL/doxygen/group__public__api.html).

Par exemple, PostGIS utilise l'API C pour exposer certaines fonctions de SFCGAL dans les bases de données spatiales (cf. [manuel de PostGIS](https://postgis.net/docs/reference.html#reference_sfcgal)).

Les coordonnées des géométries ont une représentation en nombre rationnel exact et peuvent être en 2D ou en 3D.

En gros, SFCGAL, fait la géométrie comme on connaît dans nos SIG, mais avec le moteur de CGAL et surtout des nombres « différents » : rationnel exact. L'explication plus détaillée sera donnée dans [la partie algorithme et code](#algorithmes-et-code-comment-cela-fonctionne-t-il), mais considérons que ce sont des fractions.

On utilisera SFCGAL de deux façons, pour comparer leurs résultats :

- avec Python
- et avec PostGIS.
```

2024-07-16 05:07 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +PySFCGAL est une interface Python pour la bibliothèque SFCGAL, en cours de développement et de packaging. À défaut d'avoir une application `sfcgalop` à la `geosop`  (au moment de la publication de l'
```suggestion
[PySFCGAL](https://gitlab.com/sfcgal/pysfcgal) est une interface Python pour la bibliothèque SFCGAL, en cours de développement et de packaging. À défaut d'avoir une application `sfcgalop` à la `geosop`  (au moment de la publication de l'article, celle-ci est en cours de développement) l'interface Python permet de faire des calculs plus facilement qu'en C ou C++. Promis, c'est « lisible » comme code.
```

2024-07-16 05:07 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Sur mon système FreeBSD, voici, comment je l'utilise pour notre test :
```suggestion
Sur mon système FreeBSD, voici comment je l'utilise pour notre test :
```

2024-07-16 05:07 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +```python
````suggestion
```python title="Lecture de WKB avec PySFCGAL"
````

2024-07-16 05:07 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +```python
````suggestion
```python title="Calcul d'intersection avec PySFCGAL"
````

2024-07-16 05:12 UTC, Guts requested changes

2024-07-16 05:12 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +
```suggestion
## Approche alternative : utilisation de SFCGAL pour des calculs plus robustes

Dans les parties précédentes, nous avons montré que le « intersects » d'une intersection, était faux, sauf avec la topologie ou la tolérance.  
Nous allons maintenant utiliser une « approche alternative » dans les calculs. Promis, je garde le code pour une autre partie à la lecture optionnelle.

Pour cela, laissez-moi introduire [SFCGAL](https://sfcgal.gitlab.io/SFCGAL/).

Il s'agit d'une bibliothèque logicielle C++ sous licence [LGPL2+](https://www.gnu.org/licenses/old-licenses/lgpl-2.0.html) construite comme une surcouche de [CGAL](https://www.cgal.org/) avec pour objectif de supporter l'[ISO 19107:2013](https://www.iso.org/fr/standard/26012.html) et la norme OGC [Simple Features Access](www.opengeospatial.org/standards/sfa) 1.2 de l'OGC pour les opérations en 3D.

Concrètement, SFCGAL fournit des types de géométries et des opérations conformes aux normes, auxquels on accède via ses API [C](https://sfcgal.gitlab.io/SFCGAL/doxygen/group__capi.html) ou [C++](https://sfcgal.gitlab.io/SFCGAL/doxygen/group__public__api.html).

Par exemple, PostGIS utilise l'API C pour exposer certaines fonctions de SFCGAL dans les bases de données spatiales (cf. [manuel de PostGIS](https://postgis.net/docs/reference.html#reference_sfcgal)).

Les coordonnées des géométries ont une représentation en [nombre rationnel exact](https://fr.wikipedia.org/wiki/Nombre_rationnel) et peuvent être en 2D ou en 3D.

En gros, SFCGAL, fait la géométrie comme on connaît dans nos SIG, mais avec le moteur de CGAL et surtout des nombres « différents » : rationnel exact.   
L'explication plus détaillée sera donnée dans [la partie algorithme et code](#algorithmes-et-code-comment-cela-fonctionne-t-il), mais considérons que ce sont des fractions.

On utilisera SFCGAL de deux façons, pour comparer leurs résultats :

- avec Python
- et avec PostGIS.


```

2024-07-16 05:13 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +
@lbartoletti je m'auto commit pour pouvoir avancer sur le découpage. On reprendra les échanges une fois les articles en morceaux indépendants.

2024-07-16 05:14 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +```python title="Exemple d'utilisation avec des points colinéaires"
On reprendra plus tard au moment de la publication de ce morceau.

2024-07-16 05:21 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Je ne vais pas m'étendre sur le WKB qui est « étrange », il est en Big Endian, alors que jusqu'à présent, je n'ai eu que du Little Endian ; encore une fois plus d'explications dans l'article sur le W
Note de bas de page ajoutée.

2024-07-16 05:21 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +[^1] - **WKB (Well-Known Binary)** : Le WKB est un format binaire utilisé pour représenter des objets géométriques de manière compacte et efficace, couramment utilisé dans les bases de données géospa
C'est une note de bas de page qui était mal placée. Déjà corrigé.

2024-07-16 05:23 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Ici, nous avons la représentation d'un multipoint, où les coordonnées peuvent se retrouver dans ces parties :
C'est vrai que c'est pas clair. @lbartoletti  ?

2024-07-16 05:47 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Ici, nous avons la représentation d'un multipoint, où les coordonnées peuvent se retrouver dans ces parties :
Par cette phrase, je veux dire que lorsque l'on lit le WKB d'un multipoint comme `0104000000020000000101000000A899EFC8C83C3E4175E5698166D553410101000000B5EBDD9E8F3C3E416BF8515379D55341` 

On voit qu'il y a nos deux points : 
- `0101000000A899EFC8C83C3E4175E5698166D55341`
- `0101000000B5EBDD9E8F3C3E416BF8515379D55341`

Ainsi, on peut continuer de décomposer le WKB pour obtenir les coordonnées du premier point  `0101000000A899EFC8C83C3E4175E5698166D55341` qui sont : 
- `A899EFC8C83C3E41`
- `75E5698166D55341`

2024-07-16 05:48 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Ici, nous avons la représentation d'un multipoint, où les coordonnées peuvent se retrouver dans ces parties :
C'est là, où je pense que l'article sur le WKT/WKB aurait été intéressant, mais bon, il se fera dans quelques mois, histoire d'avoir 1 an de retard sur le planning 😅

2024-07-16 05:50 UTC, lbartoletti commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Ici, nous avons la représentation d'un multipoint, où les coordonnées peuvent se retrouver dans ces parties :
Ceci étant, c'est vrai que c'est "brut" et ça se voit que j'avais la tête dans le guidon.  Quelle formulation plus pédagogique/claire me conseillez-vous ?

2024-07-16 06:35 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +- base : 0102000000050000007997c6b68d3c3e4139eb62c260d55341ac9ea7316a3c3e41cbeb40e073d55341403e0bfbc33c3e41b3fc06f380d55341387a2a800c3d3e41f256b8176dd553417997c6b68d3c3e4139eb62c260d55341
Corrigé.

2024-07-16 06:38 UTC, Guts commented on content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md
> +Ici, nous avons la représentation d'un multipoint, où les coordonnées peuvent se retrouver dans ces parties :
Reformulation et mise en encart :

![image](https://github.com/user-attachments/assets/dc1ce14c-9568-4755-85b3-c125adbfdc97)

2024-07-16 07:13 UTC, merged

2024-07-16 07:56 UTC, Guts commented
Merci tout le monde, j'ai rushé pour finaliser des corrections et autres soucis de syntaxe. 
J'ai également entamé le découpage en jonglant avec le git log...

Le billet d'annonce est publié : https://geotribu.fr/articles/2024/2024-07-16_de-la-tolerance-en-sig-geometrie-01-annonce/
La partie 2 est sur les rails de lancement pour jeudi.