Article prodige 2024
geotribu/website pull request #1169
Opened 2024-07-11 20:49 UTC by bchartier

Article associé à cette proposition : #1153 
(premier article que j'écris et j'ai bien conscience qu'il n'est pas hyper fun à lire)

2024-07-11 21:10 UTC, Guts commented
Merci @bchartier  pour la proposition d'article 🙏 !

J'ai inséré le message automatique dans la description de la PR. Merci de le lire attentivement et de remplir ce qui doit l'être.

## 👓 Relecture

Pour la relecture, nous la réalisons de préférence via [le mode Review de GitHub](https://docs.github.com/fr/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews).

Si tu n'es pas à l'aise avec ce mode de travail, ne pas hésiter à nous le dire, soit pour former rapidement, accompagner ou trouver un autre moyen.

A noter que nous nous permettons de modifier directement ce qui est de l'ordre des règles de contribution (syntaxe Markdown, images, etc.), sans jamais toucher au fond (formulation, structure de l'article, etc.) sans commentaire.

### :information_source: **Aux relecteur/ices**

Merci d'utiliser autant que possible le mode Suggestion de la review : https://docs.github.com/fr/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request#starting-a-review

![image](https://github.com/geotribu/website/assets/1596222/4d081e97-7290-48c4-b1ff-587a8920b508)

@geotribu/relecture c'est à vous !

2024-07-12 07:41 UTC, Guts requested changes

2024-07-12 07:41 UTC, Guts commented on content/articles/2024/2024-07-12_journee_annuelle_prodige_2024.md
La date de publication pour aujourd'hui n'est pas possible : comme indiqué dans le guide de contribution, il y a un délai incompressible de 2 semaines pour la relecture collégiale et aujourd'hui c'est jour de GeoRDP donc c'est pas idéal.

Il faut la changer dans le nom du fichier et en ligne 8.

2024-07-12 07:46 UTC, bchartier commented
> Merci d'indiquer en commentaire tes comptes à utiliser pour être cité/e dans les messages et de cocher ci-après la "stratégie" de diffusion qui te convient pour chaque réseau.

Pas besoin de me citer, je déteste les réseaux sociaux.
Je laisserai le soin éventuellement à l'Afigéo de faire des repartages.

> Pour la relecture, nous la réalisons de préférence via [le mode Review de GitHub](https://docs.github.com/fr/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews).
> Si tu n'es pas à l'aise avec ce mode de travail, ne pas hésiter à nous le dire, soit pour former rapidement, accompagner ou trouver un autre moyen.

Effectivement, je ne sui pas des plus à l'aise avec cela mais je vais essayer de me débrouiller.

2024-07-12 07:51 UTC, Guts commented
> Pas besoin de me citer, je déteste les réseaux sociaux.

Certes. On peut au moins te arobaser sur Linkedin vu que tu y as une présence ? C'est pour être aligné avec les lauriers et l'attribution.

2024-07-12 07:54 UTC, bchartier commented
> > Pas besoin de me citer, je déteste les réseaux sociaux.
> 
> Certes. On peut au moins te arobaser sur Linkedin vu que tu y as une présence ? C'est pour être aligné avec les lauriers et l'attribution.

https://www.linkedin.com/in/benjaminchartier

2024-07-12 08:02 UTC, mapperfr reviewed
Et voilà une rapide review! Merci Benjamin pour cet article, c'est intéressant et l'écriture est fluide, ça se lit bien.

2024-07-12 08:15 UTC, bchartier commented on content/articles/2024/2024-07-12_journee_annuelle_prodige_2024.md
> +La communauté [Prodige](https://www.prodige-opensource.org/accueil) s'est réunie lors d'un évènement en ligne organisé le 3 juin 2024 : [Journée annuelle PRODIGE 2024](https://www.prodige-opensource.
Oui, bonne idée.

2024-07-12 08:16 UTC, bchartier commented on content/articles/2024/2024-07-12_journee_annuelle_prodige_2024.md
> +Cet article met en avant quelques points remarquables de cette journée. Je l'ai rédigé à l'occasion de mon intervention à propos du collectif CICCLO dans le cadre des missions d'animation que l'[Afig
Je vais mettre le lien vers la page officielle et indiquer que j'en parle un peu plus loin. Ça marche.

2024-07-12 08:16 UTC, bchartier commented on content/articles/2024/2024-07-12_journee_annuelle_prodige_2024.md
> +- [CICCLO](https://cnig.gouv.fr/collectif-interoperabilite-et-mise-en-commun-de-a26159.html) : ce collectif formé en fin d'année dernière au sein du [CNIG](https://cnig.gouv.fr/) et animé par l'[Afig
Ok.

2024-07-12 08:17 UTC, bchartier commented on content/articles/2024/2024-07-12_journee_annuelle_prodige_2024.md
Ok, je mets le 26/07 alors ?

2024-07-12 08:22 UTC, bchartier commented
> Et voilà une rapide review! Merci Benjamin pour cet article, c'est intéressant et l'écriture est fluide, ça se lit bien.

Merci 🙏

2024-07-12 08:37 UTC, Guts commented on content/articles/2024/2024-07-12_journee_annuelle_prodige_2024.md
> +La communauté [Prodige](https://www.prodige-opensource.org/accueil) s'est réunie lors d'un évènement en ligne organisé le 3 juin 2024 : [Journée annuelle PRODIGE 2024](https://www.prodige-opensource.
Peut-être dans un encart qui aura en plus l'avantage de mettre un peu de couleur ? rompre l'aspect full text https://contribuer.geotribu.fr/guides/admonition/?h=encart

2024-07-12 09:01 UTC, Guts commented on content/articles/2024/2024-07-12_journee_annuelle_prodige_2024.md
Si tu veux. C'est pas le meilleur créneau pour l'audience mais c'est toi ou ton commanditaire qui voit.

2024-07-12 14:15 UTC, Guts requested changes

2024-07-12 14:15 UTC, Guts commented on content/articles/2024/2024-07-26_journee_annuelle_prodige_2024.md
> +image: https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/journee_annuelle_prodige_2024/prodige_au_service_des_territoires.webp
L'image sélectionnée pour l'en-tête n'est pas conforme :

- les dimensions doivent être entre entre 600x300 et 800x400. Le ratio doit correspondre à celui du cadre en page d'accueil (voir le rendu actuel ci-dessous)
- le format doit être png ou jpeg (webp pas géré le vieux format qu'est le RSS)



Ref: https://contribuer.geotribu.fr/guides/metadata_yaml_frontmatter/#syntaxe

![image](https://github.com/user-attachments/assets/1d3aac0b-3a69-4d6d-a7e2-096eb2784578)


À noter qu'il est aussi possible de laisser le site autogénérer une image d'en-tête. Pour cela, laisser le champ `image:` vide.

2024-07-14 21:01 UTC, Michael-cd30 reviewed
Je ne connaissais pas prodige avant de lire cet article.

2024-07-14 21:01 UTC, Michael-cd30 commented on content/articles/2024/2024-07-26_journee_annuelle_prodige_2024.md
> +- Datavisualisations : nouveau module de gestion des dataviz, avec la capacité de les exploiter dans le générateur d'application métier, de les cataloguer et les rendre accessibles via le DataHub ;
```suggestion
- Datavisualisations : nouveau module de gestion des dataviz, avec la capacité de les exploiter dans le générateur d'applications métiers, de les cataloguer et les rendre accessibles via le DataHub ;
```

2024-07-15 11:35 UTC, Michael-cd30 commented on content/articles/2024/2024-07-12_journee_annuelle_prodige_2024.md
> +La communauté [Prodige](https://www.prodige-opensource.org/accueil) s'est réunie lors d'un évènement en ligne organisé le 3 juin 2024 : [Journée annuelle PRODIGE 2024](https://www.prodige-opensource.
> Peut-être dans un encart qui aura en plus l'avantage de mettre un peu de couleur ? rompre l'aspect full text https://contribuer.geotribu.fr/guides/admonition/?h=encart

Ah m****e, j'ai justement fait la proposition inverse. Ne connaissant pas prodige, j'ai été surpris par le démarrage de l'article...

2024-07-15 13:59 UTC, bchartier commented on content/articles/2024/2024-07-12_journee_annuelle_prodige_2024.md
Bah, pour moi le plus est le mieux. J'ai juste fait 12+14=26.

2024-07-15 14:19 UTC, bchartier commented on content/articles/2024/2024-07-26_journee_annuelle_prodige_2024.md
> +- Nouvelle version du générateur d'applications métier no-code. Deux exemples d'applications métier créées avec Prodige : [Base de données des ZAE en Centre-Val de Loire](https://zae.doterr.fr), ou [
Effectivement, je pense qu'il peut y a voir débat.
Perso, je préfère laisser au singulier.
Deux liens qui illustrent cela :
- https://www.languefrancaise.net/forum/viewtopic.php?id=12327 (voir la remarque sur "timbres poste")
- https://techcommunity.microsoft.com/t5/educator-developer-blog/les-applications-m%C3%A9tier-les-super-h%C3%A9ros-incontournable-des/ba-p/3867274 (bon, c'est vrai que je ne sais pas si les articles de Microsoft sont relus par des correcteurs)

2024-07-15 14:29 UTC, bchartier commented on content/articles/2024/2024-07-26_journee_annuelle_prodige_2024.md
> +Un constat fait par les plateformes de données : leurs portails actuels ne sont pas adaptés à des non spécialistes de l'information géographique. Ce constat est partagé par bon nombre de plateformes
Bon, je viens de voir que cette question d'accord n'est pas triviale comme en témoigne cette page (dont je ne sais pas dans quelle mesure elle est fiable) : https://www.projet-voltaire.fr/regle-orthographe/leur-chapeau-leurs-chapeaux-adjectif-possessif-singulier-pluriel-accord/
De ce que je comprends je peux utiliser le singulier ou le pluriel dans ce cas de figure (cf. partie 3 en raison de "un seul être pour chaque possesseur"). Mais comme ma phrase parle de l'ensemble de ces êtres possédés je suis censé utiliser le pluriel :

> on emploie le pluriel si l’on considère l’ensemble des choses ou des êtres possédés

Je propose que je laisse comme c'est actuellement.

2024-07-15 14:39 UTC, bchartier commented on content/articles/2024/2024-07-26_journee_annuelle_prodige_2024.md
> +Plusieurs plateformes ont entamé des travaux sur l'expérience utilisateur pour refondre leurs portails afin de mieux répondre aux attentes de leurs usagers : en particulier [DatARA](https://www.datar
Ces travaux sont encore en cours (c'est pour cette raison que j'ai utilisé le terme "entamé"). De mémoire, lorsque ces présentations ont été faites les plateformes concernées en étaient à l'étape des constats et pas encore à la réalisation opérationnelle d'une nouvelle interface utilisateur. Leurs présentations était surtout centrées sur le pourquoi de la démarche et ce qu'elles ont mis en place pour mettre en évidence ce qui fonctionne et ce qui ne fonctionne pas en termes d'expérience utilisateur et comment impliquer différentes catégories d'utilisateurs. Comme les administrateurs de pas mal de plateformes sont convaincus que l'expérience utilisateur qu'elles offrent n'est pas top ils ont demandé à pouvoir bénéficier de ces travaux d'analyse. DatARA et AtlaSanté ont répondu qu'elles partageraient les résultats volontiers. Pour l'instant on en est là.

2024-07-15 14:43 UTC, bchartier commented on content/articles/2024/2024-07-26_journee_annuelle_prodige_2024.md
> +- Datavisualisations : nouveau module de gestion des dataviz, avec la capacité de les exploiter dans le générateur d'application métier, de les cataloguer et les rendre accessibles via le DataHub ;
Je vais mettre "applications" au pluriel et laisser "métier " au singulier (voir autre commentaire sur l'accord de "métier").

2024-07-15 14:44 UTC, bchartier commented
Est-ce que c'est à moi de passer les commentaires en "résolu" ?

2024-07-15 14:57 UTC, Guts commented on content/articles/2024/2024-07-12_journee_annuelle_prodige_2024.md
> +La communauté [Prodige](https://www.prodige-opensource.org/accueil) s'est réunie lors d'un évènement en ligne organisé le 3 juin 2024 : [Journée annuelle PRODIGE 2024](https://www.prodige-opensource.
T'inquiète, on n'est pas obligé d'être d'accord :)

2024-07-15 15:01 UTC, Guts commented on content/articles/2024/2024-07-12_journee_annuelle_prodige_2024.md
> +- [CICCLO](https://cnig.gouv.fr/collectif-interoperabilite-et-mise-en-commun-de-a26159.html) : ce collectif formé en fin d'année dernière au sein du [CNIG](https://cnig.gouv.fr/) et animé par l'[Afig
La doc pour les notes de bas de page : https://squidfunk.github.io/mkdocs-material/reference/footnotes/

Exemple : https://github.com/geotribu/website/blob/44080f07bfb4fb9cfac116909075cd00d7747a15/content/articles/2024/2024-07-01_de_la_tolerance_en_sig.md?plain=1#L1666-L1677

Syntaxe :

```markdown

[...] 
CICCLO [^cicclo]
[...]

<!-- Notes de bas de page -->
[^cicclo]: blbalblaba
```


Pour les "abbréviations" : https://squidfunk.github.io/mkdocs-material/reference/tooltips/#adding-abbreviations

Syntaxe :

```markdown
<!-- Notes de bas de page -->
*[CICCLO]: Blablablabla
```

2024-07-15 15:04 UTC, Guts commented
> Est-ce que c'est à moi de passer les commentaires en "résolu" ?

En fait, quand tu es OK pour intégrer une suggestion, tu es supposé cliquer sur "Sign off and commit suggestion". Cela intègre automatiquement la suggestion et en plus ça crédite automatiquement le relecteur.

2024-07-15 15:38 UTC, bchartier commented on content/articles/2024/2024-07-12_journee_annuelle_prodige_2024.md
> +- [CICCLO](https://cnig.gouv.fr/collectif-interoperabilite-et-mise-en-commun-de-a26159.html) : ce collectif formé en fin d'année dernière au sein du [CNIG](https://cnig.gouv.fr/) et animé par l'[Afig
Ça vous va si je laisse comme c'est et qu'intègre les tooltip et notes de bas de page pour les articles suivants ?

2024-07-16 09:58 UTC, Guts commented on content/articles/2024/2024-07-12_journee_annuelle_prodige_2024.md
> +- [CICCLO](https://cnig.gouv.fr/collectif-interoperabilite-et-mise-en-commun-de-a26159.html) : ce collectif formé en fin d'année dernière au sein du [CNIG](https://cnig.gouv.fr/) et animé par l'[Afig
Bien sûr, c'est toi qui voit _in fine_. L'idée c'est de nourrir la discussion et donner des pistes de mises en forme auxquelles tu n'a pas forcément pensé ou en tête.

2024-07-17 15:41 UTC, bchartier commented on content/articles/2024/2024-07-26_journee_annuelle_prodige_2024.md
> +Plusieurs plateformes ont entamé des travaux sur l'expérience utilisateur pour refondre leurs portails afin de mieux répondre aux attentes de leurs usagers : en particulier [DatARA](https://www.datar
Je vais compléter cette partie pour que ce soit plus clair.

2024-07-23 14:09 UTC, bchartier commented
Est-ce que cela vous paraît bon ?
J'ai vu que @Guts a approuvé l'article #1174, du coup je me demande si c'est ok pour celui-ci.
J'aurai un peu de temps pour apporter des modifs demain matin si besoin. Après je ne serai plus disponible avant une semaine.

2024-07-26 20:52 UTC, Guts approved these changes

2024-07-26 20:53 UTC, merged

2024-07-30 07:34 UTC, Michael-cd30 commented
BSky : https://bsky.app/profile/geotribu.bsky.social/post/3kyibt56kxt2h
LinkedIn : https://www.linkedin.com/feed/update/urn:li:activity:7223678088658710528/?actorCompanyId=104008370