Article geocom 2024
geotribu/website pull request #1174
Opened 2024-07-15 17:23 UTC by bchartier

Proposition d'article sur les dernières rencontres de la communauté geOrchestra.

----

:information_source: Message automatique à lire et remplir :arrow_down: 

### Liens importants

- pour modifier ton article via l'interface de GitHub,  tu peux le retrouver facilement via l'icône crayon en haut de la page sur le site de prévisualisation ([cf. documentation](https://contribuer.geotribu.fr/edit/fix_content_from_website/)). Sinon :
  - [article](https://github.com/bchartier/geotribu-website/edit/article-prodige-2024/content/articles/2024/2024-07-12_journee_annuelle_prodige_2024.md?pr=%2Fgeotribu%2Fwebsite%2Fpull%2F1169)
  - [page auteur/ice](https://github.com/bchartier/geotribu-website/edit/article-prodige-2024/content/team/benjamin-chartier.md?pr=%2Fgeotribu%2Fwebsite%2Fpull%2F1169) 
- [site temporaire de prévisualisation de l'article](https://preview-pullrequest-1169--geotribu-preprod.netlify.app/) - merci de ne pas le diffuser

## Ressources

Pour info, voici quelques extraits de notre guide de contribution :

- [comprendre et compléter l'en-tête](https://contribuer.geotribu.fr/guides/metadata_yaml_frontmatter/)
- [intégrer une image](https://contribuer.geotribu.fr/guides/image/)
- [choisir une licence](https://contribuer.geotribu.fr/guides/licensing/)
- [signer un article](https://contribuer.geotribu.fr/guides/authoring/)

## 📢 Diffusion

Une fois l'article publié, il sera alors temps de le diffuser. Il sera automatiquement intégré au [flux RSS](http://geotribu.fr/feed_rss_created.xml) et à [la newsletter](http://geotribu.fr/newsletter/signup/).

Mais la publication sur les réseaux sociaux est manuelle.

Nous avons des comptes officiels sur ces réseaux sociaux :

- [BlueSky](https://bsky.app/profile/geotribu.bsky.social)
- ~~[Facebook](https://www.facebook.com/geotribu) - inactif~~
- [LinkedIn](https://www.linkedin.com/company/geotribu/) avec [le hashtag #Geotribu](https://www.linkedin.com/feed/hashtag/?keywords=geotribu)
- [Mastodon](https://mapstodon.space/@geotribu)
- [X/Twitter](https://twitter.com/geotribu)

Merci d'indiquer en commentaire tes comptes à utiliser pour être cité/e dans les messages et de cocher ci-après la "stratégie" de diffusion qui te convient pour chaque réseau.

### BlueSky

- [x] un/e membre de Geotribu publie, tu repartages avec ton compte
- [ ] tu publies, on repartage
- [ ] chacun/e publie de son côté
- [ ] je souhaite que mon contenu ne soit pas diffusé sur ce réseau

### LinkedIn

- [x] un/e membre de Geotribu publie, tu repartages avec ton compte
- [ ] tu publies, on repartage
- [ ] chacun/e publie de son côté
- [ ] je souhaite que mon contenu ne soit pas diffusé sur ce réseau

### Mastodon

- [x] un/e membre de Geotribu publie, tu repartages avec ton compte
- [ ] tu publies, on repartage
- [ ] chacun/e publie de son côté
- [ ] je souhaite que mon contenu ne soit pas diffusé sur ce réseau

### X/Twitter

- [x] un/e membre de Geotribu publie, tu repartages avec ton compte
- [ ] tu publies, on repartage
- [ ] chacun/e publie de son côté
- [ ] je souhaite que mon contenu ne soit pas diffusé sur ce réseau

Compte LinkedIn à citer : https://www.linkedin.com/in/benjaminchartier

2024-07-15 17:33 UTC, Guts requested changes
On ne l'arrête plus :star_struck:

2024-07-15 17:33 UTC, Guts commented on content/articles/2024/2024-07-29_geocom_2024.md
> +{% include "licenses/beerware.md" %}
Même si l'ordre n'a pas d'importance visuellement, c'est mieux de garder la cohérence avec le rendu : le bloc auteur, la licence puis les notes de bas de page

```suggestion

<!-- geotribu:authors-block -->

{% include "licenses/beerware.md" %}

<!-- Notes de bas de page -->
[^cicclo]: CICCLO signifie Collectif Interopérabilité et mise en Commun de Composants Logiciels pour les plateformes de données. Ce collectif porté par le [CNIG](https://cnig.gouv.fr/collectif-interoperabilite-et-mise-en-commun-de-a26159.html) et animé par l'Afigéo[^afigeo]. Son but : favoriser le développement collaboratif de composants ou modules, la mise en œuvre commune des standards et recommandations, la réutilisation efficace des logiciels existants et la création d’écosystèmes de données plus cohérents et interconnectés.
[^afigeo]: [Afigéo](https://www.afigeo.asso.fr/) signifie Association pour l'information géographique. Il s'agit de l'association professionnelle nationale française dédiée au secteur de l'information géographique.

*[WFS]: Web Feature Service
*[WMS]: Web Map Service
*[WMTS]: Web Map Tile Service
```

2024-07-15 17:33 UTC, Guts commented on content/articles/2024/2024-07-29_geocom_2024.md
> +{% include "licenses/beerware.md" %}
Concernant les 3 derniers, on peut peut-être les ajouter au glossaire général (càd ajouté automatiquement à tous les articles) https://github.com/geotribu/website/blob/master/content/toc_nav_ignored/snippets/glossaire.md?plain=1

2024-07-15 17:33 UTC, Guts commented on content/articles/2024/2024-07-29_geocom_2024.md
> +La refonte de cet outil de suivi serait aussi l'occasion d'enregistrer l'ensemble des requêtes reçues par geOrchestra et non simplement les requêtes adressées aux services OGC.
```suggestion
- [Superset](https://superset.apache.org/) pour exploiter les données collectées et produire des indicateurs et tableaux de bord.

La refonte de cet outil de suivi serait aussi l'occasion d'enregistrer l'ensemble des requêtes reçues par geOrchestra et non simplement les requêtes adressées aux services OGC.
```

2024-07-15 17:33 UTC, Guts commented on content/articles/2024/2024-07-29_geocom_2024.md
> +L'outil actuel de geOrchestra dédié au suivi de la consommation des services OGC est maintenant très anciens et mériterait d'être revu. Jean Pommier ([Pi-geosolutions](https://www.pi-geosolutions.fr/
```suggestion
L'outil actuel de geOrchestra dédié au suivi de la consommation des services OGC est maintenant très ancien et mériterait d'être revu. Jean Pommier ([Pi-geosolutions](https://www.pi-geosolutions.fr/)) a proposé à la communauté geOrchestra une architecture basée sur des composants logiciels qui pourraient bénéficier à d'autres usages :
```

2024-07-15 17:33 UTC, Guts commented on content/articles/2024/2024-07-29_geocom_2024.md
> +    - Plateformes de données
Je ne sais pas ce que tu en penses mais mon instinct de métadonneur ~~de leçons~~ me dit que c'est un peu étrange comme mot-clé. Ça fait pas très thésaurus...

2024-07-15 17:33 UTC, Guts commented on content/articles/2024/2024-07-29_geocom_2024.md
> +image: https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/geocom_2024/photo.webp
Peux-tu renommer le fichier avce quelque chose de plus explicite stp ? Sinon l'index des images que nous utilisons va être un peu sec et il risque d'y avoir bcp de fichiers qui s'appellent juste photo.* ou icone.* etc

_Désolé je pinaille mais avec toi je me permets, car je sais que ta corde de perfectionniste est sensible._

2024-07-15 17:36 UTC, Guts commented
Merci @bchartier pour la proposition d'article 🙏 !

## 👓 Relecture

Pour la relecture, nous la réalisons de préférence via [le mode Review de GitHub](https://docs.github.com/fr/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews).

Si tu n'es pas à l'aise avec ce mode de travail, ne pas hésiter à nous le dire, soit pour former rapidement, accompagner ou trouver un autre moyen.

A noter que nous nous permettons de modifier directement ce qui est de l'ordre des règles de contribution (syntaxe Markdown, images, etc.), sans jamais toucher au fond (formulation, structure de l'article, etc.) sans commentaire.

Allez zou, c'est parti pour la @geotribu/relecture  !

:information_source: **Aux relecteur/ices**

Merci d'utiliser autant que possible le mode Suggestion de la review : https://docs.github.com/fr/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request#starting-a-review

![image](https://github.com/geotribu/website/assets/1596222/4d081e97-7290-48c4-b1ff-587a8920b508)

C'est vraiment **IMPORTANT** pour le confort de l'auteur/ice :pray:

2024-07-15 17:41 UTC, Guts requested changes

2024-07-15 17:41 UTC, Guts commented on content/articles/2024/2024-07-29_geocom_2024.md
> +![logo geOrchestra](https://cdn.geotribu.fr/images/logos-icones/logiciels_librairies/georchestra-logo-small.png){: .img-thumbnail-left }
Le logo existe existe déjà (et on privilégie les versions carrées sinon c'est le booordel du responsive) :

```suggestion
![logo geOrchestra](https://cdn.geotribu.fr/images/logos-icones/logiciels_librairies/georchestra.png){: .img-thumbnail-left }
```

Penser à supprimer l'autre du coup.

2024-07-16 09:03 UTC, bchartier commented on content/articles/2024/2024-07-29_geocom_2024.md
> +image: https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/geocom_2024/photo.webp
> Désolé je pinaille

Non, non, c'est juste que j'avais l'intention de changer le nom avant de faire mon commit et j'ai oublié.
En plus, comme le format de l'image n'est pas vraiment standard je vais virer le tag image dans le header pour éviter de me casser la tête pour rien.

2024-07-16 09:57 UTC, Guts commented on content/articles/2024/2024-07-29_geocom_2024.md
> +- **Mise à jour des composants** : comme à l'accoutumé, cette version intègre des révisions des briques logicielles qui composent sont cœur : [GeoNetwork](https://www.geonetwork-opensource.org/), [Ge
```suggestion
- **Mise à jour des composants** : comme à l'accoutumé, cette version intègre des révisions des briques logicielles qui composent son cœur : [GeoNetwork](https://www.geonetwork-opensource.org/), [GeoServer](https://geoserver.org/) et CAS notamment ;
```

2024-07-17 15:35 UTC, bchartier commented on content/articles/2024/2024-07-29_geocom_2024.md
> +- **Mise à jour des composants** : comme à l'accoutumé, cette version intègre des révisions des briques logicielles qui composent sont cœur : [GeoNetwork](https://www.geonetwork-opensource.org/), [Ge
Ok, corrigé.

2024-07-17 17:16 UTC, Guts commented
Pour rappel, il est possible de chercher dans le CDN de 2 façons :

- via l'interface web (mais c'est un peu galère)
- via la ligne de commande geotribu :
  -  `pipx install geotribu[all]` pour installer
  - `geotribu si geonetwork` ou `geotribu si mapstor*`

Voir https://contribuer.geotribu.fr/guides/cdn-images-recherche/#chercher-une-image

2024-07-22 12:23 UTC, Guts approved these changes

2024-07-23 15:09 UTC, Guts commented
@bchartier ça te dérange si décale la publication à la semaine suivante, voire plus tard ?

Sinon avec #1169 et la série d'été, ça va faire bcp en très peu de temps et la newsletter va être un peu trop grosse (https://contribuer.geotribu.fr/internal/auto_newsletter/)

2024-07-24 04:54 UTC, lbartoletti commented on content/articles/2024/2024-07-29_geocom_2024.md
> +La communauté des développeurs et des utilisateurs de [geOrchestra](https://www.georchestra.org/fr/) s'est réunie du 17 juin au 21 juin 2024 à Lille dans les locaux de la [Métropole Européenne de Lil
```suggestion
La communauté des développeurs et des utilisateurs de [geOrchestra](https://www.georchestra.org/fr/),  [geOcom 2024](https://www.georchestra.org/blog/2024/05/16/geocom-2024-fr/), s'est réunie du 17 juin au 21 juin 2024 à Lille dans les locaux de la [Métropole Européenne de Lille](https://www.lillemetropole.fr/). Dans un esprit similaire à la Journée annuelle Prodige qui a eu lieu un peu plus tôt au mois de juin, elle a accueilli des représentants d'autres communautés logicielles : notamment la plateforme [OPenIG](https://www.openig.org/) et la [Géoplateforme de l'IGN](https://www.ign.fr/geoplateforme). Comme les années précédentes, les représentants d'organismes de recherche ([CIRAD](https://www.cirad.fr/), [INRAE](https://www.inrae.fr/) et [IRD](https://www.ird.fr/)) étaient présents au côté des plateformes de données territoriales et d'acteurs privés (prestataires de services et utilisateurs).
```

2024-07-24 04:54 UTC, lbartoletti commented on content/articles/2024/2024-07-29_geocom_2024.md
> +La prochaine version de geOrchestra est la version 24. Elle est prête à 99% (elle a été publiée depuis que ces rencontres ont eu lieu).
Si, elle est désormais publiée, je reformulerais la phrase.

2024-07-24 04:54 UTC, lbartoletti commented on content/articles/2024/2024-07-29_geocom_2024.md
> +- **Mise à jour des composants** : comme à l'accoutumée, cette version intègre des révisions des briques logicielles qui composent son cœur : [GeoNetwork](https://www.geonetwork-opensource.org/), [Ge
Un lien ou une définition pour CAS ?

2024-07-24 04:54 UTC, lbartoletti commented on content/articles/2024/2024-07-29_geocom_2024.md
> +Cet article met en avant quelques points remarquables de cette journée. Il ne prétend pas être exhaustif, ni dénué de biais. Je l'ai rédigé à l'occasion de mon intervention à propos du collectif CICC
```suggestion
Cet article met en avant quelques points remarquables de cette journée. Il ne prétend pas être exhaustif ni dénué de biais. Je l'ai rédigé à l'occasion de mon intervention à propos du collectif CICCLO[^cicclo] dans le cadre des missions d'animation que l'Afigéo[^afigeo] m'a confiées pour dynamiser l'écosystème technique des plateformes de données géographiques (l'objet et les travaux de CICCLO[^cicclo] sont rapidement décrits plus bas dans la section de l'article consacrée à l'interopérabilité).
```

2024-07-24 04:54 UTC, lbartoletti commented on content/articles/2024/2024-07-29_geocom_2024.md
> +- **Gateway** : avec cette version il sera possible de déployer un nouveau module, la gateway, utilisable à la place du security proxy. Ce dernier peut néanmoins être conservé conjointement avec la g
```suggestion
- **Gateway** : avec cette version, il sera possible de déployer un nouveau module, la gateway, utilisable à la place du security proxy. Ce dernier peut néanmoins être conservé conjointement avec la gateway pour les plateformes qui ont développé des modules complémentaires exploitant les capacités techniques du security proxy. La gateway apporte des fonctionnalités très intéressantes en matière d'authentification : support de fournisseurs d'identité externes via [OAuth 2.0](https://oauth.net/2/) et [OpenID Connect](https://openid.net/developers/how-connect-works/) (tels que [FranceConnect](https://franceconnect.gouv.fr/), [Renater](https://www.renater.fr/) et [Google](https://www.google.com)). Notons également l'intégration d'un *message broker* (en l'occurrence [RabbitMQ](https://www.rabbitmq.com/)) pour assurer un couplage faible entre la gateway et la console de geOrchestra (le module d'administration des utilisateurs et de leurs droits) pour des questions de modularité et d'évolutivité de geOrchestra ;
```

2024-07-24 04:54 UTC, lbartoletti commented on content/articles/2024/2024-07-29_geocom_2024.md
> +- Le **DataHub** : interface de recherche et découverte des données référencées dans un catalogue GeoNetwork ;
```suggestion
- Le **DataHub** : interface de recherche et de découverte des données référencées dans un catalogue GeoNetwork ;
```

2024-07-24 04:54 UTC, lbartoletti commented on content/articles/2024/2024-07-29_geocom_2024.md
> +![Logo de MapStore](https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/mapstore.png){: .img-thumbnail-left } [MapStore](https://github.com/geosolutions-it/MapStore2) est le client cartogra
```suggestion
![Logo de MapStore](https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/mapstore.png){: .img-thumbnail-left } [MapStore](https://github.com/geosolutions-it/MapStore2) est le client cartographique intégré à geOrchestra depuis quelques années. Plusieurs présentations ont permis d'illustrer les capacités de cet outil très riche développé par [GeoSolutions](https://www.geosolutionsgroup.com/) : création d'applications métier (avec saisie collaborative par exemple), développement de plugins, gestion de la 3D. Malgré ces démonstrations techniques intéressantes, MapStore n'est pas le seul outil cartographique utilisé au sein de la communauté geOrchestra. Pour certains cas d'usage, d'autres outils cartographiques peuvent être déployés : [mviewer](https://mviewer.netlify.app/fr/) et GéoContrib ont été cités plusieurs fois.
```

2024-07-24 04:54 UTC, lbartoletti commented on content/articles/2024/2024-07-29_geocom_2024.md
> +La publication des données dans geOrchestra n'est pas un processus très guidé comme cela peut l'être sur d'autres solutions équivalentes. L'administrateur de données doit maitriser GeoServer et GeoNe
Je trouve la dernière phrase très longue. Est-il possible de la scinder ?

2024-07-24 04:54 UTC, lbartoletti commented on content/articles/2024/2024-07-29_geocom_2024.md
> +A aussi évoqué le besoin de disposer d'un tableau de bord des données intégrées dans une instance geOrchestra qui faciliterait bien la vie des administrateurs.
```suggestion
Il a aussi été évoqué le besoin de disposer d'un tableau de bord des données intégrées dans une instance geOrchestra qui faciliterait bien la vie des administrateurs.
```

2024-07-24 04:54 UTC, lbartoletti commented on content/articles/2024/2024-07-29_geocom_2024.md
> +![Logo de Timescale](https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/timescale-logo-black.png){: .img-thumbnail-left } [Timescale](https://www.timescale.com/) : un PostgreSQL enrichi de
```suggestion
![Logo de Timescale](https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/timescale-logo-black.png){: .img-thumbnail-left } [Timescale](https://www.timescale.com/) : un PostgreSQL enrichi de capacités à traiter des séries temporelles ; ce qui,  par exemple, permettrait de facilement consolider des indicateurs par agrégation de données sur des périodes glissantes ;
```

2024-07-24 04:54 UTC, lbartoletti commented on content/articles/2024/2024-07-29_geocom_2024.md
> +![Logo de Superset](https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/superset-logo.png){: .img-thumbnail-left } [Apache Superset](https://superset.apache.org/) pour exploiter les données
```suggestion
![Logo de Superset](https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/superset-logo.png){: .img-thumbnail-left } [Apache Superset](https://superset.apache.org/) pour exploiter les données collectées et produire des indicateurs et des tableaux de bord.
```

2024-07-24 04:54 UTC, lbartoletti commented on content/articles/2024/2024-07-29_geocom_2024.md
> +Depuis années, la communauté geOrchestra évoque l'opportunité de pouvoir exploiter des fournisseurs d'identité externes. On n'a jamais été aussi proche du but avec deux évènements proches :
```suggestion
Depuis des années, la communauté geOrchestra évoque l'opportunité d'exploiter des fournisseurs d'identité externes. On n'a jamais été aussi proche du but avec deux évènements proches :
```
"des années" ou "plusieurs années" ?

2024-07-24 04:54 UTC, lbartoletti commented on content/articles/2024/2024-07-29_geocom_2024.md
> +3 types d'usages ont été illustrés avec des démonstrations convaincantes :
```suggestion
Trois types d'usages ont été illustrés avec des démonstrations convaincantes :
```

2024-07-24 04:54 UTC, lbartoletti commented on content/articles/2024/2024-07-29_geocom_2024.md
> +- Identifier les jeux de données d'un catalogue qui se rapproche le plus d'une description textuelle fournie par l'utilisateur. L'intérêt ici est de proposer une recherche bien plus souple que les mo
```suggestion
- Identifier les jeux de données d'un catalogue qui se rapproche le plus d'une description textuelle fournie par l'utilisateur. L'intérêt ici est de proposer une recherche bien plus souple que les moteurs de recherche intégrés à nos catalogues. En effet, les LLM, de par leur conception et leur entrainement, gèrent nativement la proximité sémantique d'un vocabulaire considérable et ainsi que le multilinguisme. Camptocamp a publié une [vidéo sur LinkedIn](https://www.linkedin.com/posts/fgravin_geonetwork-genai-llm-ugcPost-7216068187488956416-OqUk?utm_source=share&utm_medium=member_desktop) pour illustrer ce cas d'usage.
```

2024-07-24 04:54 UTC, lbartoletti commented on content/articles/2024/2024-07-29_geocom_2024.md
> +- Réaliser un calcul à partir des bases de données, par exemple un indice de végétation à partir d'images d'observation de la Terre.
```suggestion
- Réaliser un calcul à partir des bases de données, par exemple, un indice de végétation à partir d'images d'observation de la Terre.
```

2024-07-24 04:54 UTC, lbartoletti commented on content/articles/2024/2024-07-29_geocom_2024.md
> +- CICCLO[^cicclo] : en tant que co-animateur de ce collectif (au nom de l'Afigéo[^afigeo]) j'en ai fait une présentation et a préciser les objectifs des travaux actuels portant sur l'intégration de l
```suggestion
- CICCLO[^cicclo] : en tant que co-animateur de ce collectif (au nom de l'Afigéo[^afigeo]) j'en ai fait une présentation et j'ai précisé les objectifs des travaux actuels portant sur l'intégration de l'API Features et d'AgentConnect aux différentes solutions des parties prenantes (Géoplateforme, geOrchestra, Onegeo et Prodige) ;
```
Je ne suis pas certain d'avoir compris la phrase

2024-07-24 04:57 UTC, lbartoletti commented
Merci pour l'article @bchartier c'est très clair comme CR ! Juste quelques corrections/propositions mineures.

2024-07-24 07:40 UTC, bchartier commented on content/articles/2024/2024-07-29_geocom_2024.md
> +La prochaine version de geOrchestra est la version 24. Elle est prête à 99% (elle a été publiée depuis que ces rencontres ont eu lieu).
Ok, phrase et titre de section reformulés.

2024-07-24 07:41 UTC, bchartier commented on content/articles/2024/2024-07-29_geocom_2024.md
> +- **Mise à jour des composants** : comme à l'accoutumée, cette version intègre des révisions des briques logicielles qui composent son cœur : [GeoNetwork](https://www.geonetwork-opensource.org/), [Ge
Lien ajouté.

2024-07-24 07:42 UTC, bchartier commented on content/articles/2024/2024-07-29_geocom_2024.md
> +A aussi évoqué le besoin de disposer d'un tableau de bord des données intégrées dans une instance geOrchestra qui faciliterait bien la vie des administrateurs.
Ok. J'en ai profité pour reformuler la fin de la phrase et le paragraphe précédent.

2024-07-24 07:43 UTC, bchartier commented on content/articles/2024/2024-07-29_geocom_2024.md
> +La publication des données dans geOrchestra n'est pas un processus très guidé comme cela peut l'être sur d'autres solutions équivalentes. L'administrateur de données doit maitriser GeoServer et GeoNe
Ok. Phrase scindée.

2024-07-24 07:43 UTC, bchartier commented
> Merci pour l'article @bchartier c'est très clair comme CR ! Juste quelques corrections/propositions mineures.

Désolé. La relecture a dû sembler pénible.

2024-07-24 07:45 UTC, bchartier commented
> @bchartier ça te dérange si décale la publication à la semaine suivante, voire plus tard ?

Je préfèrerais que ce ne soit pas beaucoup plus tard : c'est une actualité qui perd de sa saveur petit à petit.

> Sinon avec #1169 et la série d'été, ça va faire bcp en très peu de temps et la newsletter va être un peu trop grosse (https://contribuer.geotribu.fr/internal/auto_newsletter/)

Je comprends.

2024-07-24 08:06 UTC, Guts commented
> Je préfèrerais que ce ne soit pas beaucoup plus tard : c'est une actualité qui perd de sa saveur petit à petit.

L'idée c'est de publier en août, même début août, pour que ça parte dans l'édition mensuelle de la newsletter d'août et pas celle de juillet (qui est déjà blindée).

2024-07-24 09:40 UTC, bchartier commented
> > Je préfèrerais que ce ne soit pas beaucoup plus tard : c'est une actualité qui perd de sa saveur petit à petit.
> 
> L'idée c'est de publier en août, même début août, pour que ça parte dans l'édition mensuelle de la newsletter d'août et pas celle de juillet (qui est déjà blindée).

Faites au mieux en fonction de vos contraintes/envies.

2024-07-24 09:45 UTC, Guts commented
@bchartier je te propose de publier le mardi 3 août.

Si c'est OK pour toi, je m'occupe du renommage et du changement de date.

2024-07-24 09:47 UTC, bchartier commented
> @bchartier je te propose de publier le mardi 3 août.
> 
> Si c'est OK pour toi, je m'occupe du renommage et du changement de date.

Oui, tu peux faire les modifications.
Merci. 🙏🏻

2024-07-24 09:58 UTC, lbartoletti commented
> > Merci pour l'article @bchartier c'est très clair comme CR ! Juste quelques corrections/propositions mineures.
> 
> Merci beaucoup pour la relecture. Désolé. Cela a dû être pénible.

Pas pénible du tout, bien au contraire, quand c'est bien écrit comme ça, c'est très agréable et fluide 😊 !

2024-07-29 13:19 UTC, Michael-cd30 commented
C'est sur LinkedIn : https://www.linkedin.com/feed/update/urn:li:activity:7223678088658710528/?actorCompanyId=104008370

2024-07-31 07:41 UTC, bchartier commented
> > @bchartier je te propose de publier le mardi 3 août.
> > Si c'est OK pour toi, je m'occupe du renommage et du changement de date.
> 
> Oui, tu peux faire les modifications. Merci. 🙏🏻

Finalement, je fais le changement de date pour cet article ?

2024-07-31 07:49 UTC, Guts commented
> Finalement, je fais le changement de date pour cet article ?

Si tu veux le faire, vas-y. Je le fais généralement au moment de la publication. Tu peux mettre au 6 août.

2024-08-05 11:34 UTC, merged

2024-08-05 11:35 UTC, Guts commented
Je publie dès maintenant car je ne serai pas disponible demain a priori.

2024-08-06 11:13 UTC, Guts commented
LinkedIn : https://www.linkedin.com/feed/update/urn:li:share:7226545764137644033/