[Article] Créer un environnement virtuel Python pour le développement de plugin QGIS avec VSCode sous Windows
geotribu/website pull request #1216
Opened 2024-10-24 16:11 UTC by nicogodet

2024-10-27 10:36 UTC, Guts commented
Merci @nicogodet pour la proposition d'article 🙏 !

J'ai édité la description avec notre message type dans lequel il y a quelques infos immanquables et dans laquelle tu peux choisir les canaux et modes de diffusion.

Pour la relecture, nous la réalisons de préférence via [le mode Review de GitHub](https://docs.github.com/fr/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews). Ergonomiquement c'est pas la plus grande réussite de GitHub mais ça le gros avantage de coller au workflow et de permettre la collaboration.

Si tu n'es pas à l'aise avec ce mode de travail, ne pas hésiter à nous le dire, soit pour former rapidement, accompagner ou trouver un autre moyen.

A noter que nous nous permettons de modifier directement ce qui est de l'ordre des règles de contribution (syntaxe Markdown, images, etc.), sans jamais toucher au fond (formulation, structure de l'article, etc.) sans commentaire.

2024-10-27 10:37 UTC, Guts commented
Allez zou, c'est parti pour la @geotribu/relecture  !

:information_source: **Aux relecteur/ices**

Merci d'utiliser autant que possible le mode Suggestion de la review : https://docs.github.com/fr/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request#starting-a-review

![image](https://github.com/geotribu/website/assets/1596222/4d081e97-7290-48c4-b1ff-587a8920b508)

C'est vraiment **IMPORTANT** pour le confort de l'auteur/ice :pray:


:arrow_right: https://github.com/geotribu/website/pull/1216/files

2024-10-27 10:55 UTC, Guts requested changes
Première salve de relecture pour la forme !

2024-10-27 10:55 UTC, Guts commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +image: "Image d'illustration de l'article qui sert ensuite dans la mise en avant : réseaux sociaux, flux RSS... 400x800 en PNG"
Soit tu as la motivation/envie de faire une image d'en-tête aux bonnes dimensions soit tu laisses vide pour avoir une image auto-générée.

```suggestion
image:
```

2024-10-27 10:55 UTC, Guts commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +title: "Créer un environnement virtuel Python pour le développement de plugin QGIS avec VSCode sous Windows"
Tu peux ajouter un subtil _subtitle_ qui s'affiche dans la navigation de gauche. Une idée comme une autre, mais change pour la tienne évidemment :

```suggestion
title: "Créer un environnement virtuel Python pour le développement de plugin QGIS avec VSCode sous Windows"
subtitle: Protégeons notre environnement, pour nos enfants PyQGIS
```

2024-10-27 10:55 UTC, Guts commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +    - plugin qgis
Appliquer l'ordre alphabétique et respecter la casse des noms officiels. Tu peux te baser sur les tags existants https://geotribu.fr/tags/

2024-10-27 10:55 UTC, Guts commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +Et bien plus maintenant ! Après avoir fouiller les archives d'internet et explorer les pistes fournis par Julien, voici l'une des méthodes permettant d'avoir toutes (ou presque) les autocomplétions d
```suggestion
Et bien plus maintenant ! Après avoir fouiller les archives d'internet et explorer les pistes fournis par [Julien](../../team/julien-moura.md), voici l'une des méthodes permettant d'avoir toutes (ou presque) les autocomplétions d'objets et méthodes PyQGIS, PyQt, etc. dans VS Code.
```

2024-10-27 10:55 UTC, Guts commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +Je suppose dans la suite que vous avez QGIS installé via l'installateur réseau OSGeo4W et que l'installation est localisée dans `C:\OSGeo4W`.
En installant avec le MSI tu as aussi accès à la console non ?

2024-10-27 10:55 UTC, Guts commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +2. Exécuter les commandes suivantes :
En général, on préfère la numérotation avec des `1` pour moins se casser la tête si jamais on doit insérer une nouvelle puce :

```suggestion
1. Ouvrir un console OSGeo Shell et naviguer jusqu'à l'emplacement où vous souhaiter créer l'environnement virtuel. Par exemple, un template de plugin fraichement créé via l'outil [QGIS Plugin Templater](https://gitlab.com/Oslandia/qgis/template-qgis-plugin).
1. Exécuter les commandes suivantes :
```

2024-10-27 10:55 UTC, Guts commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +    ```text
```suggestion
    ```ini
```

2024-10-27 10:55 UTC, Guts commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +![Contribuez GeoPF Altimétrie](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/pyqgis_environnement_dev_windows/vscode_geopf.webp)
```suggestion
![Contribuez GeoPF Altimétrie](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/pyqgis_environnement_dev_windows/vscode_geopf.webp){: .img-center loading=lazy }
```

2024-10-27 10:55 UTC, Guts commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +![PyQt](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/pyqgis_environnement_dev_windows/vscode_pyqt.webp)
```suggestion
![PyQt](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/pyqgis_environnement_dev_windows/vscode_pyqt.webp){: .img-center loading=lazy }
```

2024-10-27 10:55 UTC, Guts commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +![Complétion des imports](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/pyqgis_environnement_dev_windows/vscode.webp)
```suggestion
![Complétion des imports](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/pyqgis_environnement_dev_windows/vscode.webp){: .img-center loading=lazy }
```

2024-10-27 10:55 UTC, Guts commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +![Complétion des méthodes](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/pyqgis_environnement_dev_windows/vscode2.webp)
```suggestion
![Complétion des méthodes](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/pyqgis_environnement_dev_windows/vscode2.webp){: .img-center loading=lazy }
```

2024-10-27 10:55 UTC, Guts commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +4. Créer le fichier _sitecustomize.py_ dans le dossier _.venv\Lib\site-packages_ avec le contenu suivant :
```suggestion
3. Pour que VSCode reconnaisse les imports `processing`, ajouter la ligne suivante dans le fichier _.venv\qgis.pth_ :  
    `C:\OSGeo4W\apps\qgis\python\plugins`

    Votre fichier devrait ressembler à ça :

    ```text
    C:\OSGeo4W\apps\qgis\python
    C:\OSGeo4W\apps\qgis\python\plugins
    ```

    Veiller à ce que l'encodage du fichier _.venv\qgis.pth_ soit bien en UTF-8.

4. Créer le fichier `sitecustomize.py` dans le dossier `.venv\Lib\site-packages` avec le contenu suivant :
```

2024-10-27 10:55 UTC, Guts commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +    ```python
Ajout titre au bloc de code :

````suggestion
    ```python title="venv\Lib\site-packages\sitecustomize.py"
````

2024-10-27 11:44 UTC, gounux reviewed
Merci pour l'article @nicogodet ! Quelques petites corrections de typo / orthographe, je vais essayer de dérouler les commandes de l'article

2024-10-27 11:44 UTC, gounux commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +TOut ceux qui s'y sont frottés le savent, configurer son environnement PyQGIS et PyQt pour développer des plugins Python pour QGIS est un réel parcours du combattant. À la fin, on est souvent perdant
```suggestion
Tout ceux qui s'y sont frottés le savent, configurer son environnement PyQGIS et PyQt pour développer des plugins Python pour QGIS est un réel parcours du combattant. À la fin, on est souvent perdant...
```

2024-10-27 11:44 UTC, gounux commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +1. Ouvrir un console OSGeo Shell et naviguer jusqu'à l'emplacement où vous souhaiter créer l'environnement virtuel.
```suggestion
1. Ouvrir un console OSGeo Shell et naviguer jusqu'à l'emplacement où vous souhaitez créer l'environnement virtuel.  
```

2024-10-27 11:44 UTC, gounux commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +   Par exemple, un template de plugin fraichement créé via l'outil [QGIS Plugin Templater](https://gitlab.com/Oslandia/qgis/template-qgis-plugin).
```suggestion
   Par exemple, un template de plugin fraîchement créé via l'outil [QGIS Plugin Templater](https://gitlab.com/Oslandia/qgis/template-qgis-plugin).
```

2024-10-27 11:48 UTC, nicogodet commented
> Pour la relecture, nous la réalisons de préférence via [le mode Review de GitHub](https://docs.github.com/fr/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews). Ergonomiquement c'est pas la plus grande réussite de GitHub mais ça le gros avantage de coller au workflow et de permettre la collaboration.
> 
> 
> 
> Si tu n'es pas à l'aise avec ce mode de travail, ne pas hésiter à nous le dire, soit pour former rapidement, accompagner ou trouver un autre moyen.


Entièrement familier à ce mode de fonctionnement !
Je regarde tes commentaires dès que j'ai un moment

2024-10-27 21:32 UTC, Guts commented
@nicogodet au fait, la peinture est encore fraîche mais une fois l'article finalisé, ça vaudra le coup de le traduire si ça te tente https://blog.geotribu.net/blog/

2024-10-28 11:06 UTC, nicogodet commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +    - plugin qgis
```suggestion
tags:
    - Plugin QGIS
    - PyQGIS
    - Python
    - VS Code
    - Windows
```

2024-11-09 16:30 UTC, nicogodet commented
@Guts Ayé !

2024-11-15 13:38 UTC, Guts approved these changes
Allez quelques dernières suggestions d'améliorations et c'est bon pour publication.

Mardi 19, c'est OK pour toi ?

Tu publies sur le blog en anglais en suivant ? Outils de traduction automatisés acceptés.

2024-11-15 13:38 UTC, Guts commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +![Complétion des méthodes](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/pyqgis_environnement_dev_windows/vscode2.webp){: .img-center loading=lazy }
J'ai opté pour des noms explicites car c'est déjà bien le bordel dans ce pseudo cdn pour ne pas en rajouter et c'est plus pratique quand on fait un `geotribu si vscode*` 

```suggestion
![Complétion des imports](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/pyqgis_environnement_dev_windows/vscode_intellisense_completion_imports.webp){: .img-center loading=lazy }

![Complétion des méthodes](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/pyqgis_environnement_dev_windows/vscode_intellisense_completion_methodes.webp){: .img-center loading=lazy }
```

2024-11-15 13:38 UTC, Guts commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +Dans le terminal VS Code, exécuter la commande `pip install PyQt5-stubs`.
````suggestion
Dans le terminal VS Code, exécuter la commande : 

```powershell title="Installer la complétion PyQT dans l'environnement virtuel"
pip install PyQt5-stubs
```
````

2024-11-15 13:38 UTC, Guts commented on content/articles/2024/2024-10-XX_pyqgis_environnement_dev_windows.md
> +Tout ceux qui s'y sont frottés le savent, configurer son environnement Python, PyQGIS et PyQt sous Windows pour développer des plugins pour QGIS est un réel parcours du combattant. À la fin, on est s
Parce-que j'aime bien les icônes/logo en mode lettrine de paragraphe :yum: 

```suggestion

![logo PyQGIS](https://cdn.geotribu.fr/img/logos-icones/programmation/pyqgis.png){: .img-thumbnail-left }

Tout ceux qui s'y sont frottés le savent, configurer son environnement Python, PyQGIS et PyQt sous Windows pour développer des plugins pour QGIS est un réel parcours du combattant. À la fin, on est souvent perdant...
```

2024-11-15 14:18 UTC, nicogodet commented
> Mardi 19, c'est OK pour toi ?

OK !

> Tu publies sur le blog en anglais en suivant ? Outils de traduction automatisés acceptés.

Je sortirais ma plus belle prose dans la langue de Shakespeare

2024-11-15 15:34 UTC, Guts commented
> > Mardi 19, c'est OK pour toi ?
> 
> OK !
> 
> > Tu publies sur le blog en anglais en suivant ? Outils de traduction automatisés acceptés.
> 
> Je sortirais ma plus belle prose dans la langue de Shakespeare

@nicogodet alors désolé mais ça t'embête si on priorise https://github.com/geotribu/website/pull/1225 pour mardi prochain ? vu que c'est lié à un événement en cours, c'est mieux s'il paraît au plus tôt

On peut planifier le tien pour le 25

2024-11-25 12:23 UTC, Guts commented
Allez zou, on publie aujourd'hui pour nourrir le référencement et les fans du flux RSS.


On diffuse dans la semaine.

2024-11-25 12:23 UTC, merged

2024-11-25 13:02 UTC, Guts commented
https://geotribu.fr/articles/2024/2024-11-25_pyqgis_environnement_dev_windows/