article: Suivre le Vendée Globe 2024 depuis un SIG
geotribu/website pull request #1225
Opened 2024-11-14 07:32 UTC by florentfgrs

Proposition d'article : 
>  Suivre le Vendée Globe 2024 depuis un SIG 

## Résumé 

Le Vendée globe ne fourni pas de données SIG de la course, cet article propose une méthode pour construire ces données à partir du classement. Et ensuite pourquoi exploité ces données dans n'importe quel SIG.

## 📢 Diffusion

Une fois l'article publié, il sera alors temps de le diffuser. Il sera automatiquement intégré au [flux RSS](http://geotribu.fr/feed_rss_created.xml) et à [la newsletter](http://geotribu.fr/newsletter/signup/).

Mais la publication sur les réseaux sociaux est manuelle.

Nous avons des comptes officiels sur ces réseaux sociaux :

- ~~[Facebook](https://www.facebook.com/geotribu) - inactif~~
- [Mastodon](https://mapstodon.space/@geotribu)
- [Twitter](https://twitter.com/geotribu)

Et nous utilisons nos comptes persos pour diffuser sur LinkedIn avec [le hashtag #Geotribu](https://www.linkedin.com/feed/hashtag/?keywords=geotribu).

Merci d'indiquer en commentaire tes comptes à utiliser pour être cité/e dans les messages et de cocher ci-après la "stratégie" de diffusion qui te convient pour chaque réseau.

### LinkedIn

- [x] un/e membre de Geotribu publie, tu repartages avec ton compte
- [ ] tu publies, on repartage
- [ ] chacun/e publie de son côté

### Mastodon

- [x] un/e membre de Geotribu publie, tu repartages avec ton compte
- [ ] tu publies, on repartage
- [ ] chacun/e publie de son côté

### Twitter

- [x] un/e membre de Geotribu publie, tu repartages avec ton compte
- [ ] tu publies, on repartage
- [ ] chacun/e publie de son côté

2024-11-14 09:05 UTC, Guts requested changes
Merci pour ce super article ! J'ai fait quelques remarques et corrections mais on sent que t'es monté en compétences sur mkdocs depuis le premier article DuckDB :clap:

2024-11-14 09:05 UTC, Guts commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> + ```
indentation

```suggestion
!!! tip "Expression QGIS pour afficher uniquement le nom des navigateurs sur les étiquettes"

   ```python
   regexp_substr("bateau", '^[^-]+')
   ```
```

2024-11-14 09:05 UTC, Guts commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +- `24h` = Depuis 24h
indentation et fautes de français

```suggestion
!!! info "Signification des préfixes dans les noms de colonnes"

    - `30m` = Depuis 30 minutes
    - `last_rank` = Depuis le pointage précédent
    - `24h` = Depuis 24h
```

2024-11-14 09:22 UTC, Guts commented
Merci @florentfgrs  pour la proposition d'article 🙏 !

:information_source: Message automatique à lire et remplir :arrow_down: 

## 👓 Relecture

Pour la relecture, nous la réalisons de préférence via [le mode Review de GitHub](https://docs.github.com/fr/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews).

Si tu n'es pas à l'aise avec ce mode de travail, ne pas hésiter à nous le dire, soit pour former rapidement, accompagner ou trouver un autre moyen.

A noter que nous nous permettons de modifier directement ce qui est de l'ordre des règles de contribution (syntaxe Markdown, images, etc.), sans jamais toucher au fond (formulation, structure de l'article, etc.) sans commentaire.

### Liens importants

- pour modifier ton article via l'interface de GitHub,  tu peux le retrouver facilement via l'icône crayon en haut de la page sur le site de prévisualisation ([cf. documentation](https://contribuer.geotribu.fr/edit/fix_content_from_website/)). Sinon :
  - [article](https://github.com/florentfgrs/geotribu/edit/article/suivre-le-vendee-gloabe-2024-depuis-un-sig/content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md?pr=%2Fgeotribu%2Fwebsite%2Fpull%2F1225)
  - [page auteur/ice](https://github.com/florentfgrs/geotribu/blob/article/suivre-le-vendee-gloabe-2024-depuis-un-sig/content/team/florent-fougeres.md) 
- [site temporaire de prévisualisation de l'article](https://preview-pullrequest-1225--geotribu-preprod.netlify.app/articles/2024/2024-11-20_vendee_globe_donnees_sig/#obtenir-le-dernier-pointage) - merci de ne pas le diffuser

@geotribu/relecture c'est à vous !


## Ressources

Pour info, voici quelques extraits de notre guide de contribution :

- [comprendre et compléter l'en-tête](https://contribuer.geotribu.fr/guides/metadata_yaml_frontmatter/)
- [intégrer une image](https://contribuer.geotribu.fr/guides/image/)
- [choisir une licence](https://contribuer.geotribu.fr/guides/licensing/)
- [signer un article](https://contribuer.geotribu.fr/guides/authoring/)

2024-11-14 09:22 UTC, Guts commented
Allez zou, c'est parti pour la @geotribu/relecture  !

:information_source: **Aux relecteur/ices**

Merci d'utiliser autant que possible le mode Suggestion de la review : https://docs.github.com/fr/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request#starting-a-review

![image](https://github.com/geotribu/website/assets/1596222/4d081e97-7290-48c4-b1ff-587a8920b508)

C'est vraiment **IMPORTANT** pour le confort de l'auteur/ice :pray:

2024-11-15 05:42 UTC, gounux reviewed
Corrections de quelques petites coquilles.
J'ai pu essayer le script, c'est très cool !

![image](https://github.com/user-attachments/assets/004af2e7-dc80-43ca-91a0-eb68e9df2701)

2024-11-16 16:25 UTC, lbartoletti reviewed
Cool!
C'est très clair et sympa.

J'ai vu timemanager, tu as testé de faire une animation temporelle dans QGIS ? Ça pourrait être cool en visu.

2024-11-16 16:25 UTC, lbartoletti commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +    - voile
```suggestion
    - Voile
```

2024-11-16 16:25 UTC, lbartoletti commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +Ensuite, il est nécessaire de traiter la manière dont les données de localisation sont présentées. En effet, les positions des bateaux sont souvent fournies sous un format de coordonnées géographique
> il n'est pas directement compatible avec les outils de géomatique

Je sais que tu ne veux pas l'utiliser et que tu le refoules au fond de toi. Mais, on sait utiliser du DMS 😉 

https://proj.org/en/9.3/apps/cs2cs.html

mais oui, reste avec DD, ton code python est très bien comme ça !

2024-11-16 16:25 UTC, lbartoletti commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +Enfin, il est important d'exporter ces données SIG dans un format compatible, comme le Geopackage ou le GeoJSON. Une fois converties, ces données peuvent être utilisées dans n'importe quel SIG, qu'il
```suggestion
Enfin, il est important d'exporter ces données SIG dans un format compatible, comme le GeoPackage ou le GeoJSON. Une fois converties, ces données peuvent être utilisées dans n'importe quel SIG, qu'il s'agisse d'un SIG bureautique comme QGIS ou d'une carte web SIG avec des outils comme MapLibre ou Leaflet.
```

c'est GeoPackage

2024-11-16 16:25 UTC, lbartoletti commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +Pour aller plus dans le détail technique, une fois le fichier téléchargé, les étapes successives sont :
ça serait bien, si possible, d'ajouter un peu de visuel sur à quoi ressemble la donnée et comment tu t'en sors 😊

2024-11-16 16:25 UTC, lbartoletti commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +python dernier_pointage.py --output-dir ./data_vg
```suggestion
python dernier_pointage.py --output-dir ./data_vg.gpkg
```

Je suppose que data_vg est un GeoPackage ?

2024-11-16 16:25 UTC, lbartoletti commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +    regexp_substr("bateau", '^[^-]+')
De la magie noire !

On va supposer que le lecteur ne sache pas ce qu'est une regexp et/ou ne sache pas la lire directement, soit environ 99% d'entre nous 😉  Est-ce que tu peux l'expliquer stp ?

2024-11-16 16:25 UTC, lbartoletti commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +python trajectoires_pointages.py --output-dir ./data_vg
```suggestion
python trajectoires_pointages.py --output-dir ./data_vg.gpkg
```

2024-11-16 16:25 UTC, lbartoletti commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +Il s’agit d’une couche de points indiquant tous les pointages de chaque bateau depuis le départ, ainsi qu’une couche de lignes reliant ces points pour former la trajectoire des bateaux. Le format obt
```suggestion
Il s’agit d’une couche de points indiquant tous les pointages de chaque bateau depuis le départ, ainsi qu’une couche de lignes reliant ces points pour former la trajectoire des bateaux. Le format obtenu est également un GeoPackage.
```

2024-11-16 16:25 UTC, lbartoletti commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +Il s’agit d’une couche de points indiquant tous les pointages de chaque bateau depuis le départ, ainsi qu’une couche de lignes reliant ces points pour former la trajectoire des bateaux. Le format obt
pareil ailleurs

2024-11-16 16:41 UTC, florentfgrs commented
> Cool!
> 
> C'est très clair et sympa.
> 
> 
> 
> J'ai vu timemanager, tu as testé de faire une animation temporelle dans QGIS ? Ça pourrait être cool en visu.

Ah non je n'y avais pas pensé mais c'est une super idée, c'est possible j'ai un timestamp. Je vais essayer ça et je rajouterais dans l'article plus tard si c'est concluant.

2024-11-16 17:26 UTC, igeofr reviewed
Merci pour l'article @florentfgrs, je trouve l'idée vraiment sympa. 
Dommage que l'organisateur ne publie pas les données au format csv...

2024-11-17 08:33 UTC, florentfgrs commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +Ensuite, il est nécessaire de traiter la manière dont les données de localisation sont présentées. En effet, les positions des bateaux sont souvent fournies sous un format de coordonnées géographique
je savais même pas :)

2024-11-17 09:10 UTC, florentfgrs commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +Pour aller plus dans le détail technique, une fois le fichier téléchargé, les étapes successives sont :
Tu veux dire un visuel du DataFrame au fur et à mesure des étapes ? J'ai déjà mis un visuel du tableur, mais tu as raison, ça ne suffit peut-être pas

2024-11-17 09:11 UTC, florentfgrs commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +python dernier_pointage.py --output-dir ./data_vg
C'est un dossier de destination, le nom et l'extension du fichier sont gérés dans le code, pas par les paramètres.

2024-11-17 09:11 UTC, florentfgrs commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +python trajectoires_pointages.py --output-dir ./data_vg
Idem

2024-11-17 09:12 UTC, florentfgrs commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +    regexp_substr("bateau", '^[^-]+')
Je vais supprimer cette partie, elle est devenue obsolète, j'ai ajouté une colonne bateau et une colonne skipper.

2024-11-17 09:19 UTC, florentfgrs commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +Il faut commencer par récupérer les informations relatives aux positions des bateaux. Cela signifie télécharger les fichiers Excel, car le site ne permet pas de les récupérer en masse. J'ai donc étud
Ajouté

2024-11-17 09:20 UTC, florentfgrs commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +Il faut commencer par récupérer les informations relatives aux positions des bateaux. Cela signifie télécharger les fichiers Excel, car le site ne permet pas de les récupérer en masse. J'ai donc étud
https://github.com/geotribu/website/pull/1225/commits/6f5bb071dbe344300e7865afbb105dc47be9210a

2024-11-17 15:25 UTC, Guts commented
> > Cool!
> > 
> > C'est très clair et sympa.
> > 
> > 
> > 
> > J'ai vu timemanager, tu as testé de faire une animation temporelle dans QGIS ? Ça pourrait être cool en visu.
> 
> Ah non je n'y avais pas pensé mais c'est une super idée, c'est possible j'ai un timestamp. Je vais essayer ça et je rajouterais dans l'article plus tard si c'est concluant. 

Dans le même genre pour briller en société QGISienne, tu peux proposer un projet qui intègre ce qu'il faut pour charger et MAJ les données via du PyQGIS plutôt que des scripts Python extérieurs.

Via une action ou un script à l'ouverture du projet, etc.

2024-11-18 12:56 UTC, florentfgrs commented on content/articles/2024/2024-11-20_vendee_globe_donnees_sig.md
> +Pour aller plus dans le détail technique, une fois le fichier téléchargé, les étapes successives sont :
Ajouté

2024-11-18 13:00 UTC, florentfgrs commented
Merci à tous les reviewer ! @Guts @lbartoletti @igeofr @gounux 

Comme suggérer, j'ai ajouté : 

- Un peu d'illustration dans la partie traitement des données 
- Une nouvelle partie sur commencer utiliser ces données avec le contrôleur temporal de QGIS 

Une fois ces deux points revue, c'est ok pour moi de mon côté pour publier.

2024-11-18 13:12 UTC, Guts commented
Tip top @florentfgrs !

Allez je publie très bientôt, on fera la diffusion demain.

2024-11-18 13:27 UTC, Guts approved these changes

2024-11-18 13:29 UTC, merged