article: vendée globe 2024 et SIG partie 2
geotribu/website pull request #1231
Opened 2024-12-09 15:45 UTC by florentfgrs

Proposition d'article : 
>  Suivre le Vendée Globe 2024 depuis un SIG Partie 2

## Résumé 

Suite à la partie 1 qui expliquait une méthode pour construire des données SIG à partir du classement fourni dans un tableur. Cette partie 2 porte sur l'automatisation de la génération des données SIG avec de la CI/CD et sur le développement d'une carto web pour les visualiser.

## 📢 Diffusion

Une fois l'article publié, il sera alors temps de le diffuser. Il sera automatiquement intégré au [flux RSS](http://geotribu.fr/feed_rss_created.xml) et à [la newsletter](http://geotribu.fr/newsletter/signup/).

Mais la publication sur les réseaux sociaux est manuelle.

Nous avons des comptes officiels sur ces réseaux sociaux :

- ~~[Facebook](https://www.facebook.com/geotribu) - inactif~~
- [Mastodon](https://mapstodon.space/@geotribu)
- [Twitter](https://twitter.com/geotribu)

Merci d'indiquer en commentaire tes comptes à utiliser pour être cité/e dans les messages et de cocher ci-après la "stratégie" de diffusion qui te convient pour chaque réseau.

### LinkedIn

- [x] un/e membre de Geotribu publie, tu repartages avec ton compte
- [ ] tu publies, on repartage
- [ ] chacun/e publie de son côté

### Mastodon

- [x] un/e membre de Geotribu publie, tu repartages avec ton compte
- [ ] tu publies, on repartage
- [ ] chacun/e publie de son côté

### Twitter

- [x] un/e membre de Geotribu publie, tu repartages avec ton compte
- [ ] tu publies, on repartage
- [ ] chacun/e publie de son côté

2024-12-09 16:41 UTC, Guts commented
Merci pour la proposition d'article 🙏 !

Concernant la diffusion, le compte Twitter est désormais inactif. J'ai mis à jour la description pour que tu puisses décider pour BlueSky.

@geotribu/relecture c'est à vous !

2024-12-10 11:29 UTC, Guts commented
Allez zou, c'est parti pour la @geotribu/relecture  !

:information_source: **Aux relecteur/ices**

Merci d'utiliser autant que possible le mode Suggestion de la review : https://docs.github.com/fr/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request#starting-a-review

![image](https://github.com/geotribu/website/assets/1596222/4d081e97-7290-48c4-b1ff-587a8920b508)

C'est vraiment **IMPORTANT** pour le confort de l'auteur/ice :pray:

2024-12-14 08:14 UTC, gounux reviewed
Quelques corrections mineures, merci pour cet article documenté et instructif

2024-12-14 08:14 UTC, gounux commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +## Mise en musique de la construction des données SIG dans un pipeline de CI/CD
On dit `un` pipeline ou `une` pipeline ? J'ai un doute :thinking:

2024-12-14 08:14 UTC, gounux commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +- `generate` : ce [job](https://github.com/florentfgrs/Vendee-Globe-2024/blob/main/.github/workflows/pointages.yml#L21) installe les dépendances python puis exécute les scripts qui permettent de télé
```suggestion
- `generate` : ce [job](https://github.com/florentfgrs/Vendee-Globe-2024/blob/main/.github/workflows/pointages.yml#L21) installe les dépendances python puis exécute les scripts qui permettent de télécharger les tableurs Excel des pointages pour les convertir en données SIG.
```

2024-12-14 08:14 UTC, gounux commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +- `update-files`: ce [dernier job](https://github.com/florentfgrs/Vendee-Globe-2024/blob/main/.github/workflows/pointages.yml#L75) commit et push les données SIG dans le projet afin d'avoir une URL f
```suggestion
- `update-files`: ce [dernier job](https://github.com/florentfgrs/Vendee-Globe-2024/blob/main/.github/workflows/pointages.yml#L75) commit et push les données SIG dans le projet afin d'avoir une URL fixe pour les utiliser dans l'application web. Ce job est amené à disparaitre pour être intégré au [job de déploiement](https://github.com/florentfgrs/Vendee-Globe-2024/blob/main/.github/workflows/static.yml) de l'application web dans GitHub Pages.
```

2024-12-14 08:14 UTC, gounux commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +En [haut du pipeline](https://github.com/florentfgrs/Vendee-Globe-2024/blob/main/.github/workflows/pointages.yml#L3-L5), on peut voir ce format de morceau code.
```suggestion
En [haut du pipeline](https://github.com/florentfgrs/Vendee-Globe-2024/blob/main/.github/workflows/pointages.yml#L3-L5), on peut voir ce format de morceau de code.
```

2024-12-14 08:14 UTC, gounux commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +C'est dans cette partie qu'est paramétré l'automatisation, il s'agit d'un cron, pour plus d'informations sur cette syntaxe, je trouve cette [documentation](https://doc.ubuntu-fr.org/cron) bien faite.
```suggestion
C'est dans cette partie qu'est paramétrée l'automatisation, il s'agit d'un cron, pour plus d'informations sur cette syntaxe, je trouve cette [documentation](https://doc.ubuntu-fr.org/cron) bien faite. Ici le script s'exécute chaque jour à 3h30, 7h30, 11h30 ... etc.
```

2024-12-14 08:14 UTC, gounux commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +Chaque fois que le pipeline est exécuté, les dernières données écrasent les précédentes. Plus précisément, la dernière release est supprimé, et une nouvelle portant le même nom (`latest`) est créée.
```suggestion
Chaque fois que le pipeline est exécuté, les dernières données écrasent les précédentes. Plus précisément, la dernière release est supprimée, et une nouvelle portant le même nom (`latest`) est créée. Il n'y a donc qu'une seule release des données disponible à cette [adresse](https://github.com/florentfgrs/Vendee-Globe-2024/releases/tag/latest).  Toutes les quatre heures, vous pouvez donc télécharger les dernières données d'avancement de la course.
```

2024-12-14 08:14 UTC, gounux commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +On va donc y mettre l'URL du fichier latest_data.gpkg qui contient la couche des pointages et celle des trajectoires.
```suggestion
On va donc y mettre l'URL du fichier `latest_data.gpkg` qui contient la couche des pointages et celle des trajectoires.
```

2024-12-14 08:14 UTC, gounux commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +Par défaut aucune trace n'est affiché, il faut alors cliquer sur les concurrents de votre choix dans la barre de gauche (ils sont classés dans l'ordre de leur position en course), ou bien cliqué sur
```suggestion
Par défaut aucune trace n'est affichée, il faut alors cliquer sur les concurrents de votre choix dans la barre de gauche (ils sont classés dans l'ordre de leur position en course), ou bien cliquer sur le bouton `Tout afficher`.
```

2024-12-14 08:14 UTC, gounux commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +Cette application web est encore en phase de développement, j'aimerais encore l'améliorer. Par exemple, actuellement, dans la petite fenêtre qui s'affiche au survol,  en haut à gauche, il n'y a pas t
```suggestion
Cette application web est encore en phase de développement, j'aimerais encore l'améliorer. Par exemple, actuellement, dans la petite fenêtre qui s'affiche au survol, en haut à gauche, tous les attributs ne sont pas affichés. Comme énoncé plus haut, j'aimerais aussi ne plus lire les données en dur dans le dépôt GitHub, mais j'aimerais tout gérer dans le pipeline de déploiement de la GitHub Pages.
```

2024-12-14 21:33 UTC, Michael-cd30 commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +    - cron: "30 3,7,11,15,19,23 * * *"
3/4

[Crontab guru](https://crontab.guru/#30_3/4_*_*_*)

2024-12-14 21:33 UTC, Michael-cd30 commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +    Les heures qu'on indique sont des heures GMT 0 ([heure de Greenwich](https://time.is/fr/GMT)) dans mon exemple il y a donc un décalage de +1h avec l'heure de Paris (GMT+1).
```suggestion
    Les heures qu'on indique sont des heures GMT 0 ([heure de Greenwich](https://time.is/fr/GMT)) dans mon exemple il y a donc, en hiver, un décalage de +1h avec l'heure de Paris (GMT+1).
```

2024-12-14 21:33 UTC, Michael-cd30 commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +    Les heures qu'on indique sont des heures GMT 0 ([heure de Greenwich](https://time.is/fr/GMT)) dans mon exemple il y a donc un décalage de +1h avec l'heure de Paris (GMT+1).
de + ou de - ?

2024-12-14 21:33 UTC, Michael-cd30 commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +Chaque fois que le pipeline est exécuté, les dernières données écrasent les précédentes. Plus précisément, la dernière release est supprimé, et une nouvelle portant le même nom (`latest`) est créée.
```suggestion
Chaque fois que le pipeline est exécuté, les dernières données écrasent les précédentes. Plus précisément, la dernière release est supprimé, et une nouvelle portant le même nom (`latest`) est créée. Il n'y a donc qu'une seule release des données disponibles à cette [adresse](https://github.com/florentfgrs/Vendee-Globe-2024/releases/tag/latest).  Tous les quatre heures, vous pouvez ainsi télécharger les dernières données d'avancement de la course.
```

Pas mal de "donc", donc je propose de supprimer celui-ci.

2024-12-14 21:33 UTC, Michael-cd30 commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +Dans la fenêtre qui s'affiche, dans le champ `Jeux de données vectorielles` vous pouvez coller un URL de fichier qui provient de la release.
URL est féminin d'après le larousse

https://www.larousse.fr/dictionnaires/francais/URL/80723

2024-12-14 21:33 UTC, Michael-cd30 commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +Cette carte est basée sur les données générées par la CI, ce n'est donc pas du temps réel, mais un aperçu du dernier pointage. Les données sont donc automatiquement mises à jour toutes les 4h, là enc
2 donc

2024-12-16 08:06 UTC, florentfgrs commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +    Les heures qu'on indique sont des heures GMT 0 ([heure de Greenwich](https://time.is/fr/GMT)) dans mon exemple il y a donc un décalage de +1h avec l'heure de Paris (GMT+1).
De plus, le pipeline s'exécute à 8h30 HF alors qu'il est configuré à 7h30.

2024-12-16 08:07 UTC, florentfgrs commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +Cette carte est basée sur les données générées par la CI, ce n'est donc pas du temps réel, mais un aperçu du dernier pointage. Les données sont donc automatiquement mises à jour toutes les 4h, là enc
2 ?

2024-12-16 08:09 UTC, florentfgrs commented
Merci @gounux @Michael-cd30  pour la review, j'ai effectué toutes les reprises.

2024-12-17 06:01 UTC, Guts requested changes
Flo, je te vois évoluer à grande vitesse (je dirais à ~50 noeuds marins) alors je me suis dit qu'il était temps de mettre la barre encore plus haute.

La quantité de mes remarques et demandes n'est pas un indicateur de la qualité de ta démarche et de ce que cette série d'articles apporte.

2024-12-17 07:49 UTC, florentfgrs commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +
@Guts J'ai vu ça aussi je comprends pas bien pourquoi ça fait ça. 

Bonne idée le QGZ !

2024-12-17 08:04 UTC, florentfgrs commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +
@lbartoletti m'indique que c'est un problème du [anté méridien](https://en.wikipedia.org/wiki/180th_meridian). Je vais essayer de fixer plus tard.

2024-12-17 08:39 UTC, lbartoletti commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +
Oui, tes données doivent être découpées au niveau du 180th merdian / antemeridian.

Dans QGIS, tu as un outil pour cela : 

![image](https://github.com/user-attachments/assets/84eb42b2-7507-4a42-9007-af052472c681)

Avec l'outil `native:antimeridiansplit` tu ne retrouves plus avec les lignes faisant le tour de la terre dans l'autre sens.

Pour la blague, tu peux également regarder la projection 3832 qui va être centrée sur le Pacifique et non l'atlantique, ça va faire d'autres traits :)

2024-12-17 08:50 UTC, Guts commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +subtitle: Vendée Globe et données SIG - Partie 2
le sous-titre n'est pas là pour décrire le contenue, cf autres articles et template (?), mais plutôt pour ajouter une pointe d'humour ou une info

2024-12-17 08:51 UTC, florentfgrs commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +subtitle: Vendée Globe et données SIG - Partie 2
Ah pardon, j'avais mal compris, je pensais, c'était le titre 
go alors

2024-12-17 09:03 UTC, Guts commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +subtitle: Vendée Globe et données SIG - Partie 2
@florentfgrs c'est vraiment comme **tu** veux

2024-12-17 09:06 UTC, Guts commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +
Héhé j'étais sûr que tu allais invoquer @lbartoletti  :kissing_closed_eyes:

2024-12-17 12:26 UTC, florentfgrs commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +{: align=middle }
Bonne idée, c'est fait

2024-12-17 13:58 UTC, troopa81 commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +![QGIS - URL de couche vecteur](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/vendee_globe_donnees_sig/qgis_url_couche_vecteur.png){: .img-center loading=lazy }
En théorie je suis d'accord avec toi mais... faire du vsi proprement implique de pouvoir accéder au fichier en partie et donc que celui ci expose un header qui renseigne sur ces parties. Mais le gpkg c'est un zip de sqlite donc je vois pas trop comment ogr pourrait lire juste un header dans ce bouzin. M'étonnerai pas qu'il télécharge tout pour le coup.

Mais au final, pourquoi ne pas tout faire du vsi dans ce cas, au mieux c'est optimisé, au pire c'est pareil. Non?

2024-12-18 13:07 UTC, Guts commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +À suivre donc !
```suggestion
Cette carte est basée sur les données générées par la CI, ce n'est donc pas du temps réel, mais un aperçu du dernier pointage. Les données sont donc automatiquement mises à jour toutes les 4h, là encore, c'est la magie de la CI qui permet ça.

!!! info inline end "Transparence sur le développement"
    Le développement web n'étant pas mon domaine de prédilection, j'ai quelques connaissances de base acquise il y a quelques années lors de la formation au [master SIGAT](https://formations.univ-rennes2.fr/fr/formations/master-37/master-mention-geomatique-parcours-systeme-d-information-geographique-et-analyse-des-territoires-sigat-JEOC8L9A.html), je me suis aidé pour le développement de la partie JavaScript et CSS de l'intelligence artificielle comme indiqué dans le [readme](https://github.com/florentfgrs/Vendee-Globe-2024?tab=readme-ov-file#%EF%B8%8F-visualisateur-web).

D'un point de vue technique, elle se base sur [Maplibre](https://maplibre.org/), il s'agit d'une bibliothèque JavaScript open-source de cartographie web permettant de créer des cartes interactives personnalisées à partir de données géospatiales.

Par défaut aucune trace n'est affichée, il faut alors cliquer sur les concurrents de votre choix dans la barre de gauche (ils sont classés dans l'ordre de leur position en course), ou bien cliquer sur le bouton `Tout afficher`.

Au survol d'une trace, un popup avec le temps apparait et des informations complémentaires en haut à gauche, tel que le cap et la vitesse.

![Application web de visualisation des données](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/vendee_globe_donnees_sig/webapp.png){: .img-center loading=lazy }

Cette application web est encore en phase de développement, j'aimerais encore l'améliorer. Par exemple, actuellement, dans la petite fenêtre qui s'affiche au survol, en haut à gauche, tous les attributs ne sont pas affichés. Comme énoncé plus haut, j'aimerais aussi ne plus lire les données en dur dans le dépôt GitHub, mais j'aimerais tout gérer dans le pipeline de déploiement de la GitHub Pages.

[:material-web: Accéder à la cartographie web du Vendée Globe 2024 :map:](https://florentfgrs.github.io/Vendee-Globe-2024/){: .md-button }
{: align=middle }

À suivre donc !
```

Rendu ordi :

![image](https://github.com/user-attachments/assets/e144a740-87f0-46f0-aad6-17b7b9ac295c)


Rendu mobile :

![image](https://github.com/user-attachments/assets/0dc737bf-9dce-405a-91b4-fe05f3164903)

2024-12-19 08:55 UTC, florentfgrs commented on content/articles/2024/2024-12-18_vendee_globe_donnees_sig_partie2.md
> +À suivre donc !
top !

2024-12-19 09:35 UTC, Guts approved these changes

2024-12-19 09:38 UTC, merged

2024-12-19 15:08 UTC, gounux commented
Article annoncé :

- sur [mastodon](https://mapstodon.space/@geotribu/113679972545034959)
- sur [linkedin](https://www.linkedin.com/posts/geotribu_geotribu-suivre-le-vend%C3%A9e-globe-2024-depuis-activity-7275516635925409792-Sdqe?utm_source=share&utm_medium=member_desktop)