Article : Plugin Layer Menu From Project : LE catalogue magique !
geotribu/website pull request #1232
Opened 2024-12-10 10:55 UTC by cpornin

Une extension extension Qgis peut être (trop) méconnue : Layers Menu From Project permet de simplifier la vie des administrateurs ET des utilisateurs, retour d'expérience à deux voix.

2024-12-10 11:23 UTC, Guts commented
Merci @cpornin :partying_face: ! Je fais une première passe pour débloquer l'article de ces méchants bots et je reveins pour lancer la relecture :)

2024-12-10 11:23 UTC, Guts commented
Pour info @xcaeag :)

2024-12-10 13:24 UTC, xcaeag commented
merci @Guts pour l'info. 
@cpornin : le plugin est déjà grand-père (né en 2012 sur un QGis 1.7 !), il était un peu bancal (maintenu par des débutants), mais il prend cette année un bon coup de jeune, le code est dépoussiéré grâce aux travaux d'Oslandia (@Guts & @jmkerloch), les pb de perfs sont réglés avec la nouvelle 2.2.0, et ce n'est pas fini !
Merci à vous, l'article est sympa !

2024-12-11 11:39 UTC, Guts requested changes

2024-12-11 11:39 UTC, Guts commented on content/team/emilie-bigorne.md
> +Géomaticienne à l'Etablissement public Loire depuis 20 ans, j'accompagne les chargés de mission dans leur quotidien : accessibilité des données, automatisation des tâches, conseils.
```suggestion
Géomaticienne à l'Établissement public Loire depuis 20 ans, j'accompagne les chargés de mission dans leur quotidien : accessibilité des données, automatisation des tâches, conseils.
```

2024-12-11 11:39 UTC, Guts commented on content/articles/2024/2024-12-24_QGIS-Layers-Menu-From-Project-Le-catalogue-magique.md
> +### Nos :heavy_minus_sign:
Peu visible en mode sombre :

```suggestion
### Nos :material-minus-thick:

```

2024-12-11 11:39 UTC, Guts commented on content/articles/2024/2024-12-24_QGIS-Layers-Menu-From-Project-Le-catalogue-magique.md
> +### Nos :heavy_plus_sign:
Peu visible en mode sombre :

```suggestion
### Nos :material-plus-thick:

```

2024-12-11 13:05 UTC, Guts commented
Allez zou, c'est parti pour la @geotribu/relecture  !

:information_source: **Aux relecteur/ices**

Merci d'utiliser autant que possible le mode Suggestion de la review : https://docs.github.com/fr/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request#starting-a-review

![image](https://github.com/geotribu/website/assets/1596222/4d081e97-7290-48c4-b1ff-587a8920b508)

C'est vraiment **IMPORTANT** pour le confort de l'auteur/ice :pray:

2024-12-11 13:11 UTC, xcaeag commented on content/articles/2024/2024-12-24_QGIS-Layers-Menu-From-Project-Le-catalogue-magique.md
> +description: "Une extension extension QGIS peut être (trop) méconnue : Layers Menu From Project permet de simplifier la vie des administrateurs ET des utilisateurs, retour d'expérience à deux voix. "
et deux "extension"

2024-12-11 13:12 UTC, xcaeag commented on content/articles/2024/2024-12-24_QGIS-Layers-Menu-From-Project-Le-catalogue-magique.md
> +Avec une base PG, je peux afficher les couches directement depuis une requête, plus besoin de stocker des vues qui induise des dépendances parfois complexes. En revanche, attention, le mode de connex
induise(nt) ?

2024-12-11 13:27 UTC, Guts commented on content/articles/2024/2024-12-24_QGIS-Layers-Menu-From-Project-Le-catalogue-magique.md
> +description: "Une extension extension QGIS peut être (trop) méconnue : Layers Menu From Project permet de simplifier la vie des administrateurs ET des utilisateurs, retour d'expérience à deux voix. "
```suggestion
description: "Une extension QGIS peut être (trop) méconnue : Layers Menu From Project permet de simplifier la vie des administrateurs ET des utilisateurs, retour d'expérience à deux voix. "

```

@xcaeag essaye d'utiliser le mode suggestion pour proposer les modifs directement :wink:

2024-12-14 22:17 UTC, Michael-cd30 reviewed
Article très fluide à lire, merci de m'avoir fait découvrir ce plugin.

2024-12-14 22:17 UTC, Michael-cd30 commented on content/articles/2024/2024-12-24_QGIS-Layers-Menu-From-Project-Le-catalogue-magique.md
> +Avec LMFP : pas de sujet ! **Peu importe le modèle de données, c'est le nommage et la configuration dans le projet QGIS utilisé qui comptent**.
En plus, même si PG le permet, on nomme rarement les tables avec des espaces et des accents.
J'imagine que c'est plus pratique avec ce plugin.

2024-12-14 22:17 UTC, Michael-cd30 commented on content/articles/2024/2024-12-24_QGIS-Layers-Menu-From-Project-Le-catalogue-magique.md
> +Comme dit précédemment : la principale contrainte est alors liée au maintient du projet QGIS en entrée du plugin et à l'accès des utilisateurs à ce projet. Chez nous, il est enregistré en base de don
```suggestion
Comme dit précédemment : la principale contrainte est alors liée au maintien du projet QGIS en entrée du plugin et à l'accès des utilisateurs à ce projet. Chez nous, il est enregistré en base de données. Une authentification avec un identifiant / mot de passe est enregistrée à la première connexion de l'utilisateur, qui lui donne accès au projet via le menu et aux différentes données en base (en lecture ou en écriture).

```

2024-12-14 22:17 UTC, Michael-cd30 commented on content/articles/2024/2024-12-24_QGIS-Layers-Menu-From-Project-Le-catalogue-magique.md
> +    En plus des groupes, sous-groupes et agencement de différents projets, il est possible de créer des sections avec des titres et des séparateurs. Rendez-vous sur la documentation du plugin pour re
```suggestion
    En plus des groupes, sous-groupes et agencement de différents projets, il est possible de créer des sections avec des titres et des séparateurs. Rendez-vous sur la documentation du plugin pour rendre tout ça encore plus beau ! [C'est par ici](https://aeag.github.io/MenuFromProject-Qgis-Plugin/usage/fr_use.html#).

```

2024-12-14 22:17 UTC, Michael-cd30 commented on content/articles/2024/2024-12-24_QGIS-Layers-Menu-From-Project-Le-catalogue-magique.md
> +L'année dernière, on a commencé à intégrer des relations dans notre projet QGIS. Le problème : charger une couche depuis le menu ne chargeait ni l'autre (ou les autres ) couche(s) ni la relation.
```suggestion
L'année dernière, on a commencé à intégrer des relations dans notre projet QGIS. Le problème : charger une couche depuis le menu ne chargeait ni l'autre (ou les autres) couche(s) ni la relation.

```

2024-12-14 22:17 UTC, Michael-cd30 commented on content/articles/2024/2024-12-24_QGIS-Layers-Menu-From-Project-Le-catalogue-magique.md
> +* Trop de menus différents : temps d'ouverture de qgis plus long
```suggestion
* Trop de menus différents : temps d'ouverture de QGIS plus long

```

2024-12-18 08:04 UTC, cpornin commented on content/articles/2024/2024-12-24_QGIS-Layers-Menu-From-Project-Le-catalogue-magique.md
> +Avec une base PG, je peux afficher les couches directement depuis une requête, plus besoin de stocker des vues qui induise des dépendances parfois complexes. En revanche, attention, le mode de connex
@EmilieEPLoire Est-ce que tu as une capture pour ça ? :)

2024-12-18 08:22 UTC, cpornin commented
> Article très fluide à lire, merci de m'avoir fait découvrir ce plugin.

@Michael-cd30 Merci d'avoir pris le temps de relire et suggérer des corrections !

2024-12-18 08:38 UTC, cpornin commented on content/articles/2024/2024-12-24_QGIS-Layers-Menu-From-Project-Le-catalogue-magique.md
> +Avec LMFP : pas de sujet ! **Peu importe le modèle de données, c'est le nommage et la configuration dans le projet QGIS utilisé qui comptent**.
Tout à fait, j'ai ajouté une petite parenthèse sur les accents et les espaces, c'est plus concret.

2024-12-18 10:54 UTC, arno974 commented
Super article très instructif ! Good job :)

2024-12-23 22:42 UTC, Guts approved these changes

2024-12-23 22:43 UTC, merged

2024-12-24 14:37 UTC, Guts commented
https://mapstodon.space/@geotribu/113708302435174380

2024-12-24 15:30 UTC, Guts commented
https://www.linkedin.com/feed/update/urn:li:share:7277344691388309504?actorCompanyId=104008370&lipi=urn%3Ali%3Apage%3Aorganization_admin_admin_page_posts_published%3B6cc41d0b-709f-4e04-b629-1d9ea3271bb3