article sur une introduction au json dans postgresql
geotribu/website pull request #1238
Opened 2024-12-31 10:57 UTC by thomas-szczurek

Proposition d'article sur le json dans Postgresql avec un cas d'utilisation pour le stockage des données du recensement de l'INSEE.

2024-12-31 16:10 UTC, Guts requested changes
Merci @thomas-szczurek pour cette proposition pré-réveillon !

Avant de lancer la relecture, quelques soucis bloquants à résoudre côté syntaxe et date de publication.

Je regarde plus en détail d'ici la fin de la semaine.

2024-12-31 16:10 UTC, Guts commented on content/articles/2024/2024-12-31_sql_json.md
> +:::---
Faute de syntaxe

```suggestion
---
```

2024-12-31 16:10 UTC, Guts commented on content/articles/2024/2024-12-31_sql_json.md
> +title: "Travailler avec du json et PostgreSQL"
Respecter le nom officiel.

```suggestion
title: Travailler avec du JSON et PostgreSQL
```

2024-12-31 16:10 UTC, Guts commented on content/articles/2024/2024-12-31_sql_json.md
> +## Travailler avec du json dans PostgreSQL
titre 1 

```suggestion
# Travailler avec du json dans PostgreSQL
```

2024-12-31 16:10 UTC, Guts commented on content/articles/2024/2024-12-31_sql_json.md
> +date: 2024-12-31
Aucune chance que ce soit publié ce jour-ci ni même en 2024 :wink:.

Disons :

```suggestion
date: 2025-01-21
```

Et renommer/déplacer le fichier également.

2024-12-31 17:04 UTC, Guts commented on content/articles/2024/2024-12-31_sql_json.md
Pour renommer depuis l'interface web, il faut aller sur ce lien https://github.com/thomas-szczurek/website/edit/master/content/articles/2024/2024-12-31_sql_json.md?pr=%2Fgeotribu%2Fwebsite%2Fpull%2F1238

et c'est en haut : 

![image](https://github.com/user-attachments/assets/a9beb787-28ab-490e-a40b-6163243bab1a)

2024-12-31 17:05 UTC, Guts commented on content/articles/2024/2024-12-31_sql_json.md
Je verrais bien quelque chose 2025-01-21_travailler-avec-JSON-et-PostgreSQL

2025-01-01 16:21 UTC, Guts commented on content/articles/2024/2024-12-31_sql_json.md
psst @thomas-szczurek il faut donc mettre ton article dans le dossier `content/articles/2025` et non plus `content/articles/2024` :wink:

2025-01-01 16:26 UTC, Guts commented on content/articles/2024/2024-12-31_sql_json.md
Pour la nouvelle année, je m'en suis occupé vite fait et j'en ai profité pour faire quelques corrections de base de la syntaxe :kissing:.

2025-01-13 10:27 UTC, Guts commented
Allez zou, c'est parti pour la @geotribu/relecture  !

:information_source: **Aux relecteur/ices**

Merci d'utiliser autant que possible le mode Suggestion de la review : https://docs.github.com/fr/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request#starting-a-review

![image](https://github.com/geotribu/website/assets/1596222/4d081e97-7290-48c4-b1ff-587a8920b508)

C'est vraiment **IMPORTANT** pour le confort de l'auteur/ice :pray:

2025-01-13 10:35 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +    - json
À appliquer partout

```suggestion
    - JSON
```

2025-01-14 07:10 UTC, lbartoletti commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Notez que si votre table temporaire possède un nom différent de "rp_population_import" il vous faudra modifier la clause FROM de la CTE.
```suggestion
- `STXT` est la fonction qui permet de découper une chaine de texte avec Excel, avec comme arguments `cellule comprenant la chaine initiale` , `position du début de la découpe` , `position de fin de la découpe`
- À partir du fichier récupéré, il vous suffit de copier-coller les noms de champs INSEE sur la première ligne et de récupérer la seconde, qui contiendra les noms de champs formatés.
- On  remplace les noms de champ du fichier INSEE original.
- Et on change le nom de cette table temporaire par "rp_population_import.csv"

Avant d'insérer les données dans notre table, nous allons passer par une table temporaire afin de rendre les données accessibles dans Postgres. Utiliser `COPY` de Postgresql serait fastidieux car il faudrait indiquer la centaine de champs que contient le volet population du recensement dans la commande. Et, je n'ai pas honte de dire que j'ai un baobab dans la main à cette idée. Nous sortons donc ce merveilleux logiciel qu'est QGIS. On active les panneaux Explorateur et Explorateur2. On crée une connexion vers la base avec les droits de création, et d'un mouvement gracile du poignet, vous glissez le fichier depuis le panneau Explorateur vers la base Postgres dans l'Explorateur2. Laisser la magie opérer.

Maintenant, préparez-vous pour peut-être un des INSERT les plus bizarres de votre vie (en tout cas, ça l'a été pour moi !). Arf. Je me rends compte que si je veux bien faire, il faut aussi que j'explique les CTE (c'est très étrange, car encore une fois, si vous êtes encore ici, vous savez très probablement déjà ce qu'est une CTE).

CTE veut dire Common Table Expression. C'est une fonctionnalité qui permet grâce à la clause `WITH` d'isoler une sous-requête de la requête principale pour rendre tout un peu plus clair. Elle permet également de la nommer pour pouvoir la réutiliser à plusieurs endroits sans devoir la réécrire. On peut aussi s'en servir pour faire des requêtes récursives avec `WITH RECURSIVE` et si le sujet vous intéresse je vous encourage à aller lire la [magnifique documentation](https://www.postgresql.org/docs/current/queries-with.html#QUERIES-WITH-RECURSIVE) de Postgres a ce sujet.

On va utiliser la CTE pour concaténer le nom que l'on veut donner à nos clés avec les valeurs contenues dans notre table temporaire dans une chaine séparée par des `,`. On l'enverra dans une fonction `string_to_array()` puis dans une fonction `jsonb_object()`. On en profitera pour au passage, nettoyer toute tabulation ou retour chariot qui pourrait subsister avec une expression régulière grâce à la fonction `regex_replace()`. (ces caractères se notent `\t`, `\n` et `\r`). Cette dernière fonction prend 3 arguments : la chaine de caractères source, le `pattern` recherché, le texte de remplacement. On y ajoute le *drapeau* optionnel `g` afin de remplacer toutes les occurrences trouvées.

Notez que si votre table temporaire possède un nom différent de "rp_population_import" il vous faudra modifier la clause FROM de la CTE.
```

2025-01-14 07:10 UTC, lbartoletti commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +`-` est un opérateur qui permet de supprimer une clé d'un objet json. Pour notre UPDATE on enlève donc notre faute de frappe de l'ensemble de l'objet et on concatène tout le reste avec la constructio
```suggestion
`-` est un opérateur qui permet de supprimer une clé d'un objet json. Pour notre UPDATE on enlève donc notre faute de frappe de l'ensemble de l'objet. De plus, on concatène tout le reste avec la construction d'un nouvel objet où l'on corrige le nom de la clé. On assigne également la valeur de la clé en train d'être supprimée, elle est toujours utilisable au moment de l'UPDATE, sur les champs qui la contiennent à l'origine avec `?`.
```

2025-01-14 07:10 UTC, lbartoletti commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Jusqu'à maintenant, nous n'avons travaillé qu'avec le volet population pour son dernier millésime. Imaginons maintenant que nous répétions l'exercice pour les 6 volets et sur plusieurs millésimes et
```suggestion
Jusqu'à maintenant, nous n'avons travaillé qu'avec le volet population pour son dernier millésime. Imaginons maintenant que nous répétions l'exercice pour les 6 volets et sur plusieurs millésimes, et ce, en sachant qu'au cours du temps, certains champs peuvent apparaitre ou disparaitre ; changement dans les niveaux de diplômes observés par exemple. Il serait intéressant de récupérer une table indiquant la première et la dernière année de présence de chaque clé. Mettons que lors de ces travaux, nous en avons profité pour mettre à jour une table "correspondance_clefs_champs" listant chaque clé présentes et son nom INSEE d'origine (tout du moins, celui que nous avions normalisé).
```

2025-01-14 07:10 UTC, lbartoletti commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Maintenant, on voudrait proposer un produit un peu plus simple d'utilisation avec tout ça. Désolé d'avance, je vais copier une requête de 50 lignes une seconde fois. La seule table utilisée ici que n
```suggestion
La seule difficulté ici est la présence de [LATERAL](https://docs.postgresql.fr/17/queries-table-expressions.html#QUERIES-FROM). Ce « mot » permet d'utiliser un champ de la requête principale dans une sous-requête placée dans une clause FROM. Les éléments de la sous-requête seront ensuite évalués atomiquement avant d'être joints à la table d'origine. Oui, ce n'est pas très facile à expliquer. Ici, le WHERE de la sous-requête va interroger le champ donné de la table "donnees_communes" pour voir s'il y voit la clef_json en train d'être évaluée dans la table "correspondance_clefs_champs" possédant l'alias "c". Si oui, alors on prend la valeur minimum/maximum du champ année et on le joint à cette ligne et uniquement à cette ligne. Puis évaluation de clef_json suivante ... (*évaluée atomiquement*)

Maintenant, on voudrait proposer un produit un peu plus simple d'utilisation avec tout ça. Excusez-moi d'avance, je copierai une requête de 50 lignes une seconde fois. La seule table utilisée ici que nous n'avons pas créée est une table zonages_administratifs comprenant les codes communes dans un champ "code_admin", et un champ "fk_type" contenant le type de zonage administratif (1 pour les communes).
```

2025-01-14 07:10 UTC, lbartoletti commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Et pour ça on va utiliser gdal/ogr qui est décidemment incroyable.
```suggestion
Et, pour ça, on va utiliser gdal/ogr qui est décidément incroyable.
```

2025-01-14 07:10 UTC, lbartoletti commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Et on peut ainsi mettre le fichier sur un espace cloud, comme [ici](https://donnees-insee.s3.fr-par.scw.cloud/donnees_insee_olap.parquet) ! Vous pouvez ensuite sortir votre plus beau générateur de pu
```suggestion
Et, on peut ainsi mettre le fichier sur un espace cloud, comme [ici](https://donnees-insee.s3.fr-par.scw.cloud/donnees_insee_olap.parquet) ! Vous pouvez ensuite sortir votre plus beau générateur de publications Linkedin qui mettra plein d'émojis choupi et faire le cake sur les rezos (imaginez que 90% du contenu de Linkedin doit être fait avec ces trucs capables de vous générer des publications expliquant que le shape a des avantages sur le GeoPackage, le tout sur un ton très assuré).
```

2025-01-14 07:10 UTC, lbartoletti commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Et on peut ainsi mettre le fichier sur un espace cloud, comme [ici](https://donnees-insee.s3.fr-par.scw.cloud/donnees_insee_olap.parquet) ! Vous pouvez ensuite sortir votre plus beau générateur de pu
Mais le ShapeFile a des avantages sur le GeoPackage ! 😅

2025-01-14 18:18 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Dans le cadre d'un projet personnel encadré de type "tu l'as fait pour les iris de Lille avec Sqlite, t'as vu que tu sais faire. Bon bah maintenant tu le fait pour toutes les communes de France dans
j'ai juste un doute sur le empêche/empêche. C'est "les champs pouvant changer" donc un et un seul fait qui empêche non ?

2025-01-14 18:22 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Et on peut ainsi mettre le fichier sur un espace cloud, comme [ici](https://donnees-insee.s3.fr-par.scw.cloud/donnees_insee_olap.parquet) ! Vous pouvez ensuite sortir votre plus beau générateur de pu
Alors, c'est peut-être l'effet conversation écrite, mais si je ce n'esst pas une blague, je suis preneur des cas pour ma ~~confiture~~ culture !

2025-01-14 18:39 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Je vais éviter de vous spammer du DDL, mais vous pourrez retrouver le schéma complet de la base [ici](https://github.com/thomas-szczurek/base_donnees_insee/tree/main/sql/creation_tables)
non pour éviter de me perdre dans l'explication du modèle relationnel mais je peux faire un screen du modèle sous pgmodeler  pour montrer à voir . En plus effectivement ça serait utile car j'évoque quelques tables plus loin.

2025-01-14 18:45 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> + pk_id int4 GENERATED BY DEFAULT AS IDENTITY,
Mon prof particulier de PG était très perfectionniste :)

2025-01-14 18:54 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Pour les aventuriers et aventurières, il existe une extention de PostgreSQL `btree_gin` permettant de faire des index multi-champs mixant des champs classiques et json. Elle est disponible nativement
Je suis plutôt adepte du . mais "aventurier et aventurières" ajoute un effet comique je trouve.

2025-01-14 18:55 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +- `champ_jsonb -> 'clé'` récupère la valeur d'une clé en concervant son type json
conservant ?

2025-01-14 19:06 UTC, thomas-szczurek commented
Mes réseaux :
mastodon : thomas_szczurek@mapstodon.space
linkedin : Thomas Szczurek-Gayant

2025-01-14 19:10 UTC, Guts commented
> Mes réseaux :
> mastodon : thomas_szczurek@mapstodon.space
> linkedin : Thomas Szczurek-Gayant

Mets les dans ta page auteur !

2025-01-16 21:24 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Et on peut ainsi mettre le fichier sur un espace cloud, comme [ici](https://donnees-insee.s3.fr-par.scw.cloud/donnees_insee_olap.parquet) ! Vous pouvez ensuite sortir votre plus beau générateur de pu
:popcorn:

2025-01-16 21:25 UTC, Guts commented
> > Mes réseaux :
> > mastodon : [thomas_szczurek@mapstodon.space](mailto:thomas_szczurek@mapstodon.space)
> > linkedin : Thomas Szczurek-Gayant
> 
> Mets les dans ta page auteur !

Ok @thomas-szczurek ils y sont déjà. Niquel.

2025-01-17 05:01 UTC, lbartoletti commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Dans le cadre d'un projet personnel encadré de type "tu l'as fait pour les iris de Lille avec Sqlite, t'as vu que tu sais faire. Bon bah maintenant tu le fait pour toutes les communes de France dans
Mmm, oui, en effet, on peut garder "empêche" au singulier

2025-01-17 05:01 UTC, lbartoletti commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Maintenant, on voudrait proposer un produit un peu plus simple d'utilisation avec tout ça. Désolé d'avance, je vais copier une requête de 50 lignes une seconde fois. La seule table utilisée ici que n
Alors, dans ce cas, oui. Avec la petite syntaxe qui va bien `donnes`

2025-01-17 05:05 UTC, lbartoletti commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Et on peut ainsi mettre le fichier sur un espace cloud, comme [ici](https://donnees-insee.s3.fr-par.scw.cloud/donnees_insee_olap.parquet) ! Vous pouvez ensuite sortir votre plus beau générateur de pu
Non, ce n'est pas une blague :D 
En vrai, le GeoPackage a beaucoup d'avantages sur le ShapeFile. Mais celui-ci en a quand même une importante (dans mon cas) : une meilleure interopérabilité (SIG, DAO, Illustration type Illustrator & cie) aujourd'hui, compatibilité historique et une certaine simplicité

2025-01-18 13:54 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Dans le cadre d'un projet personnel encadré de type "tu l'as fait pour les IRIS de Lille avec Sqlite, t'as vu que tu sais faire. Bon bah maintenant tu le fais pour toutes les communes de France dans
```suggestion
Dans le cadre d'un projet personnel encadré de type "tu l'as fait pour les IRIS de Lille avec Sqlite, t'as vu que tu sais faire. Bon bah maintenant tu le fais pour toutes les communes de France dans PG", j'ai voulu stocker une bonne partie des données du recensement de l'Insee dans une base PostgreSQL avec des tables multimillésimes. Problème, même au sein d'un même jeu de données, les champs peuvent changer au cours des années et cela empêche de pouvoir dégager une structure de table fixe, ce qui est assez gênant vous en conviendrez. La solution ? Passer par des données semi-structurées, soit stocker ces données en JSON dans le champ d'une table. Cet article se veut un condensé de cette expérience.
```

2025-01-18 13:55 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Et on peut ainsi mettre le fichier sur un espace cloud, comme [ici](https://donnees-insee.s3.fr-par.scw.cloud/donnees_insee_olap.parquet) ! Vous pouvez ensuite sortir votre plus beau générateur de pu
merci ;) (désolé pour le pop corn !)

2025-01-18 14:03 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Et on peut ainsi mettre le fichier sur un espace cloud, comme [ici](https://donnees-insee.s3.fr-par.scw.cloud/donnees_insee_olap.parquet) ! Vous pouvez ensuite sortir votre plus beau générateur de pu
```suggestion
Et on peut ainsi mettre le fichier sur un espace cloud, comme [ici](https://donnees-insee.s3.fr-par.scw.cloud/donnees_insee_olap.parquet) ! Vous pouvez ensuite sortir votre plus beau générateur de publications Linkedin qui mettra plein d'emojis choupi et faire le cake sur les rezos (imaginez que 90% du contenu de Linkedin doit être fait avec ces trucs qui sont capable de vous générer des publications expliquant que l'un  des rares avantages du shape sur le geopackage est d'être un format multi-fichiers, le tout sur un ton très assuré).
```

2025-01-18 14:05 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +La seule difficulté ici est la présence de [LATERAL](https://docs.postgresql.fr/17/queries-table-expressions.html#QUERIES-FROM). Ce « mot » permet d'utiliser un champ de la requête principale dans un
```suggestion
La seule difficulté ici est la présence de [LATERAL](https://docs.postgresql.fr/17/queries-table-expressions.html#QUERIES-FROM). Ce « mot » permet d'utiliser un champ de la requête principale dans une sous-requête placée dans une clause FROM. Les éléments de la sous-requête seront ensuite évalués atomiquement avant d'être joints à la table d'origine. Oui, ce n'est pas très facile à expliquer. Ici, le WHERE de la sous-requête va interroger le champ `donnees` de la table "donnees_communes" pour voir s'il y voit la clef_json en train d'être évaluée dans la table "correspondance_clefs_champs" possédant l'alias "c". Si oui, alors on prend la valeur minimum/maximum du champ année et on le joint à cette ligne et uniquement à cette ligne. Puis évaluation de clef_json suivante ... (*évaluée atomiquement*)
```

2025-01-18 14:07 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +En voici cependant un schéma succinct pour pour aider à la compréhension du reste de l'article :
```suggestion
En voici cependant un schéma succinct pour aider à la compréhension du reste de l'article :
```

2025-01-18 14:31 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Et on peut ainsi mettre le fichier sur un espace cloud, comme [ici](https://donnees-insee.s3.fr-par.scw.cloud/donnees_insee_olap.parquet) ! Vous pouvez ensuite sortir votre plus beau générateur de pu
```suggestion
Et on peut ainsi mettre le fichier sur un espace cloud, comme [ici](https://donnees-insee.s3.fr-par.scw.cloud/donnees_insee_olap.parquet) ! Vous pouvez ensuite sortir votre plus beau générateur de publications Linkedin qui mettra plein d'emojis choupi et faire le cake sur les rezos (imaginez que 90% du contenu de Linkedin doit être fait avec ces trucs qui sont capable de vous générer des publications expliquant que l'un des rares avantages du shape sur le geopackage est d'être un format multi-fichiers, le tout sur un ton très assuré).
```

2025-01-18 23:52 UTC, Michael-cd30 reviewed
On utilise pas mal JSON dans PG. En fait, dès qu'on invoque une API qui retourne du JSON on le stocke tel quel puis on transforme en table via ce type de syntaxe. Je trouve donc super qu'un article puisse présenter cela.

Cependant, l'article me parait difficile à suivre à partir de la section "Attaquons nous au recensement". Les points connexes qui sont évoqués (CTE, LATERAL, renommage des colonnes) me semblent détourner le lecteur du sujet principal.

Par ailleurs, la coloration syntaxique n'aide pas.

2025-01-18 23:52 UTC, Michael-cd30 commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Récupérons le dernier millésime du volet population du recensement communal [au format csv sur le site de l'INSEE](https://www.insee.fr/fr/information/8183122) (vous voulez les bases des principaux i
```suggestion
Récupérons le dernier millésime du volet population du recensement communal [au format csv sur le site de l'Insee](https://www.insee.fr/fr/information/8183122) (vous voulez les bases des principaux indicateurs). Pour l'exemple, on utilisera le fichier "Evolution et structure de la population". Il faut tout d'abord nettoyer les noms de champ. En effet, l'Insee indique le millésime systématiquement dans ses noms de champ, ce qui fait que ces derniers changent tous les ans pour un même indicateur.
```

Par cohérence avec plus haut...et même si c'est des initiales, je vois que l'Insee écrit Insee sur son site.

2025-01-18 23:52 UTC, Michael-cd30 commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Avant d'insérer les données dans notre table, nous allons passer par une table temporaire afin de rendre les données accessibles dans Postgres. Utiliser `COPY` de Postgresql serait fastidieux car il
```suggestion
Avant d'insérer les données dans notre table, nous allons passer par une table temporaire afin de rendre les données accessibles dans Postgres. Utiliser `COPY` de Postgresql serait fastidieux car il faudrait indiquer la centaine de champs que contient le volet population du recensement dans la commande. Et, je n'ai pas honte de dire que j'ai un baobab dans la main à cette idée. Nous sortons donc ce merveilleux logiciel qu'est QGIS. On active les panneaux Explorateur et Explorateur2. On crée une connexion vers la base avec les droits de création, et d'un mouvement gracile du poignet, vous glissez le fichier depuis le panneau Explorateur vers la base Postgres dans l'Explorateur2. Laissez la magie opérer.
```

2025-01-18 23:52 UTC, Michael-cd30 commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Les noms de champ commencent tous par P ou C, ceci indique *exploitation principale* (réponses brutes aux questions du recensement) ou *exploitation complémentaire* (croisement de réponses pour établ
Je trouve ce qui suit, sur la gestion des noms de colonnes, plutôt éloigné de l'objet principal de l'article.
Je dirais qu'il faut diminuer, peut-être juste évoquer ce pré-traitement sans entrer dans les détails.

Inversement, si tu préfères laisser cette section, je la trouve pas assez explicite, quelques petites captures avant/après pourraient aider à comprendre chacune des étapes.

2025-01-18 23:52 UTC, Michael-cd30 commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> + regexp_replace('pop_p,' || "POP_P" || ',
Ce serait plus simple avec un concat ou concat_ws qu'avec les || non ?

2025-01-18 23:52 UTC, Michael-cd30 commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +On veillera à bien grouper les inserts dans cet ordre annee/base/code_commune afin de faciliter la lecture des données par PostgreSQL (si votre table est partitionnée, celà sera facilité).
```suggestion
On veillera à bien grouper les inserts dans cet ordre annee/base/code_commune afin de faciliter la lecture des données par PostgreSQL (si votre table est partitionnée, cela sera facilité).
```

2025-01-18 23:52 UTC, Michael-cd30 commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Ouf.
J'ai vraiment du mal à suivre ce qui précède.

En plus, le markdown en preview colore de la même façon les 'chaines' et les "CHAINES" alors que les simples et doubles guillemets ne représente pas la même chose en PG (contrairement en Python).
Ainsi, j'ai mis un temps à voir que select "CODGEO" n'est pas une sélection de constante.

2025-01-18 23:52 UTC, Michael-cd30 commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> + LATERAL (SELECT min(annee) AS premiere FROM insee.donnees_communes WHERE fk_base = c.fk_base AND donnees ? c.clef_json) AS p,
J'ai un doute, on peut pas faire le min et max dans la même sous-requêtes ?

2025-01-18 23:52 UTC, Michael-cd30 commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Enfin, histoire de vivre avec son temps et non comme un viel ours des cavernes, on va convertir cette vue matérialisée en fichier [parquet](https://parquet.apache.org/).
```suggestion
Enfin, histoire de vivre avec son temps et non comme un vieil ours des cavernes, on va convertir cette vue matérialisée en fichier [parquet](https://parquet.apache.org/).
```

2025-01-19 12:27 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Pour celles et ceux qui ne connaisent pas le `json`, il s'agit d'un format textuel de représentation des données fonctionnant en partie sur un système de `clé : valeur` qu'on peut voir comme une sort
```suggestion
Pour celles et ceux qui ne connaissent pas le `json`, il s'agit d'un format textuel de représentation des données venant du Java Script fonctionnant en partie sur un système de `clé : valeur` qu'on peut voir comme une sorte d'évolution du `xml`.
```

2025-01-19 12:27 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Je vais éviter de vous spammer du DDL, mais vous pourrez retrouver le schéma complet de la base [ici](https://github.com/thomas-szczurek/base_donnees_insee/tree/main/sql/creation_tables)
```suggestion
Je vais éviter de vous spammer du `DDL` ([Data Definition Language](https://fr.wikipedia.org/wiki/Langage_de_d%C3%A9finition_de_donn%C3%A9es), mais vous pourrez retrouver le schéma complet de la base [ici](https://github.com/thomas-szczurek/base_donnees_insee/tree/main/sql/creation_tables)
```

2025-01-19 12:27 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +  donnees ? 'melons'
```suggestion
  donnees ? 'melons'
  AND code_commune = '99999'
  AND annee = 2024
```

2025-01-19 12:27 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +
```suggestion

#### Recupération

```

2025-01-19 12:27 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +- `STXT` est la fonction qui permet de découper une chaine de texte avec Excel, avec comme arguments `cellule comprenant la chaine initiale` , `position du début de la découpe` , `position de fin de
```suggestion
```

2025-01-19 12:27 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +- À partir du fichier récupéré, il vous suffit de copier-coller les noms de champs INSEE sur la première ligne et de récupérer la seconde, qui contiendra les noms de champs formatés.
```suggestion
```

2025-01-19 12:27 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +- On  remplace les noms de champ du fichier INSEE original.
```suggestion
```

2025-01-19 12:27 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +- Et on change le nom de cette table temporaire par "rp_population_import.csv"
```suggestion
```

2025-01-19 12:27 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Les noms de champ commencent tous par P ou C, ceci indique *exploitation principale* (réponses brutes aux questions du recensement) ou *exploitation complémentaire* (croisement de réponses pour établ
```suggestion
Les noms de champ commencent tous par P ou C, ceci indique *exploitation principale* (réponses brutes aux questions du recensement) ou *exploitation complémentaire* (croisement de réponses pour établir un indicateur). Les champs provenant de l'exploitation principale et ceux issus de la complémentaire ne doivent pas être croisés entre eux. Cette information est évidemment à conserver, mais par choix personnel, je préfère la mettre à la fin plutôt qu'au début du nom. On passera ainsi de champs normés comme ceci  : `P18_POP` vers une normalisation de ce type `POP_P`.
```

2025-01-19 12:27 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Maintenant, préparez-vous pour peut-être un des INSERT les plus bizarres de votre vie (en tout cas, ça l'a été pour moi !). Arf. Je me rends compte que si je veux bien faire, il faut aussi que j'expl
```suggestion
Maintenant, préparez-vous pour peut-être un des INSERT les plus bizarres de votre vie (en tout cas, ça l'a été pour moi !). Arf. Je me rends compte que si je voulais bien faire, il faudrait aussi que j'explique les [CTE](https://www.postgresql.org/docs/current/queries-with.html). Mais pour ne pas trop alourdir, je vous laisser cliquer sur le lien.
```

2025-01-19 12:27 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +CTE veut dire Common Table Expression. C'est une fonctionnalité qui permet grâce à la clause `WITH` d'isoler une sous-requête de la requête principale pour rendre tout un peu plus clair. Elle permet
```suggestion
```

2025-01-19 12:27 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> + "CODGEO",
```suggestion
 CODGEO,
```

2025-01-19 12:27 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +    "CODGEO",
```suggestion
    CODGEO,
```

2025-01-19 12:27 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> + p.premiere AS premiere_annee_presence,
```suggestion
 a.premiere AS premiere_annee_presence,
```

2025-01-19 12:27 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> + d.derniere AS derniere_annee_presence
```suggestion
 a.derniere AS derniere_annee_presence
```

2025-01-19 12:27 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> + LATERAL (SELECT min(annee) AS premiere FROM insee.donnees_communes WHERE fk_base = c.fk_base AND donnees ? c.clef_json) AS p,
```suggestion
 LATERAL (SELECT min(annee) AS premiere FROM insee.donnees_communes WHERE fk_base = c.fk_base AND donnees ? c.clef_json) AS a
```

2025-01-19 12:27 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> + LATERAL (SELECT max(annee) AS derniere FROM insee.donnees_communes WHERE fk_base = c.fk_base AND donnees ? c.clef_json) AS d
```suggestion
```

2025-01-19 12:28 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Pour celles et ceux qui ne connaisent pas le `json`, il s'agit d'un format textuel de représentation des données fonctionnant en partie sur un système de `clé : valeur` qu'on peut voir comme une sort
la ref directe a ajouté normalement

2025-01-19 12:29 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Dans le cadre d'un projet personnel encadré de type "tu l'as fait pour les IRIS de Lille avec Sqlite, t'as vu que tu sais faire. Bon bah maintenant tu le fais pour toutes les communes de France dans
J'ai enlevé la partie entre guillemets pour alléger. C'était une ref à la personne qui m'a enseigné le sql "niveau ++" mais je comprend !

2025-01-19 12:30 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +!!! warning
Pourquoi pas mais trop tard à deux jours près si je veux pas y passer mon dimanche :). J'espère que tu me pardonnera de choisir  les modifs que je veux encore faire.

2025-01-19 12:31 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> + regexp_replace('pop_p,' || "POP_P" || ',
Je vois l'idée, mais c'est comme ça que je l'ai écrite à l'époque (j'ai appris dessus) et là pareil, trop tard pour changer

2025-01-19 12:32 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Ouf.
J'ai au moins enlevé ceux de CODGEO pour la comprehension, je vois si je peux changer les autres en masse

2025-01-19 12:33 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> + LATERAL (SELECT min(annee) AS premiere FROM insee.donnees_communes WHERE fk_base = c.fk_base AND donnees ? c.clef_json) AS p,
Si, et on gagne même 211 ms d’exécution, hourra ! Modifié, merci !

2025-01-19 12:40 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Les plus tatillons des DBA d'entre vous auront remarqué ce `CHECK`. "Mais pourquoi qu'il utilise pas varchar(5) ? Il fait vraiment n'importe quoi !" Tout simplement, car cette forme permet d'utiliser
C'est à ça que sert la table code_admin (et gérer les codes en doublons entre dpt et regions) un peu bancale du modèle ;)

2025-01-19 12:42 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +### (Bonus) Partition de la table données
Ca me donnerai l'impression de faire un article qui pourrait se résumer par un RTFM mais pour quoi pas en effet

2025-01-19 12:46 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Maintenant comment récupérer notre nombre de melons pour le code commune 99999 en 2024 ? Celà se fait grace à des opérateurs spéciaux :
pour suivre le schéma de la table, mais du coup j'ai complété le WHERE pour faire correspondre la question exacte au sql

2025-01-19 12:46 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Je précise que même si vous êtes encore ici, je suppose que vous savez déjà cela. Cependant, la forme `(quelque_chose)::int4` est un raccourci de PostgreSQL pour faire un `cast` soit convertir une va
```suggestion
Je précise que même si vous êtes encore ici, je suppose que vous savez déjà cela. Cependant, la forme `(quelque_chose)::(type)` est un raccourci de PostgreSQL pour faire un `cast` soit convertir une valeur dans un autre type. Avec `->>` la valeur nous est renvoyée sous forme de texte et nous la convertissons en entier.
```

2025-01-19 12:48 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Les noms de champ commencent tous par P ou C, ceci indique *exploitation principale* (réponses brutes aux questions du recensement) ou *exploitation complémentaire* (croisement de réponses pour établ
L'information sur les rincipales/complémentaire mon semble un bon point de culture gé pour des gens qui passent leur temps devant ce type de données, mais j'ai enlevé tout le passage Excel, en ajoutant juste sur ligne sur le produit a obtenir.

2025-01-19 13:10 UTC, thomas-szczurek commented
> On utilise pas mal JSON dans PG. En fait, dès qu'on invoque une API qui retourne du JSON on le stocke tel quel puis on transforme en table via ce type de syntaxe. Je trouve donc super qu'un article puisse présenter cela.
> 
> Cependant, l'article me parait difficile à suivre à partir de la section "Attaquons nous au recensement". Les points connexes qui sont évoqués (CTE, LATERAL, renommage des colonnes) me semblent détourner le lecteur du sujet principal.
> 
> Par ailleurs, la coloration syntaxique n'aide pas.

Merci @Michael-cd30 ! Oui, j'imagine bien qu'avec de l'API, du capteur ... c'est là où ça devient intéressant !

Je comprends l'effet surchage d'infos, je me rends moi même compte que j'ai tendance à vouloir tout expliquer pour qu'une personne partant de zero ou presque puisse suivre mais que ça n'atteint pas forcement l'effet désiré. J'ai enlevé la partie sur les CTE, celle sur la normalisation des champs dans Excel en laissant juste le forma attendu.

Je laisse cependant la partie sur LATERAL car ce "mot" et peut être moins connu (mais j'ai réécris la requête en une seule sous requete effectivement. On gagne 211 ms, c'est donc capital, on se comprend) 

Pour les partitions j’hésite, à voir dans les deux conversations que j'ai laissé dans `files changed` 

J'ai enlevé les doubles guillemets de l'INSERT et effectivement, ça aide à la compréhension, par contre à deux jours de la sortie je m’épargne la réécriture avec des concat() ce qui n'empêche pourrait mieux effectivement (surtout qu'après moi pour me normaliser derrière, j'en ai 7 des comme ça !)

2025-01-20 09:46 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Dans le cadre d'un projet personnel, j'ai voulu stocker une bonne partie des données du recensement de l'Insee dans une base PostgreSQL avec des tables multimillésimes. Problème, au sein d'un même je
Ajout de marqueurs visuels pour alléger la charge cognitive à la lecture et au parcours de l'article.

```suggestion

![logo JSON](https://cdn.geotribu.fr/img/logos-icones/programmation/json.png){: .img-thumbnail-left }

Dans le cadre d'un projet personnel, j'ai voulu stocker une bonne partie des données du recensement de l'Insee dans une base PostgreSQL avec des tables multimillésimes. Problème, au sein d'un même jeu de données, les champs peuvent changer au cours des années et cela empêche de pouvoir dégager une structure de table fixe, ce qui est assez gênant vous en conviendrez. La solution ? Passer par des données semi-structurées, soit stocker ces données en JSON dans le champ d'une table. Cet article se veut un condensé de cette expérience.
```

2025-01-20 09:47 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +!!! warning
```suggestion
!!! info "Obsolescence non programmée"
```

2025-01-20 09:47 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Puisque nous allons parler de json et de données semi-structurées, je me sens dans l'obligation de commencer cet article par un avertissement.
```suggestion
Puisque nous allons parler de JSON et de données semi-structurées, je me sens dans l'obligation de commencer cet article par un avertissement.
```

2025-01-20 09:48 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Cet article ne se veut surtout pas être une invitation à partir en mode yolo sur la gestion des données "c'est bon ya qu'a tout mettre en json" (comme un vulgaire dev qui mettrait tout dans MongoDB d
```suggestion
Cet article ne se veut surtout pas être une invitation à partir en mode YOLO sur la gestion des données "c'est bon ya qu'a tout mettre en JSON" (comme un vulgaire dev qui mettrait tout dans MongoDB diraient les mauvaises langues).
```

2025-01-20 09:48 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +## Le JSON pour les débutant.es
```suggestion
## Le JSON pour les débutant⸱es
```

2025-01-20 10:03 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +pas besoin de guillemets pour les nombres
```suggestion
Pas besoin de guillemets pour les nombres :
```

2025-01-20 10:03 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Les valeurs peuvent prendre deux formes. Soit une valeur unique comme dans l'exemple ci-dessus, soit un `array`, une liste, qu'on place entre `[]`, les deux pouvant êtres combinés au sein d'un seul o
```suggestion
Les valeurs peuvent prendre deux formes :

- soit une valeur unique comme dans l'exemple ci-dessus,
- soit un `array`, une liste, qu'on place entre `[]`, les deux pouvant êtres combinés au sein d'un seul objet JSON.
```

Et les sous-objets ?

2025-01-20 10:04 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Les valeurs peuvent prendre deux formes. Soit une valeur unique comme dans l'exemple ci-dessus, soit un `array`, une liste, qu'on place entre `[]`, les deux pouvant êtres combinés au sein d'un seul o
ok c'est dit juste après :innocent:

2025-01-20 10:20 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> + LATERAL (SELECT min(annee) AS premiere FROM insee.donnees_communes WHERE fk_base = c.fk_base AND donnees ? c.clef_json) AS a
```suggestion
 LATERAL (SELECT
     min(annee) AS premiere,
     max(annee) AS derniere 
     FROM insee.donnees_communes WHERE fk_base = c.fk_base AND donnees ? c.clef_json) AS a
```

2025-01-20 10:20 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +
```suggestion

*Ne vous préoccupez pas des tables empilées tout à droite, ce sont des partitions de la table `donnees_communes`. Le sujet ne sera pas évoqué ici et elles ne sont nécessaires pour l'exemple.*

```

2025-01-20 10:20 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +### (Bonus) Partition de la table données
```suggestion
```

2025-01-20 10:20 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Imaginons que nous travaillons sur l'ensemble des données du recensement (soit 6 fichiers sources), de 2015 à 2021 pour environ 35 000 communes. On va arriver sur du 1,5 million d'enregistrements. En
```suggestion
```

2025-01-20 10:20 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +
```suggestion
```

2025-01-20 10:20 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +- C'est une table découpée en plusieurs morceaux où une table *parent* contrôlera les tables *enfants*.
```suggestion
```

2025-01-20 10:20 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +- Une table partitionnée peut se découper selon la valeur d'un champ ou une période temporelle ("fais -moi une partition tous les mois")
```suggestion
```

2025-01-20 10:20 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +- On peut requêter la table parent ou les tables enfants.
```suggestion
```

2025-01-20 10:20 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +- Une table doit être partitionnée à sa création, une table déjà existante ne peut pas être convertie. De nouvelles partitions peuvent toutefois être créées à volonté.
```suggestion
```

2025-01-20 10:21 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Il est possible d'indexer un champ de type `json` / `jsonb` sur ses clés **de premier niveau** et cela se fait avec des index de type `GIN` :
```suggestion
## Les index

![icône index](https://cdn.geotribu.fr/img/logos-icones/divers/index_pointeur.webp){: .img-thumbnail-left }

Il est possible d'indexer un champ de type `json` / `jsonb` sur ses clés **de premier niveau** et cela se fait avec des index de type `GIN` :
```

2025-01-20 10:25 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +
```suggestion
```

2025-01-20 10:25 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Vous pouvez aussi lire le contenu de la [documentation à ce sujet](https://doc.postgresql.fr/17/ddl-partitioning.html)
```suggestion
```

2025-01-20 10:25 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +
```suggestion
```

2025-01-20 10:25 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +À quoi ressemblerait la création de insee.donnees_communes si on la partitionnait selon les différentes sources de données ?
```suggestion
```

2025-01-20 10:25 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +On remarque quelques changements : la déclaration de la clé primaire composite dans une `CONSTRAINT`, le `PARTITION BY LIST` qu'on fait suivre par le champ de partitionnement, et la création des diff
```suggestion
```

2025-01-20 10:25 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +BEGIN;
```suggestion
```

2025-01-20 10:26 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +CREATE TABLE insee.donnees_communes (
```suggestion
```

2025-01-20 10:26 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> + pk_id int4 GENERATED BY DEFAULT AS IDENTITY,
```suggestion
```

2025-01-20 10:26 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Pour les aventuriers et aventurières, il existe une extention de PostgreSQL `btree_gin` permettant de faire des index multi-champs mixant des champs classiques et json. Elle est disponible nativement
```suggestion
Pour les aventuriers et aventurières, il existe une extension de PostgreSQL `btree_gin` permettant de faire des index multi-champs mixant des champs classiques et `json`. Elle est disponible nativement à l'installation de PostgreSQL et ne vous demandera pas de devenir développeur⸱se C/C++ pour l'installer (coucou les FDW parquet ! Ça va par chez vous ?).
```

2025-01-20 10:26 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> + code_commune text NOT NULL CHECK length(code_commune) = 5,
```suggestion
```

2025-01-20 10:26 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Je vais éviter de vous spammer du `DDL` ([Data Definition Language](https://fr.wikipedia.org/wiki/Langage_de_d%C3%A9finition_de_donn%C3%A9es), mais vous pourrez retrouver le schéma complet de la base
```suggestion
Je vais éviter de vous spammer du `DDL` ([Data Definition Language](https://fr.wikipedia.org/wiki/Langage_de_d%C3%A9finition_de_donn%C3%A9es), mais vous pourrez retrouver le schéma complet de la base [ici](https://github.com/thomas-szczurek/base_donnees_insee/tree/main/sql/creation_tables).
```

2025-01-20 10:27 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +![modele_de_donnees](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/postgresql_json/modele.png){: .img-center loading=lazy }
Pour ton karma envers les outils d'accessibilité :wink: 

```suggestion
![Diagramme du modèle de la base de données](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2024/postgresql_json/modele.png){: .img-center loading=lazy }
```

2025-01-20 10:28 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Partant d'un schéma nommé `insee`, on va créer deux tables. La première contiendra la liste des *bases* disponibles, les différents volets du recensement. Une seconde permettant de stocker les donnée
```suggestion
Partant d'un schéma nommé `insee`, on va créer deux tables :+1: 
- la première contiendra la liste des *bases* disponibles, les différents volets du recensement ;
- lae seconde permettant de stocker les données.

Pour rester concentré sur le JSON, on va s'épargner 95% du modèle sous-jacent. On ne gérera donc pas ici les codes communes, etc. En bonus pour celles et ceux voulant tester ce que PostgreSQL a dans le ventre, je proposerai une variante juste en dessous :
```

2025-01-20 10:29 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Pour rester concentré sur le JSON, on va s'épargner 95% du modèle sous-jacent. On ne gérera donc pas ici les codes communes, etc. En bonus pour celles et ceux voulant tester ce que PostgreSQL a dans
```suggestion
Pour rester concentré sur le JSON, on va s'épargner 95% du modèle sous-jacent. On ne gérera donc pas ici les codes communes, etc. :
```

2025-01-20 10:30 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +```sql
````suggestion
```sql title="Script de création des tables" linenums="1"
````

2025-01-20 10:32 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +) PARTITION BY LIST (fk_base);
```suggestion
```

2025-01-20 10:32 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +```
Pourquoi 2 blocs séparés ? C'est pas une erreur ?

2025-01-20 10:32 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +CREATE TABLE insee.donnees_communes_fk_1 PARTITION OF insee.donnees_communes FOR VALUES IN (1);
```suggestion
```

2025-01-20 10:32 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +CREATE TABLE insee.donnees_communes_fk_2 PARTITION OF insee.donnees_communes FOR VALUES IN (2);
```suggestion
```

2025-01-20 10:32 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +CREATE TABLE insee.donnees_communes_fk_3 PARTITION OF insee.donnees_communes FOR VALUES IN (3);
```suggestion
```

2025-01-20 10:32 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +### Avec du json imbriqué
```suggestion
### Avec du JSON imbriqué
```

2025-01-20 10:32 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +CREATE TABLE insee.donnees_communes_fk_4 PARTITION OF insee.donnees_communes FOR VALUES IN (4);
```suggestion
```

2025-01-20 10:32 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +CREATE TABLE insee.donnees_communes_fk_5 PARTITION OF insee.donnees_communes FOR VALUES IN (5);
```suggestion
```

2025-01-20 10:32 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +CREATE TABLE insee.donnees_communes_fk_6 PARTITION OF insee.donnees_communes FOR VALUES IN (6);
```suggestion
```

2025-01-20 10:32 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +END;
```suggestion
```

2025-01-20 10:32 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +```
```suggestion
```

2025-01-20 10:34 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Bien, maintenant que nous avons essayé d'expliquer tant bien que mal les concepts avec des exemples simples, car il faut bien commencer quelque part, essayons avec quelque chose d'un peu plus volumin
```suggestion
## Attaquons nous au recensement

![logo INSEE](https://cdn.geotribu.fr/img/logos-icones/entreprises_association/INSEE.svg){: .img-thumbnail-left }

Bien, maintenant que nous avons essayé d'expliquer tant bien que mal les concepts avec des exemples simples, car il faut bien commencer quelque part, essayons avec quelque chose d'un peu plus volumineux.
```

2025-01-20 10:35 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +```
@Guts j'étais en train d'enlever la partie sur les partitions sur les conseils de Michel Galien (comme ça j'ai déjà une nouvelle idée d'articles : randoms trucs éléphantesques -> partitions de tables et fdw)

2025-01-20 10:39 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +```
ah pardon je n'avais pas fait attention. Ok ping moi quand tu as ta nouvelle version stp.

2025-01-20 10:52 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +```
done @Guts ! :)

2025-01-20 12:24 UTC, thomas-szczurek commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +On veillera à bien grouper les inserts dans cet ordre annee/base/code_commune afin de faciliter la lecture des données par PostgreSQL (si votre table est partitionnée, cela sera facilité).
```suggestion
On veillera à bien grouper les inserts dans cet ordre annee/base/code_commune afin de faciliter la lecture des données par PostgreSQL.
```

2025-01-20 13:05 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Partant d'un schéma nommé `insee`, on va créer deux tables :+1:
```suggestion
Partant d'un schéma nommé `insee`, on va créer deux tables :
```

2025-01-20 13:06 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +```sql
```suggestion
```sql title="Script SQL d'insertion de données" linenums="1"
```

2025-01-20 13:07 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +```
````suggestion
```sh title="Export vue au format parquet"
ogr2ogr -of parquet donnees_insee.parquet PG:"dbname='insee' schema='insee' tables='donnees_communes_olap' user='nom_utilisateur' password='votre_mot_de_passe'"
````
```

2025-01-20 13:08 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Attention, la création de cette vue matérialisée ou son refresh peut prendre un certain temps si vous avez stocké beaucoup de données (1 heure chez moi pour les 6 volets de 2015 à 2021).
```suggestion
Attention, la création de cette vue matérialisée ou son rafraîchissement peut prendre un certain temps si vous avez stocké beaucoup de données (1 heure chez moi pour les 6 volets de 2015 à 2021).
```

2025-01-20 13:09 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +```sql
```suggestion
```sql title="Création d'une vue matérialisée" linenums="1"
```

2025-01-20 13:10 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +Maintenant, on voudrait proposer un produit un peu plus simple d'utilisation avec tout ça. Excusez-moi d'avance, je copierai une requête de 50 lignes une seconde fois. La seule table utilisée ici que
```suggestion
Maintenant, on voudrait proposer un produit un peu plus simple d'utilisation avec tout ça. Excusez-moi d'avance, je copierai une requête de 50 lignes une seconde fois.  
La seule table utilisée ici que nous n'avons pas créée est une table `zonages_administratifs` comprenant les codes communes dans un champ `code_admin` et un champ `fk_type` contenant le type de zonage administratif (1 pour les communes).
```

2025-01-20 14:30 UTC, Guts commented on content/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL.md
> +
```suggestion
```sh title="Export vue au format parquet"
ogr2ogr -of parquet donnees_insee.parquet PG:"dbname='insee' schema='insee' tables='donnees_communes_olap' user='nom_utilisateur' password='votre_mot_de_passe'"
```

```

2025-01-20 21:43 UTC, Guts approved these changes

2025-01-20 21:44 UTC, merged

2025-01-20 21:55 UTC, Guts commented
Publié https://geotribu.fr/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL/

On fait la diffusion demain.

@thomas-szczurek j'ai vu que les légendes des images ne sont pas toutes très expressives. Tu peux faire une PR si tu tiens à ton karma de l'accessibilité :wink:.

2025-01-21 07:35 UTC, thomas-szczurek commented
> Publié https://geotribu.fr/articles/2025/2025-01-21_travailler-avec-JSON-et-PostgreSQL/
> 
> On fait la diffusion demain.
> 
> @thomas-szczurek j'ai vu que les légendes des images ne sont pas toutes très expressives. Tu peux faire une PR si tu tiens à ton karma de l'accessibilité 😉.

Je vois si je m'occupe des légendes ce midi, entre mon désir de bien faire et la craine de tout casser d'un clic malencontreux

Promi, pour le prochain je me met une pince sur le nez et fait l'effort de rédiger dans un traitement de texte plutot que directement en markdown afin d'épargner une bonne dose de taf  à mes relecteur.ices.

2025-01-21 09:31 UTC, Guts commented
> Je vois si je m'occupe des légendes ce midi @Guts , entre mon désir de bien faire et la craine de tout casser d'un clic malencontreux

T'inquiète, qu'est-ce qui pourrait mal se passer ? On est sur git, tout va bien. Au pire on revert et on aura pratiqué cette commande git.

> Promi, pour le prochain je me met une pince sur le nez et fait l'effort de rédiger dans un traitement de texte plutot que directement en markdown afin d'épargner une bonne dose de taf à mes relecteur.ices.

Alors, je ne sais pas comment tu en as conclu ça @thomas-szczurek à partir de mon message **mais** continue en Markdown, c'est parfait ! Nous envoyer un word c'est dur, on ne mérite pas ça !

Est-ce que tu aurais mal vécu la relecture ? Parce-que de mon point de vue elle s'est bien déroulée avec une bonne réactivité des deux côtés, une prise en compte des retours pour aboutir sur une version publiée meilleure mais fidèle à la copie initiale.

La syntaxe Markdown, les subtilités liées à la techno choisie et celles liées à nos propres dévs c'est vaste mais secondaire. Si tu veux, pour une prochaine fois, voici quelques pistes :

1. tu rédiges dans un pad collaboratif type hedgedoc et tu nous l'envoies en amont pour échange (on peut te filer un lien vers un pad)
1. Si t'es chaud, tu te fais le setup local https://contribuer.geotribu.fr/edit/local_edition_setup/
1. si tu veux te faire mal pour faire bien, tu peux te farcir notre guide de contribution et la doc de référence de la techno sous-jacente (https://squidfunk.github.io/mkdocs-material/reference/code-blocks/)
1. on part du principe que tu te concentres sur le fond et qu'on peut faire les modifs de syntaxe et cosmétiques sans t'embêter avec une notif GitHub  sur laquelle tu dois ensuite cliquer 200 fois sur "Commit suggestion" ou "Add suggestion to batch"

2025-01-21 09:59 UTC, thomas-szczurek commented
> > Promi, pour le prochain je me met une pince sur le nez et fait l'effort de rédiger dans un traitement de texte plutot que directement en markdown afin d'épargner une bonne dose de taf à mes relecteur.ices.
> 
> Alors, je ne sais pas comment tu en as conclu ça @thomas-szczurek à partir de mon message **mais** continue en Markdown, c'est parfait ! Nous envoyer un word c'est dur, on ne mérite pas ça !
> 
> Est-ce que tu aurais mal vécu la relecture ? Parce-que de mon point de vue elle s'est bien déroulée avec une bonne réactivité des deux côtés, une prise en compte des retours pour aboutir sur une version publiée meilleure mais fidèle à la copie initiale.

Je me suis mal fais comprendre @Guts  :) C'est plus que je n'ai pu m’empercher de voir que j'avais laissé 150 fôtes de frappe/orthographe ce qui laisse du travail aux relecteur.trices qui pourrait être dispensable. Aucun soucis avec le markdown ! C'est juste que la prochaine fois, je tape d'abord dans open effice pour bénéficier d'un correcteur avant de copier/coller et de faire la mise en forme en  md ;)

2025-01-21 10:09 UTC, Guts commented
C'est pour cela que j'ai recommandé l'extension de correction orthographique dans la config VS Code pour joindre l'utile à l'agréable : https://github.com/geotribu/website/blob/master/.vscode/extensions.json#L11

En plus, je suis sûr qu'elle est compatible avec VSCodium :kissing_cat: !

2025-01-21 10:49 UTC, Michael-cd30 commented
LinkedIn : https://www.linkedin.com/feed/update/urn:li:activity:7287420915431149573

2025-01-21 11:06 UTC, Michael-cd30 commented
BSky : https://bsky.app/profile/geotribu.bsky.social/post/3lgapemacws2n