Article 2021-06-10 Webmapping avec R
geotribu/website pull request #371
Opened 2021-06-09 10:53 UTC by rxlacroix

un tuto sur la réalisation d'un modèle de web mapping assez "brut" que j'ai eu l'occasion de tester et expérimenter dans mes conditions pro, à savoir avec une infrastructure informatique minimale, et sans besoin de compétences back end/front end poussées, avec seulement quelques packages R, du markdown et de la débrouille :)

2021-06-14 12:53 UTC, Guts commented
@datagistips (ou @mrajerisonCerema), une envie de relecture ? Vu que c'est du R ;)

2021-06-14 15:59 UTC, Guts commented on .gitignore
> +.Rhistory
@rxlacroix ?

2021-06-14 16:00 UTC, Guts requested changes

2021-06-14 16:00 UTC, Guts commented on content/articles/2021/2021-06-10_webmapping_avec_r.md
> +### Romain Lacroix
Il manque un saut de ligne @rxlacroix

2021-06-17 18:25 UTC, rxlacroix commented on .gitignore
> +.Rhistory
Juste en cas d'ouverture du document article .md avec RStudio 😄

2021-06-24 16:30 UTC, Guts approved these changes

2021-06-25 07:10 UTC, merged