Article sur la configuration de QGIS en entreprise
geotribu/website pull request #381
Opened 2021-06-30 10:07 UTC by haubourg

Hello la team Geotribu. 

Voilà un article pour parler de configuration QGIS en entreprise pour faire la peau à l'anthropie des parcs SIG hétérogènes. 

Voilà l'image principale pour le CDN 
![tuning_qgis](https://user-images.githubusercontent.com/1629853/123942500-7c176b80-d99b-11eb-861b-9a197eae47e2.png)

et pour ma trogne pour l'article sur les auteurs

![rha](https://user-images.githubusercontent.com/1629853/123942638-a10bde80-d99b-11eb-8ecb-bc59fa1d10cb.jpg)

Dites moi ce que vous en pensez, et j'améliore ça

2021-06-30 14:04 UTC, Guts commented
Salut @haubourg , merci pour le partage !

Après avoir corrigé rapidement les soucis mineurs de markdown et de liens, qqls remarques :

- :heavy_check_mark:  j'ai ajouté les images dans le CDN
- ça manque un peu d'images dans le corps de l'article je trouve
- c'est dommage d'utiliser batch alors que c'est faisable en Powershell non ? (cf autre tuto sur le déploiement automatisé)
- change la date dans le nom du fichier --> vu qu'on n'a pas bcp de tps cette semaine, je te propose de viser une publi mardi prochain ?

Zou, j'y retourne

2021-06-30 14:33 UTC, haubourg commented
> ça manque un peu d'images dans le corps de l'article je trouve

yep, je vais essayer d'illustrer un peu. 


> ✔️ j'ai ajouté les images dans le CDN

thx
Je vais revert ton commit https://github.com/geotribu/website/pull/381/commits/e6f80d80087bc0994f165f759c8e6c70e7701010, je voulais vraiment mettre une voiture jaune à la place du logo !

> c'est dommage d'utiliser batch alors que c'est faisable en Powershell non ? (cf autre tuto sur le déploiement automatisé)

huhu le vilain troll. Le batch que j'utilise est là à cause du fonctionnement d'osgeo4W qui demande des .bat pour postinstall et preremove :) . La ligne de commande d'install, moi je la lance en powershell, mais bon, je vais pas investir sur ce langage alors que dans 6 mois on fera plus que du bash sous Windows 🤣 



> change la date dans le nom du fichier --> vu qu'on n'a pas bcp de tps cette semaine, je te propose de viser une publi mardi prochain ?

ok, je fais ça

2021-06-30 14:44 UTC, Guts commented
> Je vais revert ton commit [e6f80d8](https://github.com/geotribu/website/commit/e6f80d80087bc0994f165f759c8e6c70e7701010), je voulais vraiment mettre une voiture jaune à la place du logo !

ok mais l'image que tu as déposée dans la description ? ça va pas rendre en thumbnail :thinking: 
Par contre, tu devrais la mettre en grand ! :car: :sunglasses:

2021-06-30 14:48 UTC, haubourg commented
> ok mais l'image que tu as déposée dans la description ? ça va pas rendre en thumbnail 🤔
> Par contre, tu devrais la mettre en grand ! 🚗 😎

ah oui pigé, je revert pas

2021-07-01 12:53 UTC, haubourg commented
@Guts ça devrait être bon pour moi ici !

2021-07-01 14:05 UTC, Guts requested changes

2021-07-01 14:05 UTC, Guts commented on content/articles/2021/2021-07-06_qgis_personnaliser_package_osgeo4w.md
> +# Personnaliser l'image au lancement de QGIS
T'es sûr que c'est tout bon @haubourg :trollface: ?

Au moment où tu mettras le titre de ton article (polisson de copieur/colleur). Je pense que c'est une bonne idée de mentionner l'OSGeo4W dans le titre.

2021-07-02 07:06 UTC, haubourg commented on content/articles/2021/2021-07-06_qgis_personnaliser_package_osgeo4w.md
> +# Personnaliser l'image au lancement de QGIS
> Au moment où tu mettras le titre de ton article (polisson de copieur/colleur). Je pense que c'est une bonne idée de mentionner l'OSGeo4W dans le titre.

Allez, c'est corrigé. ça m'avait échappé, pardon !

2021-07-02 07:34 UTC, Guts approved these changes

2021-07-05 15:53 UTC, Guts commented
@haubourg bon j'ai corrigé pas mal de petites choses, notamment sur la syntaxe Markdown (description des images pour les gens utilisant les outils d'accessibilité, placement...), langue fr (espaces avant les double ponctuation didou !), des casses inexactes ou inconsistantes. et certaines formulations. Bref, j'ai fait le ménage quoi.

Dernières remarques que je laisse à ton appréciation :

- à la lecture, je trouve qu'on a du mal à voir la progression ou même s'il y a des étapes dans l'article. C'est dû je pense à ce que tous les titres aient le même niveau, "aplatissant" la structure de l'article
- les commandes longues pourraient être présentées en multi-lignes car sinon c'est peu lisible sur le site
- en fait, ça ne respecte pas semver :thinking:

2021-07-05 15:56 UTC, Guts commented on content/articles/2021/2021-07-06_qgis_personnaliser_package_osgeo4w.md
> +- toujours avoir une recherche d'adresse dans la barre de recherche universelle (merci la BAN, via le plugin [French Locator Filter](https://oslandia.com/2019/10/14/rechercher-une-adresse-avec-qgis/)
@haubourg l'article du French Locator Filter est vieux et pointe même vers le dépôt GitHub. Mettre plutôt le lien vers la doc actuelle ? https://static.geotribu.fr/articles/2020/2020-10-28_gdal_windows_subsystem_linux_wsl/

2021-07-05 15:56 UTC, Guts commented on content/articles/2021/2021-07-06_qgis_personnaliser_package_osgeo4w.md
> +## Choisir sa configuration
@haubourg comme indiqué en commentaire global sur la PR, je pense que ça rendrait le tout plus lisible de placer ici un titre de niveau 2 qui indique le démarrage de la partie "tutoriel" et d'abaisser les sections suivantes à un niveau 3.

2021-07-05 15:56 UTC, Guts commented on content/articles/2021/2021-07-06_qgis_personnaliser_package_osgeo4w.md
> +
Dans la même veine, ajouter un petit ## Conclusion qui permet de clore l'article et désaplatir le volet tuto

2021-07-06 07:33 UTC, haubourg commented on content/articles/2021/2021-07-06_qgis_personnaliser_package_osgeo4w.md
> +
yep, je fais tou ça ce matin ! Bien vu oeil d'aigle.

2021-07-06 08:12 UTC, haubourg commented
@Guts correctifs poussés

2021-07-06 08:28 UTC, Guts commented
> @Guts correctifs poussés

Merci @haubourg. J'ai corrigé rapido le dernier glitch de markdown qui faisait bouder le linter. Dès que c'est bueno, je merge et ça part !

2021-07-06 08:29 UTC, merged