Homogénéisation et assainissement des contenus anciens
geotribu/website pull request #462
Opened 2021-11-01 20:34 UTC by igeofr

L'objectif est de résoudre les problèmes des contenus anciens (RDP (hors 2011/2012) et articles) en respectant la liste tâches : #443

2021-11-10 10:55 UTC, Guts requested changes

2021-11-10 10:55 UTC, Guts commented on content/rdp/2014/rdp_2014-06-20.md
> +{: align=middle }
Préférer la syntaxe .img-center

2021-11-10 10:55 UTC, Guts commented on content/rdp/2014/rdp_2014-06-27.md
> +{: align=middle }
Idem. Pourquoi spécifier la largeur en dur et centrer tout le paragraphe quand il suffit d'utiliser le CSS sur l'image ?

2021-11-10 11:16 UTC, igeofr commented on content/rdp/2014/rdp_2014-06-20.md
> +{: align=middle }
Je peux mettre ? :  `{: .img-center loading=lazy width=400px }`

2021-11-10 11:57 UTC, Guts commented on content/rdp/2014/rdp_2014-06-20.md
> +{: align=middle }
`{: .img-center loading=lazy }`

La largeur (75% de la largeur du bloc) est déjà paramétrée via le CSS https://github.com/geotribu/website/blob/f6cdb637dc3b7a838b930b8e9cbee64b6b94f777/content/theme/assets/stylesheets/extra.css#L34-L39

Mieux vaut utiliser le CSS et travailler à l'améliorer (probablement utiliser plutôt max-width plutôt que width, etc.) par ailleurs.

Exception faite des images étroites (< 600px) ou en portrait.

2021-11-10 14:52 UTC, igeofr commented on content/rdp/2014/rdp_2014-06-20.md
> +{: align=middle }
Ok, c'est noté. 
Je vais rebasculer toutes les images en `{: .img-center loading=lazy }` et à la fin je retravaillerai le CSS pour optimiser le rendu.

2021-11-10 14:54 UTC, Guts commented on content/rdp/2014/rdp_2014-06-20.md
> +{: align=middle }
ok pour les balises

pour le CSS ---> autre branche (voire sur le dépôt sandbox)

2021-11-10 15:12 UTC, igeofr commented on content/rdp/2014/rdp_2014-06-20.md
> +{: align=middle }
C'est noté pour le CSS ce sera dans un second temps.

2021-11-10 18:26 UTC, Guts commented on content/rdp/2014/rdp_2014-09-26.md
> +[![Liste OpenBeerMap](https://cdn.geotribu.fr/img/logos-icones/divers/OpenBeerMap.png "Liste OpenBeerMap"){: .img-center loading=lazy }](https://cdn.geotribu.fr/img/logos-icones/divers/OpenBeerMap.pn
Là, typiquement, cette image est trop petite/étroite pour se voir affecter la balise center : 

https://preview-pullrequest-462--geotribu-preprod.netlify.app/rdp/2014/rdp_2014-09-26/#openbeermap-ou-trouver-ma-biere-preferee

2021-11-10 20:41 UTC, igeofr commented
Je viens de terminer 2014. Je fais un balayage complet demain et je corrige les éléments pointés par @Guts.

2021-11-11 07:43 UTC, igeofr commented on content/rdp/2014/rdp_2014-06-20.md
> +{: align=middle }
@Guts, je viens de regarder les images que tu m'as indiqué font moins de 600px de largeur et sont en portrait.

2021-11-16 14:56 UTC, Guts requested changes

2021-11-16 14:56 UTC, Guts commented on content/rdp/2015/rdp_2015-09-18.md
> +[![Fond blanc](https://cdn.geotribu.fr/img/articles-blog-rdp/divers/fond_blanc.jpg "Fond blanc"){: .img-center loading=lazy }](https://cdn.geotribu.fr/img/articles-blog-rdp/capture-ecran/orange_globe
L'image n'est pas la même... j'ai l'impression qu'il y a plusieurs cas comme celui-ci, probablement liés à un copié/collé malheureux/fatigué :)

2021-11-16 14:57 UTC, Guts commented
J'ai appliqué le linter et trouvé qu'une dizaine de soucis : bravo !

Pour mémoire, les commandes :

```bash
yarn markdownlint -f -i "**/template_*.md" "content/rdp/2010/**/*.md"
yarn markdownlint -f -i "**/template_*.md" "content/rdp/2014/**/*.md"
yarn markdownlint -f -i "**/template_*.md" "content/rdp/2015/**/*.md"
```

2021-11-16 20:52 UTC, igeofr commented on content/rdp/2015/rdp_2015-09-18.md
> +[![Fond blanc](https://cdn.geotribu.fr/img/articles-blog-rdp/divers/fond_blanc.jpg "Fond blanc"){: .img-center loading=lazy }](https://cdn.geotribu.fr/img/articles-blog-rdp/capture-ecran/orange_globe
C'est pas impossible.
Je vais voir si je peux pas trouver une commande ce week-end pour identifier plus facilement ce type de cas.

2021-11-21 10:16 UTC, igeofr commented on content/rdp/2015/rdp_2015-09-18.md
> +[![Fond blanc](https://cdn.geotribu.fr/img/articles-blog-rdp/divers/fond_blanc.jpg "Fond blanc"){: .img-center loading=lazy }](https://cdn.geotribu.fr/img/articles-blog-rdp/capture-ecran/orange_globe
J'ai utilisé cette commande pour lister les images qui apparaissent plus de trois fois (en dehors des icônes) :

```bash
rep_rdp=/content/rdp
rep_temp=/temp

millesimes=( 2010 2013 2014 2015 2016 2017)
for i in "${millesimes[@]}"
do
  cd $rep_rdp'/'$i'/'
  for filename in *.md; do
    cat $filename | grep -v "image: " | grep -v "{: .img-rdp-news-thumb }" > $rep_temp$filename
  done
done

grep -Eoh "https?://[^][ ]+\.(jpg|png|tif|jpeg|gif|webp)" $rep_temp'/'*'.md'  | sort -t: -k2,2 | uniq -c | sort -nr | grep -v '^ *1 ' | grep -v '^ *2 ' > $rep_temp'/controle_img.txt'

rm $rep_temp'/'*'.md' 
```

2021-11-21 20:57 UTC, igeofr commented on content/rdp/2015/rdp_2015-09-18.md
> +[![Fond blanc](https://cdn.geotribu.fr/img/articles-blog-rdp/divers/fond_blanc.jpg "Fond blanc"){: .img-center loading=lazy }](https://cdn.geotribu.fr/img/articles-blog-rdp/capture-ecran/orange_globe
Voici la commande utilisée pour vérifier la description des images
```bash
rep_temp=/temp

cd /content/rdp/2010

grep -Eon '\!\[[^][]+\]' *.md | sed -e 's/!\[//g' | sed -e 's/\]//g' > $rep_temp'/alt.txt'
grep -Eon '\"[^][]+\"\)\{' *.md | sed -e 's/\"){//g' | sed -e 's/\"//g' > $rep_temp'/title.txt'
#grep -Eon 'data-title=\"[^][]+\" \}' *.md | sed -e 's/data-title=\"//g' | sed -e 's/\" }//g' > $rep_temp'/data_title.txt'

vim -d $rep_temp'/alt.txt' $rep_temp'/title.txt' #$rep_temp'/data_title.txt'
```

2021-12-13 16:44 UTC, Guts approved these changes

2021-12-13 16:45 UTC, merged