Article tutoriel pour réaliser une carte en relief avec QGIS
geotribu/website pull request #466
Opened 2021-11-05 16:42 UTC by Viglino

Bonjour,

Un article / tutoriel pour réaliser une carte en relief avec QGIS

Les images sont sur imgur et je n’ai pas vu comment les mettre sur le CDN de Geotribu…
Je ne sais pas si cela pose problème… sinon je peux les mettre mais il me faut un login.

Il y a une vidéo Youtube au début du tuto et une iframe avec le résultat à la fin (à voir si tu ne veux conserver que les liens).

Je prévoit de diffuser sur Twitter pour le #30DayMapChallenge le 11/11 (3D) si c'est possible.
Mais l'article peut être publié un peu avant.

@+
jmv

2021-11-06 07:28 UTC, Guts requested changes

2021-11-06 07:44 UTC, Guts requested changes

2021-11-06 07:44 UTC, Guts commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +Vous pouvez suivre le déroulement [sur la vidéo <i class="fa fa-youtube-play"></i>](https://youtu.be/wJjlKoSkmjY) (activez les sous-titres).
Pour les icones/emojis, pas besoin d'utiliser les balises HTML pour Fontawesome, elles sont accessibles directement via les codes :

```suggestion
Vous pouvez suivre le déroulement [sur la vidéo :fontawesome-brands-youtube:](https://youtu.be/wJjlKoSkmjY) (activez les sous-titres).
```

Voir https://static.geotribu.fr/contribuer/guides/emoji/ et https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/#search

2021-11-06 07:44 UTC, Guts commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +- et d'un logiciel SIG ([QGis](https://www.qgis.org/fr/site/))
Typo et règle Markdown n°32 ["Lists should be surrounded by blank lines"](https://github.com/DavidAnson/markdownlint/blob/v0.24.0/doc/Rules.md#md032)

```suggestion
Pour cela, nous aurons besoin :

- d'un modèle numérique de terrain (MNT)
- d'un fond de carte
- et d'un logiciel SIG ([QGis](https://www.qgis.org/fr/site/))
```

2021-11-06 12:58 UTC, Guts requested changes

2021-11-06 12:58 UTC, Guts commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +--8<-- "content/team/jmv.md"
```suggestion
--8<-- "content/team/jmev.md"
```

2021-11-06 13:29 UTC, ThomasG77 commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +Attention, ils sont fournis en ftp et il vous faudra un logiciel tel que [FileZilla](https://filezilla-project.org/) pour les charger. Sinon ils sont également disponible en téléchargement sur [opend
```suggestion
Attention, ils sont fournis en FTP et il vous faudra un logiciel tel que [FileZilla](https://filezilla-project.org/) pour les charger. Sinon ils sont également disponibles en téléchargement sur [opendatarchives.fr](https://files.opendatarchives.fr/professionnels.ign.fr/bdalti/).
```

2021-11-06 13:30 UTC, ThomasG77 commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +Décompressez les fichiers chargés précédemment et faite glisser les fichiers `.asc` dans le fenêtre de QGis.
```suggestion
Décompressez les fichiers chargés précédemment et faite glisser les fichiers `.asc` dans la fenêtre de QGis.
```

2021-11-06 13:31 UTC, ThomasG77 commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +En fait, vous n'aurez pas besoins de tous les fichier, seul ceux qui se superposent avec le parc sont nécessaires.
```suggestion
En fait, vous n'aurez pas besoins de tous les fichiers, seuls ceux qui se superposent avec le parc sont nécessaires.
```

2021-11-06 13:32 UTC, ThomasG77 commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +Dans le menu, choississez `Raster > Divers > Fusionner` et indiquez les tuiles à fusionner.
```suggestion
Dans le menu, choisissez `Raster > Divers > Fusionner` et indiquez les tuiles à fusionner.
```

2021-11-06 13:32 UTC, ThomasG77 commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +Pour cela, l'IGN met à disposition [un ensemble de fond de carte sur sont sit Géoservice](https://geoservices.ign.fr/services-web-experts).
```suggestion
Pour cela, l'IGN met à disposition [un ensemble de fond de carte qui sont situés sur Géoservice](https://geoservices.ign.fr/services-web-experts).
```

2021-11-06 13:33 UTC, ThomasG77 commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +En particulier, pour ajouter les cartes, rendez-vous [sur cette page](https://geoservices.ign.fr/services-web-experts-cartes) pour récupérer l'url du service :
```suggestion
En particulier, pour ajouter les cartes, rendez-vous [sur cette page](https://geoservices.ign.fr/services-web-experts-cartes) pour récupérer l'URL du service :
```

2021-11-06 13:33 UTC, ThomasG77 commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +Puis rendez-vous dans l'explorateur de QGIS à gauche pour ajouter une couche WMS/WMTS (clic-droit nouvelle connexion) et coller l'url dans le champ dédié du dialogue.
```suggestion
Puis rendez-vous dans l'explorateur de QGIS à gauche pour ajouter une couche WMS/WMTS (clic-droit nouvelle connexion) et coller l'URL dans le champ dédié du dialogue.
```

2021-11-06 13:34 UTC, ThomasG77 commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +Il vous suffit alors de cliquer sur la nouvelle icone ![](https://i.imgur.com/qzmotVy.png) (ou via le menu Internet).
```suggestion
Il vous suffit alors de cliquer sur la nouvelle icône ![](https://i.imgur.com/qzmotVy.png) (ou via le menu Internet).
```

2021-11-06 13:35 UTC, ThomasG77 commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +Dans la fenêtre, choissez la couche terrain à utiliser (DEM = Digital Elevation Model) et dans le menu `Scene > Scene settings` règlez les paramètres de la vue.
```suggestion
Dans la fenêtre, choisissez la couche terrain à utiliser (DEM = Digital Elevation Model) et dans le menu `Scene > Scene settings` réglez les paramètres de la vue.
```

2021-11-06 13:35 UTC, ThomasG77 commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +Vous pouvez modifier l'exagération vertical pour donner plus de relief...
```suggestion
Vous pouvez modifier l'exagération verticale pour donner plus de relief...
```

2021-11-06 13:35 UTC, ThomasG77 commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +- et d'un logiciel SIG ([QGis](https://www.qgis.org/fr/site/))
```suggestion
- et d'un logiciel SIG ([QGIS](https://www.qgis.org/fr/site/))
```

2021-11-06 13:36 UTC, ThomasG77 commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +Ouvrez [QGis](https://www.qgis.org/fr/site/) et faites glisser le fichier sur la fenêtre pour afficher cette limite.
```suggestion
Ouvrez [QGIS](https://www.qgis.org/fr/site/) et faites glisser le fichier sur la fenêtre pour afficher cette limite.
```

2021-11-06 13:36 UTC, ThomasG77 commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +Décompressez les fichiers chargés précédemment et faite glisser les fichiers `.asc` dans le fenêtre de QGis.
```suggestion
Décompressez les fichiers chargés précédemment et faite glisser les fichiers `.asc` dans la fenêtre de QGIS.
```

2021-11-06 13:37 UTC, ThomasG77 commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +Il vous faudra définir le système de coordonnées de référence (SCR) pour les données afin que QGis sache comment placer ces fichiers sur la carte. Faites un clic-droit sur la couche pour définir le S
```suggestion
Il vous faudra définir le système de coordonnées de référence (SCR) pour les données afin que QGIS sache comment placer ces fichiers sur la carte. Faites un clic-droit sur la couche pour définir le SCR.
```

2021-11-06 13:37 UTC, ThomasG77 commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +Comme le parc est à cheval sur deux départements, le plus simple est de recopier les fichiers `.asc` des deux archives dans un même répertoire et de les faire glisser tous ensemble sur QGis. On peut
```suggestion
Comme le parc est à cheval sur deux départements, le plus simple est de recopier les fichiers `.asc` des deux archives dans un même répertoire et de les faire glisser tous ensemble sur QGIS. On peut ensuite les sélectionner et changer leur SCR en une seule fois.
```

2021-11-06 13:37 UTC, ThomasG77 commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +Pour cela, vous devrez ajouter une extension à QGis.
```suggestion
Pour cela, vous devrez ajouter une extension à QGIS.
```

2021-11-06 13:40 UTC, ThomasG77 commented on content/team/jemv.md
> +Je m'exprim sure ce blogue à titre personnel.
```suggestion
Je m'exprime sure ce blog à titre personnel.
```

2021-11-06 13:43 UTC, ThomasG77 commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +Il vous suffit alors de cliquer sur la nouvelle icône ![](https://i.imgur.com/qzmotVy.png) (ou via le menu Internet).
Changez l'URL de l'image https://i.imgur.com/qzmotVy.png par une sur https://cdn.geotribu.fr/img/articles-blog-rdp/articles/carte_en_relief_des_ecrins/

2021-11-06 13:47 UTC, ThomasG77 commented
Usage du VRT plutôt que la section ci-dessous?

> Il faudra encore une petite opération si vous voulez éviter les discontinuités en bord de tuile : il va falloir les fusionner.
Dans le menu, choisissez `Raster > Divers > Fusionner` et indiquez les tuiles à fusionner.

2021-11-06 16:20 UTC, ThomasG77 commented on content/team/jemv.md
> +Je m'exprime sure ce blog à titre personnel.
```suggestion
Je m'exprime sur ce blog à titre personnel.
```

2021-11-06 16:23 UTC, ThomasG77 commented on content/team/jemv.md
> +J'entretiens une bibliothèque JS d'extension pour Openlayers [ol-ext](https://viglino.github.io/ol-ext/) disponible en Opensource sur Github.
```suggestion
J'entretiens une bibliothèque JS d'extensions pour Openlayers [ol-ext](https://viglino.github.io/ol-ext/) disponible en Opensource sur Github.
```

2021-11-06 16:25 UTC, Viglino commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +Il vous suffit alors de cliquer sur la nouvelle icône ![](https://i.imgur.com/qzmotVy.png) (ou via le menu Internet).
done

2021-11-06 19:46 UTC, Guts commented on content/articles/2021/2021-11-10_Carte_en_relief_des_ecrins.md
> +date: 2021-10-10 00:00
Je me suis aperçu que du coup l'article était programmé pour octobre... j'ai corrigé (et dans le nom du fichier également).

2021-11-06 19:57 UTC, Guts requested changes

2021-11-06 19:57 UTC, Guts commented on content/articles/2021/2021-11-11_carte_en_relief_des_ecrins.md
> +- [le MNT de l'Isère (06) <i class="fa fa-download"></i>](https://files.opendatarchives.fr/professionnels.ign.fr/bdalti/BDALTIV2_2-0_25M_ASC_LAMB93-IGN69_D005_2021-08-04.7z)
idem que pour les autres icones fontawesome. Ici :

```suggestion
- [le MNT de l'Isère (06) :fontawesome-solid-download:](https://files.opendatarchives.fr/professionnels.ign.fr/bdalti/BDALTIV2_2-0_25M_ASC_LAMB93-IGN69_D005_2021-08-04.7z)
```

2021-11-06 19:57 UTC, Guts commented on content/articles/2021/2021-11-11_carte_en_relief_des_ecrins.md
> +- [le MNT Hautes-Alpes (38) <i class="fa fa-download"></i>](https://files.opendatarchives.fr/professionnels.ign.fr/bdalti/BDALTIV2_2-0_25M_ASC_LAMB93-IGN69_D038_2020-11-13.7z)
```suggestion
- [le MNT Hautes-Alpes (38) :fontawesome-solid-download:](https://files.opendatarchives.fr/professionnels.ign.fr/bdalti/BDALTIV2_2-0_25M_ASC_LAMB93-IGN69_D038_2020-11-13.7z)
```

2021-11-06 19:57 UTC, Guts commented on content/articles/2021/2021-11-11_carte_en_relief_des_ecrins.md
> +Vous en trouverez disponible en OpenData [sur le site de l'IGN, rubrique BDAlti <i class="fa fa-external-link"></i>](https://geoservices.ign.fr/bdalti).
Fontawesome toujours :

```suggestion
Vous en trouverez disponible en OpenData [sur le site de l'IGN, rubrique BDAlti :fontawesome-solid-external-link-alt:](https://geoservices.ign.fr/bdalti).
```

2021-11-06 19:57 UTC, Guts commented on content/articles/2021/2021-11-11_carte_en_relief_des_ecrins.md
> +[Voir en plein écran <i class="fa fa-external-link"></i>](https://viglino.github.io/maps/static/PNE_coeur.html)
Fontawesome encore :

```suggestion
[Voir en plein écran :fontawesome-solid-external-link-alt:](https://viglino.github.io/maps/static/PNE_coeur.html)
```

2021-11-06 19:57 UTC, Guts commented on content/articles/2021/2021-11-11_carte_en_relief_des_ecrins.md
> +## Et voilà le résultat...
```suggestion
----

## Et voilà le résultat !
```

2021-11-06 19:57 UTC, Guts commented on content/articles/2021/2021-11-11_carte_en_relief_des_ecrins.md
> +## Charger les cartes
```suggestion
----

## Charger les cartes
```

2021-11-06 19:57 UTC, Guts commented on content/articles/2021/2021-11-11_carte_en_relief_des_ecrins.md
> +## Passez dans la 3ième dimension
```suggestion
----

## Passez dans la 3ème dimension
```

2021-11-06 19:57 UTC, Guts commented on content/articles/2021/2021-11-11_carte_en_relief_des_ecrins.md
> +
Homogénéisation avec le modèle d'article :

```suggestion
:calendar: Date de publication initiale : 11 novembre 2021

## Introduction

```

2021-11-06 19:57 UTC, Guts commented on content/articles/2021/2021-11-11_carte_en_relief_des_ecrins.md
> +## Le MNT
```suggestion
----

## Le MNT
```

2021-11-06 19:57 UTC, Guts commented on content/articles/2021/2021-11-11_carte_en_relief_des_ecrins.md
> +Pour cela, nous aurons besoins :
typo

```suggestion
Pour cela, nous aurons besoin :
```

2021-11-06 19:57 UTC, Guts commented on content/articles/2021/2021-11-11_carte_en_relief_des_ecrins.md
> +<iframe width="100%" height="315" src="https://www.youtube-nocookie.com/embed/wJjlKoSkmjY?cc_load_policy=1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-writ
Conseil : hauteur plus grande pour éviter l'aspect rectangle écrasé

```suggestion
<iframe width="100%" height="400" src="https://www.youtube-nocookie.com/embed/wJjlKoSkmjY?cc_load_policy=1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

2021-11-06 20:56 UTC, Guts requested changes

2021-11-06 20:56 UTC, Guts commented on content/articles/2021/2021-11-11_carte_en_relief_des_ecrins.md
> +  - Viglino
```suggestion
  - Jean-Marc Viglino
```

2021-11-07 18:28 UTC, Guts approved these changes

2021-11-09 13:56 UTC, igeofr approved these changes

2021-11-10 17:50 UTC, merged