Article sur les process data OSM chez Geovelo
geotribu/website pull request #472
Opened 2021-11-15 15:36 UTC by samDB-gv

Bonjour, 

Une première version d'un article sur la gestion des données OSM chez Geovelo (il manque quelques images, je n'ai pas les droits pour les stocker sur le CDN de Geotribu :p ) 

N'hésitez pas s'il y a des modifications/eclaircissements/suppressions à faire ! 

Merci et bonne journée

2021-11-17 08:10 UTC, Guts requested changes
Merci de ne pas modifier autre chose que les markdown liés à l'article :)

2021-11-17 08:21 UTC, Guts commented
Premier jet.

> Merci de ne pas modifier autre chose que les markdown liés à l'article :)

J'ai donc annulé la modif du package.json.  
J'ai ajouté ton mail au mailmap pour que ce soit plus joli.

Attention, le fichier de ta bio a 5 lettres au lieu des 4.

Sinon, j'ai juste appliqué les corrections automatiques du linter : `yarn markdownlint -f content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md`

2021-11-17 08:38 UTC, samueldb commented
Merci pour les corrections et désolé pour le package.json qui m'a échappé :$

2021-11-22 10:26 UTC, igeofr commented
Bonjour @samueldb,
J'ai fait une relecture de l'article et j'en ai profité pour faire quelques corrections sur le rendu.

- Pour l’image de l’en-tête notamment utilisée pour la page d’accueil, est-ce que c'est possible de pousser sur le cdn une image horizontale aux dimensions approximative de 1000x600px?
- Une remarque à discuter, avec @Guts et @Jersig, je trouve que la citation markdown est trop utilisée

2021-11-24 13:06 UTC, Guts requested changes
Première passe sur la syntaxe globale et les coquilles typos.

2021-11-24 13:06 UTC, Guts commented on content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md
> +{: list-style-type: none;}
Pourquoi cette balise ?

2021-11-24 13:06 UTC, Guts commented on content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md
> +> :warning: Si la note comprend des informations personnelles ou semble trop fantaisiste, nous supprimons la contribution.
Idem, le style citation ne semble pas adapté. S'il s'agit d'une suite logique, opter plutôt pour une liste numérotée ou un schéma Mermaid.

J'en profite pour corriger des coquilles typos et orthos mais aussi mettre le cas du warning en premier car ça me paraît plus logique et en lien (alternative) avec le cas où c'est pertinent :

```suggestion
- :warning: Si la note comprend des informations personnelles ou semble trop fantaisiste, nous supprimons la contribution.
- :checkered_flag: Si les informations sont pertinentes, les données OpenStreetMap sont modifiées.
- :thinking: Si nous manquons d’informations, nous demandons des détails au contributeur initial. Tout commentaire sur note, qu’il soit été effectué coté OpenStreetMap ou coté Geovelo, est transmis par mail au créateur de la note.
    - :arrow_right_hook: Si l’usager nous répond uniquement par mail, nous recevons ses précisions et nous traitons la demande, mais sa réponse ne s’affiche pas sur la note.
    - :arrow_right_hook:️ Si l’usager nous répond en utilisant [amenagements-cyclables.fr](amenagements-cyclables.fr), sa réponse s'affiche sur la note OpenStreetMap


```

2021-11-24 13:06 UTC, Guts commented on content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md
> +> Une part de l'activité de Geovelo réside dans l'intégration de données des collectivités. Avec leurs accords, nous importons donc leurs données cyclables à partir de multiples sources de données (d
Idem pour le style citation.

```suggestion
Une part de l'activité de Geovelo réside dans l'intégration de données des collectivités. Avec leurs accords, nous importons donc leurs données cyclables à partir de multiples sources de données, de la carte annotée au fichier GPKG.
```

2021-11-24 13:06 UTC, Guts commented on content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md
> +- des analyses [Osmose](http://osmose.openstreetmap.fr/fr/map/), détecteur de problèmes à large spectre,
Le https par défaut, c'est mieux.

```suggestion
- des analyses [Osmose](https://osmose.openstreetmap.fr/fr/map/), détecteur de problèmes à large spectre,
```

2021-11-24 13:11 UTC, samDB-gv commented on content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md
> +{: list-style-type: none;}
Une scorie d'un test, je supprime

2021-11-24 15:33 UTC, Guts requested changes

2021-11-24 15:33 UTC, Guts commented on content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md
> +    - :arrow_right_hook:️ Si l’usager nous répond en utilisant [amenagements-cyclables.fr](amenagements-cyclables.fr), sa réponse s'affiche sur la note OpenStreetMap
J'ai trouvé ce qui fait planté le build : en markdown, les liens sont relatifs par défaut, du coup le générateur pense qu'il y a un lien qui pointe vers 'articles/2021/amenagements-cyclables.fr' donc un contenu local qui n'existe pas.

Voici le correctif :

```suggestion
    - :arrow_right_hook:️ Si l’usager nous répond en utilisant [amenagements-cyclables.fr](https://www.amenagements-cyclables.fr/), sa réponse s'affiche sur la note OpenStreetMap
```

2021-11-24 15:57 UTC, samDB-gv commented on content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md
> +    - :arrow_right_hook:️ Si l’usager nous répond en utilisant [amenagements-cyclables.fr](amenagements-cyclables.fr), sa réponse s'affiche sur la note OpenStreetMap
hhoooo, merci ! Je n'arrivais pas à comprendre pourquoi le checker plantait -_-"

2021-11-24 19:34 UTC, Jersig commented
Bonjour @samueldb,
Merci pour cet article, j'ai jeté un œil, j'effectue une relecture plus complète vendredi matin pour compléter celle d'@igeofr

2021-11-25 16:13 UTC, Guts requested changes

2021-11-25 16:13 UTC, Guts commented on content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md
> +[![Suivi OSM chez Geovelo](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/geovelo_traitements_data_osm/process_traitement_data_cyclables_osm.png "Suivi OSM chez Geovelo"){: loading=lazy align
L'alignement à droite pour une image large ne rend pas très bien avec une liste à puces, en particulier sur mobile :

![Screenshot_20211125-081544_Firefox](https://user-images.githubusercontent.com/1596222/143473546-6c7a9f14-1279-479d-abd8-0c3c96f1ed39.jpg)


Je suggère de la placer plutôt avant ou après la liste.

2021-11-25 16:13 UTC, Guts commented on content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md
> +*Une part de l'activité de Geovelo réside dans l'intégration de données des collectivités. Avec leurs accords, nous importons donc leurs données cyclables à partir de multiples sources de données, de
Pourquoi mettre en italique @samDB-gv ?

```suggestion
Une part de l'activité de Geovelo réside dans l'intégration de données des collectivités. Avec leurs accords, nous importons donc leurs données cyclables à partir de multiples sources de données, de la carte annotée au fichier GPKG.
```

2021-11-25 16:13 UTC, Guts commented on content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md
> +*L’outil de signalement interne à l’application incite l’utilisateur à nous joindre une photo et une description du problème.*
Pourquoi l'italique ? C'est du corps de texte, non ?

```suggestion
L’outil de signalement interne à l’application incite l’utilisateur à nous joindre une photo et une description du problème.
```

2021-11-25 16:13 UTC, Guts commented on content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md
> +Avant toute intégration de données, un audit des données OpenStreetMap est effectué. **L’exhaustivité attributaire et géographique** ainsi que **la qualité de la description** des données dans OpenSt
```suggestion
Avant toute intégration de données, un audit des données OpenStreetMap est effectué. **L’exhaustivité attributaire et géographique** ainsi que **la qualité de la description** des données dans OpenStreetMap sont vérifiées, afin d’établir un état des lieux précis du territoire existant sur OSM.
```

2021-11-25 16:13 UTC, Guts commented on content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md
> +3. Les données déjà présentes sur OSM sont croisées avec les sources disponibles (Orthophotos, Mapillary, cadastre …) afin d'être certains de la modification à effectuer.
```suggestion
3. Les données déjà présentes sur OSM sont croisées avec les sources disponibles (orthophotos, Mapillary, cadastre …) afin d'être certains de la modification à effectuer.
```

2021-11-25 16:13 UTC, Guts commented on content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md
> +> En cas de doute sur des données à intégrer (pas de sources permettant de confirmer ou d’infirmer la donnée), l’objet n’est pas intégré et nous demandons au producteur de nous confirmer ou non la ré
Suppression du style citation :

```suggestion
En cas de doute sur des données à intégrer (pas de sources permettant de confirmer ou d’infirmer la donnée), l’objet n’est pas intégré et nous demandons au producteur de nous confirmer ou non la réalité de cet objet.
```

2021-11-25 16:13 UTC, Guts commented on content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md
> +## Réutilisation des données
En général, on insère une barre horizontale pour séparer visuellement les grandes parties mais ça n'est pas obligatoire.

```suggestion
----

## Réutilisation des données
```

2021-11-25 16:13 UTC, Guts commented on content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md
> +>Postgis, Osmosis, Osm2pgsql, GDAL
Suppression style citation.

```suggestion
Pour les traitements de réutilisation, on est sur du classique libre : Postgis, Osmosis, Osm2pgsql, GDAL.
```

2021-11-25 16:13 UTC, Guts commented on content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md
> +## Auteur
```suggestion
----

## Auteur
```

2021-11-26 07:48 UTC, samDB-gv commented on content/articles/2021/2021-11-20_traitements_data_osm_geovelo.md
> +*Une part de l'activité de Geovelo réside dans l'intégration de données des collectivités. Avec leurs accords, nous importons donc leurs données cyclables à partir de multiples sources de données, de
@Guts j'aime bien utiliser l'italique pour replacer un peu de contexte et le bloc citation pour donner des infos (ça évite d'avoir une grosse masse de texte que les gens ne lisent plus...)

2021-11-26 09:35 UTC, Guts approved these changes

2021-11-26 09:45 UTC, merged