Ajout article MapSCII et bio JG
geotribu/website pull request #495
Opened 2021-12-24 12:38 UTC by mapperfr

2021-12-24 14:09 UTC, Guts requested changes
Trop cool !

Première livrée de coquilles

2021-12-24 14:09 UTC, Guts commented on content/articles/2021/21-12-24_mapscii.md
> +[Publié sur Github](https://github.com/rastapasta/mapscii) en 2017 par le développeur allemant Michael Straßburger, MapSCII est une application Node.js qui propose de naviguer dans la carte mondiale
```suggestion
[Publié sur Github](https://github.com/rastapasta/mapscii) en 2017 par le développeur allemand Michael Straßburger, MapSCII est une application Node.js qui propose de naviguer dans la carte mondiale d'OpenStreetMap... depuis un [terminal](https://fr.wikipedia.org/wiki/Terminal), avec un style cartographique détonnant construit en braille et en [ASCII](https://fr.wikipedia.org/wiki/American_Standard_Code_for_Information_Interchange) ! Le projet, qui nous avait échappé jusqu'ici, dispose d'une démo rapidement consultable, mais peut aussi être téléchargé et personnalisé.

Tour d'horizon.
```

2021-12-24 14:09 UTC, Guts commented on content/articles/2021/21-12-24_mapscii.md
> +`telnet mapscii.me`
Rendre la commande copiable/collable facilement :

```suggestion
```bash
telnet mapscii.me
```
```

2021-12-24 14:09 UTC, Guts commented on content/articles/2021/21-12-24_mapscii.md
> +`brew install telnet`
Rendre la commande copiable/collable facilement :

```suggestion
```bash
brew install telnet
```
```

2021-12-24 14:09 UTC, Guts commented on content/articles/2021/21-12-24_mapscii.md
> +![](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/mapscii/mapscii_5.png)
Il manque les éléments d'accessibilité du web sur l'image : texte de remplacement et description.

cf tuto image sur geotribu

2021-12-24 14:09 UTC, Guts commented on content/articles/2021/21-12-24_mapscii.md
> +Il est possible d'installer MapSCII en local, via[Node.js](https://nodejs.org/fr/download/) : `npm install -g mapscii` (Ou, pour une installation moins invasive, en retirant le `-g` qui indique une i
```suggestion
Il est possible d'installer MapSCII en local, via [Node.js](https://nodejs.org/fr/download/) : `npm install -g mapscii` ou, pour une installation moins invasive, en retirant le `-g` qui indique une installation globale au niveau du système.
```

2021-12-24 14:33 UTC, mapperfr commented on content/articles/2021/21-12-24_mapscii.md
> +![](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/mapscii/mapscii_5.png)
Yep celui-ci m'a échappé. A quel endroit je peux corriger ?

2021-12-24 14:34 UTC, mapperfr commented
> Trop cool !
> 
> Première livrée de coquilles

Super merci pour la relecture. Il me semble que je n'ai rien à valider ?

2021-12-24 14:35 UTC, mapperfr commented
Je vois d'autres coquilles... Même question que pour l'alt text, sur quelle version est-ce que je peux corriger les coquilles ?

2021-12-24 14:38 UTC, mapperfr reviewed
OK pour les corrections / changement proposés

2021-12-24 14:53 UTC, Guts commented
> Je vois d'autres coquilles... Même question que pour l'alt text, sur quelle version est-ce que je peux corriger les coquilles ?

Il suffit de modifier le fichier sur ton fork.

De même pour valider les suggestions de changement de la review, il suffit de cliquer sur commit suggestion

2021-12-24 14:54 UTC, Guts commented
Ici https://github.com/mapperfr/website/blob/master/content/articles/2021/2021-12-31_mapscii_osm_terminal.md

2021-12-24 15:01 UTC, mapperfr commented
> De même pour valider les suggestions de changement de la review, il suffit de cliquer sur commit suggestion
Tous les boutons "commit suggestion" sont grisés, je ne peux pas cliquer...

2021-12-24 15:53 UTC, Guts commented
> Je n'ai pas de droits en écriture sur le dépôt de Géotribu ça doit être pour ça ? 


Non puisque les commits vont sur ton fork. Je pense que c'est lié au changement de nom du fichier.

2021-12-30 16:54 UTC, Guts requested changes
Hop, première fournée, 2è édition

2021-12-30 16:54 UTC, Guts commented on content/articles/2021/2021-12-31_mapscii_osm_terminal.md
> +title: "OpenStreetMap dans le terminal, en braille et en ASCII "
```suggestion
title: "OpenStreetMap dans le terminal, en braille et en ASCII"
```

2021-12-30 16:54 UTC, Guts commented on content/articles/2021/2021-12-31_mapscii_osm_terminal.md
> +
Une petite vignette pour rendre l'intro plus visuelle

```suggestion

![logo OpenStreetMap](https://cdn.geotribu.fr/img/logos-icones/OpenStreetMap/Openstreetmap.png "logo OpenStreetMap"){: .img-rdp-news-thumb }

```

2021-12-30 16:54 UTC, Guts commented on content/articles/2021/2021-12-31_mapscii_osm_terminal.md
> +[Publié sur Github](https://github.com/rastapasta/mapscii) en 2017 par le développeur allemant Michael Straßburger, MapSCII est une application Node.js qui propose de naviguer dans la carte mondiale
Coquille et espacement

```suggestion
[Publié sur Github](https://github.com/rastapasta/mapscii) en 2017 par le développeur allemand Michael Straßburger, MapSCII est une application Node.js qui propose de naviguer dans la carte mondiale d'OpenStreetMap... depuis un [terminal](https://fr.wikipedia.org/wiki/Terminal), avec un style cartographique détonnant construit en braille et en [ASCII](https://fr.wikipedia.org/wiki/American_Standard_Code_for_Information_Interchange) !

Le projet, qui nous avait échappé jusqu'ici, dispose d'une démo rapidement consultable, mais peut aussi être téléchargé et personnalisé.  
Tour d'horizon.
```

2021-12-30 16:54 UTC, Guts commented on content/articles/2021/2021-12-31_mapscii_osm_terminal.md
> +## Lancer la démo
Une ligne horizontale pour garder la cohérence avec les autres articles.

```suggestion
----

## Lancer la démo
```

2021-12-30 16:54 UTC, Guts commented on content/articles/2021/2021-12-31_mapscii_osm_terminal.md
> +![MapSCII_1](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/mapscii/mapscii_1.png)
- Inversion illustration/bouton commentaires
- ajout balises accessibilité et performances sur l'image

```suggestion

![MapSCII 1](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/mapscii/mapscii_1.png "MapSCII Asie"){: .img-center loading=lazy }

[Commenter cet article :fontawesome-solid-comments:](#__comments){: .md-button }
{: align=middle }
```

2021-12-30 16:57 UTC, Guts commented on content/articles/2021/2021-12-31_mapscii_osm_terminal.md
> +MapSCII est accessible via le protocole [telnet](https://fr.wikipedia.org/wiki/Telnet). Si vous êtes sous Linux, telnet devrait être installé par défaut. Sous MacOS, vous pouvez utiliser le gestionna
> Si vous êtes sous Linux

Tous les Linux ou principalement les Debian/Ubuntu ?

2021-12-30 17:00 UTC, Guts requested changes

2021-12-30 17:00 UTC, Guts commented on content/articles/2021/2021-12-31_mapscii_osm_terminal.md
> +Un snap dédié est aussi disponible sous Linux : `sudo snap install mapscii`.
Linux ~= Ubuntu ?

2021-12-30 17:07 UTC, mapperfr commented on content/articles/2021/2021-12-31_mapscii_osm_terminal.md
> +Un snap dédié est aussi disponible sous Linux : `sudo snap install mapscii`.
Yep bien vu

2021-12-30 17:36 UTC, Guts requested changes

2021-12-30 17:36 UTC, Guts commented on content/articles/2021/2021-12-31_mapscii_osm_terminal.md
> +[Publié sur Github](https://github.com/rastapasta/mapscii) en 2017 par le développeur allemand Michael Straßburger, MapSCII est une application Node.js qui propose de naviguer dans la carte mondiale
```suggestion
[Publié sur Github](https://github.com/rastapasta/mapscii) en 2017 par le développeur allemand Michael Straßburger, MapSCII est une application Node.js qui propose de naviguer dans la carte mondiale d'OpenStreetMap... depuis un [terminal](https://fr.wikipedia.org/wiki/Terminal), avec un style cartographique détonnant construit en braille et en [ASCII](https://fr.wikipedia.org/wiki/American_Standard_Code_for_Information_Interchange) !  
Le projet, qui nous avait échappé jusqu'ici, dispose d'une démo rapidement consultable, mais peut aussi être téléchargé et personnalisé.

Petit tour d'horizon.
```

2021-12-30 17:36 UTC, Guts commented on content/articles/2021/2021-12-31_mapscii_osm_terminal.md
> +
- Inversion illustration/bouton commentaires
- ajout balises accessibilité et performances sur l'image


```suggestion

![MapSCII 1](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/mapscii/mapscii_1.png "MapSCII Asie"){: .img-center loading=lazy }

[Commenter cet article :fontawesome-solid-comments:](#__comments){: .md-button }
{: align=middle }

```

2021-12-30 17:36 UTC, Guts commented on content/articles/2021/2021-12-31_mapscii_osm_terminal.md
> +
````suggestion
```bash
brew install telnet
```

````

2021-12-30 17:36 UTC, Guts commented on content/articles/2021/2021-12-31_mapscii_osm_terminal.md
> +telnet mapscii.me
````suggestion
```bash
telnet mapscii.me
```
````

2021-12-30 17:43 UTC, Guts requested changes

2021-12-30 17:43 UTC, Guts commented on content/articles/2021/2021-12-31_mapscii_osm_terminal.md
> +npm install -g mapscii
````suggestion
```sh
npm install -g mapscii
```

````

2021-12-30 17:43 UTC, Guts commented on content/articles/2021/2021-12-31_mapscii_osm_terminal.md
> +## Personnalisation
```suggestion
----

## Personnalisation
```

2021-12-30 17:43 UTC, Guts commented on content/articles/2021/2021-12-31_mapscii_osm_terminal.md
> +![MapSCII_screenshot_5](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/mapscii/mapscii_5.png)
Ajoute description image (accessibilité) et balise perf

```suggestion
![MapSCII_screenshot_5](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/mapscii/mapscii_5.png "MapSCII 5"){: .img-center loading=lazy }
```

2021-12-30 17:43 UTC, Guts commented on content/articles/2021/2021-12-31_mapscii_osm_terminal.md
> +Vous pouvez également personnaliser différents aspects de MapSCII : changer le style (l'application est fournie avec deux styles Mapbox au choix, Bright ou Dark), ou bien explorer d'autres services d
Ajout lien vers ligne du code en question

```suggestion
Vous pouvez également personnaliser différents aspects de MapSCII : changer le style (l'application est fournie avec deux styles Mapbox au choix, Bright ou Dark), ou bien explorer d'autres services d'autres lots de tuiles vecteurs, en local ou en se connectant à un service distant.
Ces éléments sont assez faciles à identifier dans le code source : par exemple, le fichier [`/src/config.js`](https://github.com/rastapasta/mapscii/blob/2315a3515c8870b8f88b1aa7978922fc7d426777/src/config.js#L10) permet d'indiquer, ligne 10, le fichier de style au format JSON à utiliser.
```

2021-12-31 07:20 UTC, mapperfr commented
![mapscii_telnet_putty](https://user-images.githubusercontent.com/3398608/147809445-a633c6c9-2647-485a-bc3d-ef6db518fc79.png)

2021-12-31 08:22 UTC, Guts approved these changes

2021-12-31 08:31 UTC, merged