Create 2022_01_04_quantifier_inegalites_traitement_meteo.md
geotribu/website pull request #503
Opened 2022-01-04 19:33 UTC by Valexandre

# Amorcer une nouvelle revue de presse

- [ ] nommer cette _Pull Request_ de façon claire et lisible. Exemple : `GeoRDP du JJ MM AAAA`
- [ ] partir du modèle disponible (copier/coller) [sur Github](https://github.com/geotribu/website/blob/master/content/rdp/templates/template_rdp.md?plain=1) ou [sur le pad](https://geotripad.herokuapp.com/DCBQirjYSp6sqxPd5JYqLg?both)
- [ ] changer la date dans les métadonnées :
  - [ ] `date` : au format `AAAA-MM-JJ HH-MM` - mais laisser l'heure sur 14h20 c'est historique
  - [ ] `title` : correspond à ce qui est affiché dans le menu de navigation, l'onglet du navigateur et le SEO. Bien **indiquer l'année** pour améliorer le référencement et en prévision d'une refonte du moteur de rendu.
- [ ] changer la date du titre principal (en début de contenu). Idem, **indiquer l'année**.

## Encourager les contributions

- [ ] informer l'équipe que la prochaine RDP a été initiée en publiant le lien de la PR sur [le canal `#revues-de-presse` de Slack](https://geotribu.slack.com/archives/C010DD7FMEX)
- [ ] tweeter le lien du fichier de la RDP. Voici ci-dessous un modèle dans lequel :

- remplacer `XXXXXXXXXX` par le lien vers le fichier de la GeoRDP dans la branche créée (par exemple : <https://github.com/geotribu/website/blob/rdp/2021-02-26/content/rdp/2021/rdp_2021-02-26.md?plain=1>)
- insérer cette image dans le tweet <https://cdn.geotribu.fr/img/internal/contribution/geotribu_contribuer_rdp_github_edit.png>

```txt
Ce vendredi c'est #GeoRDP !

💡 Une idée de news ? Une envie de parler de #carte ? d'outil #SIG ? de relayer un article, un tutoriel  sur la #géographie ou la #géomatique ?

C'est par ici 👉 XXXXXXXXXX 👈
(icône 🖍️)

Modèle de news ici : https://github.com/geotribu/website/blob/master/content/rdp/templates/template_rdp_news.md
```

Exemple de [tweet](https://twitter.com/geotribu/status/1364625815099613185) :

![tweet geordp](https://cdn.geotribu.fr/img/internal/contribution/geotribu_rdp_tweet_incitation.png)

----

## Check-list de publication

### Qualité

- [ ] les news sont bien réparties dans les bonnes sections
- [ ] les sections vides sont supprimées
- [ ] vérifier le rendu de la syntaxe markdown (cf. linter)
- [ ] chasse aux coquilles orthographiques et dyslexiques

### Images

- [ ] les images téléversées sur le CDN n'ont pas de caractère spécial dans leur nom de fichier (espace, accent, etc.) et n'excédent pas 1000px de largeur
- [ ] les images sont hébergées sur des sites sécurisés (HTTPS)
- [ ] chaque news a une vignette
- [ ] les images (sauf les vignettes) ont l'attribut `loading` défini sur `lazy` (cf. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading) et [guide material-mkdocs](https://squidfunk.github.io/mkdocs-material/reference/images/#image-lazy-loading))
- [ ] accessibilité : chaque image a un texte de remplacement (entre les crochets) et un titre lisible par les outils d'assistance. Bref, qui respecte la [syntaxe générale](https://static.geotribu.fr/contribuer/guides/image/#syntaxe-generale)

### SEO

- [ ] `image` pointe vers l'URL d'une des images de la revue de presse
- [ ] `description` contient les mots-clés et grandes lignes du contenu (par exemple, la reprise de l'intro)

----

## Publier

1. S'assurer que la branche soit à jour par rapport à la branche principale. Le cas échéant, utiliser le bouton `Update branch` en bas.
2. S'assurer que les éléments de la check-list ci-dessus soient tous remplis
3. Fusionner (_merge_) en utilisant un _merge commit_ ou un _rebase_, mais **surtout pas un squash**.

----

## Diffuser sur Twitter

Une fois le déploiement effectué (~ 5 minutes), diffuser a minima sur Twitter :

- avec le hashtag `#GeoRDP`, en citant les contributeur/ices avec leur éventuel compte
- si possible en intégrant quelques hastags des personne, organisations ou logiciels cités dans la revue de presse
- de préférence via le compte `@geotribu` en utilisant Tweetdeck.

2022-01-04 20:31 UTC, Guts commented
Ping @datagistips pour relecture ?

2022-01-04 21:13 UTC, igeofr commented
@Valexandre, est-que tu pourrais déplacer ton article dans le répertoire suivant website/content/articles/2022 pour permettre la prévisualisation ?

2022-01-04 22:04 UTC, Guts requested changes

2022-01-04 22:33 UTC, Guts commented
Gif optimisé

![image_couleur_distance](https://user-images.githubusercontent.com/1596222/148133096-3c3349ea-f9ff-4d7e-9b73-1a163ad0fda1.gif)

2022-01-06 05:21 UTC, datagistips reviewed
Quelques modifs : ajout de titres, formatages divers, caractère flèche

2022-01-06 05:21 UTC, datagistips commented on content/articles/2022/2022-01-04_quantifier_inegalites_traitement_meteo.md
> +    Article initialement paru sur ma [page Github personnelle](https://github.com/Valexandre/zones_meteo).
> ☝️ Article initialement paru sur ma [page Github personnelle](https://github.com/Valexandre/zones_meteo)

2022-01-06 05:21 UTC, datagistips commented on content/articles/2022/2022-01-04_quantifier_inegalites_traitement_meteo.md
> +- Source vidéo : Je me suis appuyé sur le bulletin météo de France 2 précédant le journal de 20h, tel qu'il a été posté sur la chaîne Youtube de Anaïs Baydemir (la fameuse dame de la météo).
- **Source vidéo** : Je me suis appuyé sur le bulletin météo de France 2 précédant le journal de 20h, tel qu'il a été posté sur la chaîne Youtube de Anaïs Baydemir (la fameuse dame de la météo).
- **Logiciel** : `ffmpeg` et `R`, avec les packages `imagemagick`, `tidyverse` et `colorscale`.

2022-01-06 05:21 UTC, datagistips commented on content/articles/2022/2022-01-04_quantifier_inegalites_traitement_meteo.md
> +1. Flux vidéo --> listes d'images
### 1. Flux vidéo → listes d'images

2022-01-06 05:21 UTC, datagistips commented on content/articles/2022/2022-01-04_quantifier_inegalites_traitement_meteo.md
> +2. Extraction des images avec une carte de France
### 2. Extraction des images avec une carte de France

2022-01-06 05:21 UTC, datagistips commented on content/articles/2022/2022-01-04_quantifier_inegalites_traitement_meteo.md
> +La quatrième et dernière représente les températures du lendemain après-midi.
- La première ligne représente les prévisions du lendemain matin.
- La seconde représente les prévisions du lendemain après-midi.
- La troisième représente les températures du lendemain matin.
- La quatrième et dernière représente les températures du lendemain après-midi.

2022-01-06 05:21 UTC, datagistips commented on content/articles/2022/2022-01-04_quantifier_inegalites_traitement_meteo.md
> +3. Découpage de la carte de métropole en zones
### 3. Découpage de la carte de métropole en zones

2022-01-06 05:21 UTC, datagistips commented on content/articles/2022/2022-01-04_quantifier_inegalites_traitement_meteo.md
> +4. Estimation de la couleur médiane par zone de la carte sans présentatrice (référence)
### 4. Estimation de la couleur médiane par zone de la carte sans présentatrice (référence)

2022-01-06 05:21 UTC, datagistips commented on content/articles/2022/2022-01-04_quantifier_inegalites_traitement_meteo.md
> +5. Estimation de la couleur médiane par zone de la carte pour chaque image relative à la séquence
### 5. Estimation de la couleur médiane par zone de la carte pour chaque image relative à la séquence

2022-01-06 05:21 UTC, datagistips commented on content/articles/2022/2022-01-04_quantifier_inegalites_traitement_meteo.md
> +6. Estimation de la distance moyenne par zone entre la référence et la séquence
### 6. Estimation de la distance moyenne par zone entre la référence et la séquence

2022-01-06 07:25 UTC, Guts commented on content/articles/2022/2022-01-04_quantifier_inegalites_traitement_meteo.md
> +    Article initialement paru sur ma [page Github personnelle](https://github.com/Valexandre/zones_meteo).
J'ai peut-être pas les yeux en face des trous mais je ne vois pas de différence.

Tu veux juste ajouter l'émoji ?
Si c'est bien cela, je trouve que l'admonition suffit non ?

2022-01-06 20:50 UTC, datagistips commented on content/articles/2022/2022-01-04_quantifier_inegalites_traitement_meteo.md
> +    Article initialement paru sur ma [page Github personnelle](https://github.com/Valexandre/zones_meteo).
Il y a l'émoji et un bloc de citation pour un autre formatage. Je trouvais l'émoji plus sympa que le !!!, mais comme vous sentez !

2022-01-06 21:55 UTC, Guts commented on content/articles/2022/2022-01-04_quantifier_inegalites_traitement_meteo.md
> +    Article initialement paru sur ma [page Github personnelle](https://github.com/Valexandre/zones_meteo).
Le triple `!`  est l'élément de syntaxe qui permet de marquer les admonitions HTML, que je trouve plus propre et plus sympa que le simple emoji et la syntaxe quote qu'on réserve généralement aux citations ou au sourcing : 

- cf la doc https://squidfunk.github.io/mkdocs-material/reference/admonitions/
- cf le rendu :

![image](https://user-images.githubusercontent.com/1596222/148457535-43d203c9-1a14-46e8-89bf-6cf93fb6f4e7.png)

2022-01-07 19:20 UTC, datagistips commented on content/articles/2022/2022-01-04_quantifier_inegalites_traitement_meteo.md
> +    Article initialement paru sur ma [page Github personnelle](https://github.com/Valexandre/zones_meteo).
Carrément  ! Je ne connaissais pas du tout. Merci pour l'astuce. J'apprends, j'apprends

2022-01-07 19:23 UTC, datagistips reviewed
Il y a une ligne en trop. Je viens de la supprimer.

2022-01-07 19:23 UTC, datagistips commented on content/articles/2022/2022-01-11_quantifier_inegalites_traitement_meteo.md
> +- Logiciel : ffmpeg et R, avec les packages imagemagick, tidyverse et colorscale.
```suggestion
```

2022-01-07 19:44 UTC, Guts commented on content/articles/2022/2022-01-04_quantifier_inegalites_traitement_meteo.md
> +    Article initialement paru sur ma [page Github personnelle](https://github.com/Valexandre/zones_meteo).
Trop cool de te voir par ici Mat :)

2022-01-09 17:50 UTC, Guts requested changes

2022-01-09 17:50 UTC, Guts commented on content/articles/2022/2022-01-11_quantifier_inegalites_traitement_meteo.md
> +[Consulter le code R :fontawesome-regular-file-code:](https://raw.githubusercontent.com/Valexandre/zones_meteo/main/code.R){: .md-button }
Lien vers le code mis en page plutôt que le brut

```suggestion
[Consulter le code R :fontawesome-regular-file-code:](https://github.com/Valexandre/zones_meteo/blob/main/code.R){: .md-button }
```

2022-01-09 18:01 UTC, Guts approved these changes

2022-01-10 14:12 UTC, merged