Proposition article -> 3DS : Impacts du déclassement du réseau routier national aux départements
geotribu/website pull request #504
Opened 2022-01-06 15:53 UTC by Michael-cd30

L'article vise à montrer comment, avec quelques requêtes PostgreSQL/PostGIS et la BDTopo, un département peut étudier l'impact qu'aurait/aura le déclassement des routes nationales à ses services.

Ce déclassement est normalement prévu par la loi 3DS.

2022-01-12 22:58 UTC, Jersig requested changes
@Michael-cd30 , merci pour ta contribution, je viens de faire une relecture, je te propose quelques reformulations pour faciliter la lecture.

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Les fonctionnaires territoriaux connaissent par coeur les 3 actes de la décentralisation, la loi 3DS sera peut-être considérée comme le quatrième acte.
A supprimer je pense

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +La loi ambitionne de [donner aux collectivités de nouvelles compétences](https://www.cnews.fr/france/2022-01-04/decentralisation-quest-ce-que-le-projet-3ds-qui-doit-etre-adopte-par-les-deputes). Il y
La loi ambitionne de [donner aux collectivités de nouvelles compétences](https://www.cnews.fr/france/2022-01-04/decentralisation-quest-ce-que-le-projet-3ds-qui-doit-etre-adopte-par-les-deputes), comprenant notamment le transfert d'une partie des routes nationales (RN) aux Départements, gestionnaires de la voirie départementale.

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +C'est dans ce cadre que le département du Gard m'a demandé d'analyser les impacts de ce transfert sur nos organisations.
C'est dans ce cadre que le département du Gard (CD30) a souhaité analyser l'impact pour son organisation de ce transfert de la voirie nationale vers la voirie départementale.

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +* Un client d'accès à la base de données type _pgAdmin_ ou _DBeaver_.
QGIS, non ?

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +J'utilise pour cette analyse la BDTopo de l'IGN et plus précisément la classe _troncon_de_route_ du thème _transport_ que j'ai importée dans une table nommée `bdtopo_troncon_de_route`.
J'utilise pour cette analyse la [BD Topo® de l'IGN](https://geoservices.ign.fr/bdtopo) et plus précisément la classe _troncon_de_route_ du thème _transport_ que j'ai importée dans une table nommée `bdtopo_troncon_de_route`.

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Je dispose des données France entière et je dois donc limiter l'analyse aux seuls tronçons du département.
Je dispose des données France entière et je dois donc limiter l'analyse aux seuls tronçons du département du Gard (30).

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Je pourrais pour cela faire une jointure géographique mais pour ne pas avoir à utiliser une autre table, je m'appuie sur les champs `insee_commune_droite` et `insee_commune_gauche`. Je regarde que l'
Afin ne pas avoir à réaliser une jointure géographique sur une autre table, je m'appuie sur les champs `insee_commune_droite` et `insee_commune_gauche`. Je vérifie que l'un ou l'autre matche avec le [COG](https://fr.wikipedia.org/wiki/Code_officiel_g%C3%A9ographique) d'une commune du Gard c'est à dire qu'il commence par 30.

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +## Les requêtes
## Les requêtes réalisées

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +### RN concernées
### Les Routes Nationales (RN) concernées

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Le premier besoin est simplement de connaître la liste des routes nationales concernées.
Le premier besoin est d'identifier la liste des routes nationales sur le territoire d'étude.

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Je cherche pour cela les numéros distincts des nationales présentes sur l'emprise d'étude grâce à la requête suivante :
Je cherche pour cela les numéros distincts des routes nationales présentes sur l'emprise d'étude grâce à la requête suivante :

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Si ces premiers indicateurs sont intéressants, ils ne permettent pas de bien mesurer les incidences pour le département.
Cette première liste des RN avec les longueurs associées est intéressante mais elle ne permet pas de mesurer précisément l'impact pour le Département du Gard.

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +En effet, les profils de routes sont variés et nécessitent un entretien adapté. Une 2 * 2 sera plus consommatrice de ressources qu'une simple chaussée.
En effet, les profils de routes nationales sont variés et nécessitent un entretien adapté. Une 2 * 2 voies sera plus consommatrice de ressources qu'une simple chaussée.

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +J'adapte ici la requête qui précède pour afficher les longueurs par nature et nombre de voies, ce qui donne :
J'adapte ici la requête qui précède pour afficher les longueurs par nature et nombre de voies, ce qui donne le résultat suivant :

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +La requête me permet d'obtenir les mesures suivantes :
La requête permet d'obtenir les mesures suivantes :

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +On a appris grâce au résultat qui précède que le département devrait récupérer l'équivalent d'environ 5 Km de ronds-points, mais combien de giratoires cela représente ?
Grâce à la requête précédente, on apprend qu'environ 5 Km de ronds-points pourraient être transférés au Département du Gard, il serait intéressant de connaître le nombre exact de giratoires que cela représente ?

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Il est possible de répondre à cette question en se focalisant sur les tronçons de nature _Rond-point_ et à l'aide de la fonction [`ST_ClusterIntersecting`](https://postgis.net/docs/ST_ClusterIntersec
Il est possible de répondre à cette question en se focalisant sur les tronçons de nature _Rond-point_ et à l'aide de la fonction [`ST_ClusterIntersecting`](https://postgis.net/docs/ST_ClusterIntersecting.html), qui retourne un tableau dont chaque cellule agrège les géométries qui s'intersectent.

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Il ne reste alors plus qu'à compter le nombre de cellules du tableau, ce qui donne :
Il reste ensuite à compter le nombre de cellules du tableau, ce qui donne la requête suivante :

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Il sera donc question pour le Gard d'assurer la gestion de 36 nouveaux giratoires ainsi répartis :
Le département du Gard pourra potentiellement assurer la gestion de 36 nouveaux giratoires ainsi répartis :

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Les ouvrages d'art nécessitent une attention particulière. Il est donc utile de savoir combien d'ouvrages se trouvent sur l'actuel réseau national.
Les ouvrages d'art nécessitent un entretien suivi et une organisation de service spécifique. Il est donc utile de le nombre d'ouvrages d'art se trouvant actuellement sur le réseau routier national.

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Ma première idée était de réutiliser la fonction [`ST_ClusterIntersecting`](https://postgis.net/docs/ST_ClusterIntersecting.html) mais celle-ci présente une limite pour ce cas d'usage.
A supprimer.

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Lorsqu'on regarde en détail, on remarque que plusieurs ouvrages supportent 2 chaussées séparées et donc 2 lignes distinctes dans la BDTopo.
En visualisant les données, on remarque que plusieurs ouvrages supportent deux  chaussées séparées et donc deux géométries distinctes dans la BD Topo®.

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Pour contourner ce cas, j'utilise plutôt la fonction [`ST_ClusterWithin`](https://postgis.net/docs/ST_ClusterWithin.html).
J'utilise  la fonction [`ST_ClusterWithin`](https://postgis.net/docs/ST_ClusterWithin.html) qui permet d'agréger des géométries dès lors qu'elles sont à moins d'une distance donnée.

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Son fonctionnement est équivalent mais les géométries sont cette fois agrégées dès lors qu'elles sont à moins d'une distance donnée.
A supprimer

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +J'ai fixé de façon empirique cette distance à 25 mêtres dans les requêtes qui suivent. La mesure doit être suffisante pour raccrocher les chaussées séparées mais pas trop importante pour ne pas assoc
J'ai fixé de façon empirique cette distance à 25 mètres dans les requêtes qui suivent. La distance utilisée doit être suffisante pour raccrocher les deux géométries représentant les chaussées séparées mais pas trop importante afin d'éviter d'associer à tord deux ouvrages qui seraient proches.

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Requête de comptage des ponts :
Requête permettant de compter les ponts :

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Requête de comptage des tunnels :
Requête permettant de compter les ponts :

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Plus que les distances, il est surtout intéressant de mesurer l'évolution du linéaire que cela représente.
Plus que les distances, il est surtout intéressant de mesurer l'évolution du linéaire que cela représente par rapport à l'actuelle voirie départementale gérée par le Département du Gard.

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +En conclusion, on peut voir qu'il est assez rapide de produire quelques indicateurs routiers à l'aide de la BDTopo IGN et grâce au couple PostgreSQL/PostGIS.
En conclusion, le couple PostgreSQL/PostGIS nous a permis d'évaluer assez rapidement l'impact de la loi 3DS en mesurant quelques indicateurs routiers à partir des données présentes dans la BD Topo® de l'IGN.

2022-01-12 22:58 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Les ratios obtenus avec la dernière requête peuvent être appliqués aux ressources financières et humaines actuelles pour en déduire les besoins futurs.
Il est désormais possible d'utiliser les ratios obtenus avec la dernière requête pour mesurer précisément l'impact financier et les besoins RH associés au transfert de la voirie nationale vers les départements.

2022-01-12 23:21 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +# 3DS : Impacts du déclassement du réseau routier national aux départements
Pour être cohérent avec la proposition qui suit, ne faudrait-il pas mettre le même titre soit :
3DS : Mesurer l'impact du transfert des routes du réseau national aux Départements avec PostgreSQL/PostGIS

2022-01-12 23:21 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +title: "3DS : Impacts du déclassement du réseau routier national aux départements"
ok

2022-01-12 23:21 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Les fonctionnaires territoriaux connaissent par coeur les 3 actes de la décentralisation, la loi 3DS sera peut-être considérée comme le quatrième acte.
ok

2022-01-12 23:22 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +La loi ambitionne de [donner aux collectivités de nouvelles compétences](https://www.cnews.fr/france/2022-01-04/decentralisation-quest-ce-que-le-projet-3ds-qui-doit-etre-adopte-par-les-deputes). Il y
ok

2022-01-12 23:23 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +C'est dans ce cadre que le département du Gard m'a demandé d'analyser les impacts de ce transfert sur nos organisations.
Je n'aime pas et n'utilise pas la notation CDXX qui fait référence aux élus et non à l'administration.

2022-01-12 23:25 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Requête de comptage des tunnels :
Ok

2022-01-12 23:25 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Plus que les distances, il est surtout intéressant de mesurer l'évolution du linéaire que cela représente.
ok

2022-01-12 23:25 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +En conclusion, on peut voir qu'il est assez rapide de produire quelques indicateurs routiers à l'aide de la BDTopo IGN et grâce au couple PostgreSQL/PostGIS.
ok

2022-01-12 23:26 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Les ratios obtenus avec la dernière requête peuvent être appliqués aux ressources financières et humaines actuelles pour en déduire les besoins futurs.
ok (mais peut-être sans le mot précisément)

2022-01-12 23:31 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Ce que j'apprécie avec ce type d'analyse c'est que d'une donnée géographique sont déduits plusieurs indicateurs...preuve que la géomatique ne se limite pas à la cartographie.
Je travaille pour la direction métier en charge des routes du coup je reformulerai un peu.
Pas de service SIG à la DSI.

2022-01-13 12:42 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +* Un client d'accès à la base de données type _pgAdmin_ ou _DBeaver_.
Non, en règle générale je n'utilise QGis que pour visualiser, pas pour les analyses.

2022-01-13 12:50 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Je dispose des données France entière et je dois donc limiter l'analyse aux seuls tronçons du département.
ok

2022-01-13 12:54 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Je pourrais pour cela faire une jointure géographique mais pour ne pas avoir à utiliser une autre table, je m'appuie sur les champs `insee_commune_droite` et `insee_commune_gauche`. Je regarde que l'
C'est effectivement mieux dit ;o)

2022-01-13 12:54 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +## Les requêtes
ok

2022-01-13 12:55 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +### RN concernées
ok

2022-01-13 12:55 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Le premier besoin est simplement de connaître la liste des routes nationales concernées.
ok

2022-01-13 12:56 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Je cherche pour cela les numéros distincts des nationales présentes sur l'emprise d'étude grâce à la requête suivante :
ok

2022-01-13 12:57 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Si ces premiers indicateurs sont intéressants, ils ne permettent pas de bien mesurer les incidences pour le département.
ok

2022-01-13 12:58 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +En effet, les profils de routes sont variés et nécessitent un entretien adapté. Une 2 * 2 sera plus consommatrice de ressources qu'une simple chaussée.
ok

2022-01-13 13:00 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +J'adapte ici la requête qui précède pour afficher les longueurs par nature et nombre de voies, ce qui donne :
J'ai remplacé "résultat" pas "syntaxe" pour qu'il n'y ait pas d'ambiguïté avec le résultat d'exécution de la requête.

2022-01-13 13:01 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +On a appris grâce au résultat qui précède que le département devrait récupérer l'équivalent d'environ 5 Km de ronds-points, mais combien de giratoires cela représente ?
ok

2022-01-13 13:02 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Il est possible de répondre à cette question en se focalisant sur les tronçons de nature _Rond-point_ et à l'aide de la fonction [`ST_ClusterIntersecting`](https://postgis.net/docs/ST_ClusterIntersec
ok

2022-01-13 13:03 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Il ne reste alors plus qu'à compter le nombre de cellules du tableau, ce qui donne :
ok

2022-01-13 13:06 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Lorsqu'on regarde en détail, on remarque que plusieurs ouvrages supportent 2 chaussées séparées et donc 2 lignes distinctes dans la BDTopo.
ok

2022-01-13 13:07 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Ma première idée était de réutiliser la fonction [`ST_ClusterIntersecting`](https://postgis.net/docs/ST_ClusterIntersecting.html) mais celle-ci présente une limite pour ce cas d'usage.
Adapter pour que la suite du texte ("Pour contourner ce cas...") reste cohérente.

Ca donne :
Ici la fonction [`ST_ClusterIntersecting`](https://postgis.net/docs/ST_ClusterIntersecting.html) ne convient pas car en visualisant les données, on remarque que plusieurs ouvrages supportent deux chaussées séparées et donc deux géométries distinctes dans la BD Topo®.

2022-01-13 13:10 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Pour contourner ce cas, j'utilise plutôt la fonction [`ST_ClusterWithin`](https://postgis.net/docs/ST_ClusterWithin.html).
ok

2022-01-13 13:10 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Son fonctionnement est équivalent mais les géométries sont cette fois agrégées dès lors qu'elles sont à moins d'une distance donnée.
Modifié/adapté au regard des deux remarques qui précèdent.

2022-01-13 13:11 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +J'ai fixé de façon empirique cette distance à 25 mêtres dans les requêtes qui suivent. La mesure doit être suffisante pour raccrocher les chaussées séparées mais pas trop importante pour ne pas assoc
bien mieux merci

2022-01-13 13:12 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Requête de comptage des tunnels :
ok

2022-01-13 13:18 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Ce que j'apprécie avec ce type d'analyse c'est que d'une donnée géographique sont déduits plusieurs indicateurs...preuve que la géomatique ne se limite pas à la cartographie.
Ce qui donne :
J'apprécie ce type d'analyse, qui permet à partir de quelques requêtes sur un jeu de donnée géographique de sortir une analyse assez fine qui pourra aider la direction des routes, à laquelle je suis rattaché, et les élus à la prise de décision. Cela montre par ailleurs que la géomatique ne se limite pas à la cartographie.

2022-01-13 13:18 UTC, Jersig commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +* Un client d'accès à la base de données type _pgAdmin_ ou _DBeaver_.
J'entends, mais l'objet de l'article est d'exposer une méthode reproductible à travers un ensemble de requête SQL, un lecteur pourrait très bien reprendre l'ensemble de tes requêtes directement dans l'éditeur SQL de QGIS, le résultat serait identique, d'où cette proposition, mais pas de souci pour ne pas le mentionner.

2022-01-13 17:06 UTC, Guts commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +## Données sources
Barre horizontale entre parties de niveau 2 (cf template et cohérence autres contenus)

```suggestion
----

## Données sources
```

2022-01-13 17:06 UTC, Guts commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +
Ajout bouton commentaires (cohérence contenus)

```suggestion

[Commenter cet article :fontawesome-solid-comments:](#__comments){: .md-button }
{: align=middle }

```

2022-01-13 17:06 UTC, Guts commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +## Les requêtes réalisées
Barre horizontale entre parties de niveau 2 (cf template et cohérence autres contenus)

```suggestion
----

## Les requêtes réalisées
```

2022-01-13 17:06 UTC, Guts commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +## Bilan
Barre horizontale entre parties de niveau 2 (cf template et cohérence autres contenus)

```suggestion
----

## Bilan
```

2022-01-13 17:06 UTC, Guts commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +## Auteur
Barre horizontale entre parties de niveau 2 (cf template et cohérence autres contenus)

```suggestion
----

## Auteur
```

2022-01-13 18:36 UTC, igeofr commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +    - Voirie
```suggestion
     - loi 3DS
     - PostGIS
     - PostgreSQL
     - route
     - SQL
     - voirie
```

2022-01-13 18:40 UTC, igeofr commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Let's go !
```suggestion
Let's go !

[Commenter cet article :fontawesome-solid-comments:](#__comments){: .md-button }
{: align=middle }

----
```

2022-01-13 18:42 UTC, igeofr commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +* Une base de données PostgreSQL/PostGIS.
```suggestion
* Une base de données [PostgreSQL](https://www.postgresql.org)/[PostGIS](https://postgis.net).
```

2022-01-13 18:42 UTC, igeofr commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +* La BD Topo® de l'IGN sur l'emprise d'étude.
```suggestion
* La [BDTopo](https://geoservices.ign.fr/bdtopo) sur l'emprise d'étude.
```

2022-01-13 18:43 UTC, igeofr commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +
```suggestion

![icône route 66](https://cdn.geotribu.fr/img/logos-icones/divers/route66.png "icône route 66]"){: .img-rdp-news-thumb }

```

2022-01-13 18:44 UTC, igeofr commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +
Proposition d'un icône pour marquer la conclusion.

2022-01-13 18:45 UTC, igeofr commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +* La BD Topo® de l'IGN sur l'emprise d'étude.
Ajout du lien

2022-01-13 18:45 UTC, igeofr commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +* Une base de données PostgreSQL/PostGIS.
Ajout du lien

2022-01-13 20:03 UTC, Michael-cd30 commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +* La BD Topo® de l'IGN sur l'emprise d'étude.
Ok, mais il y est aussi plus bas.

2022-01-13 20:41 UTC, merged

2022-01-14 18:14 UTC, datagistips reviewed
quelques petits réajustements

2022-01-14 18:14 UTC, datagistips commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Et non, je ne vais pas vous parler dans cet article de la célèbre console Nintento (11 ans déjà) mais de la loi relative à la Différenciation, la Décentralisation, la Déconcentration et portant diver
```suggestion
Et non, je ne vais pas vous parler dans cet article de la célèbre console Nintendo (11 ans déjà) mais de la loi relative à la Différenciation, la Décentralisation, la Déconcentration et portant diverses mesures de Simplification de l'action publique locale.
```

2022-01-14 18:14 UTC, datagistips commented on content/articles/2022/2022-01-14_etude_impacts_loi_3ds_voirie.md
> +Enfin, je trie le résultat dans l'ordre décroissant des valeurs ce qui donne la requête suivante :
```suggestion
Enfin, je trie le résultat dans l'ordre décroissant des valeurs, ce qui donne la requête suivante :
```

2022-01-14 19:18 UTC, Guts commented
> quelques petits réajustements

Salut @datagistips,

Merci pour ton oeil aiguisé sur ces coquilles passées à la trappe de multiples relectures, mais une fois la branche mergée, elle est supprimée. Pour corriger un contenu déjà publié, il faut créer une branche + PR. Le plus simple est d'utiliser l'icône de crayon (voir https://static.geotribu.fr/contribuer/edit/fix_content_from_website/).