Article/qgis dashboard cd14
geotribu/website pull request #531
Opened 2022-02-04 12:45 UTC by Theogron

Article de présentation dashboard

2022-02-04 12:49 UTC, Guts requested changes

2022-02-04 12:49 UTC, Guts commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +title: "Dashboard QGIS : Suivi des indicateurs adresse du Département du Calvados"
```suggestion
title: "Dashboard QGIS : suivi des indicateurs adresse du Département du Calvados"
```

2022-02-04 12:50 UTC, Theogron commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +title: "Dashboard QGIS : Suivi des indicateurs adresse du Département du Calvados"
non

2022-02-04 12:56 UTC, Guts requested changes

2022-02-04 12:56 UTC, Guts commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +
````suggestion
```python
aggregate(layer:= 'Infos Communes', aggregate:='sum', expression:=pt_total)
```
````

2022-02-04 19:14 UTC, Guts requested changes

2022-02-04 19:14 UTC, Guts commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +date: "2022-01-16 10:20"
```suggestion
date: "2022-02-11 10:20"
```

2022-02-04 19:14 UTC, Guts commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +:calendar: Date de publication initiale : 16 janvier 2022
```suggestion
:calendar: Date de publication initiale : 11 février 2022
```

2022-02-07 20:16 UTC, aurelienchaumet requested changes
Salut Théo !
Je viens de faire une première passe sur ton article uniquement sur les aspects purement de structure markdown. Je le lis et je te dis si j'ai des remarques sur la structuration ou le contenu d'ici demain

2022-02-07 20:16 UTC, aurelienchaumet commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +image: ""
Choisir une image à mettre pour le partage

2022-02-07 20:16 UTC, aurelienchaumet commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +
Pas mal d’espaces en trop :  
- Entre chaque paragraphe, un seul espace suffit  
- De même, entre un paragraphe et un titre  
 
Je te les fais pas tous un par un, mais j'imagine que t'as compris le truc 😉

2022-02-07 20:16 UTC, aurelienchaumet commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +Sur le logiciel QGIS aucun module additionnel (plugin) ne propose à ce jour de solution complète de dashboarding. Nous nous nous sommes donc appuyer sur une méthodologie publiée sur le site https://p
Sur les liens url direct, il faut les enrober par des crochets <blablabla.com> 
```suggestion
Sur le logiciel QGIS aucun module additionnel (plugin) ne propose à ce jour de solution complète de dashboarding. Nous nous nous sommes donc appuyer sur une méthodologie publiée sur le site <https://plugins.QGIS.org/geopackages/5/> (Sutton, 2020) , afin de développer un « Dashboard » par manipulation des étiquettes de couches QGIS.
```

2022-02-07 20:16 UTC, aurelienchaumet commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +```sql
Il faut également mettre un espace entre un paragraphe et les blocs de codes

2022-02-08 12:08 UTC, Theogron commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +
ok je reprend ça. Merci :)

2022-02-08 12:09 UTC, Theogron commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +image: ""
ok

2022-02-08 12:23 UTC, Theogron commented
> Merci pour les remarques Aurelien!

2022-02-08 13:54 UTC, aurelienchaumet approved these changes

2022-02-08 14:18 UTC, aurelienchaumet requested changes
J'ai fait un petit commit dans mon coin juste sur quelques coquilles de rédaction.
Et je te laisse quelques remarques et/ou corrections à faire dans cette review.
En tout cas, globalement c'est un bel article c'est très chouette :+1:

2022-02-08 14:18 UTC, aurelienchaumet commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +L’adressage est obligatoire pour les communes de plus de 2000 habitants et est très fortement conseillé aux plus petites communes.
L’adresse va maintenant être une compétence obligatoire pour l’ensemble des communes cf loi 3DS.
Est-ce qu'il ne faudrait pas (légèrement) reformuler la phrase ou bien au moins une astérisque ligne 31 ?

2022-02-08 14:18 UTC, aurelienchaumet commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +Afin d’accompagner les communes dans cette démarche, le Département du Calvados met à disposition des communes une application cartographique de gestion des adresses <https://atlas-calvados.fr> (base
Quand on clique sur le lien, on arrive sur le portail des applis.
Est-ce bien ce à quoi tu veux mener le lecteur, ou plutôt à l'application base adresse ?

2022-02-08 14:18 UTC, aurelienchaumet commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +![QGIS label](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/qgis_dashboard_calvados/selection_commune_dashboard.gif "Table attributaire Dashboard partie 2")
Le gif est top pour montrer le résultat et arrive à point nommé !
En revanche, est-ce vraiment opportun sur un site autour des outils libres d'utiliser un outil comme screenpresso avec la grosse pub à la fin ?
Je pense que tu peux soit utiliser un autre outil de capture comme LiceCap par exemple ou bien couper le gif avant la "pub" :wink:

2022-02-08 14:18 UTC, aurelienchaumet commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +![QGIS label](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/qgis_dashboard_calvados/2_polygon_dashboard.png "QGIS - Création polygone Dashboard")
Je ne suis pas sûr de bien comprendre la capture...
On au début de la constitution d'une couche dashboard et on voit déjà apparaître des éléments de dashboard.
C'est moi qui rate un truc ?

2022-02-08 14:18 UTC, aurelienchaumet commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +
Dernière remarque de curiosité personnelle : t'as essayé d'utiliser le plugin en développement de Luis Eduardo Perez ?
https://github.com/luisCartoGeo/QGIS_Dashboard

2022-02-08 14:18 UTC, aurelienchaumet commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +
Je trouve que le début de l'article fait un poil "austère".
Est-ce qu'il serait opportun d'ajouter l'image que tu utilises dans le front matter par ici ?
Qu'est-ce que t'en penses ?

2022-02-09 10:14 UTC, Theogron commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +![QGIS label](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/qgis_dashboard_calvados/2_polygon_dashboard.png "QGIS - Création polygone Dashboard")
Oui, ce n'est pas pertinent, je vais changer l'image

2022-02-09 10:15 UTC, Theogron commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +
Le plugin ne répondait pas à notre besoin à l'époque

2022-02-09 10:17 UTC, Theogron commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +![QGIS label](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/qgis_dashboard_calvados/selection_commune_dashboard.gif "Table attributaire Dashboard partie 2")
J'aime bien screen presso :P 
mais c'est vrai que ça prend une partie importante du gif. Je vais couper cette partie

2022-02-09 10:17 UTC, Theogron commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +
Je vais tester pour voir

2022-02-09 10:17 UTC, Theogron commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +Afin d’accompagner les communes dans cette démarche, le Département du Calvados met à disposition des communes une application cartographique de gestion des adresses <https://atlas-calvados.fr> (base
oui c'est vrai

2022-02-10 14:37 UTC, aurelienchaumet commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +L’adressage est obligatoire pour les communes de plus de 2000 habitants et est très fortement conseillé aux plus petites communes.
Je chipote sans doute un peu, mais est-ce que ce serait mieux direct comme ça ?

```suggestion
L’adressage est obligatoire pour les communes de plus de 2000 habitants et le deviendra pour l'ensemble des communes [avec l'entrée en vigueur prochaine de la loi 3DS](https://www.legifrance.gouv.fr/dossierlegislatif/JORFDOLE000043496065/).

2022-02-10 14:38 UTC, aurelienchaumet commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +
Cool merci pour l'info :+1:

2022-02-10 14:47 UTC, aurelienchaumet requested changes
Peut-être la dernière review... :smile: 
Encore un ou 2 petits trucs rien de bien méchant, perso je le trouve très bien ton article, merci pour la contrib' :+1:

2022-02-10 14:47 UTC, aurelienchaumet commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +Afin d’accompagner les communes dans cette démarche, le Département du Calvados met à disposition des communes une application cartographique de gestion des adresses <https://atlas.calvados.fr/index.
Tu peux aussi mettre un lien derrière le texte, je trouve que ça fait un peu plus "propre"

```suggestion
Afin d’accompagner les communes dans cette démarche, le Département du Calvados met à disposition des communes [une application cartographique de gestion des adresses](https://atlas.calvados.fr/index.php/view/map/?repository=04&project=52_bac_14) (base adresse du calvados), permettant de consulter la BAN, dénommer des voie, créer des nouvelles adresses et modifier ou supprimer des adresses existantes. Cette application a été développée à partir des logiciels open sources Lizmap/PostGIS/QGIS serveur.

2022-02-10 14:47 UTC, aurelienchaumet commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +Sélectionner ‘Etiquettes simples’ dans l’onglet Étiquettes. Dans le sous onglet valeur, faites une sélection par expression et inscrivez le code suivant : eval( "label_expression")
```suggestion
Sélectionner ‘Etiquettes simples’ dans l’onglet Étiquettes. Dans le sous onglet valeur, faites une sélection par expression et inscrivez le code suivant : ***eval( "label_expression")***

2022-02-10 14:47 UTC, aurelienchaumet commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +Puis indiquer dans le champs label expression l’expression qui s’affichera dans la première fenêtre dashboard, ici, simplement le titre *****'nbr pt total'*****
Pourquoi t'as mis 5 * ?

2022-02-10 16:20 UTC, Guts commented on content/articles/2022/2022-02-11_dashboard_qgis_adresse_CD14.md
> +Sélectionner ‘Etiquettes simples’ dans l’onglet Étiquettes. Dans le sous onglet valeur, faites une sélection par expression et inscrivez le code suivant : eval( "label_expression")
Pour ce qui est code, on utilise plutôt les backtick : `eval( "label_expression")`

2022-02-11 14:06 UTC, aurelienchaumet approved these changes

2022-02-11 16:18 UTC, Guts commented
L'erreur est signalée https://github.com/squidfunk/mkdocs-material/issues/3572 : en gros, les icônes ont changé...

2022-02-11 16:33 UTC, Guts commented
Corrigée dans #539

2022-02-11 17:09 UTC, merged