Proposition d'article pour GeoTribu
geotribu/website pull request #550
Opened 2022-02-28 10:57 UTC by stephyritz

Salut !

J'avais discuté il y a quelques mois avec Julien sur la possibilité d'écrire un article pour GeoTribu. Je vous le propose ici.
J'ai essayé de suivre au mieux les différentes consignes sur la forme et la méthode de soumission d'un article.

J'espère que le contenu vous semblera pertinent. Si ce n'est pas le cas, ce n'est pas grave, on est pas obligé de publier ; )

J'aurais bien voulu rajouter plus d'illustrations, notamment du côté de QGIS mais malheuresement je n'ai plus accès au projet.. J'ai changé de boulot depuis et je n'ai pas fait les backups nécessaires avant de partir. C'est un peu dommage mais l'essentiel à partager de mon point de vue, c'est les scripts sql.

Je reste à dispo pour faire des modifs ou autres concernant ce partage.

A+
Stéphane

2022-02-28 11:12 UTC, Guts requested changes

2022-02-28 11:12 UTC, Guts commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +ltitle: "Eclairage Public - Gestion et visualisation du réseau avec QGIS et Postgresql/Postgis"
```suggestion
title: "Éclairage Public - Gestion et visualisation du réseau avec QGIS et PostGIS"

```

2022-02-28 11:20 UTC, Guts requested changes

2022-02-28 11:20 UTC, Guts commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +authors: ["Stéphane RITZENTHALER"]
```suggestion
authors:
    - Stéphane RITZENTHALER

```

2022-02-28 11:20 UTC, Guts commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +categories: ["article"]
```suggestion
categories:
    - article

```

2022-02-28 11:20 UTC, Guts commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +tags: "Eclairage,PostgreSQL,PostGIS,QGIS,sql"
```suggestion
tags:
    - éclairage public
    - PostGIS
    - PostgreSQL
    - QGIS
    - SQL
```

2022-02-28 11:20 UTC, Guts commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +:calendar: Date de publication initiale : 24 septembre 2021
Je propose de publier mardi 8 mars histoire de se donner le temps de relire et échanger.

```suggestion
:calendar: Date de publication initiale : 8 mars 2022

```

2022-02-28 11:20 UTC, Guts commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +**Mots-clés :** Eclairage | PostgresSQL | PostGIS | Collectivité| QGIS
Désormais inutiles.

```suggestion

```

2022-02-28 11:20 UTC, Guts commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> + ## Conclusion
Espace en trop

```suggestion
## Conclusion

```

2022-02-28 11:20 UTC, Guts commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +--8<-- "content/team/mbos.md"
Tu pointes sur le bloc auteur de Mathieu Bossaert.
Pour ajouter le tien, c'est par ici https://static.geotribu.fr/contribuer/guides/authoring/#bloc-auteur

2022-02-28 16:26 UTC, Guts requested changes

2022-02-28 16:26 UTC, Guts commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +Dans une démarche d'analyse de faisabilité, nous avons monté un projet pour étudier comment le duo Postgres/Postgis et QGIS pourrait répondre à ces enjeux.
Attention à bien écrire PostgreSQL et PostGIS (en respectant la casse officielle)

2022-02-28 16:26 UTC, Guts commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +* Permettre la gestion des stocks et anticiper sur les commandes de matériel
Il faut ajouter un saut de ligne avant une liste à puces (cf https://static.geotribu.fr/contribuer/guides/markdown_quality/#sauts-de-ligne-et-lignes-vides)

```suggestion
Les besoins identifiés, par ordre de priorité, étaient les suivants :

* Visualiser le réseau et les objets le composant sur un fond de plan
* Offrir la possibilité d'éditer des cartes dans le contexte de DT-DICT
* Proposer un réseau topographiquement correct où les objets sont en relations les uns avec les autres
* Faciliter les interventions sur le réseau (historique, identifications des objets sur lesquels intervenir, conséquence de l'intervention sur le réseau, etc...)
* Permettre la gestion des stocks et anticiper sur les commandes de matériel

```

2022-03-03 23:52 UTC, ThomasG77 commented
Pour info, https://georezo.net/forum/viewtopic.php?pid=350670

J'ai failli répondre en mentionnant la page de preview et la PR mais ne voulant pas communiquer sur de l'officieux même public, je me suis retenu.
Cela témoigne d'un intérêt de la part d'autres acteurs pour mutualiser. Je laisse le soin de voir comment répondre dans le fil Georezo mentionné

2022-03-04 06:12 UTC, aurelienchaumet commented
> Pour info, https://georezo.net/forum/viewtopic.php?pid=350670
> 
> J'ai failli répondre en mentionnant la page de preview et la PR mais ne voulant pas communiquer sur de l'officieux même public, je me suis retenu. Cela témoigne d'un intérêt de la part d'autres acteurs pour mutualiser. Je laisse le soin de voir comment répondre dans le fil Georezo mentionné

Bien vu @ThomasG77 pour la veille croisée 😉  !
On va regarder tout ça, en tout cas merci !

Perso, je vois pas trop où est le problème de communiquer sur un éventuel article en préparation, qui de plus, comme tu le dis bien, est public 😄

2022-03-04 06:42 UTC, aurelienchaumet requested changes
Salut Stéphane !
Pour commencer, merci pour ton article et pour 2 raisons :
- je ne connaissais pas la thématique, et franchement c'est génial d'avoir un premier niveau d'infos là-dessus
- on sent rapidement la richesse du modèle de données... 😃  et l'intérêt des scripts évidemment

Sur la review en elle-même, je te laisse regarder les quelques modifs que je te suggère, c'est principalement des petits ajouts, hormis pour la 1ère partie introductive qu'il manque (à mon sens).
Et quand t'auras vu cette review, je referai une pass sur les petites coquilles rédactionnelles qui traînent rien de méchant 😉 
Je me suis demandé à quel moment t'allais parler d'utilisation en mobilité, notamment pour les interventions. Le cas d'usage ne s'est pas présenté ?
Pour finir, c'est vrai qu'il manque peut-être 1 ou 2 illustrations pour le rendre un peu plus "sexy", à réfléchir si tu peux coller quelque chose. T'as plus du tout accès aux projets QGIS ?

En tout cas merci, beau boulot de contribution !!! 👏

2022-03-04 06:42 UTC, aurelienchaumet commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +La gestion de réseau ne peut que se faire de manière efficace si elle repose sur une base de données relationnelles solide. Le premier défi de cette étude fut de trouver la formule la plus adéquate p
```suggestion
     La gestion de réseau ne peut se faire de manière efficace que si elle repose sur une base de données 
     relationnelles solide. Le premier défi de cette étude fut de trouver la formule la plus adéquate pour nos besoins.
```
C'est une broutille, mais ça me paraissait plus fluide dans ce sens-là ?

2022-03-04 06:42 UTC, aurelienchaumet commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +
Je trouve qu'il manque une partie introductive pour contextualiser le besoin.
Le début de l'article arrive un peu comme un cheveu sur la soupe.
- A l'époque, pour qui travaillais-tu ?
- Tu commences directement par dire que "la solution précédente a affiché ses limites" j'imagine que tu ne veux pas la citer, mais peut-être ajouter un peu ce que vous faisiez à l'époque avec
Et peut-être d'autres éléments en fonction de ce que tu penses pertinents

2022-03-04 06:42 UTC, aurelienchaumet commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +Dans le cadre de cette étude, nous avons opté pour la création de 2 projets qgis distincts en fonction du type d'utilisateurs. Le premier projet est à destination des utilisateurs qui ne souhaitent q
Au vu de tes explications en intro de la PR, j'imagine que tu n'as plus la main sur les projets GQIS ?

2022-03-04 06:42 UTC, aurelienchaumet commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +Le POC s'est arrêté à ce stade car la preuve a été faite que le duo QGIS/Postgresql pouvait bien répondre aux principaux besoins mentionnés. La suite des développements seraient déjà orientés vers un
Peut-être bien de renvoyer vers de la ressource là-dessus ? J'ai mis celui que j'ai trouvé rapidos, mais s'il y a qqch de plus explicite/visuel qui existe ne pas hésiter !

```suggestion
Le POC s'est arrêté à ce stade car la preuve a été faite que le duo QGIS/Postgresql pouvait bien répondre aux principaux besoins mentionnés. La suite des développements seraient déjà orientés vers une mise en production opérationnelle. Logiquement, il faudrai poursuivre en améliorant l'ergonomie des formulaires [via QT par exemple.](https://docs.qgis.org/3.16/fr/docs/training_manual/create_vector_data/forms.html#hard-fa-creating-a-new-form) De même, des développements supplémentaires pourraient être fait pour créer des boutons dédiés aux actions d'édition réalisées le plus couramment, pourquoi pas un plugin spécifique à la gestion de l'éclairage public...
```

2022-03-04 06:42 UTC, aurelienchaumet commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +[Lien vers le Github du projet](https://github.com/stephyritz/ep_structure)
@Guts est-ce que ce serait pertinent de mettre un bouton ici ?

2022-03-04 06:59 UTC, Guts commented
> J'ai failli répondre en mentionnant la page de preview et la PR mais ne voulant pas communiquer sur de l'officieux même public, je me suis retenu.

> Perso, je vois pas trop où est le problème de communiquer sur un éventuel article en préparation, qui de plus, comme tu le dis bien, est public 😄

Je rejoins @ThomasG77 (merci pour le relai) : les preview sont là pour accompagner le travail de rédaction et ne doivent pas être relayées avant la publication, puisque justement l'auteur/e doit pouvoir maitriser sa "communication" sur son contenu et être certain de sa diffusion seulement quand il l'a validé. Je réfléchis d'ailleurs à les rendre uniquement accessibles aux personnes participant à la MR (committers et reviewers).

2022-03-04 07:12 UTC, Guts commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +[Lien vers le Github du projet](https://github.com/stephyritz/ep_structure)
Oui, carrément.

2022-03-04 07:14 UTC, Guts commented
> Pour finir, c'est vrai qu'il manque peut-être 1 ou 2 illustrations pour le rendre un peu plus "sexy", à réfléchir si tu peux coller quelque chose. T'as plus du tout accès aux projets QGIS ?

@stephyritz  je rejoins @aurelienchaumet, ce serait plus sympa et digeste avec des illustrations même génériques (des photos d'éclairage public ou que sais-je). Attention aux crédits quand même 😉. Tu peux regarder du côté de Reshot dont le lien est là https://static.geotribu.fr/contribuer/guides/image/#ressources

2022-03-04 08:31 UTC, aurelienchaumet commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +[Lien vers le Github du projet](https://github.com/stephyritz/ep_structure)
@stephyritz tu peux remplacer la ligne 101 par
[Lien vers le Github du projet :fontawesome-solid-comments:](https://github.com/stephyritz/ep_structure){: .md-button }
{: align=middle }

2022-03-04 08:54 UTC, Guts commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +[Lien vers le Github du projet](https://github.com/stephyritz/ep_structure)
Ou pas, vue l'icône 😆 !

```suggestion
[Lien vers le Github du projet :fontawesome-brands-github:](https://github.com/stephyritz/ep_structure/){: .md-button }
{: align=middle }

```

2022-03-07 10:19 UTC, stephyritz commented
Salut Aurélien,
Merci pour ton retour encourageant et tes améliorations ! Tu as raison, je vais un peu mieux introduire le sujet ! Je vais voir si je trouve quelques illustrations.. Non malheureusement, je n'ai plus accès aux projets QGIS.. Par contre, j'avais également utilisé les "fonctions avancées" de formulaire dans un autre projet (en archéologie), qui pourrait peut-être faire l'objet d'un futur article ?! @ThomasG77 , merci pour la réf! Drôle de coïncidence, c'est marrant!

2022-03-07 10:23 UTC, stephyritz commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +
Ok, je vais faire une proposition ! Pour info, je travaillais à l'époque pour la communauté de communes Thann-Cernay (68) et la solution précédente était un progiciel développé par un auto-entrepreneur mais qu'il a arrêté de maintenir. Du coup, l'accès à l'outil a tout simplement été coupé du jour au lendemain pour des "raisons de sécurité informatique" dont je n'ai pas compris les tenants et aboutissants. Bref, ensuite c'était retour à la gestion par les bons vieux échanges de mails et téléphonique ET connaissance/expérience/mémoire du gestionnaire du réseau ; ).

2022-03-07 10:24 UTC, stephyritz commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +Dans le cadre de cette étude, nous avons opté pour la création de 2 projets qgis distincts en fonction du type d'utilisateurs. Le premier projet est à destination des utilisateurs qui ne souhaitent q
oui malheureusement.. Mais je vais tenter tout de même une récupération par le biais de mon successeur.

2022-03-07 10:29 UTC, stephyritz commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +Le POC s'est arrêté à ce stade car la preuve a été faite que le duo QGIS/Postgresql pouvait bien répondre aux principaux besoins mentionnés. La suite des développements seraient déjà orientés vers un
j'ai une ref qui date un peu  : https://archeomatic.wordpress.com/2012/03/06/qgis-qtcreator-creer-son-formulaire-dans-qgis/

Je m'en étais inspiré lors d'un projet précédent. Est-ce que vous pensez que c'est tout de même pertinent ?

Sinon, il y aussi cette réf mais c'est plus par rapport aux outils interne QGIS pour customiser le formulaire (c'ets plus proche de ce que j'avais fait initialement dans ce POC sur l'éclairage public) : https://data.sigea.educagri.fr/download/sigea/supports/QGIS/distance/perfectionnement/M10_Formulaires/co/10_N2_Presentation_formulaire.html

2022-03-07 10:59 UTC, stephyritz commented
> @stephyritz je rejoins @aurelienchaumet, ce serait plus sympa et digeste avec des illustrations même génériques (des photos d'éclairage public ou que sais-je). Attention aux crédits quand même 😉. Tu peux regarder du côté de Reshot dont le lien est là https://static.geotribu.fr/contribuer/guides/image/#ressources

@Guts j'ai trouvé cette image générique : https://www.reshot.com/free-stock-photos/photo/my-train-just-arrived-9J2O06/ mais je n'ai pas les droits pour ajouter une image sur le CDN de Geotribu. Tu peux gérer ça stp ? Ou tu me créer un compte comme tu veux ?

2022-03-07 11:09 UTC, stephyritz commented on content/articles/2022/2022-02-28_gestion_eclairage_public.md
> +Le POC s'est arrêté à ce stade car la preuve a été faite que le duo QGIS/Postgresql pouvait bien répondre aux principaux besoins mentionnés. La suite des développements seraient déjà orientés vers un
et encore mieux en fait : http://piece-jointe-carto.developpement-durable.gouv.fr/NAT002/QGIS/formations/FOAD_PERF_QGIS34/pdf/M09_Formulaires_papier.pdf

2022-03-07 11:54 UTC, Guts commented
@stephyritz je me suis permis de faire des corrections mineures directement :

- coquilles sur la syntaxe Markdown
- ajout de vignettes pour certains paragraphes
- téléversement des images sur notre CDN
- style galerie sur les images
- ajout de l'image du train

Mais je suis sceptique sur cette image car son orientation n'est pas adaptée au style du site. Il en faudrait une en mode paysage/

2022-03-07 15:25 UTC, stephyritz commented
Voilà j'ai apporté mes dernières modifications en fonction de vos premiers retours. Vous pouvez, si vous voulez ,procéder à une dernière relecture avant publication. Si vous pensez que c'est un peu trop short pour un publication demain, on peut reporter ultérieurement! Je ne suis absolument pas pressé, votre timing sera le mien ; )

2022-03-07 16:32 UTC, Guts requested changes

2022-03-07 18:58 UTC, aurelienchaumet commented on content/articles/2022/2022-03-08_qgis_postgis_gestion_eclairage_public.md
> +Les besoins identifiés, par ordre de priorité, étaient les suivants :
Entièrement d'accord, en modifiant dans la ligne 24 

> nous avons mené une réflexion sur ***la possibilité d'utiliser QGIS pour gérer un réseau d'éclairage public*** après que le progiciel...

2022-03-07 19:10 UTC, aurelienchaumet commented
Salut @stephyritz !
Je viens de faire une relecture et hormis l'image dans le font matter qui sert au partage de l'article et quelques coquilles qui trainaient, pour moi c'est bon 😉  !
Donc il n'y a plus qu'à modifier peut-être le premier titre comme le suggère @Guts plus haut et on est bien !
Beau boulot et encore bravo 👍

2022-03-08 08:25 UTC, stephyritz commented on content/articles/2022/2022-03-08_qgis_postgis_gestion_eclairage_public.md
> +Les besoins identifiés, par ordre de priorité, étaient les suivants :
@Guts Ok très bien, ça sera plus clair en découpant ainsi ! Et @aurelienchaumet d'accord aussi avec ta formulation.
Par contre je n'ai pas les droits pour faire le commit proposé par Julien. Je modifie direct dans mon répertoire ou je te laisse faire toi-même le changement ?

2022-03-08 09:40 UTC, stephyritz commented on content/articles/2022/2022-03-08_qgis_postgis_gestion_eclairage_public.md
> +Les besoins identifiés, par ordre de priorité, étaient les suivants :
j'ai finalement modifié directement dans mon répertoire à l'instant et ai donc fait remonté les changements via ce dernier commit.

2022-03-08 10:10 UTC, Guts approved these changes

2022-03-08 10:20 UTC, merged

2022-03-10 13:21 UTC, Guts commented
@stephyritz, je crois que @ThomasG77 t'a grillé la politesse sur GeoRezo :wink: c'est déjà relayé !