Ajout d'un article sur la réalisation de relevés de terrain avec QGIS et Input
geotribu/website pull request #554
Opened 2022-03-04 17:05 UTC by cedricr

2022-03-05 10:47 UTC, igeofr requested changes

2022-03-05 10:47 UTC, igeofr commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +Votre projet va être envoyé sur le cloud Mergin
```suggestion
Votre projet va être envoyé sur le cloud Mergin.
```

2022-03-05 10:47 UTC, igeofr commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +[Collecting data using QGIS and Input app](https://www.lutraconsulting.co.uk/blog/2020/02/14/survey-qgis-input/)
```suggestion
Ce tutoriel est en partie basé sur l’article de blog de Lutra Consulting [Collecting data using QGIS and Input app](https://www.lutraconsulting.co.uk/blog/2020/02/14/survey-qgis-input/).
```

2022-03-05 10:51 UTC, igeofr approved these changes

2022-03-05 11:10 UTC, cedricr commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +image: "Image d'illustration de l'article qui sert ensuite dans la mise en avant : réseaux sociaux, flux RSS..."
@igeofr plutôt une des captures d'ecran de l'article, ou une image de stock, genre unsplash?

2022-03-05 11:14 UTC, cedricr commented on content/team/cros.md
> +![Portrait Cedric Rossi](https://cdn.geotribu.fr/img/internal/contributeurs/cros.png "Portrait Cedric Rossi"){: .img-rdp-news-thumb }
Je n'y ai pas accès, mais je l'ai envoyée à @Guts.
Pour les autres images: je lui ai envoyé une version optimisée, redimensionnée à une taille plus raisonnable, mais du coup elles marcheront peut-être moins bien avec Lightbox, à voir!
Je peux aussi transmettre tout ça à qqun d'autre si c'est plus pratique pour vous.

2022-03-05 11:16 UTC, igeofr commented
Bonjour Cédric,
Je me suis permis de réduire la taille de certaines images car on essaye de ne pas dépasser 800px de largeur pour optimiser le chargement de la page. Par contre, est-ce que ça te dérange si on recadre également tes captures de QGIS pour ne pas avoir de contour blanc?
Pour le reste, c'est ok pour moi. Je passe la main à @aurelienchaumet qui va également faire une relecture.

2022-03-05 11:18 UTC, cedricr commented
> Bonjour Cédric,
> Je me suis permis de réduire la taille de certaines images car on essaye de ne pas dépasser 800px de largeur pour optimiser le chargement de la page. Par contre, est-ce que ça te dérange si on recadre également tes captures de QGIS pour ne pas avoir de contour blanc?
> Pour le reste, c'est ok pour moi. Je passe la main à @aurelienchaumet qui va également faire une relecture.

Hello @igeofr,
Merci beaucoup pour cette relecture! Je t'ai déjà répondu dans un commentaire — j'avais déjà préparé une version optimisée des images que j'ai envoyée à @Guts, je l'envoie ailleurs? 
Aucun soucis pour le recadrage bien sûr, mais je peux m'en occuper.

2022-03-05 11:25 UTC, igeofr commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +image: "Image d'illustration de l'article qui sert ensuite dans la mise en avant : réseaux sociaux, flux RSS..."
@cedricr généralement, on utilise une capture d'écran ou une illustration en lien direct avec l'article.

2022-03-05 11:26 UTC, igeofr commented on content/team/cros.md
> +![Portrait Cedric Rossi](https://cdn.geotribu.fr/img/internal/contributeurs/cros.png "Portrait Cedric Rossi"){: .img-rdp-news-thumb }
C'est comme tu veux. Tu peux aussi me les transmettre par mail et je m'en occuperai cet après-midi.

2022-03-05 14:06 UTC, igeofr commented on content/team/cros.md
> +![Portrait Cedric Rossi](https://cdn.geotribu.fr/img/internal/contributeurs/cros.png "Portrait Cedric Rossi"){: .img-rdp-news-thumb }
@Guts @cedricr Les nouvelles images ont été intégrées.

2022-03-05 14:25 UTC, cedricr commented on content/team/cros.md
> +![Portrait Cedric Rossi](https://cdn.geotribu.fr/img/internal/contributeurs/cros.png "Portrait Cedric Rossi"){: .img-rdp-news-thumb }
Merci!

2022-03-07 19:27 UTC, aurelienchaumet approved these changes
J'ai modifié 2-3 petites coquilles rédactionnelles de rien du tout c'est top !
Et c'est nickel avec le petit ajout sur le service Mergin dans l'introduction.
Ca donne envie d'essayer donc c'est bon signe 😄

2022-03-07 19:56 UTC, cedricr commented
> Ca donne envie d'essayer donc c'est bon signe 😄

Excellent, merci !

2022-03-08 13:26 UTC, Guts commented on content/team/cros.md
> +![Portrait Cedric Rossi](https://cdn.geotribu.fr/img/internal/contributeurs/cros.png "Portrait Cedric Rossi"){: .img-rdp-news-thumb }
Merci @igeofr. @cedricr juste pour info, je t'avais envoyé les accès au CDN via Slack :wink:

2022-03-08 13:30 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +description: "Description pour le SEO."
Fait.

2022-03-08 13:43 UTC, cedricr commented on content/team/cros.md
> +![Portrait Cedric Rossi](https://cdn.geotribu.fr/img/internal/contributeurs/cros.png "Portrait Cedric Rossi"){: .img-rdp-news-thumb }
argh, je n'avais pas vu désolé!

2022-03-11 07:20 UTC, Guts requested changes
Pardon pour la revue détaillée de dernière minute mais ce sont les espaces insécables qui ont attiré mon attention au moment de publier.   
Je comprends qu'il faut idéalement employer une espace insécable fine avant un ; ou un : mais quand on publie sur Geotribu, il faut garder en tête qu'on veut mettre toutes les chances de notre côté de pouvoir faire des traitements par lot dans le futur. Et les regex sont déjà suffisamment douloureuses à élaborer pour ne pas avoir à gérer une espace simple d'une espace fine insécable.

Désolé pour l'entorse aux règles typos "pures" :pray: ! &nbsp;

J'en ai profité pour corriger 2/3 petites coquillettes mineures (ligne vide avant la liste à puces) et ajouter des lignes horizontales entre les titres de niveau 2 pour garder une cohérence avec les autres contenus.

2022-03-11 07:20 UTC, Guts commented on content/team/cros.md
> +Développeur web depuis une vingtaine d’années, je suis tombé dans la géomatique en 2014 en développant un outil de cartographie 2D/3D en ligne pour une startup d’urbanisme, et le virus ne m'a plus qu
```suggestion
Développeur web depuis une vingtaine d’années, je suis tombé dans la géomatique en 2014 en développant un outil de cartographie 2D/3D en ligne pour une startup d’urbanisme, et le virus ne m'a plus quitté depuis !
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +Plusieurs possibilités existent pour réaliser un relevé de terrain et l’exploiter dans QGIS, parmi lesquelles&nbsp;:
```suggestion
Plusieurs possibilités existent pour réaliser un relevé de terrain et l’exploiter dans QGIS, parmi lesquelles :
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +## Préparation
```suggestion
[Commenter cet article :fontawesome-solid-comments:](#__comments){: .md-button }
{: align=middle }

----

## Préparation
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +Vous devriez voir s’afficher la barre d’outils suivante
```suggestion
Vous devriez voir s’afficher la barre d’outils suivante :
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +## Dans QGIS…
```suggestion
{: align=middle }

----

## Dans QGIS…
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +Pour le type de géométrie, choisissez `Point`.
```suggestion
Pour le nom de la table, tapez `Arbres`.  
Pour le type de géométrie, choisissez `Point`.
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +Vous pouvez maintenant choisir les colonnes de la table `Arbres`, par exemple&nbsp;:
```suggestion
Vous pouvez maintenant choisir les colonnes de la table `Arbres`, par exemple :
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +Résultat final&nbsp;:
```suggestion
Résultat final :
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +- `fid` est un champ auto-incrémenté&nbsp;; nous pouvons le masquer à l’édition. Cliquez donc sur le champ`fid` , et choisissez `Cachée` comme `Type d’outil`
```suggestion
- `fid` est un champ auto-incrémenté ; nous pouvons le masquer à l’édition. Cliquez donc sur le champ `fid` , et choisissez `Cachée` comme `Type d’outil`
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +- Pour `espece` , il est plus simple d’avoir une liste déroulante que de la renseigner à chaque fois. Saisissez `Espèces` dans le champ `Alias`, puis choisissez `Liste de valeurs` comme `Type d’outil
```suggestion
- Pour `espece`, il est plus simple d’avoir une liste déroulante que de la renseigner à chaque fois. Saisissez `Espèces` dans le champ `Alias`, puis choisissez `Liste de valeurs` comme `Type d’outil`. Vous pouvez alors :
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +- soit les saisir directement.
```suggestion

- soit les saisir directement.
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +  Vous pouvez également si vous le désirez cliquer sur `Réutiliser la dernière valeur saisie`, ce qui facilitera la saisie pour les inventaires d’espèces relativement homogènes.
```suggestion
Vous pouvez également si vous le désirez cliquer sur `Réutiliser la dernière valeur saisie`, ce qui facilitera la saisie pour les inventaires d’espèces relativement homogènes.
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +Dernière étape, facultative&nbsp;: vous pouvez définir l’empreinte maximale de la carte, pour que l’application mobile affiche directement la zone du projet.
```suggestion
Dernière étape, facultative : vous pouvez définir l’empreinte maximale de la carte, pour que l’application mobile affiche directement la zone du projet.
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +Sauvegardez enfin votre projet&nbsp;; il est maintenant prêt à être envoyé sur votre téléphone.
```suggestion
Sauvegardez enfin votre projet ; il est maintenant prêt à être envoyé sur votre téléphone.
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +cliquez sur la seconde icône&nbsp;: `Create Mergin Project`&nbsp;; puis dans la fenêtre de dialogue qui s’affiche, choisissez `Package current QGIS project`
```suggestion
Cliquez sur la seconde icône : `Create Mergin Project`, puis dans la fenêtre de dialogue qui s’affiche, choisissez `Package current QGIS project`
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +Sélectionnez les couches à synchroniser&nbsp;:
```suggestion
Sélectionnez les couches à synchroniser :
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +Et enfin, nommez votre projet (par exemple `Mon Inventaire`)
```suggestion
Et enfin, nommez votre projet (par exemple `Mon Inventaire`).  
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +## Dans l’application mobile Input…
```suggestion

----

## Dans l’application mobile Input…
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +Cliquez sur le bouton `Sauver`&nbsp;; un curseur va s’afficher à votre position courante. Vous pouvez le déplacer si nécessaire.
```suggestion
Cliquez sur le bouton `Sauver` ; un curseur va s’afficher à votre position courante. Vous pouvez le déplacer si nécessaire.
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +Cliquez sur `Ajouter un point`&nbsp;; Le formulaire d’ajout s’affiche&nbsp;:
```suggestion
Cliquez sur `Ajouter un point` ; Le formulaire d’ajout s’affiche :
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +Choisissez l’espèce dans le menu déroulant&nbsp;:
```suggestion
Choisissez l’espèce dans le menu déroulant :
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +puis remplissez le reste des champs&nbsp;:
```suggestion
Puis remplissez le reste des champs :
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +Une fois que vous avez terminé la saisie, cliquez sur l’onglet `Projets`, puis sur l’icône à droite du nom de votre projet pour lancer la synchronisation&nbsp;: vos données sont envoyées dans le clou
```suggestion
Une fois que vous avez terminé la saisie, cliquez sur l’onglet `Projets`, puis sur l’icône à droite du nom de votre projet pour lancer la synchronisation : vos données sont envoyées dans le cloud Mergin.
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +## Retour à QGIS
```suggestion

----

## Retour à QGIS
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +## Pour aller plus loin
```suggestion

----

## Pour aller plus loin
```

2022-03-11 07:20 UTC, Guts commented on content/articles/2022/2022-03-11_releve_terrain_qgis_input.md
> +La documentation de l’application Input est extrêmement complète&nbsp;; vous pouvez par exemple regarder comment&nbsp;:
```suggestion
La documentation de l’application Input est extrêmement complète ; vous pouvez par exemple regarder comment :
```

2022-03-11 08:40 UTC, cedricr commented
> Pardon pour la revue détaillée de dernière minute mais ce sont les espaces insécables qui ont attiré mon attention au moment de publier. 

Aucun problème! Par contre ils restent tous ceux qui étaient dans les `title` des images; il faut les enlever aussi?

> J'en ai profité pour corriger 2/3 petites coquillettes mineures (ligne vide avant la liste à puces) et ajouter des lignes horizontales entre les titres de niveau 2 pour garder une cohérence avec les autres contenus.

Merci beaucoup!

2022-03-11 08:43 UTC, Guts commented
> Aucun problème! Par contre ils reste tous ceux qui étaient dans les `title` des images; il faut les enlever aussi?

Ah oui, si tu peux faire un rechercher/remplacer rapidement de ton côté, c'est cool !

2022-03-11 08:50 UTC, Guts approved these changes

2022-03-11 08:55 UTC, merged