Article: Données de Mapillary via les VT
geotribu/website pull request #603
Opened 2022-05-09 10:03 UTC by igeofr

Article sur l'accès aux données de Mapillary via les tuiles vectorielles.

2022-05-22 21:48 UTC, Guts requested changes
Coquilles et quelques suggestions/remarques

2022-05-22 21:48 UTC, Guts commented on content/articles/2022/2022-05-17_donnees_mapillary.md
> +    Un article de Morgan Hite sur son blog : [QGIS 3 and Vector map tiles](https://wanderingcartographer.wordpress.com/2021/01/09/qgis-3-and-vector-map-tiles/)
Je trouve bizarre d'avoir cet encar d'entrée de jeu. Je verrais plutôt une section Bibliographie en fin d'article.

2022-05-22 21:48 UTC, Guts commented on content/articles/2022/2022-05-17_donnees_mapillary.md
> +- d'intérroger la donnée
```suggestion
- d'interroger la donnée
```

2022-05-22 21:48 UTC, Guts commented on content/articles/2022/2022-05-17_donnees_mapillary.md
> +Il exite trois URL permettant d'accéder aux tuiles vectorielles de Mapillary :
```suggestion
Il existe trois URL permettant d'accéder aux tuiles vectorielles de Mapillary :
```

2022-05-22 21:48 UTC, Guts commented on content/articles/2022/2022-05-17_donnees_mapillary.md
> +    - ```https://tiles.mapillary.com/maps/vtp/mly1_computed_public/2/{z}/{x}/{y}?access_token=XXX```
Je trouve que de mettre une sous-puce pour chaque URL est pas très beau. Je suggère d'utiliser le code inline :

```suggestion
1. [Tuiles de couverture](https://www.mapillary.com/developer/api-documentation/#coverage-tiles) : qui permettent de visualiser les séquences (traces) et la position des prises de vue :  `https://tiles.mapillary.com/maps/vtp/mly1_computed_public/2/{z}/{x}/{y}?access_token=XXX`
```

2022-05-22 21:48 UTC, Guts commented on content/articles/2022/2022-05-17_donnees_mapillary.md
> +    - ```https://tiles.mapillary.com/maps/vtp/mly1_computed_public/2/{z}/{x}/{y}?access_token=XXX```
idem pour les 2 autres mais je laisse faire si jamais la suggestion est retenue

2022-05-22 21:48 UTC, Guts commented on content/articles/2022/2022-05-17_donnees_mapillary.md
> +
```suggestion
Ajouter la nouvelle couche de tuiles dans QGIS (pour visualiser l'information, vous devrez zoomer au niveau 14 ou +).

```

2022-05-22 21:48 UTC, Guts commented on content/articles/2022/2022-05-17_donnees_mapillary.md
> +Les tuiles vectorielles sont interrogeables et permettent une consultation des différents champs publiés. Si l'on prend l'exemple du flux lié à la signalisation, il est possible possible d'accéder au
```suggestion
Les tuiles vectorielles sont interrogeables et permettent une consultation des différents champs publiés. Si l'on prend l'exemple du flux lié à la signalisation, il est possible d'accéder au type de panneau detecté ainsi qu'aux dates auxquelles il a été vu pour la première et la dernière fois.
```

2022-05-22 21:48 UTC, Guts commented on content/articles/2022/2022-05-17_donnees_mapillary.md
> +Avant de se lancer, il est bon de paramétrer le fichier de configuration que vous devrez adapter à votre organisation et qui sera utilisé pour intégrer les données Mapillary dans votre base de donnée
```suggestion
Avant de se lancer, il est bon de paramétrer le fichier de configuration que vous devrez adapter à votre organisation et qui sera utilisé pour intégrer les données Mapillary dans votre base de données. On y définit les différents répertoires de travail ainsi que les variables permettant d'accéder à la base de données (connexion par [pg_service.conf](http://archives.postgresql.fr/v2/index9215.html?q=node/1388)).
```

2022-05-22 21:48 UTC, Guts commented on content/articles/2022/2022-05-17_donnees_mapillary.md
> +Les tuiles ne sont pas définies par une longitude/latitude mais par une numérotation spécique, il nous faut donc identifier les numéros des tuiles qui croisent notre emprise de travail et pour cela,
```suggestion
Les tuiles ne sont pas définies par une longitude/latitude mais par une numérotation spécifique, il nous faut donc identifier les numéros des tuiles qui croisent notre emprise de travail et pour cela, je me suis appuyé sur une [solution proposée sur le wiki d'OpenStreetMap](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames#Bourne_shell_with_Awk).
```

2022-05-22 21:48 UTC, Guts commented on content/articles/2022/2022-05-17_donnees_mapillary.md
> +Grâce aux possibilités de rendu des tuiles vectorielles de QGIS, il est possible de filtrer et customiser les données de Mapillary en fonction des besoins, tout en ayant accès à l'information en quas
```suggestion
Grâce aux capacités de rendu des tuiles vectorielles de QGIS, il est possible de filtrer et personnaliser les données de Mapillary en fonction des besoins, tout en ayant accès à l'information en quasi temps réel.
```

2022-05-22 21:48 UTC, Guts commented on content/articles/2022/2022-05-17_donnees_mapillary.md
> +1. bénéficier à vos services concernées (services techniques, voirie, ...),
```suggestion
1. bénéficier à vos services concernés (services techniques, voirie...),
```

2022-05-23 07:24 UTC, igeofr commented on content/articles/2022/2022-05-17_donnees_mapillary.md
> +    Un article de Morgan Hite sur son blog : [QGIS 3 and Vector map tiles](https://wanderingcartographer.wordpress.com/2021/01/09/qgis-3-and-vector-map-tiles/)
Oui, tu as raison. 
Je ne savais pas trop ou le caser!

2022-05-30 09:02 UTC, Guts commented on content/articles/2022/2022-05-31_donnees_mapillary.md
> +graph TD;
Je crois que dans les versions plus récentes de Mermaid, il est préférable d'utiliser flowchart : https://mermaid-js.github.io/mermaid/#/flowchart. Tu peux uassi tester sans les `;` finaux je pense. De même, les flèches à double pointe sont désormais supportées.

```suggestion
flowchart TD;
```

2022-05-30 19:33 UTC, igeofr commented on content/articles/2022/2022-05-31_donnees_mapillary.md
> +graph TD;
Merci @Guts, testé et validé.

2022-05-30 19:49 UTC, Guts approved these changes

2022-05-30 19:55 UTC, merged