Article article/2022-07-02_qgis_joy_division.md
geotribu/website pull request #643
Opened 2022-07-03 08:11 UTC by datagistips

Hello,

Dans cet article, j'explique comment créer des cartes à la façon de l'album 'Unknown Pleasures' de Joy Division en utilisant essentiellement les générateurs de géométrie de QGIS et le MNT de l'IGN BDALTI 25m;

Mon secteur de prédilection- ma muse - pour ce genre d'exercice topographique est la montagne Sainte-Victoire.

Bonne lecture et bonne revue s'il y a des petites erreurs ou des choses à améliorer !

2022-07-05 10:38 UTC, igeofr reviewed
Mes retours sur la forme.

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![joy division cover](https://upload.wikimedia.org/wikipedia/commons/5/5f/Radio_joy_division.jpg "joy division cover"){: loading=lazy .img-center }
```suggestion
[![Joy Division cover](https://upload.wikimedia.org/wikipedia/commons/5/5f/Radio_joy_division.jpg "Joy Division cover"){: loading=lazy .img-center }](https://upload.wikimedia.org/wikipedia/commons/5/5f/Radio_joy_division.jpg){: data-mediabox="lightbox-gallery" data-title="Joy Division cover" }
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![carte de l'islande](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/islande.jpg "carte de l'islande"){: loading=lazy .img-center }
```suggestion
[![Carte de l'Islande](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/islande.jpg "Carte de l'Islande"){: loading=lazy .img-center }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/islande.jpg){: data-mediabox="lightbox-gallery" data-title="Carte de l'Islande" }
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![ridgeline plots](https://www.data-to-viz.com/graph/ridgeline_files/figure-html/unnamed-chunk-1-1.png "ridgeline plots"){: loading=lazy .img-center }
```suggestion
[![Ridgeline plots](https://www.data-to-viz.com/graph/ridgeline_files/figure-html/unnamed-chunk-1-1.png "Ridgeline plots"){: loading=lazy .img-center }](https://www.data-to-viz.com/graph/ridgeline_files/figure-html/unnamed-chunk-1-1.png){: data-mediabox="lightbox-gallery" data-title="Ridgeline plots" }
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +[![](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/grass.png){: loading=lazy .img-center }](https://youtu.be/cZia3ShzTWM?t=558)
```suggestion
[![GRASS GIS 1987](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/grass.png "GRASS GIS 1987"){: loading=lazy .img-center }](https://youtu.be/cZia3ShzTWM?t=558)
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![image originale des impulsions](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/cp1919.jpg "image originale des impulsions"){: loading=lazy .img-center }
```suggestion
[![Image originale des impulsions](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/cp1919.jpg "Image originale des impulsions"){: loading=lazy .img-center }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/cp1919.jpg){: data-mediabox="lightbox-gallery" data-title="Image originale des impulsions" }
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![Localisation d'Aix](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/aix.png "Localisation d'Aix"){: loading=lazy .img-center }
```suggestion
[![Localisation d'Aix](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/aix.png "Localisation d'Aix"){: loading=lazy .img-center }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/aix.png){: data-mediabox="lightbox-gallery" data-title="Localisation d'Aix" }
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![Découpe avec QGIS](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/decoupe.png "Découpe avec QGIS"){: loading=lazy .img-center }
```suggestion
[![Découpe avec QGIS](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/decoupe.png "Découpe avec QGIS"){: loading=lazy .img-center }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/decoupe.png){: data-mediabox="lightbox-gallery" data-title="Découpe avec QGIS" }
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![MNT découpé](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/0-dem.jpeg "MNT découpé"){: loading=lazy .img-center }
```suggestion
[![MNT découpé](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/0-dem.jpeg "MNT découpé"){: loading=lazy .img-center }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/0-dem.jpeg){: data-mediabox="lightbox-gallery" data-title="MNT découpé" }
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![Extraction de l'emprise](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/couche.png "Extraction de l'emprise"){: loading=lazy .img-center }
```suggestion
[![Extraction de l'emprise](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/couche.png "Extraction de l'emprise"){: loading=lazy .img-center }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/couche.png){: data-mediabox="lightbox-gallery" data-title="Extraction de l'emprise" }
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![Extraire l'emprise](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/extraire.png "Extraire l'emprise"){: loading=lazy .img-center }
```suggestion
[![Extraire l'emprise](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/extraire.png "Extraire l'emprise"){: loading=lazy .img-center }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/extraire.png){: data-mediabox="lightbox-gallery" data-title="Extraire l'emprise" }
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![Emprise](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/1-Carre.jpeg "Emprise"){: loading=lazy .img-center }
```suggestion
[![Emprise](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/1-Carre.jpeg "Emprise"){: loading=lazy .img-center }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/1-Carre.jpeg){: data-mediabox="lightbox-gallery" data-title="Emprise" }
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![Générateur de géométries](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/rendu-ligne.png "Générateur de géométries"){: loading=lazy .img-center }
```suggestion
[![Générateur de géométries](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/rendu-ligne.png "Générateur de géométries"){: loading=lazy .img-center }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/rendu-ligne.png){: data-mediabox="lightbox-gallery" data-title="Générateur de géométries" }
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![Rendu en lignes](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/2-lines.jpeg "Rendu en lignes"){: loading=lazy .img-center }
```suggestion
[![Rendu en lignes](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/2-lines.jpeg "Rendu en lignes"){: loading=lazy .img-center }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/2-lines.jpeg){: data-mediabox="lightbox-gallery" data-title="Rendu en lignes" }
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	)
Indiquer le langage du bloc code : sql

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	)
Indiquer le langage du bloc code : sql

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	)
Indiquer le langage du bloc code : sql

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	)
Indiquer le langage du bloc code : sql

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![Rendu en points](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/3-points.jpeg "Rendu en points"){: loading=lazy .img-center }
```suggestion
[![Rendu en points](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/3-points.jpeg "Rendu en points"){: loading=lazy .img-center }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/3-points.jpeg){: data-mediabox="lightbox-gallery" data-title="Rendu en points" }
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![Déplacement des points](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/shift-points.jpeg "Déplacement des points"){: loading=lazy .img-center }
```suggestion
[![Déplacement des points](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/shift-points.jpeg "Déplacement des points"){: loading=lazy .img-center }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/shift-points.jpeg){: data-mediabox="lightbox-gallery" data-title="Déplacement des points" }
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	)
Indiquer le langage du bloc code : sql

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	raster_value('dem', 1, @point)
Indiquer le langage du bloc code : sql

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	raster_value('dem', 1, @point) * 2
Indiquer le langage du bloc code : sql

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	)
Indiquer le langage du bloc code : sql

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	make_line([point1, point2, point3, ...])
Indiquer le langage du bloc code : sql

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	smooth(..., 1000)
Indiquer le langage du bloc code : sql

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![Mon T-Shirt Joy Division](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/joy-photo.jpeg "Mon T-Shirt Joy Division"){: loading=lazy .img-center }
```suggestion
[![Mon T-Shirt Joy Division](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/joy-photo.jpeg "Mon T-Shirt Joy Division"){: loading=lazy .img-center }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/joy-photo.jpeg){: data-mediabox="lightbox-gallery" data-title="Mon T-Shirt Joy Division" }
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +## Crédits
```suggestion
## Crédits

```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +## Crédits
Manque un retour à la ligne

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +<iframe src="https://giphy.com/embed/U8RXSRKv8uMPS" width="480" height="360" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
@Guts c'est quoi la meilleure solution pour centrer le gifphy?

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![Rendu basique](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/joy.jpeg "Rendu basique"){: loading=lazy .img-center }
```suggestion
[![Rendu basique](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/joy.jpeg "Rendu basique"){: loading=lazy .img-center }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/joy.jpeg){: data-mediabox="lightbox-gallery" data-title="Rendu basique" }
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![Rendu puriste](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/joy-puriste.jpeg "Rendu puriste"){: loading=lazy .img-center }
```suggestion
[![Rendu puriste](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/joy-puriste.jpeg "Rendu puriste"){: loading=lazy .img-center }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/joy-puriste.jpeg){: data-mediabox="lightbox-gallery" data-title="Rendu puriste" }
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +Dans cet article, nous allons voir comment créer une carte Post-punk à la mode Joy Division en utilisant les générateurs de géométrie de QGIS.
```suggestion
## Introduction

![icône globe musique note](https://cdn.geotribu.fr/img/internal/icons-rdp-news/musique_note.png "icône globe musique note"){: .img-rdp-news-thumb }

Dans cet article, nous allons voir comment créer une carte Post-punk à la mode Joy Division en utilisant les générateurs de géométrie de QGIS.
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +Dans cet article, nous allons voir comment créer une carte Post-punk à la mode Joy Division en utilisant les générateurs de géométrie de QGIS.
Ajout d'une icône

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +<blockquote class="twitter-tweet" data-lang="fr" data-dnt="true"><p lang="en" dir="ltr">Manicougan Crater, ridgeplot syle. SRTM DEM, Blender. <a href="https://t.co/KGZQh7j57p">pic.twitter.com/KGZQh7j
```suggestion
<blockquote class="twitter-tweet tw-align-center" data-lang="fr" data-dnt="true"><p lang="en" dir="ltr">Manicougan Crater, ridgeplot syle. SRTM DEM, Blender. <a href="https://t.co/KGZQh7j57p">pic.twitter.com/KGZQh7j57p</a></p>&mdash; Steven Kay (@stevefaeembra) <a href="https://twitter.com/stevefaeembra/status/1543318675230543874?ref_src=twsrc%5Etfw">2 juillet 2022</a></blockquote>
```

2022-07-05 10:38 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +<blockquote class="twitter-tweet" data-lang="fr" data-dnt="true"><p lang="en" dir="ltr">Manicougan Crater, ridgeplot syle. SRTM DEM, Blender. <a href="https://t.co/KGZQh7j57p">pic.twitter.com/KGZQh7j
Centrer le tweet

2022-07-05 10:39 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +![joy division cover](https://upload.wikimedia.org/wikipedia/commons/5/5f/Radio_joy_division.jpg "joy division cover"){: loading=lazy .img-center }
Permet l'affichage : lightbox-gallery

2022-07-07 18:24 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +[![Image originale des impulsions](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/cp1919.jpg "Image originale des impulsions"){: loading=lazy .img-center }](
```suggestion
[![Image originale des impulsions](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/cp1919.webp "Image originale des impulsions"){: loading=lazy .img-center }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/cp1919.webp){: data-mediabox="lightbox-gallery" data-title="Image originale des impulsions" }
```

2022-07-07 18:27 UTC, Guts approved these changes

2022-07-07 18:27 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +[![](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2022/2022-07-02-qgis-joy-division/grass.png){: loading=lazy .img-center }](https://youtu.be/cZia3ShzTWM?t=558)
Pourquoi ne pas intégrer la vidéo directement plutôt (cf https://static.geotribu.fr/contribuer/guides/video/) ?

```suggestion
<iframe width="100%" height="400" src="https://www.youtube-nocookie.com/embed/cZia3ShzTWM?start=558" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

2022-07-07 18:32 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +image: ![](images/joy-puriste.jpeg)
L'en-tête est du YAML et non du Markdown (voir https://static.geotribu.fr/contribuer/guides/metadata_yaml_frontmatter/, https://static.geotribu.fr/contribuer/internal/seo_extraits_enrichis/ et tout ce qui est YAML frontammter in Markdown).

Donc la syntaxe pour l'image n'est pas valide. @datagistips regarde les autres articles ou le template : il faut mettre l'URL vers l'image.

MAIS, comme indiqué dans le guide, si tu veux que l'article soit mis en avant sur la page d'accueil, il faut que l'image soit dans les dimensions du rectangle de mise en avant : 800x450 environ.

2022-07-07 18:34 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +date: "2022-07-02 20:00"
Penser à MAJ la date de publication une fois l'article prêt :wink:. Idem dans le nom du fichier (à faire en dernier).

Sinon, mais bon c'est vraiment pas bloquant mais du détail, je te conseille de laisser l'heure habituelle indiquée dans le modèle (template) d'article et utilisée dans tous les articles ou presque (10:20) pour éviter la diffusion tardive dans les lecteurs RSS.

2022-07-07 18:37 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +    - Post-Punk
Règles pour les tags :

- ordre alphabétique
- suivre la casse naturelle (majuscules pour les noms propres ou sigles, etc.)
- réutiliser au possible les tags déjà existants sur le site https://static.geotribu.fr/tags/
 
```suggestion
tags:
    - cartographie
    - geometry generators
    - Generative Design
    - post-punk
    - QGIS
```

2022-07-07 18:52 UTC, Guts requested changes

2022-07-07 18:52 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +> The image was originally created by radio astronomer Harold Craft at the Arecibo Observatory for his 1970 doctoral dissertation as a way to visualize smaller pulses within larger ones, which might
Interligne manquant

```suggestion
Voici ce que dit [Wikipedia](https://en.wikipedia.org/wiki/Unknown_Pleasures#Artwork_and_packaging) sur cette image :

> The image was originally created by radio astronomer Harold Craft at the Arecibo Observatory for his 1970 doctoral dissertation as a way to visualize smaller pulses within larger ones, which might help explain what had been causing the pulses. He was unaware for years that the image was associated with the album cover until a friend told him; afterwards he bought a copy because he felt he should have one as the creator of the image.
```

2022-07-07 18:52 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +Je ferai la carte Joy Division de la Montagne Sainte-Victoire. Celle-ci domine Aix-en-Provence où j'habite.
Interligne manquant

```suggestion
## Téléchargement du MNT

Je ferai la carte Joy Division de la Montagne Sainte-Victoire. Celle-ci domine Aix-en-Provence où j'habite.
```

2022-07-07 18:52 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +, c'est-à-dire ceci :
typo

```suggestion
Maintenant, ce que l'on va faire, c'est déplacer chaque point vers le haut en fonction de la valeur du MNT qui se situe en dessous.  
C'est-à-dire ceci :
```

2022-07-07 19:22 UTC, igeofr commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +<iframe src="https://giphy.com/embed/U8RXSRKv8uMPS" width="480" height="360" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
Une solution pour les intégrer au cdn : 

`curl https://media.giphy.com/media/U8RXSRKv8uMPS/giphy.gif --output ~/Desktop/download.gif` ([Source](https://eric.blog/2019/01/12/how-to-download-a-gif-from-giphy/))

2022-07-08 17:48 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +image: ![](images/joy-puriste.jpeg)
Corrigé avec https://github.com/geotribu/website/pull/643/commits/f767793a940e9cf96b4f3486f9bd02930936e6f1

2022-07-08 18:34 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +<iframe src="https://giphy.com/embed/U8RXSRKv8uMPS" width="480" height="360" frameBorder="0" class="giphy-embed" allowFullScreen></iframe>
J'ai trouvé, y'a un lien direct vers le GIF

2022-07-10 19:21 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +- une autre fois pour agréger toutes les lignes horizontales de points
Corrigé.

2022-07-10 19:21 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	)
Fait.

2022-07-10 19:22 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	)
Fait.

2022-07-10 19:22 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	raster_value('dem', 1, @point) * 2
Fait.

2022-07-10 19:22 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	)
Fait.

2022-07-10 19:22 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	raster_value('dem', 1, @point)
Fait.

2022-07-10 19:22 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	)
Fait.

2022-07-10 19:22 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	)
Fait.

2022-07-10 19:22 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	)
Fait.

2022-07-10 19:22 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +	)
Fait.

2022-07-10 21:11 UTC, Guts commented on content/articles/2022/2022-07-02_qgis_joy_division.md
> +date: "2022-07-02 20:00"
@datagistips il reste plus qu'à renommer le fichier et c'est bon :)

2022-07-11 18:18 UTC, Guts approved these changes

2022-07-11 18:22 UTC, merged