Article sur l'intrégation de GDAL dans FME
geotribu/website pull request #656
Opened 2022-07-19 20:08 UTC by fiorinoh

Voici l'article sur l'utilisation de la librairie GDAL dans FME. L'idée est que les transformateurs de FME sont loin de couvrir tous les besoins. Il est parfois nécessaire d'écrire son propre transformateur en intégrant une librairie tierce. Je donne ici un exemple avec GDAL. La difficulté consiste à "aligner" les API Python de FME et de GDAL, en particulier sur leurs formats raster. 

En espérant que cela puisse être utile à d'autres et les aider à rentrer dans ces API laconiquement documentées !

N'hésitez pas à faire toute modification ou correction nécessaire.

2022-07-26 15:44 UTC, Guts commented
@fiorinoh a priori, @aurelienchaumet devrait faire une review demain.

Désolé, on n'est peu dispos de notre côté.

@lbartoletti a également fait une relecture.

2022-07-26 19:47 UTC, Guts commented on content/articles/2022/2022-07-26_API_Python_FME_travailler_avec_GDAL.md
> +FME Workbench est un fantastique ETL, très populaire dans la communauté de géomatique. Il permet d'assembler par de simples "glisser/déposer" dans une interface graphique des "transformateurs" opéran
> modification du style d'une couche vectorielle etc.

C'est vraiment faisable avec FME ?

2022-07-26 19:50 UTC, Guts commented on content/articles/2022/2022-07-26_API_Python_FME_travailler_avec_GDAL.md
> +Dans cette dernière partie du code Python, je crée un nouveau raster avec les mêmes propriétés que le raster initial. Je remplis une nouvelle bande avec les données de proximité et je la rattache au
En mettant le commentaire avant la dernière fonction, ça semble plus logique à la lecture et ça permet de découper le gros bloc de code.

Mais je suis pas sûr qu ça reste pertinent.

````suggestion
```

Dans cette dernière partie du code Python, je crée un nouveau raster avec les mêmes propriétés que le raster initial. Je remplis une nouvelle bande avec les données de proximité et je la rattache au raster. La sortie de `PythonCaller` est ensuite générée par la méthode `pyoutput(feature)` et le raster de proximité ainsi produit peut être utilisé par d'autres transformateurs du workflow.

```python
    def process_group(self):
        """When 'Group By' attribute(s) are specified, this method is called
        once all the FME Features in a current group have been sent to input().

        FME Features sent to input() should generally be cached for group-by
        processing in this method when knowledge of all Features is required.
        The resulting Feature(s) from the group-by processing should be emitted
        through self.pyoutput().

        FME will continue calling input() a number of times followed
        by process_group() for each 'Group By' attribute, so this
        implementation should reset any class members for the next group.
        """
        pass
```

````

2022-07-26 21:52 UTC, fiorinoh commented on content/articles/2022/2022-07-26_API_Python_FME_travailler_avec_GDAL.md
> +FME Workbench est un fantastique ETL, très populaire dans la communauté de géomatique. Il permet d'assembler par de simples "glisser/déposer" dans une interface graphique des "transformateurs" opéran
Oui je le fais dans ce workflow en changeant la couleur des routes. On peut changer l'épaisseur des lignes, paramétrer la couleur de polygones en fonction des valeurs d'un attribut etc.

2022-07-26 21:53 UTC, fiorinoh commented on content/articles/2022/2022-07-26_API_Python_FME_travailler_avec_GDAL.md
> +Dans cette dernière partie du code Python, je crée un nouveau raster avec les mêmes propriétés que le raster initial. Je remplis une nouvelle bande avec les données de proximité et je la rattache au
Oui !

2022-07-27 07:01 UTC, Guts commented on content/articles/2022/2022-07-26_API_Python_FME_travailler_avec_GDAL.md
> +FME Workbench est un fantastique ETL, très populaire dans la communauté de géomatique. Il permet d'assembler par de simples "glisser/déposer" dans une interface graphique des "transformateurs" opéran
- FME : 1
- @lbartoletti (le sceptique) : 0

2022-07-27 07:03 UTC, lbartoletti commented on content/articles/2022/2022-07-26_API_Python_FME_travailler_avec_GDAL.md
> +FME Workbench est un fantastique ETL, très populaire dans la communauté de géomatique. Il permet d'assembler par de simples "glisser/déposer" dans une interface graphique des "transformateurs" opéran
@fiorinoh il va falloir que tu me montres ce transformer :sweat_smile:

2022-07-28 12:13 UTC, aurelienchaumet requested changes
Hormis les micro coquilles relevées en début d'article, le reste est top et clair 👏
Merci pour l'article !!

2022-07-28 12:13 UTC, aurelienchaumet commented on content/articles/2022/2022-07-26_API_Python_FME_travailler_avec_GDAL.md
> +FME Workbench est un fantastique ETL, très populaire dans la communauté de géomatique. Il permet d'assembler par de simples "glisser/déposer" dans une interface graphique des "transformateurs" opéran
```suggestion
FME Workbench est un fantastique ETL, très populaire dans la communauté de géomatique. Il permet d'assembler par de simples "glisser/déposer" dans une interface graphique des "transformateurs" opérant sur toutes sortes de flux de données (fichiers, bases de données, services web, etc.). Avec ces transformateurs, on réalise les opérations classiques d'un SIG, d'une base de données : sélection de données attributaires, jointures spatiales, modification du style d'une couche vectorielle, etc.
```

2022-07-31 19:59 UTC, Guts requested changes

2022-07-31 19:59 UTC, Guts commented on content/articles/2022/2022-07-26_API_Python_FME_travailler_avec_GDAL.md
> +La question est donc : comment obtenir le même résultat avec FME Workbench ? Une possibilité consiste à utiliser le transformateur `PythonCaller` qui permet de créer son propre transformateur à parti
```suggestion
La question est donc : comment obtenir le même résultat avec FME Workbench ?

[Commenter cet article :fontawesome-solid-comments:](#__comments){: .md-button }
{: align=middle }

----

## Le transformateur `PythonCaller`

Une possibilité consiste à utiliser le transformateur `PythonCaller` qui permet de créer son propre transformateur à partir d'un script Python et d'importer la librairie [GDAL](https://gdal.org/tutorials/). J'ai mis en ligne [le "template" FME](http://blog.fiorino.fr/wp-content/uploads/2022/05/TransportationRoads.fmwt) correspondant à cet article.
```

2022-07-31 19:59 UTC, Guts commented on content/articles/2022/2022-07-26_API_Python_FME_travailler_avec_GDAL.md
> +FME Workbench est un fantastique ETL, très populaire dans la communauté de géomatique. Il permet d'assembler par de simples "glisser/déposer" dans une interface graphique des "transformateurs" opéran
Ajout titre 2 introduction et logo FME

```suggestion
:calendar: Date de publication initiale : 26 juillet 2022

## Introduction

![logo FME](https://cdn.geotribu.fr/img/logos-icones/logiciels_librairies/FME.png "logo FME"){: .img-rdp-news-thumb }

FME Workbench est un fantastique ETL, très populaire dans la communauté de géomatique. Il permet d'assembler par de simples "glisser/déposer" dans une interface graphique des "transformateurs" opérant sur toutes sortes de flux de données (fichiers, bases de données, services web, etc.). Avec ces transformateurs, on réalise les opérations classiques d'un SIG, d'une base de données : sélection de données attributaires, jointures spatiales, modification du style d'une couche vectorielle, etc.
```

2022-07-31 20:00 UTC, Guts requested changes

2022-07-31 20:00 UTC, Guts commented on content/articles/2022/2022-07-26_API_Python_FME_travailler_avec_GDAL.md
> +date: "2022-07-26 20:00"
Allez, cette fois c'est la bonne, on publie mardi !

```suggestion
date: "2022-08-02 14:00"
```

2022-07-31 20:00 UTC, Guts commented on content/articles/2022/2022-07-26_API_Python_FME_travailler_avec_GDAL.md
> +:calendar: Date de publication initiale : 26 juillet 2022
```suggestion
:calendar: Date de publication initiale : 2 août 2022
```

2022-08-01 08:48 UTC, Guts commented
> Hormis les micro coquilles relevées en début d'article, le reste est top et clair clap Merci pour l'article !!

Du coup, @aurelienchaumet peux-tu valider ta review stp ?

2022-08-01 14:26 UTC, aurelienchaumet approved these changes

2022-08-02 13:24 UTC, Guts approved these changes

2022-08-02 14:27 UTC, merged