Update rdp_2022-09-09.md
geotribu/website pull request #686
Opened 2022-09-06 14:12 UTC by Doctor-Who

News/tuto publication des métadonnées avec GeoServer pour RDP du 2022-09-09

2022-09-06 14:33 UTC, Guts requested changes
Cool, merci :)

Le wording officiel c'est pas geOrchestra plutôt ? ping @MaelREBOUX et @fvanderbiest

2022-09-06 14:33 UTC, Guts commented on content/rdp/2022/rdp_2022-09-09.md
> +![apercumetadata_geoserver](https://cdn.geotribu.fr/img/articles-blog-rdp/serveur/metadata_geoserver_csw.png){: text-align="center" }
```suggestion
![GeoServer - Edit metadata](https://cdn.geotribu.fr/img/articles-blog-rdp/serveur/metadata_geoserver_csw.png "GeoServer - Edit metadata"){: .img-center loading=lazy }
```

2022-09-06 14:33 UTC, Guts commented on content/rdp/2022/rdp_2022-09-09.md
> +![icône geoserver](https://cdn.geotribu.fr/img/logos-icones/geoserver.png "icône geoserver"){: .img-rdp-news-thumb } Vous ne supportez plus l'éditeur de métadonnées de GeoNetwork ? En attendant un po
```suggestion
![icône geoserver](https://cdn.geotribu.fr/img/logos-icones/geoserver.png "icône geoserver"){: .img-rdp-news-thumb }

Vous ne supportez plus l'éditeur de métadonnées de GeoNetwork ? En attendant un possible projet d'éditeur de métadonnées (ergonomique) évoqué lors du FOSS4G à Florence, [Julien Sabatier](https://github.com/jusabatier) de la communauté d'agglomération du Puy-en-Velay et membre très actif de la communauté GeOrchestra vous offre une solution alternative.
```

2022-09-06 14:43 UTC, fvanderbiest commented
> Le wording officiel c'est pas geOrchestra plutôt ?

Exact !

2022-09-07 07:51 UTC, Doctor-Who commented
Poke @Guts pour vérification

2022-09-07 08:16 UTC, Guts commented
@Doctor-Who ça me parait bien.

Peux-tu déplacer dans **Logiciel** stp ? **Serveur** est une section dépréciée : https://static.geotribu.fr/contribuer/rdp/add_news/#sections-categories

2022-09-07 13:11 UTC, Doctor-Who commented
@Guts Done :)

2022-09-07 13:16 UTC, Guts approved these changes

2022-09-07 13:18 UTC, merged