Proposition article Ed Fairburn / modes de fusion
geotribu/website pull request #709
Opened 2022-09-29 20:09 UTC by Michael-cd30

Voilà l'article sur les modes de fusion QGis.
J'ai pris en compte dans cette version certaines remarques de @Gab-OPenIG et @igeofr.

PS : y'a 3 commits dont 1 commit/revert car j'ai merdé sur mon clone et comme je suis une tanche en git j'ai pas réussi à faire mieux.

2022-09-29 20:39 UTC, Guts commented
Merci @Michael-cd30 pour l'article :clap: !

> Et alors que je m'apprête à mettre un point final à cet article, un relecteur que nous nommerons G-DOPenIG pour ne pas briser son anonymat me propose de, je cite, te "renvoyer à la différence entre synthèse additive (RVB, écran) et soustractive (CMJN, imprimerie)", preuve irréfutable qu'il en connait plus que moi sur le sujet. Cet anonyme nous propose [cette page explicative](https://www.colorimetrie.be/chapter/introduction_colorimetrie/synthese-additive-et-soustractive) pour en savoir plus.

Hahaha serait-ce un début (ou une fin) de TOC @Gab-OPenIG ?

2022-09-29 20:42 UTC, Michael-cd30 commented
Au plaisir...
Et pour la mention, c'est surtout une main tendue à @Gab-OPenIG pour qu'ils nous fasse de beaux articles ! Je suis sûr qu'il a des idées.

2022-09-30 07:31 UTC, igeofr commented on content/articles/2022/2022-09-30_carte_facon_ed_fairburn.md
> +C'est à cette étape qu'on va ajouter l'objet `Carte`, mais avant ça, parlons un peu du mode de fusion _Addition_.
```suggestion
C'est à cette étape qu'on va ajouter l'objet `Carte`, mais avant ça, parlons un peu du mode de fusion `Addition`.
```

2022-09-30 07:31 UTC, igeofr commented on content/articles/2022/2022-09-30_carte_facon_ed_fairburn.md
> +Comme pour _Addition_, avec le mode _Éclaircir_ couleur + blanc = blanc et couleur + noir = couleur, mais le résultat est différent sur les valeurs intermédiaires, la preuve en image.
```suggestion
Comme pour `Addition`, avec le mode `Éclaircir` couleur + blanc = blanc et couleur + noir = couleur, mais le résultat est différent sur les valeurs intermédiaires, la preuve en image.
```

2022-09-30 07:31 UTC, igeofr commented on content/articles/2022/2022-09-30_carte_facon_ed_fairburn.md
> +On voit que le mode _Addition_ tend plus rapidement vers le blanc.
```suggestion
On voit que le mode `Addition` tend plus rapidement vers le blanc.
```

2022-09-30 07:31 UTC, igeofr commented on content/articles/2022/2022-09-30_carte_facon_ed_fairburn.md
> +Le mode _Éclaircir_ permet de remplacer le noir des bâtiments par le visage de Mona Lisa et d'avoir un mélange plus fondu sur les zones de végétation, les surfaces hydrographiques et les voies nommée
```suggestion
Le mode `Éclaircir` permet de remplacer le noir des bâtiments par le visage de Mona Lisa et d'avoir un mélange plus fondu sur les zones de végétation, les surfaces hydrographiques et les voies nommées.
```

2022-09-30 07:31 UTC, igeofr commented on content/articles/2022/2022-09-30_carte_facon_ed_fairburn.md
> +[![La Joconde par DALL.E - version 1](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/carte_facon_ed_fairburn/DALL.E_mona_misa_1.png "La Joconde par DALL.E - version 1"){: .img-center loading=
```suggestion
[![La Joconde par DALL.E - version 1](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/carte_facon_ed_fairburn/DALL.E_mona_misa_1.png "La Joconde par DALL.E - version 1"){: .img-center loading=lazy }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/carte_facon_ed_fairburn/DALL.E_mona_misa_1.png){: data-mediabox="gallery-lightbox" data-title="La Joconde par DALL.E - version 1" }
```

2022-09-30 07:31 UTC, igeofr commented on content/articles/2022/2022-09-30_carte_facon_ed_fairburn.md
> +[![La Joconde par DALL.E - version 2](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/carte_facon_ed_fairburn/DALL.E_mona_misa_2.png "La Joconde par DALL.E - version 2"){: .img-center loading=
```suggestion
[![La Joconde par DALL.E - version 2](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/carte_facon_ed_fairburn/DALL.E_mona_misa_2.png "La Joconde par DALL.E - version 2"){: .img-center loading=lazy }](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/carte_facon_ed_fairburn/DALL.E_mona_misa_2.png){: data-mediabox="gallery-lightbox" data-title="La Joconde par DALL.E - version 2" }
```

2022-09-30 07:31 UTC, igeofr commented on content/articles/2022/2022-09-30_carte_facon_ed_fairburn.md
> +Par contre, on va cette fois opter pour le mode _Éclaircir_ qui conserve sur chacune des composantes RGB celle qui a la plus grande valeur.
```suggestion
Par contre, on va cette fois opter pour le mode `Éclaircir` qui conserve sur chacune des composantes RGB celle qui a la plus grande valeur.
```

2022-09-30 07:31 UTC, igeofr commented on content/articles/2022/2022-09-30_carte_facon_ed_fairburn.md
> +* _surface_hydrographique_
```suggestion
* `batiment`
* `voie_nommee`
* `zone_de_vegetation_
* `troncon_hydrographique`
* `surface_hydrographique`
```

2022-09-30 08:04 UTC, igeofr commented
@Gab-OPenIG si jamais tu veux le relire une dernière fois!
Pour moi c'est ok > publication prévue à 14h

2022-09-30 08:13 UTC, Gab-OPenIG commented
J'y vais ! 

> @Gab-OPenIG si jamais tu veux le relire une dernière fois! Pour moi c'est ok > publication prévue à 14h

2022-09-30 08:19 UTC, Michael-cd30 commented
Précision @Gab-OPenIG , il faut regarder la preview car les dernières corrections ne sont pas dans le pad.

2022-09-30 08:24 UTC, Gab-OPenIG commented
Une ptite coquille [ici](https://preview-pullrequest-709--geotribu-preprod.netlify.app/articles/2022/2022-09-30_carte_facon_ed_fairburn/#les-modes-de-fusion-en-quelques-mots) : disponible dans **_le documention_** --> dans la documentation

2022-09-30 09:13 UTC, Guts commented
@igeofr tu sais mettre en page d'accueil ou je m'en charge ?

2022-09-30 09:36 UTC, igeofr commented
@Guts, non je n'ai pas la manip pour la page d’accueil! Tu peux t'en charger ou m'indiquer la manip?

2022-09-30 09:49 UTC, Guts commented
> @Guts, non je n'ai pas la manip pour la page d’accueil! Tu peux t'en charger ou m'indiquer la manip?

Je le fais dans une branche à part histoire que les commits soient faciles à relire et tu regardes comment j'ai fait ?

2022-09-30 09:58 UTC, Guts requested changes

2022-09-30 09:58 UTC, Guts commented on content/articles/2022/2022-09-30_carte_facon_ed_fairburn.md
> +    - QGis
```suggestion
    - QGIS
```

2022-09-30 09:59 UTC, Guts commented on content/articles/2022/2022-09-30_carte_facon_ed_fairburn.md
> +    - QGis
C'est un nom officiel et le plugin de gestion des tags est sensible à la casse.

2022-09-30 10:10 UTC, Guts approved these changes

2022-09-30 10:28 UTC, Guts requested changes

2022-09-30 10:28 UTC, Guts commented on content/articles/2022/2022-09-30_carte_facon_ed_fairburn.md
> +## Introduction
```suggestion

:calendar: Date de publication initiale : 30 septembre 2022

## Introduction
```

2022-09-30 11:39 UTC, igeofr commented
> Je le fais dans une branche à part histoire que les commits soient faciles à relire et tu regardes comment j'ai fait ?

Oui, on fait comme ça.

2022-09-30 13:02 UTC, Guts approved these changes

2022-09-30 13:03 UTC, merged