Ajout article QGIS zooms circulaires
geotribu/website pull request #750
Opened 2022-11-07 18:44 UTC by jeremieprudhomme

Une traduction en grande partie grâce à https://www.deepl.com mais avec relecture et en essayant de modifier les phrases qui n'avaient pas de sens en français. Ce n'est pas parfait mais compréhensible je pense.

J'ai également repris les captures avec les menus pour les mettre avec les menus en français de QGIS.

**Attention, les images ne sont pas hébergées sur le CDN car je n'ai pas accès.**

Également, j'ai demandé la permission à North Road de traduire leur article mais pas de retour pour le moment.
https://twitter.com/lim_on_air/status/1588864258661838849

2022-11-07 18:59 UTC, aurelienchaumet commented
> > Attention, les images ne sont pas hébergées sur le CDN car je n'ai pas accès.
> 
> Mais que fait la police ! :kissing: @aurelienchaumet 
> 
> Je regarde dans le détail dans la semaine.

😁 On n'en était pas là encore...
T'inquiète je vais m'en occuper 😉

2022-11-08 01:48 UTC, jeremieprudhomme commented
> Également, j'ai demandé la permission à North Road de traduire leur article mais pas de retour pour le moment. https://twitter.com/lim_on_air/status/1588864258661838849
Réponse favorable reçue.
Ça ne me dit pas quelle licence mettre sur l'article étant donné que celui d'origine n'est pas en CC.

@Guts ou @aurelienchaumet vous avez déjà eu ce genre de cas j'imagine, vous mettiez quoi comme licence ?

2022-11-08 06:18 UTC, Guts commented
> Ça ne me dit pas quelle licence mettre sur l'article étant donné que celui d'origine n'est pas en CC.
> 
> @Guts ou @aurelienchaumet vous avez déjà eu ce genre de cas j'imagine, vous mettiez quoi comme licence ?

Je leur ai posé la question : https://twitter.com/geotribu/status/1589864057305460736

2022-11-08 06:29 UTC, Guts commented
D'après ce que tu m'as dit @jeremieprudhomme dans le ticket initial https://github.com/geotribu/website/issues/741#issuecomment-1304501247, je suggère que tu utilises tes propres captures d'écran pour la carte et les données.

L'idéal serait de partager également le Geopackage avec l'ensemble des éléments : projet, mpt, data (un échantillon au moins), etc. On peut mettre ça sur le CDN ou bien sur un dépôt GitHub dédié.

Penses-tu que ce soit jouable ?

2022-11-08 06:43 UTC, Guts requested changes
@jeremieprudhomme voici quelques remarques pour améliorer le rendu : syntaxe markdown, admonition et optimisation des images (pour ce point, j'ai eu la flemme de tout commenter donc je te laisse appliquer à toutes les autres).

2022-11-08 06:43 UTC, Guts commented on content/articles/2022/2022-11-05_zoom_circulaires_mise_en_page_qgis.md
> +_Suite à l'appel de Julien [dans la GeoRDP du 4 novembre](https://static.geotribu.fr/rdp/2022/rdp_2022-11-04/#trucs-et-astuces-sur-le-composeur-dimpression-de-qgis), j'ai tenté de traduire au plus ju
Utilisation d'une admontion pour faire jouli et pas de lien absolu dans les URLs internes (pour le jour où le site reviendra sur https://geotribu.fr).

```suggestion
!!! info "Traduction"
    Suite à l'appel de Julien [dans la GeoRDP du 4 novembre](/rdp/2022/rdp_2022-11-04/#trucs-et-astuces-sur-le-composeur-dimpression-de-qgis), j'ai tenté de traduire au plus juste le [billet de blog](https://north-road.com/2022/11/04/creating-circular-insets-and-other-fun-qgis-layout-tricks/) publié le 4 novembre 2022 par North Road à l'occasion du [30 Day Map Challenge](https://twitter.com/hashtag/30DayMapChallenge) concernant la création de zooms circulaires dans les mises en page de QGIS.
```

2022-11-08 06:43 UTC, Guts commented on content/articles/2022/2022-11-05_zoom_circulaires_mise_en_page_qgis.md
> +_Grâce à la récente popularité du «30 Day Map Challenge», le mois de novembre est devenu synonyme de belles cartes et cartographies.  Au cours de ce mois de novembre, nous allons partager un certain
En général, on évite d'utiliser les mises en forme d'emphase (italique, gras...) pour faire ce genre d'intro.

```suggestion
Grâce à la récente popularité du «30 Day Map Challenge», le mois de novembre est devenu synonyme de belles cartes et cartographies.  Au cours de ce mois de novembre, nous allons partager un certain nombre de conseils et d'astuces qui utilisent certaines fonctionnalités avancées de QGIS pour aider à créer de belles cartes.
```

2022-11-08 06:43 UTC, Guts commented on content/articles/2022/2022-11-05_zoom_circulaires_mise_en_page_qgis.md
> +
Saut de ligne avant l'image et ajout balises pour centrer et optimiser le chargement des images.

```suggestion
Commençons par un exemple de carte. Nous vous présentons ci-dessous un extrait de la [candidature de Brisbane aux Jeux olympiques de 2032](https://stillmed.olympics.com/media/Documents/Olympic-Games/Brisbane-2032/General/IOC-Feasibility-Assessment-Brisbane.pdf?_ga=2.48780838.1295957495.1666960789-1227590087.1665520398) que certains membres de l'équipe de North Road ont contribué à créer (au nom de [SMEC](https://www.smec.com/au/) pour [EKS](https://www.eks.com/)). Cette carte est conçue pour mettre en évidence les sites potentiels dans le sud-est du Queensland et les possibilités de déplacement entre ces régions :

![Plan d'ensemble des sites pour les Jeux olympiques de 2032](https://user-images.githubusercontent.com/9571164/200112536-e938f1aa-e4fc-4959-8952-e6e4e56f4ebf.png "Plan d'ensemble des sites pour les Jeux olympiques de 2032, évaluation de faisabilité du CIO - Jeux olympiques, Brisbane février 2021"){: .img-center loading=lazy }

```

2022-11-08 06:43 UTC, Guts commented on content/articles/2022/2022-11-05_zoom_circulaires_mise_en_page_qgis.md
> +![Carte de base et zoom rectangulaire](https://user-images.githubusercontent.com/9571164/200113058-5c6d24a9-8297-4181-b771-9bdbe3314056.png "Carte de base et zoom rectangulaire")
Idem

```suggestion
Tout d'abord, préparez une mise en page avec une carte principale et un zoom. Veillez à ce que celui-ci soit suffisamment grand pour couvrir le cercle souhaité :

![Carte de base et zoom rectangulaire](https://user-images.githubusercontent.com/9571164/200113058-5c6d24a9-8297-4181-b771-9bdbe3314056.png "Carte de base et zoom rectangulaire"){: .img-center loading=lazy }
```

2022-11-08 06:43 UTC, Guts commented on content/articles/2022/2022-11-05_zoom_circulaires_mise_en_page_qgis.md
> +![Capture d'écran du menu QGIS Ajouter Ellipse](https://user-images.githubusercontent.com/9571164/200113152-5de641be-2847-4e7f-bce0-b141daa264e8.PNG "Menu Ajouter Ellipse")
```suggestion
Dans la barre d'outils de mise en page, cliquez sur le bouton Ajouter Forme, puis sélectionnez Ajouter Ellipse :

![Capture d'écran du menu QGIS Ajouter Ellipse](https://user-images.githubusercontent.com/9571164/200113152-5de641be-2847-4e7f-bce0-b141daa264e8.PNG "Menu Ajouter Ellipse"){: .img-center loading=lazy }
```

2022-11-08 06:43 UTC, Guts commented on content/articles/2022/2022-11-05_zoom_circulaires_mise_en_page_qgis.md
> +_Et voilà ! Ces deux techniques peuvent vous aider à pousser plus loin vos créations de cartes QGIS et à faciliter la création de belles cartographies directement dans QGIS lui-même. Si vous avez tro
No emphasis

```suggestion
Et voilà ! Ces deux techniques peuvent vous aider à pousser plus loin vos créations de cartes QGIS et à faciliter la création de belles cartographies directement dans QGIS lui-même. Si vous avez trouvé ces conseils utiles, gardez un œil sur ce blog car nous publierons d'autres conseils et astuces au cours du mois de novembre. Et n'oubliez pas de suivre le [30 Day Map Challenge](https://30daymapchallenge.com/) pour découvrir tout un assortiment de cartes absolument époustouflantes.
```

2022-11-08 06:43 UTC, Guts commented on content/articles/2022/2022-11-05_zoom_circulaires_mise_en_page_qgis.md
> +{% include "licenses/default.md" %}
Il manque ton bloc auteur : https://static.geotribu.fr/contribuer/guides/authoring/#bloc-auteur

2022-11-08 06:43 UTC, Guts commented on content/articles/2022/2022-11-05_zoom_circulaires_mise_en_page_qgis.md
> +(Vous pouvez en savoir plus sur [les courbes et les arcs SVG](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths) sur MDN)
```suggestion
!!! tip
    Vous pouvez en savoir plus sur [les courbes et les arcs SVG](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths) sur le site de ressources MDN.
```

2022-11-08 11:35 UTC, aurelienchaumet commented
> D'après ce que tu m'as dit @jeremieprudhomme dans le ticket initial [#741 (comment)](https://github.com/geotribu/website/issues/741#issuecomment-1304501247), je suggère que tu utilises tes propres captures d'écran pour la carte et les données.
> 
> L'idéal serait de partager également le Geopackage avec l'ensemble des éléments : projet, mpt, data (un échantillon au moins), etc. On peut mettre ça sur le CDN ou bien sur un dépôt GitHub dédié.
> 
> Penses-tu que ce soit jouable ?

D'ailleurs Jérémie, tu peux m'envoyer tout ça, et je les collerai dans le CDN en modifiant les liens dans ton article 😉

2022-11-08 19:52 UTC, jeremieprudhomme commented on content/articles/2022/2022-11-05_zoom_circulaires_mise_en_page_qgis.md
> +{% include "licenses/default.md" %}
Oui, il faut que je prenne le temps de le créer 😀

2022-11-09 11:37 UTC, Guts commented
@jeremieprudhomme on ne pourra pas merger tant que ton fichier auteur n'est pas dans la même branche. 2 options :

- tu fais pointer ta PR #754 sur la branche de ton article (a priori tu n'as pas créé de branche dédiée sur ton fork donc bon...)
- tu ajoutes ton fichier jpru.md à la branche de ton article (d'où émane la présente PR) et tu fermes la PR #754

2022-11-09 14:52 UTC, jeremieprudhomme commented
> @jeremieprudhomme on ne pourra pas merger tant que ton fichier auteur n'est pas dans la même branche. 2 options :
> 
>     * tu fais pointer ta PR [Create jpru.md #754](https://github.com/geotribu/website/pull/754) sur la branche de ton article (a priori tu n'as pas créé de branche dédiée sur ton fork donc bon...)
> 
>     * tu ajoutes ton fichier jpru.md à la branche de ton article (d'où émane la présente PR) et tu fermes la PR [Create jpru.md #754](https://github.com/geotribu/website/pull/754)

Pas sûr de comprendre comment faire la première option. En effet je n'ai pas de branche spécifique dans mon fork pour l'article.
Du coup j'ai créé le fichier jpru.md sur ma branche master.

2022-11-09 14:58 UTC, Guts commented
> Pas sûr de comprendre comment faire la première option.

Désolé si c'était pas clair, je réponds entre 2 tâches...

> En effet je n'ai pas de branche spécifique dans mon fork pour l'article.

C'est une bonne habitude à prendre car master peut être modifiée par une autre PR entre-temps et ça rend la résolution des conflits de modifications plus délicate.

> Du coup j'ai créé le fichier jpru.md sur ma branche master.

Top !

2022-11-14 13:12 UTC, aurelienchaumet requested changes
Salut Jérémie, je viens d'ajouter les images sur le cdn et j'ai donc modifié les liens vers les images dans le fichier.
Quelques remarques/coquilles qui trainent encore, tu verras je t'ai mis des remarques.

Concernant la structure de l'article, sans pour autant remettre en question ce que Northroad a rédigé, il faudrait peut-être redécoupé la 1ère partie en intro et ajouter quelques sous-parties pour aérer un peu plus l'article ?

Un dernier truc, si on veut publier l'article pour demain, il faudra penser à modifier le nom du fichier à la date de publication 😉

2022-11-14 13:16 UTC, aurelienchaumet commented
Encore un truc, concernant la licence, tu peux mettre la beerware qui n'a rien de bien méchant en termes de droit

2022-11-16 15:22 UTC, Guts commented
@jeremieprudhomme peux-tu voir les remarques d' @aurelienchaumet stp ? ça se bouscule au portillon https://static.geotribu.fr/contribuer/introduction/#isso-198 :wink:

2022-11-16 16:50 UTC, jeremieprudhomme commented on content/articles/2022/2022-11-05_zoom_circulaires_mise_en_page_qgis.md
> +Pour les utilisateurs avancés, nous avons une autre astuce amusante... et par amusante nous voulons dire « jouons avec les radians » ! Ici, nous allons créer un titre avec un arrière-plan calé sur le
Jouons avec les courbes me parait pas mal en effet. Même si radian existe bien dans la langue française on l'utilise pas trop en effet.

2022-11-16 16:51 UTC, jeremieprudhomme commented on content/articles/2022/2022-11-05_zoom_circulaires_mise_en_page_qgis.md
> +Pour les utilisateurs avancés, nous avons une autre astuce amusante... et par amusante nous voulons dire « jouons avec les radians » ! Ici, nous allons créer un titre avec un arrière-plan calé sur le
```suggestion
Pour les utilisateurs avancés, nous avons une autre astuce amusante... et par amusante nous voulons dire « jouons avec les courbes » ! Ici, nous allons créer un titre avec un arrière-plan calé sur le contour de notre zoom circulaire. Cela demande un peu de doigté, mais le résultat final peut être visuellement remarquable ! Nous allons utiliser l'élément HTML de la mise en page de QGIS pour créer un dessin avancé. Une certaine expérience du codage HTML et CSS est donc souhaitable. (Une autre approche serait d'utiliser une application d'illustration vectorielle comme Inkscape, et d'ajouter votre titre et votre fond circulaire en tant qu'élément SVG dans la mise en page d'impression).
```

2022-11-16 16:58 UTC, jeremieprudhomme commented on content/articles/2022/2022-11-05_zoom_circulaires_mise_en_page_qgis.md
> +Une technique qui peut améliorer considérablement l'apparence des cartes consiste à remplacer les zooms rectangulaires par des formes plus organiques, telles que des cercles ou des ovales.
```suggestion
Une technique qui peut améliorer considérablement l'apparence des cartes consiste à remplacer les zooms rectangulaires par des formes plus douces; inspirées par la nature, telles que des cercles ou des ovales.
```
Ça vient du design organique qui est existe vraiment mais peut-être pas trop utilisé dans  le langage courant.

2022-11-16 17:21 UTC, Guts commented
@jeremieprudhomme pour renommer le fichier, si tu passes par l'interface web de Github, ça se passe en haut quand t'es en mode édition :

![image](https://user-images.githubusercontent.com/1596222/202249446-9107609e-f6f0-4df7-a68e-7a3b20966b2b.png)

Tu peux mettre 2022-11-17_zoom_circulaires_mise_en_page_qgis.md

2022-11-16 17:22 UTC, Guts commented on content/articles/2022/2022-11-05_zoom_circulaires_mise_en_page_qgis.md
> +date: "2022-11-05 13:30"
```suggestion
date: "2022-11-17 13:30"
```

2022-11-16 17:22 UTC, Guts commented on content/articles/2022/2022-11-05_zoom_circulaires_mise_en_page_qgis.md
> +:calendar: Date de publication initiale : 8 novembre 2022
```suggestion
:calendar: Date de publication initiale : 17 novembre 2022
```

2022-11-16 18:27 UTC, jeremieprudhomme commented on content/articles/2022/2022-11-05_zoom_circulaires_mise_en_page_qgis.md
> +date: "2022-11-05 13:30"
done

2022-11-16 18:27 UTC, jeremieprudhomme commented on content/articles/2022/2022-11-05_zoom_circulaires_mise_en_page_qgis.md
> +:calendar: Date de publication initiale : 8 novembre 2022
done

2022-11-16 18:33 UTC, jeremieprudhomme commented
> Salut Jérémie, je viens d'ajouter les images sur le cdn et j'ai donc modifié les liens vers les images dans le fichier. Quelques remarques/coquilles qui trainent encore, tu verras je t'ai mis des remarques.
> 
> Concernant la structure de l'article, sans pour autant remettre en question ce que Northroad a rédigé, il faudrait peut-être redécoupé la 1ère partie en intro et ajouter quelques sous-parties pour aérer un peu plus l'article ?
> 
> Un dernier truc, si on veut publier l'article pour demain, il faudra penser à modifier le nom du fichier à la date de publication 😉

J'ai revu l'organisation des titres/sous-titres pour avoir un menu plus d'article sympa.

2022-11-16 19:43 UTC, Guts commented
Je me suis permis de :

- ajouter la balise vignette sur ton portrait
- changer l'image d'en-tête qui pointait tjs sur une image twitter
- utiliser l'image déjà téléversée dans la précédente RDP pour éviter de stocker des images en double. En plus, elle est bien plus légère : 97ko contre 287ko. @aurelienchaumet pense à optimiser les images stp avant de les uploader sur le CDN

2022-11-16 19:46 UTC, Guts commented
> J'ai revu l'organisation des titres/sous-titres pour avoir un menu plus d'article sympa.

C'est top !

2022-11-16 20:04 UTC, jeremieprudhomme commented
Merci @Guts pour ces modifications.
C'est normal ce check non successful https://github.com/geotribu/website/actions/runs/3482621607/jobs/5825152194 ?

Et faut-il bien faire un "Update branch with merge commit" comme c'est indiqué que This branch is out-of-date with the base branch ?

2022-11-16 20:13 UTC, Guts commented
> Merci @Guts pour ces modifications.
> C'est normal ce check non successful https://github.com/geotribu/website/actions/runs/3482621607/jobs/5825152194 ?

Tu peux ignorer. En gros, y'a un souci avec le jeton d'authentification de cette étape-ci. Elle utilise le jeton généré par l'auteur de la PR mais qui n'a pas les droits suffisants pour commenter. Enfin je crois, j'ai pas encore regardé :innocence: 

> Et faut-il bien faire un "Update branch with merge commit" comme c'est indiqué que This branch is out-of-date with the base branch ?

Oui. Done.

2022-11-17 11:04 UTC, aurelienchaumet approved these changes

2022-11-17 11:53 UTC, merged