Article: Retour vers le futur du 30DayMapChallenge
geotribu/website pull request #816
Opened 2023-01-15 14:20 UTC by gounux

Article d'humeur via une rétrospective profane et gratuite sur les perles du 30DayMapChallenge de 2022

2023-01-16 08:48 UTC, Guts requested changes
Merci Guilhem.

J'ai fait rapidement une passe sur les grosses erreurs de syntaxe ou de structure, notamment celles qui empêchent de builder.

Une fois corrigées, je demanderai à notre groupe de relecture de se pencher sur le fond :)

2023-01-16 08:48 UTC, Guts commented on content/articles/2023/2023-01-17_retour-vers-le-futur-du-30dmc.md
> +date: "2023-01-17 10:00"
La date semble trop ambitieuse. Il faut laisser plus de temps aux relecteur/ices (bénévoles).

2023-01-16 08:48 UTC, Guts commented on content/articles/2023/2023-01-17_retour-vers-le-futur-du-30dmc.md
> +date: "2023-01-17 10:00"
Je propose le mardi 24 :

```suggestion
date: "2023-01-24 10:00"
```

Penser à changer également le nom du fichier et la ligne 22.

2023-01-16 08:48 UTC, Guts commented on content/articles/2023/2023-01-17_retour-vers-le-futur-du-30dmc.md
> +
1. Créer un fichier gall.md dans le dossier content/team
2. l'inclure via la syntaxe
3. déplacer l'image du portrait sur le CDN dans le dossier https://cdn.geotribu.fr/tinyfilemanager.php?p=internal%2Fcontributeurs

Voir https://contribuer.geotribu.fr/guides/authoring/#bloc-auteur

2023-01-16 08:48 UTC, Guts commented on content/articles/2023/2023-01-17_retour-vers-le-futur-du-30dmc.md
> +À cette occasion, les :two_women_holding_hands: _[géotribuns](https://static.geotribu.fr/team/)_ :two_women_holding_hands: n'avaient d'ailleurs pas manqué d'aborder [en long](/rdp/2022/rdp_2022-10-21
Les liens internes (càd vers d'autres contenus du site) doivent être relatifs : https://contribuer.geotribu.fr/guides/markdown_quality/#liens-internes-relatifs

C'est ce qui provoque l'erreur du build : https://github.com/geotribu/website/actions/runs/3925313515/jobs/6710151026#step:6:1157

2023-01-16 10:21 UTC, Guts requested changes

2023-01-16 10:21 UTC, Guts commented on content/articles/2023/2023-01-17_retour-vers-le-futur-du-30dmc.md
> +À cette occasion, les :two_women_holding_hands: _[géotribuns](https://static.geotribu.fr/team/)_ :two_women_holding_hands: n'avaient d'ailleurs pas manqué d'aborder [en long](/rdp/2022/rdp_2022-10-21
```suggestion
À cette occasion, les :two_women_holding_hands: _[géotribuns](/team/)_ :two_women_holding_hands: n'avaient d'ailleurs pas manqué d'aborder [en long](/rdp/2022/rdp_2022-10-21/#cest-bientot-le-30daymapchallenge) et [en large](/rdp/2022/rdp_2022-11-18/#30daymapchallenge) la tenue de cet évènement, particulièrement apprécié par la communauté :world_map:. Un évènement décousu et attendu de longue date, mais pas cousu de fil blanc, bien au contraire : découvrons ensemble les décoctions géoréférencées et autres remèdes cartographiques concoctés par les herboristes véhéments qui ont participé au challenge :herb:
```

2023-01-16 10:39 UTC, gounux commented
> Merci Guilhem.
> 
> J'ai fait rapidement une passe sur les grosses erreurs de syntaxe ou de structure, notamment celles qui empêchent de builder.
> 
> Une fois corrigées, je demanderai à notre groupe de relecture de se pencher sur le fond :)

Merci @Guts pour les bonnes pratiques et les suggestions appliquées ;)

2023-01-17 04:25 UTC, lbartoletti commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +À cette occasion, les :two_women_holding_hands: _[géotribuns](/team/)_ :two_women_holding_hands: n'avaient d'ailleurs pas manqué d'aborder [en long](/rdp/2022/rdp_2022-10-21/#cest-bientot-le-30daymap
> Un évènement décousu et attendu de longue date, mais pas cousu de fil blanc, bien au contraire

Je ne comprends pas la phrase

2023-01-17 04:28 UTC, lbartoletti commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +:fire: Sous forme de défis ludiques, sur un ton jovial, fédérateur, social, sans souci mais malheureusement sans saucisses à l'ail ni halal inch'Allah, et ce pour la quatrième édition maintenant d'un
Je couperai la phrase en deux.

2023-01-17 04:28 UTC, lbartoletti commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +:point_right: Ce qui, au doigt mouillé, revient à environ :one: sujet par jour, one topic for teh day ([one two tri viva la cartographie](https://youtu.be/MQndYND2s9M)), que doivent suivre les cartes
```suggestion
:point_right: Ce qui, au doigt mouillé, revient à environ :one: sujet par jour, one topic for the day ([one two tri viva la cartographie](https://youtu.be/MQndYND2s9M)), que doivent suivre les cartes postées sur le achetague, et ce tout au long des 30 jours que compte le mois de [novembre](https://fr.wikipedia.org/wiki/Tom_Novembre).
```

2023-01-17 04:29 UTC, lbartoletti commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +:calendar: _À ce propos, il pourrait être futile de noter que si le 30DayMapChallenge se déroulait en [février](https://fr.wikipedia.org/wiki/Ann%C3%A9e_bissextile#R%C3%A8gle_actuelle) ou en [décembr
```suggestion
:calendar: _À ce propos, il pourrait être futile de noter que si le 30DayMapChallenge se déroulait en [février](https://fr.wikipedia.org/wiki/Ann%C3%A9e_bissextile#R%C3%A8gle_actuelle) ou en [décembre](https://www.senscritique.com/bd/32_decembre_La_Tetralogie_du_monstre_tome_2/193399), il porterait probablement un nom différent, toutes choses égales par ailleurs. Mais avec des si on mettrait Paris en bouteille, ce qui aurait cependant l'avantage de mettre certain.e.s au sec en ces temps bien arrosés... enfin, au niveau de la météo du moins_ #DryJaruany
```

2023-01-17 04:32 UTC, lbartoletti commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +:sunglasses: Les sujets sont annoncés quelques semaines à l'avance, et l'idée est de s'amuser, de se détendre, de prendre du plaisir. Le choix des [outils](https://30daymapchallenge.com/resources/#to
De ma compréhension, il y a, en effet, une préférence vers les outils open source, mais ce n'est pas une obligation. Tu peux même utiliser autre chose que de l'informatique.

2023-01-17 04:34 UTC, lbartoletti commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +:sound: Le _#30DayMapChallenge_, c'est aux géomaniacs ce que le _[#harlemshake](https://youtu.be/iXCl0fY-HfQ)_ ou le _[#wayawayachallenge](https://www.tiktok.com/@mrgoodvibesonly/video/71410411334838
```suggestion
:sound: Le _#30DayMapChallenge_, c'est aux géomaniacs ce que le _[#harlemshake](https://youtu.be/iXCl0fY-HfQ)_ ou le _[#wayawayachallenge](https://www.tiktok.com/@mrgoodvibesonly/video/7141041133483871493)_ sont aux ambianceurs. Cette année, le [bruit](https://youtu.be/l5ozpoOmvNc) et les [décibels](https://youtu.be/3ag62f8Vr14) mesurés sur les [fréquences métriques](https://30daymapchallenge.com/statistics/) du mot dièse ont pu s'avérer assourdissants, et ce sans aucune fausse note ni bémol à la clef. Les géochefs d'orchestre ont investi la sphère en masse : ils étaient des dizaines de milliers selon les organisateurs, seulement [4326](https://spatialreference.org/ref/epsg/4326/) selon les [CRS](https://fr.wikipedia.org/wiki/Syst%C3%A8me_de_coordonn%C3%A9es_(cartographie)#Les_codes_EPSG)... On connaît la :notes: !
```

Très joli, le 4326 selon les CRS :)

2023-01-17 04:35 UTC, lbartoletti commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +:large_blue_diamond: rencontrer les cartes  les plus :fire: de ta région
```suggestion
:large_blue_diamond: rencontrer les cartes les plus :fire: de ta région
```

2023-01-17 04:38 UTC, lbartoletti commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +:large_blue_diamond: libérer la créativité, déchaîner l'audace et développer la sensibilité du cartomaniac qui sommeille en chacun de nous, afin de nous élever collectivement dans une transe céleste
maniac : https://www.youtube.com/watch?v=AIgJenz0ZK4

2023-01-17 04:42 UTC, lbartoletti commented on content/team/gall.md
> +:confused: Au fil d'un parcours professionnel éclectique , pas tibulaire et pas toujours binaire, je suis maintenant ingénieur et développeur indépendant. D'abord (mal) éduqué par Java :yum: (mon lan
```suggestion
:confused: Au fil d'un parcours professionnel éclectique, pas tibulaire et pas toujours binaire, je suis maintenant ingénieur et développeur indépendant. D'abord (mal) éduqué par Java :yum: (mon langage maternel, le croque-mitaine des devs :pray: Namasté :pray: Amen :pray:), j'ai par la suite eu la chance de pouvoir découvrir les joies diverses des SIG, pour m'y prendre de passion et m'y spécialiser : python, PostGreSQL/PostGIS, QGIS... et patati et patata.
```

2023-01-17 04:43 UTC, lbartoletti commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +Ou encore rêvasser, s'évader dans des vapes reprojettées tout au long d'un mois de novembre qu'on aime aussi pour ses feuilles qui se colorent, puis qui tombent lentement, paisiblement, dans la subti
Ça mériterait d'être mis en forme sous forme de poème :feather:

2023-01-17 04:44 UTC, lbartoletti commented
Merci Guilhem ! Ça fait plaisir de te retrouver par ici :)

2023-01-17 09:30 UTC, gounux commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +À cette occasion, les :two_women_holding_hands: _[géotribuns](/team/)_ :two_women_holding_hands: n'avaient d'ailleurs pas manqué d'aborder [en long](/rdp/2022/rdp_2022-10-21/#cest-bientot-le-30daymap
Au-delà du mauvais jeu de mot avec "cousu", je dirais que le sens de la phrase est le suivant: le 30dmc est une sorte de patchwork de cartes diverses et variées, mais on ne sait jamais à quoi s'attendre et sur quoi on va tomber ;)

2023-01-17 09:34 UTC, gounux commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +:sunglasses: Les sujets sont annoncés quelques semaines à l'avance, et l'idée est de s'amuser, de se détendre, de prendre du plaisir. Le choix des [outils](https://30daymapchallenge.com/resources/#to
C'est clair, je suis d'accord, je voulais mettre une petite touche d'ironie pas forcément bien placée. Et qui aurait peut-être plutôt vocation à être adressée aux logiciels propriétaires

2023-01-17 09:38 UTC, gounux commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +:large_blue_diamond: libérer la créativité, déchaîner l'audace et développer la sensibilité du cartomaniac qui sommeille en chacun de nous, afin de nous élever collectivement dans une transe céleste
Emballez, c'est pesé !

2023-01-17 09:40 UTC, gounux commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +:point_right: Ce qui, au doigt mouillé, revient à environ :one: sujet par jour, one topic for teh day ([one two tri viva la cartographie](https://youtu.be/MQndYND2s9M)), que doivent suivre les cartes
C'est [fait exprès](https://en.wikipedia.org/wiki/Teh) :disappointed:

2023-01-17 09:47 UTC, lbartoletti commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +:point_right: Ce qui, au doigt mouillé, revient à environ :one: sujet par jour, one topic for teh day ([one two tri viva la cartographie](https://youtu.be/MQndYND2s9M)), que doivent suivre les cartes
Ah, je ne connaissais pas !

2023-01-17 09:54 UTC, gounux commented
> Merci Guilhem ! Ça fait plaisir de te retrouver par ici :)

Merci et pareilllement ;)

2023-01-17 11:04 UTC, Guts commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +:point_right: Ce qui, au doigt mouillé, revient à environ :one: sujet par jour, one topic for teh day ([one two tri viva la cartographie](https://youtu.be/MQndYND2s9M)), que doivent suivre les cartes
Moi non plus. PEux-tu ajouter le lien de la réf dessus ?

2023-01-17 14:56 UTC, gounux commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +:point_right: Ce qui, au doigt mouillé, revient à environ :one: sujet par jour, one topic for teh day ([one two tri viva la cartographie](https://youtu.be/MQndYND2s9M)), que doivent suivre les cartes
C'est fait

2023-01-28 09:39 UTC, igeofr commented
Bonjour @gounux,
Je viens de lire l'article que je trouve excellent avec une bonne dose de références!
Deux petites choses :  
- pour terminer, j'aurai bien vu une ouverture sur le [MapFailbruaryChallenge](https://github.com/datagistips/MapFailbruaryChallenge) lancé par @datagistips.
- pour les images, mettre plutôt `{: .img-center loading=lazy }` à la place `{: loading=lazy }`

2023-01-28 10:01 UTC, Guts requested changes
Quelques petites remarques pour faire remonter l'intro (si tu es OK) mais surtout changer l'image d'en-tête histoire qu'elle soit adaptée.

Sinon, j'aime bien quand on peut naviguer par le menu dans un article, surtout quand il est long. Donc je trouve que ça manque de titres de niveau 2 voire 3 :

![image](https://user-images.githubusercontent.com/1596222/215260175-b1d91f85-19ea-4b4e-91d3-37677317acd0.png)

Mais c'est peut-être un TOC qu'il faut que je soigne :)

2023-01-28 11:59 UTC, gounux commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +image: "https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_thumbdesc.png"
Je l'ai redimensionnée de sorte à ce qu'elle ait les dimensions 800x400, en gardant la transparence derrière. Je sais pas si c'est toléré mais c'est vrai que cette carte est belle

2023-01-28 12:00 UTC, gounux commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +![20: My favourite](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_02_d20.png){: loading=lazy}
C'est remis en forme en suivant tes suggestions, merci !

2023-01-28 12:02 UTC, gounux commented
> Bonjour @gounux, Je viens de lire l'article que je trouve excellent avec une bonne dose de références! Deux petites choses :
> 
>     * pour terminer, j'aurai bien vu une ouverture sur le [MapFailbruaryChallenge](https://github.com/datagistips/MapFailbruaryChallenge) lancé par @datagistips.
> 
>     * pour les images, mettre plutôt `{: .img-center loading=lazy }` à la place `{: loading=lazy }`

Merci @igeofr pour les retours. Et pour la suggestion du MapFailbruaryChallenge en fin : c'est vrai que ça lance une très bonne transition, tout en étant dans l'ambiance de l'article ;)

2023-01-28 12:03 UTC, gounux commented on content/articles/2023/2023-01-24_retour-vers-le-futur-du-30dmc.md
> +![20: My favourite](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/retrospective_30dmc_2022/30dmc_2022_retro_02_d20.png){: loading=lazy}
Est-ce que les modifs apportées correspondent à ce que tu avais en (en)tête ?

2023-01-28 12:07 UTC, gounux commented
> Quelques petites remarques pour faire remonter l'intro (si tu es OK) mais surtout changer l'image d'en-tête histoire qu'elle soit adaptée.
> 
> Sinon, j'aime bien quand on peut naviguer par le menu dans un article, surtout quand il est long. Donc je trouve que ça manque de titres de niveau 2 voire 3 :
> 
> ![image](https://user-images.githubusercontent.com/1596222/215260175-b1d91f85-19ea-4b4e-91d3-37677317acd0.png)
> 
> Mais c'est peut-être un TOC qu'il faut que je soigne :)

Merci @Guts pour le retour. On a tous nos TOC... J'essaie de suivre le tien avec quelques titres dans le même esprit que l'article.

Sinon j'ai changé la date pour le mardi 31 janvier, est-ce que ça vous convient ?

2023-01-28 14:30 UTC, Guts approved these changes

2023-01-28 14:32 UTC, Guts commented
Merci @gounux pour les changements !

Est-ce qu'on ajouterait pas 2022 au titre histoire de savoir sur quelle édition ça porte ?

> Sinon j'ai changé la date pour le mardi 31 janvier, est-ce que ça vous convient ?

J'allais même te proposer de publier aujourd'hui et de communiquer quand tu veux dessus courant semaine prochaine, sachant qu'ainsi ça partira avec la newsletter lundi matin.

A noter qu'on doit publier notre billet carte de voeux avant le 1er février donc c'est mieux si les 2 contenus ne se carambolent pas trop.


Tu nous dis !

2023-01-28 15:12 UTC, gounux commented
> Est-ce qu'on ajouterait pas 2022 au titre histoire de savoir sur quelle édition ça porte ?

C'est vrai, la mémoire numérique est sélective elle aussi ..

> J'allais même te proposer de publier aujourd'hui et de communiquer quand tu veux dessus courant semaine prochaine, sachant qu'ainsi ça partira avec la newsletter lundi matin.
> 
> A noter qu'on doit publier notre billet carte de voeux avant le 1er février donc c'est mieux si les 2 contenus ne se carambolent pas trop.
> 
> Tu nous dis !

Super, feu alors :fire:

2023-01-28 15:27 UTC, merged