Article :  Portail d'accès aux données Sentinel passé et évolutions
geotribu/website pull request #835
Opened 2023-01-26 11:10 UTC by ndavid

Une proposition d'article retraçant l'historique des portails d'accès aux données Copernicus/Sentinel à l'occasion du lancement du nouveau portail dataspace.copernicus.eu.

Je ne fait pas partie des entreprises ou organismes gérant ces différents portails d'accès, par contre je suis un utilisateur assez ancien et j'ai souvent des questions sur le sujet de la part de personnes qui découvrent les images sentinel d'où cette idée d'article (type billet)

L'article est finalement assez long donc je ne sais pas si vous préférez que cela soit découpé en plusieurs parties ou bien que j'essaye de faire plus court. 
Je n'ai pas mis d'images ou d'illustrations pour le moment mais je peux en trouver et en ajouter si vous pensez que cela manque un peu. 
Il me reste à refaire une bonne passe de correction orthographe/grammaire mais je préfère le soumettre rapidement pour voir si le contenu convient.

2023-01-26 18:43 UTC, Guts commented
Bonsoir @ndavid ,

Merci pour la proposition d'article. 

Désolé pour le bruit, j'ai profité de votre PR pour corriger le bug que vous aviez repéré et surtout enfin corrigé notre CI qui, pour de sombres raisons de token en lecture seule depuis des forks, faisait planter systématiquement le linter même quand le markdown est nique.

Bref, maintenant, on peut se concentrer sur le contenu :)

A vous @geotribu/relecture !

2023-01-27 08:03 UTC, lbartoletti reviewed
Merci pour cet article très intéressant !

J'ai fait quelques propositions, principalement d'orthotypographie.

2023-01-27 08:03 UTC, lbartoletti commented on content/articles/2023/2023-01-27_portails-copernicus-passee-futur.md
> +raster (de type calculatrice rasterà, cela permet par exemple de calculer à la
```suggestion
raster (de type calculatrice raster, cela permet par exemple de calculer à la
```

2023-01-27 08:03 UTC, lbartoletti commented on content/articles/2023/2023-01-27_portails-copernicus-passee-futur.md
> +    beaucoup de ces nouveaux services sont en partie issus de travaux
```suggestion
    Beaucoup de ces nouveaux services sont en partie issus de travaux
```

2023-01-27 08:03 UTC, lbartoletti commented on content/team/ndavid.md
> +Géomaticien et photogramméètre formation, je travaille à l'IGN depuis 2006 ou j'ai commencé par faire du Lidar (aériens, mobile, terrestre ..) au service de la recherche IGN, j'ai ensuite participer
```suggestion
Géomaticien et photogrammètre en formation, je travaille à l'IGN depuis 2006 ou j'ai commencé par faire du Lidar (aériens, mobile, terrestre ..) au service de la recherche IGN, j'ai ensuite participé à la mise en place de la chaine de production OCSGE (Occupation du Sol). Depuis 2019, je suis au service de l'innovation principalement sur des thématiques télédétection et intelligence articielle.
```

2023-01-27 14:23 UTC, ndavid commented on content/articles/2023/2023-01-27_portails-copernicus-passee-futur.md
> +* une **infrastructure cloud** : soit un accès à des serveurs de calcul et du stockage de données, etc.. . Donc des services de type OVH/Orange cloud/... ou Google/Amazon.
Oui j'ai du le penser comme deux catégories différentes en écrivant mais c'est vrai que ce n'est pas très justifié donc je prends la suggestion.

2023-01-27 15:01 UTC, ndavid commented on content/articles/2023/2023-01-27_portails-copernicus-passee-futur.md
> +Le premier service d'accès aux données a été [scihub](https://scihub.copernicus.eu/) ouvert en 2014 pour la diffusion des données du premier satellite Sentinel-1A.
Bonne remarque. Officiellement c'est "Open Acess Hub" mais la plupart des personnes disent "scihub" comme c'est l'url d'accès et surtout vu que c'est plus court à dire. Je rajoute une ligne pour clarifier cela.

2023-01-27 15:08 UTC, ndavid commented on content/articles/2023/2023-01-27_portails-copernicus-passee-futur.md
> +!!! warning
effectivement c'est plus cohérent de le mettre à la première mention

2023-01-27 15:42 UTC, ndavid commented on content/articles/2023/2023-01-27_portails-copernicus-passee-futur.md
> +soit par exemple les données servant à la production des données Corinne
oui tournure pas très claire, je reformule.

2023-01-27 16:43 UTC, ndavid commented on content/articles/2023/2023-01-27_portails-copernicus-passee-futur.md
> +notamment citer [les produits d'occupation du sol](https://land.copernicus.eu) comme Corinne Land Cover, produit
fait

2023-01-27 16:44 UTC, ndavid commented on content/articles/2023/2023-01-27_portails-copernicus-passee-futur.md
> +PEPS et THEIA.
ajouté

2023-01-28 10:11 UTC, igeofr reviewed
Bonjour @ndavid 
Article très intéressant, j'ai proposé quelques ajustements.
Deux remarques générales : 
- il faudrait supprimer les retours à la ligne inutiles,
- je pense que ce serait bien d'ajouter une ou deux images pour illustrer.

2023-01-28 10:11 UTC, igeofr commented on content/articles/2023/2023-01-27_portails-copernicus-passee-futur.md
> +* RHEA
Ajouter le lien vers le site web des industriels.

2023-01-28 10:11 UTC, igeofr commented on content/articles/2023/2023-01-27_portails-copernicus-passee-futur.md
> +évoluer et être maintenant "Copernicus Data Space Ecosystem" associé à l'url dataspace.copernicus.eu.
```suggestion
évoluer et être maintenant "Copernicus Data Space Ecosystem" associé à l'url [dataspace.copernicus.eu](https://dataspace.copernicus.eu/).
```

2023-01-28 14:39 UTC, Guts commented on content/articles/2023/2023-01-27_portails-copernicus-passee-futur.md
> +image: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.copernicus.eu%2Fen&psig=AOvVaw15niRUcSg8Zs1jzufbxn2h&ust=1674806243021000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCKCorMvh5PwCFQAAAAAdAAAAA
Ou sur la PR, en description ou en commentaire

2023-01-28 14:43 UTC, Guts commented
Bonjour @ndavid,

> L'article est finalement assez long donc je ne sais pas si vous préférez que cela soit découpé en plusieurs parties ou bien que j'essaye de faire plus court.

Perso, les articles longs ne me dérangent pas mais d'expérience ils sont rarement lus jusqu'au bout... Le scinder permettrait d'améliorer les chances de faire passer le message et de cibler le lectorat : ceux qui aiment avoir l'historique et les autres qui aiment être spoilés ;) ! Comment ça, le monde n'est pas aussi binaire ?!

> Je n'ai pas mis d'images ou d'illustrations pour le moment mais je peux en trouver et en ajouter si vous pensez que cela manque un peu.

Je trouve en effet que cela manque d'images, logso et illustrations. Vous pouvez les glisser/déposer dans la description de la PR en indiquant où l'insérer et on s'occupera de les intégrer.

2023-01-30 22:01 UTC, Guts commented
Bonsoir, 

Inutile de faire des lignes de 80 caractères en effet. 
Concernant les retours à la ligne, je n'ai pas encore regardé. 

Mais globalement, tu peux t'inspirer d'un article déjà publié, dont la structure et la mise en page te convient puis regarder dans les sources (icône crayon en haut de chaque page sur Geotribu) 

> *   **scinder l'article** : ok pour le scinder, est-ce qu'une découpe en trois articles vous semblerait bien ? :   
>     1 - Rappels sur les données copernicus sentinel
>     2 - Historique sur l'accès aux données Sentinel
>     3 - Nouveau portail d'accès sentinel et description fonctionnalités ?

Niquel.

2023-01-31 15:29 UTC, Guts commented
@ndavid je pense qu'il est préférable de faire la publication des 3 articles en 3 étapes et donc 3 PR.

On peut relire l'ensemble ici puis séparer une fois qu'on a terminé.

2023-02-10 08:37 UTC, igeofr reviewed
Merci @ndavid 
Je viens de déposer les images sur notre cdn. 
Il faut ajouter le chemin complet vers les images `https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/`, j'ai proposé des modifications mais il en reste peut-être.

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +![Orthophotographie RVB sur Clermont-Ferrand](copernicus_data/clermont_ferrand_ortho_a.jpg "Orthophotographie RVB sur Clermont-Ferrand - Crédits : IGN"){: .img-center loading=lazy }
```suggestion
![Orthophotographie RVB sur Clermont-Ferrand](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/clermont_ferrand_ortho_a.jpg "Orthophotographie RVB sur Clermont-Ferrand - Crédits : IGN"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +![Corinne land Cover sur Clermont-Ferrand](copernicus_data/clermont_ferrand_CLC18_a.jpg "Données Corinne Land Cover 2018 sur Clermont-Ferrand - Crédits : IGN / Copernicus"){: .img-center loading=lazy
```suggestion
![Corinne land Cover sur Clermont-Ferrand](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/clermont_ferrand_CLC18_a.jpg "Données Corinne Land Cover 2018 sur Clermont-Ferrand - Crédits : IGN / Copernicus"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +![Urban Atlas sur Clermont-Ferrand](copernicus_data/clermont_ferrand_UA18_a.jpg "Données Urban Atlas 2018 sur Clermont-Ferrand - Crédits : IGN / Copernicus"){: .img-center loading=lazy }
```suggestion
![Urban Atlas sur Clermont-Ferrand](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/clermont_ferrand_UA18_a.jpg "Données Urban Atlas 2018 sur Clermont-Ferrand - Crédits : IGN / Copernicus"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +![Couche HRL imperviousness sur Clermont-Ferrand](copernicus_data/clermont_ferrand_HRL18_impervious_a.jpg "Données Copernicus HRL imperviousness 2018 sur Clermont-Ferrand - Crédits : IGN / Copernicus
```suggestion
![Couche HRL imperviousness sur Clermont-Ferrand](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/clermont_ferrand_HRL18_impervious_a.jpg "Données Copernicus HRL imperviousness 2018 sur Clermont-Ferrand - Crédits : IGN / Copernicus"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +![Couche HRL Forest sur Clermont-Ferrand](copernicus_data/clermont_ferrand_HRL18_tree_density_a.jpg "Données Copernicus HRL Tree Cover Density 2018 sur Clermont-Ferrand - Crédits : IGN / Copernicus")
```suggestion
![Couche HRL Forest sur Clermont-Ferrand](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/clermont_ferrand_HRL18_tree_density_a.jpg "Données Copernicus HRL Tree Cover Density 2018 sur Clermont-Ferrand - Crédits : IGN / Copernicus"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +![Images Sentinel 2 RVB](copernicus_data/Sentinel_2_L2A_with_or_without_cloud.jpg "Images Sentinel 2 RVB- Crédits : IGN"){: .img-center loading=lazy }
```suggestion
![Images Sentinel 2 RVB](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/Sentinel_2_L2A_with_or_without_cloud.jpg "Images Sentinel 2 RVB- Crédits : IGN"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +![Composition colorée temporelle NDVI Sentinel 2](copernicus_data/composition_ndvi_3dates_nov_jan_avr.png "Composition colorée temporelle NDVI Sentinel 2 - Crédits : IGN"){: .img-center loading=lazy
```suggestion
![Composition colorée temporelle NDVI Sentinel 2](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/composition_ndvi_3dates_nov_jan_avr.png "Composition colorée temporelle NDVI Sentinel 2 - Crédits : IGN"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +![Image Sentinel 1 SLC](copernicus_data/Sentinel_1_SLC.jpg "Image Sentinel 1 SLC - Crédits : ESA"){: .img-center loading=lazy }
```suggestion
![Image Sentinel 1 SLC](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/Sentinel_1_SLC.jpg "Image Sentinel 1 SLC - Crédits : ESA"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +![Cohérence radar Sentinel-1](copernicus_data/sentinel_1_esa.png "Images de cohérence sentinel-1 6 jours - Crédits : ESA"){: .img-center loading=lazy }
```suggestion
![Cohérence radar Sentinel-1](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/sentinel_1_esa.png "Images de cohérence sentinel-1 6 jours - Crédits : ESA"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-2-passe.md
> +![Portail scihub illustration](copernicus_data/scihub_copernicus_access_hub_1.jpg "Portail scihub example page - Crédits : ESA"){: .img-center loading=lazy }
```suggestion
![Portail scihub illustration](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/scihub_copernicus_access_hub_1.jpg "Portail scihub example page - Crédits : ESA"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-2-passe.md
> +![Portail PEPS CNES](copernicus_data/PEPS_CNES_captrue_site.png "Portail PEPS CNES - Crédits : PEPS"){: .img-center loading=lazy }
```suggestion
![Portail PEPS CNES](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/PEPS_CNES_captrue_site.png "Portail PEPS CNES - Crédits : PEPS"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-2-passe.md
> +![Exemple open data AWS](copernicus_data/aws-odr-s2-1024x702.png "Exemple open data AWS - Crédits: Elements84"){: .img-center loading=lazy }
```suggestion
![Exemple open data AWS](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/aws-odr-s2-1024x702.png "Exemple open data AWS - Crédits: Elements84"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-2-passe.md
> +![Creodias components](copernicus_data/creodias_components.jpg "Creodias components - Crédits : CREODIAS"){: .img-center loading=lazy }
```suggestion
![Creodias components](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/creodias_components.jpg "Creodias components - Crédits : CREODIAS"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-2-passe.md
> +![Icones DIAS](copernicus_data/DIAS_0.jpg "Icones DIAS - Crédits : JRC"){: .img-center loading=lazy }
```suggestion
![Icones DIAS](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/DIAS_0.jpg "Icones DIAS - Crédits : JRC"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-2-passe.md
> +![Profil temporel S2](copernicus_data/sen4cap_example_profil_s2_b.png "Profil temporel S2] - Crédits : SEN4CAP"){: .img-center loading=lazy }
```suggestion
![Profil temporel S2](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/sen4cap_example_profil_s2_b.png "Profil temporel S2] - Crédits : SEN4CAP"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-2-passe.md
> +![JRC CBM DIAS](copernicus_data/cbm_dias_software.png "JRC CBM DIAS - Crédits : JRC"){: .img-center loading=lazy }
```suggestion
![JRC CBM DIAS](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/cbm_dias_software.png "JRC CBM DIAS - Crédits : JRC"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-3-futur.md
> +![Portail dataspace](copernicus_data/dataspace_accueil.png "Portail dataspace - Crédits : ESA"){: .img-center loading=lazy }
```suggestion
![Portail dataspace](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/dataspace_accueil.png "Portail dataspace - Crédits : ESA"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-3-futur.md
> +![Portail dataspace service](copernicus_data/dataspace_service_description.png "Portail dataspace service- Crédits : ESA"){: .img-center loading=lazy }
```suggestion
![Portail dataspace service](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/dataspace_service_description.png "Portail dataspace service- Crédits : ESA"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-3-futur.md
> +![dataspace roadmap](copernicus_data/dataspace_RoadmapSummary.png "dataspace roadmap - Crédits : ESA"){: .img-center loading=lazy }
```suggestion
![dataspace roadmap](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/dataspace_RoadmapSummary.png "dataspace roadmap - Crédits : ESA"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-3-futur.md
> +![dataspace browser clermont](copernicus_data/dataspace_browser_clermont_ir.png "dataspace browser clermont - Crédits : IGN"){: .img-center loading=lazy }
```suggestion

![dataspace browser clermont](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/dataspace_browser_clermont_ir.png "dataspace browser clermont - Crédits : IGN"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-3-futur.md
> +![creodias jupyterhub](copernicus_data/creodias_jupyterlab.jpg "creodias jupyterhub- Crédits : ESA"){: .img-center loading=lazy }
```suggestion
![creodias jupyterhub](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/creodias_jupyterlab.jpg "creodias jupyterhub- Crédits : ESA"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-3-futur.md
> +![VHR_IMAGES_2018 COPERNICUS](copernicus_data/VHR_IMAGES_2018_COPERNICUS.png "VHR_IMAGES_2018 COPERNICUS - Crédits : ESA"){: .img-center loading=lazy }
```suggestion
![VHR_IMAGES_2018 COPERNICUS](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/VHR_IMAGES_2018_COPERNICUS.png "VHR_IMAGES_2018 COPERNICUS - Crédits : ESA"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-3-futur.md
> +![illustration WCS](copernicus_data/200px-OGC_WCS,_trim_and_slice_operations.png "illustration WCS - Crédits Wikipedia"){align=right }
```suggestion
![illustration WCS](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/200px-OGC_WCS,_trim_and_slice_operations.png "illustration WCS - Crédits Wikipedia"){align=right }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-3-futur.md
> +![logo OPENEO](copernicus_data/openeo_logo.png "Logo OPENEO"){: .img-rdp-news-thumb }
```suggestion
![logo OPENEO](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/openeo_logo.png "Logo OPENEO"){: .img-rdp-news-thumb }

```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-3-futur.md
> +![schema openeo](copernicus_data/openeo_schema.png "schema openeo - Crédits : OPENEO"){: .img-center loading=lazy }
```suggestion
![schema openeo](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/openeo_schema.png "schema openeo - Crédits : OPENEO"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-3-futur.md
> +![logo COG](copernicus_data/COG_logo.png "Logo COG"){: .img-rdp-news-thumb }
```suggestion
![logo COG](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/COG_logo.png "Logo COG"){: .img-rdp-news-thumb }

```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-2-passe.md
> +![Portail THEIA land](copernicus_data/theia_land_page.jpg "Portail THEIA Land - Crédits : THEIA"){: .img-center loading=lazy }
```suggestion
![Portail THEIA land](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/theia_land_page.jpg "Portail THEIA Land - Crédits : THEIA"){: .img-center loading=lazy }
```

2023-02-10 08:37 UTC, igeofr commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +![Constellation sentinel 1 slide](copernicus_data/copernicus_sentinel_esa_mission.jpg "Satellites constellation Sentinel une diapo ESA - Crédits : ESA"){: .img-center loading=lazy }
```suggestion
![Constellation sentinel 1 slide](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/copernicus_sentinel_esa_mission.jpg "Satellites constellation Sentinel une diapo ESA - Crédits : ESA"){: .img-center loading=lazy }
```

2023-02-10 09:12 UTC, ndavid commented
@igeofr , merci pour l'aide sur les images. A priori c'est tout bon maintenant.

2023-02-17 15:02 UTC, Guts commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +    - Télédétection
Attention à la casse des tags. Voir la liste du site pour utiliser de préférence un existant ou le plus utilisé.

2023-02-17 15:13 UTC, Guts requested changes
Désolé de la relecture tardive mais je pensais que d'autres avant moi auraient été attentifs à ma place ;)

J'ai le mauvais rôle du gardien du temple, garant que je suis que le rendu du site soit viable et durable. Désolé...

je n'ai fait une passe que sur le premier article mais la plupart des remarques s'appliquent aux 2 autres volets.

Globalement le contenu est très bon, bravo et merci.

2 dernières remarques :

- les titres sont un peu longs je trouve et le rendu dans la navigation de gauche est bof ou peu lisible. Ne garder peut-être que la deuxième partie de chaque titre à chaque fois ? Et mettre "Accès aux données Copernicus et Sentinel" en `subtitle` ?
- @ndavid es-tu certain de vouloir appliquer la licence par défaut qui a une clause restrictive sur les usages commerciaux ? Je n'ai pas d'avis personnel mais je veux être certain que tu choisisses en pleine conscience https://contribuer.geotribu.fr/guides/licensing/

2023-02-17 15:13 UTC, Guts commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +image: "https://cdn.geotribu.fr/img/logos-icones/copernicus_logo.50f4fc3b.png"
Nom d'image invalide

2023-02-17 15:13 UTC, Guts commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +:calendar: Date de publication initiale : 27 janvier 2023
Date à changer

2023-02-17 15:13 UTC, Guts commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +* [Partie 3 : évolution de l'accès aux données Copernicus](2023-02-03_portails-copernicus-3-futur.md).
les liens internes ne sont pas valides. Voir https://contribuer.geotribu.fr/guides/markdown_quality/#liens-internes-relatifs

2023-02-17 15:13 UTC, Guts commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +## Programme Copernicus et données d'occupation du sol
```suggestion
----

## Programme Copernicus et données d'occupation du sol
```

2023-02-17 15:13 UTC, Guts commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +![Urban Atlas sur Clermont-Ferrand](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/clermont_ferrand_UA18_a.jpg "Données Urban Atlas 2018 sur Clermont-Ferrand - Crédits :
Il est recommandé d'éviter les caractères un peu trop spéciaux d'un point de vue HTML dans les descriptions d'images ("/", ":", etc.)

2023-02-17 15:13 UTC, Guts commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +![Couche HRL Forest sur Clermont-Ferrand](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/clermont_ferrand_HRL18_tree_density_a.jpg "Données Copernicus HRL Tree Cover Dens
Sauter une ligne pour éviter d'avoir un effet d'images collées (à cause de la bordure légère qui leur est appliquée)

```suggestion
![Couche HRL imperviousness sur Clermont-Ferrand](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/clermont_ferrand_HRL18_impervious_a.jpg "Données Copernicus HRL imperviousness 2018 sur Clermont-Ferrand - Crédits : IGN / Copernicus"){: .img-center loading=lazy }

![Couche HRL Forest sur Clermont-Ferrand](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/clermont_ferrand_HRL18_tree_density_a.jpg "Données Copernicus HRL Tree Cover Density 2018 sur Clermont-Ferrand - Crédits : IGN / Copernicus"){: .img-center loading=lazy }
```

2023-02-17 15:13 UTC, Guts commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +![Urban Atlas sur Clermont-Ferrand](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/clermont_ferrand_UA18_a.jpg "Données Urban Atlas 2018 sur Clermont-Ferrand - Crédits :
Sauter une ligne pour éviter d'avoir un effet d'images collées (à cause de la bordure légère qui leur est appliquée)

```suggestion
![Orthophotographie RVB sur Clermont-Ferrand](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/clermont_ferrand_ortho_a.jpg "Orthophotographie RVB sur Clermont-Ferrand - Crédits : IGN"){: .img-center loading=lazy }

![Corinne land Cover sur Clermont-Ferrand](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/clermont_ferrand_CLC18_a.jpg "Données Corinne Land Cover 2018 sur Clermont-Ferrand - Crédits : IGN / Copernicus"){: .img-center loading=lazy }

![Urban Atlas sur Clermont-Ferrand](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/clermont_ferrand_UA18_a.jpg "Données Urban Atlas 2018 sur Clermont-Ferrand - Crédits : IGN / Copernicus"){: .img-center loading=lazy }
```

2023-02-17 15:13 UTC, Guts commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +      - SLC : Single Look Complex , amplitude et phase du signal retour SAR
Indentation trop importante (voir https://contribuer.geotribu.fr/guides/markdown_basics/#listes-a-puces)

```suggestion
    - GRD : Ground Range Detected, amplitude du signal retour SAR (selon les deux polarités VV et VH)
    - SLC : Single Look Complex , amplitude et phase du signal retour SAR
```

2023-02-17 15:13 UTC, Guts commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +## je veux plus d'images !!
Majuscule et éviter le doublon de `!` qui peut être utilisé par une syntaxe spécifique à un plugin ou une extension markdown, présent ou future.

```suggestion
----

## Je veux plus d'images !
```

2023-02-17 17:42 UTC, ndavid commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +image: "https://cdn.geotribu.fr/img/logos-icones/copernicus_logo.50f4fc3b.png"
oui je fais la correction. L'image est dans le dossier associé à l'article et non dans logos-icones.

2023-02-17 17:43 UTC, ndavid commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +:calendar: Date de publication initiale : 27 janvier 2023
Ok. Je modifie pour la date d'ajourd'hui, dites-moi si vous préférez une autre date ?

2023-02-17 17:43 UTC, ndavid commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +* [Partie 3 : évolution de l'accès aux données Copernicus](2023-02-03_portails-copernicus-3-futur.md).
ok modification faites sur les 3 articles. J'ai utilisé les chemins relatifs à la racine du site.

2023-02-17 17:45 UTC, ndavid commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +![Urban Atlas sur Clermont-Ferrand](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/clermont_ferrand_UA18_a.jpg "Données Urban Atlas 2018 sur Clermont-Ferrand - Crédits :
Ok j'ai supprimé les slash "/" et ":" dans les légendes. Est-ce qu'il faut supprimer les tirets "-" aussi ?

2023-02-17 17:46 UTC, ndavid commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +![Couche HRL Forest sur Clermont-Ferrand](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/copernicus_data/clermont_ferrand_HRL18_tree_density_a.jpg "Données Copernicus HRL Tree Cover Dens
ok. Modification appliquée et j'ai vérifié s'il fallait aussi le faire sur les 2 autres articles.

2023-02-17 17:46 UTC, ndavid commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +      - SLC : Single Look Complex , amplitude et phase du signal retour SAR
fait

2023-02-17 17:47 UTC, ndavid commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +## je veux plus d'images !!
Argh, je n'avais pas fait attention au problème posé par le double !. Modification faite.

2023-02-17 17:54 UTC, ndavid commented
@Guts aucun soucis pour les remarques sur la mise en forme c'est bien normal, et je comprends tout a fait que vous préfériez que cela soit le plus propre possible avant intégration !

Sur les 2 remarques : 

- effectivemement les titres un peu longs ne rendaient pas très bien. Je les ai donc raccourcis comme conseillé et j'ai ajouté la balise/métadonnées subtitle (je ne l'avais pas vue passée..)
- j'ai changé la license en Beerware. Effectivement je n'avais pas vérifié que celle par défaut était la moins permissive donc berrware me convient mieux finalement.

2023-02-17 18:24 UTC, ndavid reviewed
modifications faites sur les 3 articles par commit précédents.

2023-02-17 20:31 UTC, Guts commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +* [Partie 3 : évolution de l'accès aux données Copernicus](/articles/2023/2023-02-03_portails-copernicus-3-futur.md).
Corrige les liens et retire le lien vers l'article en cours

```suggestion
* [Partie 2 : portails d'accès, 'the road so far'](/articles/2023/2023-02-03_portails-copernicus-2-passe/).
* [Partie 3 : évolution de l'accès aux données Copernicus](/articles/2023/2023-02-03_portails-copernicus-3-futur/).
```

2023-02-17 21:30 UTC, ndavid commented on content/articles/2023/2023-02-03_portails-copernicus-1-donnees.md
> +* [Partie 3 : évolution de l'accès aux données Copernicus](/articles/2023/2023-02-03_portails-copernicus-3-futur.md).
ok je vois, j'ai oublié de supprimer le suffix .md. Je fais un commit/push pour modifier les trois articles avec ces corrections.

2023-02-17 21:41 UTC, Guts approved these changes

2023-02-17 21:45 UTC, Guts commented
@ndavid peux-tu splitter en 3 PRs du coup stp ?

Je propose les dates suivantes :

- volet 1 : mardi 21/02
- volet 2 : mardi 28/02
- volet 3 : mardi 07/03

Tu peux évidemment en choisir d'autres (je déconseille les vendredis où il y a une RDP et le lundi qui suit), l'essentiel est de répartir un peu et surtout de changer les dates dans les noms des fichiers, l'en-tête et la ligne sous le titre 1.

2023-02-17 21:52 UTC, ndavid commented
@Guts oui pas de soucis pour splitter en trois PR pour les dates proposées et mettre à jour les noms/liens et en tête en fonction. Je lance la première rapidement dans le week-end.

2023-02-18 07:19 UTC, Guts commented
Super @ndavid

Tu peux garder celle-ci pour le premier volet histoire d'avoir l'historique de ce bel échange en relecture, puis créer deux branches qui dérivent de celle-ci

2023-02-20 09:07 UTC, ndavid commented
@Guts Modifications faites dans cette branche pour le premier article. 

En plus de changer la date dans le nom de fichier, entête et ligne sous titre 1, j'ai aussi enlevé temporairement les liens pour les articles suivants (non encore publié) je les remettrais à jour dans les prochaines pull request.

2023-02-20 20:37 UTC, merged

2023-02-20 20:58 UTC, Guts commented
Premier article en ligne : https://static.geotribu.fr/articles/2023/2023-02-21_portails-copernicus-1-donnees/

Félicitations et merci !