Copernicus dataspace 2
geotribu/website pull request #864
Opened 2023-02-27 08:16 UTC by ndavid

Voici la proposition de deuxième partie pour la série d'article sur les portails d'accès aux données Copernicus/Sentinel à l'occasion du lancement du nouveau portail dataspace.copernicus.eu. 
Fait suite à la pull request pour la première partie #835 qui contient la discussion sur le sujet.

La pull request modifie aussi le premier article afin de mettre à jour les liens vers ce second article.

2023-02-27 10:05 UTC, Guts commented
Merci @ndavid !

J'ai commité la mise en page d'accueil de ta trilogie d'articles. 

On a oublié de discuter diffusion et communication lors de la publication du premier opus :

- on diffuse avec les comptes Geotribu, tu repartages ?
- tu diffuses, on repartage ?
- chacun pour soi
- peux-tu nous donner tes comptes sur ces réseaux sociaux si tu en disposes et souhaites être mentionné stp : Mastodon, Twitter, LinkedIn ? Peux-tu les ajouter à ta page auteur stp ?
- peux-tu ajouter un avatar à ta page auteur stp ? Pas besoin d'une photo réelle mais c'est pour que toutes les pages aient la même structure (oui tjs cette histoire de ~~névrose~~ pouvoir faciliter un éventuel traitement par lot)

2023-02-27 10:19 UTC, Guts requested changes
Relecture du deuxième article donc chipotage niveau 2 :wink:

2023-02-27 10:19 UTC, Guts commented on content/articles/2023/2023-02-28_portails-copernicus-2-passe.md
> +!!! warning
```suggestion
!!! warning "Attention, risque de confusion"
```

2023-02-27 10:19 UTC, Guts commented on content/articles/2023/2023-02-28_portails-copernicus-2-passe.md
> +Le site Scihub offre principalement deux services : recherche de données et téléchargement de données.
```suggestion
Le site Scihub offre principalement deux services : recherche de données et téléchargement de données.  
```

2023-02-27 10:19 UTC, Guts commented on content/articles/2023/2023-02-28_portails-copernicus-2-passe.md
> +Ces dernières sont adaptées des API REST de type [OpenSearch](https://www.opensearch.org/) ou [OData,(Open Data Protocol)](https://www.odata.org/).
```suggestion
Ces dernières sont adaptées des API REST de type [OpenSearch](https://www.opensearch.org/) ou [OData (_Open Data Protocol_)](https://www.odata.org/).
```

2023-02-27 10:19 UTC, Guts commented on content/articles/2023/2023-02-28_portails-copernicus-2-passe.md
> +```bash
````suggestion
```sh
````

2023-02-27 10:19 UTC, Guts commented on content/articles/2023/2023-02-28_portails-copernicus-2-passe.md
> +    Le code du portail scihub est lui même opensource via le projet **sentineldatahub**. Liens pour la [documentation](https://sentineldatahub.github.io/DataHubSystem/index.html) et le [github](https
```suggestion
    Le code du portail scihub est lui même opensource via le projet **sentineldatahub**. Liens pour la [documentation](https://sentineldatahub.github.io/DataHubSystem/index.html) et le [github](https://github.com/SentinelDataHub/DataHubSystem).
```

2023-02-27 10:19 UTC, Guts commented on content/articles/2023/2023-02-28_portails-copernicus-2-passe.md
> +api = SentinelAPI('user', 'password', 'https://apihub.copernicus.eu/apihub')
Application de la convention de l'ordre des imports :

```suggestion
# imports
from datetime import date
from sentinelsat import SentinelAPI


# connect to the API
api = SentinelAPI('user', 'password', 'https://apihub.copernicus.eu/apihub')
```

2023-02-27 10:19 UTC, Guts commented on content/articles/2023/2023-02-28_portails-copernicus-2-passe.md
> +[PEPS](https://peps.cnes.fr/rocket/#/home) (Plateforme d’Exploitation des Produits Sentinel) est un portail développé et maintenu par le CNES qui offre la recherche et le téléchargement des données S
Je trouve que le logo en vignette a plus d'intérêt juste sous le titre

```suggestion
![logo PEPS](https://cdn.geotribu.fr/img/logos-icones/entreprises_association/peps.png "Logo PEPS"){: .img-rdp-news-thumb }

En France il existe actuellement deux portails nationaux d'accès aux données Sentinel : [PEPS](https://peps.cnes.fr/rocket/#/home) et [THEIA](https://theia.cnes.fr/atdistrib/rocket/#/home).

[PEPS](https://peps.cnes.fr/rocket/#/home) (Plateforme d’Exploitation des Produits Sentinel) est un portail développé et maintenu par le CNES qui offre la recherche et le téléchargement des données Sentinel-1 et Sentinel-2.
```

2023-02-27 10:19 UTC, Guts commented on content/articles/2023/2023-02-28_portails-copernicus-2-passe.md
> +    Les portails PEPS et THEIA utilisent l'outil [RESTO](https://github.com/jjrom/resto) donc le code est aussi disponible sur github
```suggestion
    Les portails PEPS et THEIA utilisent l'outil [RESTO](https://github.com/jjrom/resto) dont le code est aussi disponible sur GitHub.
```

2023-02-27 10:19 UTC, Guts commented on content/articles/2023/2023-02-28_portails-copernicus-2-passe.md
> +## Saison 2 : here comme the dragons, GAFAM et réponse européenne
En règle générale on ajoute une ligne horizontale entre les niveaux 2, de façon à "marquer le coup" cognitivement et aérer l'ensemble, plus coquille sur comme -> come :

```suggestion

----

## Saison 2 : here com the dragons, GAFAM et réponse européenne
```

2023-02-27 10:31 UTC, ndavid commented
@Guts 

Sur la publication : 

-  Plutôt option vous diffusez et je repartage
-  pas de compte mastodon ou twitter. Pour linkedin c'est https://www.linkedin.com/in/nicolas-david-28722129/
-  ok pour l'avatar je vous ajoute ça. Là rapidement pas sur d'avoir une photo à jour mais j'essaye de trouver ça pour la semaine prochaine, en attendant je vous trouve une image avatar.

2023-02-27 11:42 UTC, ndavid commented
Mise à jour des infos auteur faites. Voici l'image à utiliser pour l'avatar
![ndavid](https://user-images.githubusercontent.com/873438/221554809-2cdf3e83-e449-470c-aeea-ee198b674662.jpeg)

2023-02-27 12:13 UTC, Guts commented
> Plutôt option vous diffusez et je repartage

Ok, mais sur LinkedIn, on te laisse l'initiative vu qu'il n'y a pas de compte Geotribu

J'ai téléversé ton portrait et ajusté l'URL ainsi que le nom du fichier qui doit être précisément l'initiale du nom et les 3 premières du prénom, notamment pour que https://contribuer.geotribu.fr/internal/seo_extraits_enrichis/ fonctionnent.

Faut que je MAJ le guide de contribution...

2023-02-27 12:13 UTC, Guts approved these changes

2023-02-27 12:36 UTC, ndavid commented
Super merci !
Ah oui je n'avais pas les infos sur le nom du fichier "portait auteur" dans le guide la contribution. Mais au passage il est déjà très bien ce guide et m'a beaucoup servi pour la rédaction !!

2023-02-27 17:53 UTC, merged

2023-02-28 07:57 UTC, ndavid commented
Merci pour la publication !  
J'essaye de vous faire la troisième PR un peu plus tôt dans la semaine pour vous laissez plus de temps de relecture ^^.