Copernicus dataspace end
geotribu/website pull request #869
Opened 2023-03-03 13:51 UTC by ndavid

Voici la proposition de troisième et dernière partie pour la série d'article sur les portails d'accès aux données Copernicus/Sentinel à l'occasion du lancement du nouveau portail dataspace.copernicus.eu.

Fait suite à : 
-   la pull request pour la première partie https://github.com/geotribu/website/pull/835 qui contient la discussion sur le sujet.
-   la pull request pour la deuixème partie https://github.com/geotribu/website/pull/864.

La pull request modifie aussi les 2 premiers articles afin de mettre à jour les liens vers ce dernier article.

2023-03-06 23:05 UTC, Guts commented on content/articles/2023/2023-03-07_portails-copernicus-3-futur.md
> +description: "Évolution des portails d'accès aux données europénnes de la constellation satellites Sentinel : des début en 2015 aux évolutions prévues en 2023"
```suggestion
description: "Évolution des portails d'accès aux données europénnes de la constellation satellites Sentinel : des débuts en 2015 aux évolutions prévues en 2023"
```

2023-03-06 23:05 UTC, Guts commented on content/articles/2023/2023-03-07_portails-copernicus-3-futur.md
> +---
```suggestion
    - WMS
---
```

2023-03-06 23:06 UTC, Guts commented on content/articles/2023/2023-03-07_portails-copernicus-3-futur.md
> +En particulier, outre le téléchargement des données Sentinel en Open-data, leur accès via différents services "free" de plus haut niveaux est au programme, soit : visualisation des données via des fl
```suggestion
En particulier, outre le téléchargement des données Sentinel en Open-data, leur accès via différents services "free" de plus hauts niveaux est au programme, soit : visualisation des données via des flux, accès facilité aux données anciennes, utilisation des technologies dites "cloud ready"  etc.
```

2023-03-06 23:08 UTC, Guts commented on content/articles/2023/2023-03-07_portails-copernicus-3-futur.md
> +
Je trouve que ça manque d'une petite conclusion non ? Pas forcément longue (ni courte d'ailleurs) mais histoire de ponctuer la série.

```suggestion

## Conclusion

```

2023-03-06 23:09 UTC, Guts requested changes
Des coquilles mais sinon c'est propre !

2023-03-07 09:12 UTC, ndavid commented
@Guts  : noter pour la conclusion. Je vous propose un petit qqch rapidement

2023-03-07 13:00 UTC, Guts commented on content/articles/2023/2023-03-07_portails-copernicus-3-futur.md
> +Et bien sur n'hésitez pas à revenir partager ici vos exemples d'utilisation ou vos plus jolies visualisations de données !
```suggestion
Et bien sûr, n'hésitez pas à revenir partager ici vos exemples d'utilisation ou vos plus jolies visualisations de données !
```

2023-03-07 13:01 UTC, Guts commented on content/articles/2023/2023-03-07_portails-copernicus-3-futur.md
> +J'espère que cette série d'articles vous aura plu et donné l'envie d'utiliser un peu les données du programme Copernicus, qui offrent déjà de très belles opportunités pour l'observation des territoir
```suggestion
J'espère que cette série d'articles vous aura plu et donné l'envie d'utiliser les données du programme Copernicus, qui offrent déjà de très belles opportunités pour l'observation des territoires et promettent d'en offrir encore plus dans l'avenir, que cela soit au niveau de données disponibles ou bien des différents outils de l'écosystème Copernicus.  
```

2023-03-07 13:14 UTC, Guts commented
Merci pour la prise en compte des remarques et pour la trilogie d'article d'excellente facture qui témoigne en plus d'un effort pour tenir compte de notre guide de contribution :pray: .

2023-03-07 13:14 UTC, merged