Article : Qualité et validation des données de HOT OSM
geotribu/website pull request #873
Opened 2023-03-08 21:13 UTC by KazeNoOni

Bonjour,

Voici un article sur la qualité des données issues de HOT OSM. Bonne relecture !
CW : beaux paysages

2023-03-08 21:29 UTC, Guts requested changes
Merci pour cette proposition d'article. Une première passe sur quelques éléments saillants en attendant la vraie relecture.

2023-03-08 21:29 UTC, Guts commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +image: "Image d'illustration de l'article qui sert ensuite dans la mise en avant : réseaux sociaux, flux RSS..."
Description à modifier (cf https://contribuer.geotribu.fr/guides/metadata_yaml_frontmatter/)

2023-03-08 21:29 UTC, Guts commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +    - HOT OSM
Les mots-clés sont de préférence dans l'ordre alphabétique.

2023-03-08 21:29 UTC, Guts commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +    - HOT OSM
```suggestion
tags:
    - HOT OSM
    - JOSM
    - OpenStreetMap
```

2023-03-08 21:29 UTC, Guts commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +:calendar: Date de publication initiale : 24 février 2023
```suggestion
:calendar: Date de publication initiale : 24 mars 2023
```

2023-03-08 21:29 UTC, Guts commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +![Début de validation d'une zone avec des carrés plus ou moins carrés](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/hot_qualite_contributions/00_hot_grille_travail.webp)
```suggestion
![Début de validation d'une zone avec des carrés plus ou moins carrés](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/hot_qualite_contributions/00_hot_grille_travail.webp){: .img-center loading=lazy }
```


cf https://contribuer.geotribu.fr/guides/image/#centrer

2023-03-08 23:54 UTC, Michael-cd30 reviewed
Merci pour cet article qui m'a permis de découvrir HOT.
Marrant de faire la "review" d'un article qui parle de "review" de données.

2023-03-08 23:54 UTC, Michael-cd30 commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +En premier, je regarde les oublis. Toutes les maisons ont-elles été cartographiées ? Si en zone rurale l’opération ressemble à une chasse aux trésors, au contraire en zone urbaine un bâtiment peut en
Intéressant !
Dans une démarche qualité, il me semble qu'on travaillerait plus par échantillonnage. Là, je comprend que c'est réellement une analyse exhaustive.

2023-03-08 23:54 UTC, Michael-cd30 commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +Mais comment s’assurer que ces multiples contributions de personnes de niveaux et d’expériences différentes permettront d’obtenir des données homogènes à utiliser sur place, sans oubli ou erreur ? C’
Comment as-tu intégré cette équipe ? Il faut avoir participer à d'autres projets avant ?

2023-03-08 23:54 UTC, Michael-cd30 commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +En premier, je regarde les oublis. Toutes les maisons ont-elles été cartographiées ? Si en zone rurale l’opération ressemble à une chasse aux trésors, au contraire en zone urbaine un bâtiment peut en
"Sont-elles bien dessinées" : la phrase qui précède parle de bâtiment (et non de maisons), il serait donc plus cohérent d'utiliser le masculin ici.

2023-03-08 23:54 UTC, Michael-cd30 commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +![Avant/après la validation](https://pad.oslandia.net/uploads/2a72becf-946e-4b86-bac6-2964691c4650.png)
Sur cet avant/après, il serait intéressant d'avoir l'équivalent satellite en troisième image.

2023-03-08 23:54 UTC, Michael-cd30 commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +### Faire habiter la carte : la validation des bâtiments
Je ne comprends pas le sens de "faire habiter".

2023-03-08 23:54 UTC, Michael-cd30 commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +Zoomer et dézoomer, c’est une opération continuelle en validant les routes. Plus que leur existence, la validation cherche à savoir si elles sont nécessaires. Les informations doivent permettre aux p
j'adoucie -> j'adoucis

2023-03-08 23:54 UTC, Michael-cd30 commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +![Imaga aérienne et une route étrange...](https://pad.oslandia.net/uploads/9732955c-86fc-472a-8789-edf4c7b4376f.png)
Imaga aérienne -> Image aérienne

2023-03-08 23:54 UTC, Michael-cd30 commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +Généralement, la cartographie agit « égoïstement » sur son carré bien délimité. Lorsque l’on valide, il faut réfléchir à l’échelle des carrés voisins, voire à l’échelle de tout le projet. On apprend
Est-ce la cartographie ou le cartographe qui agit égoïstement ?

2023-03-08 23:54 UTC, Michael-cd30 commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +Très vite, un logiciel est indispensable pour valider : [JOSM](https://josm.openstreetmap.de/). La marche est haute pour le configurer, mais une fois adopté, on ne peut plus se passer de la qualité d
"erreurs illogiques" je trouve que ça ressemble à une double négation. Proposition : un nombre incalculable d'incohérences qu’il pointe automatiquement

2023-03-08 23:54 UTC, Michael-cd30 commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +JOSM me permet de déplacer toutes les contributions d’une personne qui s’est trompée d’imagerie sans toucher à celles d’une autre. Il m’offre la possibilité remonter l’historique d’un objet pour lequ
la possibilité remonter l’historique -> la possibilité de remonter l’historique

2023-03-08 23:54 UTC, Michael-cd30 commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +Une imagerie précise me permet moins d'hésitations et d’avoir des détails capables de lever les doutes. Les défauts, comme les reflets des toits métalliques, y sont moins étendus. Le fait de ne pas a
d’avoir des détails capables de lever -> d’avoir des détails qui permettent de lever

2023-03-08 23:54 UTC, Michael-cd30 commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +![A l'est, village cartographié. A l'ouest, rien de nouveau en raison de nuages : la carte est vide](https://pad.oslandia.net/uploads/2da14f2b-56e4-4cce-b25f-7fbef8af70cf.png)
Ici aussi il serait intéressant de voir l'image sat avec le nuage.

2023-03-08 23:54 UTC, Michael-cd30 commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +Si je suis validatrice aujourd’hui, c’est que j’ai été formée il y a cinq ans par l’association de cartographie humanitaire [CartONG](https://www.cartong.org/fr) (merci Violaine, Jean-Yves, Jean-Paul
Ce qui répond à ma question sur comment devient on validateur ?

2023-03-08 23:54 UTC, Michael-cd30 commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +Toutes les personnes qui valident ajoutent-elles ce que j'appelle des « éléments bonus » ? Rien ne les y oblige, même si cela améliore grandement la qualité des données.
Je parlerais plus de "richesse" que de "qualité" ici.

2023-03-08 23:54 UTC, Michael-cd30 commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +Si cet article parle beaucoup des erreurs et du fouillis que je dois démêler, il arrive aussi que l’ouverture d’un carré provoque un ravissement devant la qualité du minutieux travail réalisé. On not
derrière des règles simpes -> derrière des règles simples

2023-03-09 13:38 UTC, Guts commented
Merci pour la proposition d'article 🙏 !

## 👓 Relecture

Pour la relecture, nous la réalisons de préférence via [le mode Review de GitHub](https://docs.github.com/fr/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews).

Si tu n'es pas à l'aise avec ce mode de travail, ne pas hésiter à nous le dire, soit pour former rapidement, accompagner ou trouver un autre moyen.

### Liens importants

- pour modifier ton contenu via l'interface de GitHub, tu peux le retrouver facilement via l'icône crayon en haut de la page sur le site de prévisualisation ([cf. documentation](https://contribuer.geotribu.fr/edit/fix_content_from_website/)). Sinon :
  - [article](https://github.com/KazeNoOni/website_geotribu/edit/article/hotosm_qualite_validation/content/articles/2023/2023-03-24_validation-data-HOT-OSM.md?pr=%2Fgeotribu%2Fwebsite%2Fpull%2F873) - 
  - [page auteur/ice](https://github.com/KazeNoOni/website_geotribu/edit/article/hotosm_qualite_validation/content/team/dmon.md) 
- [site temporaire de prévisualisation de l'article](https://preview-pullrequest-873--geotribu-preprod.netlify.app/articles/2023/2023-03-24_validation-data-hot-osm/) automatiquement généré après chaque modification (_commit_), dans un délai d'environ 7 minutes - merci de ne pas le diffuser

@geotribu/relecture c'est à vous !

## 📢 Diffusion

Une fois l'article publié, il sera alors temps de le diffuser. Il sera automatiquement intégré au [flux RSS](http://geotribu.fr/feed_rss_created.xml) et à [la newsletter](http://geotribu.fr/newsletter/signup/).

Mais la publication sur les réseaux sociaux est manuelle.

Nous avons des comptes officiels sur ces réseaux sociaux :

- ~~[Facebook](https://www.facebook.com/geotribu) - inactif~~
- [Mastodon](https://mapstodon.space/@geotribu)
- [Twitter](https://twitter.com/geotribu)

Et nous utilisons nos comptes persos pour diffuser sur LinkedIn avec [le hashtag #Geotribu](https://www.linkedin.com/feed/hashtag/?keywords=geotribu).

Merci d'indiquer en commentaire tes comptes à utiliser pour être cité/e dans les messages et de cocher ci-après la "stratégie" de diffusion qui te convient pour chaque réseau.

### LinkedIn

- [ ] un/e membre de Geotribu publie, tu repartages avec ton compte
- [ ] tu publies, on repartage
- [ ] chacun/e publie de son côté

### Mastodon

- [ ] un/e membre de Geotribu publie, tu repartages avec ton compte
- [ ] tu publies, on repartage
- [ ] chacun/e publie de son côté

### Twitter

- [ ] un/e membre de Geotribu publie, tu repartages avec ton compte
- [ ] tu publies, on repartage
- [ ] chacun/e publie de son côté

## Ressources

Pour info, voici quelques extraits de notre guide de contribution :

- [comprendre et compléter l'en-tête](https://contribuer.geotribu.fr/guides/metadata_yaml_frontmatter/)
- [intégrer une image](https://contribuer.geotribu.fr/guides/image/)
- [choisir une licence](https://contribuer.geotribu.fr/guides/licensing/)
- [signer un article](https://contribuer.geotribu.fr/guides/authoring/)

2023-03-14 21:36 UTC, KazeNoOni commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +Car très vite en effet, la plateforme propose différents projets afin de cartographier, grâce aux images aériennes, une zone découpée en petits carrés.
Voila qui est corrigé, merci !

2023-03-14 21:37 UTC, KazeNoOni commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +> Plus ou moins carrés : en bleu cartographié, cadenas pour le travail en cours, en vert validé, en gris mauvaise imagerie
Je l'ai pris en compte, merci pour votre retour !

2023-03-14 21:37 UTC, KazeNoOni commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +Des bénévoles de tous niveaux choisissent une tâche qu’ils et elles complètent en ajoutant les informations sur OpenStreetMap. Quand tous les carrés sont terminés, la zone est cartographiée, et les d
J'ai mis "ouvertes", mais je trouve que cela sonne faux. J'y reviendrai sûrement.

2023-03-14 21:38 UTC, KazeNoOni commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +Des bénévoles de tous niveaux choisissent une tâche qu’ils et elles complètent en ajoutant les informations sur OpenStreetMap. Quand tous les carrés sont terminés, la zone est cartographiée, et les d
Excellente remarque en effet. J'ai fait un clin d'oeil ici et à la fin du texte #prosélytisme

2023-03-14 21:39 UTC, KazeNoOni commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +Mais comment s’assurer que ces multiples contributions de personnes de niveaux et d’expériences différentes permettront d’obtenir des données homogènes à utiliser sur place, sans oubli ou erreur ? C’
L'art du suspense.

2023-03-14 21:40 UTC, KazeNoOni commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +### Faire habiter la carte : la validation des bâtiments
Merci pour ce retour : j'avais peur que cela ne soit pas clair, cela l'est donc.
Je penser "habiter" = mettre des habitations.
Je vais trouver autre chose qui fasse écho au paragraphe suivant.

2023-03-20 19:42 UTC, Guts commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +Si je suis validatrice aujourd’hui, c’est que j’ai été formée il y a cinq ans par l’association de cartographie humanitaire [CartONG](https://www.cartong.org/fr) (merci Violaine, Jean-Yves, Jean-Paul
Oui, je pense :)

2023-03-20 19:44 UTC, Guts commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +Des bénévoles de tous niveaux choisissent une tâche qu’ils et elles complètent en ajoutant les informations sur OpenStreetMap. Quand tous les carrés sont terminés, la zone est cartographiée, et les d
Personnellement, j'enlèverais bien le qualificatif :

> Quand tous les carrés sont terminés, la zone est cartographiée et les données ainsi produites serviront immédiatement aux différentes équipes sur place.

2023-03-20 19:46 UTC, Guts commented
Bonsoir,

Comme évoqué lors de notre point, je me suis chargé de télécharger, compresser, redimensionner et téléverser les images sur notre CDN : https://cdn.geotribu.fr/tinyfilemanager.php?p=articles-blog-rdp/articles/2023/hot_qualite_contributions

En suivant, j'ai modifié les liens vers les images et appliqué les balises d'optimisation dans l'article directement.

2023-03-20 19:58 UTC, Guts commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +Quant aux statistiques elles sont formelles : on passe beaucoup moins de temps à valider qu’à cartographier. Nous sommes  parfaitement complémentaires pour obtenir notre résultat : [une carte de qual
Suppression espace en trop


```suggestion
Quant aux statistiques elles sont formelles : on passe beaucoup moins de temps à valider qu’à cartographier. Nous sommes parfaitement complémentaires pour obtenir notre résultat : [une carte de qualité](https://hal.science/hal-02157229) destinée aux personnes sur le terrain et [aux multiples utilisations](https://www.openstreetmap.org/user/pedrito1414/diary/401009). Vous vous joignez au mouvement ?
```

2023-03-20 20:04 UTC, Guts commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +Si je suis validatrice aujourd’hui, c’est que j’ai été formée il y a cinq ans par l’association de cartographie humanitaire [CartONG](https://www.cartong.org/fr) (merci Violaine, Jean-Yves, Jean-Paul
```suggestion
## Valider : une question de personnes

![logo cartONG](https://cdn.geotribu.fr/img/logos-icones/entreprises_association/cartONG.webp){: .img-rdp-news-thumb }

Si je suis validatrice aujourd’hui, c’est que j’ai été formée il y a cinq ans par l’association de cartographie humanitaire [CartONG](https://www.cartong.org/fr) (merci Violaine, Jean-Yves, Jean-Paul et Michel !). Faire partie d’un groupe de validation permet de poser des questions de manière conviviale, de [découvrir des ouvrages](https://presses-universitaires.univ-amu.fr/signatures-sahariennes) pour nous aider dans notre lecture des images, de demander des avis sur une donnée et de partager ses devinettes, sa chasse aux trésors et son enquête généalogique de [POI](https://wiki.openstreetmap.org/wiki/FR:Points_d%27int%C3%A9r%C3%AAt).
```

2023-03-20 20:05 UTC, Guts commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +### Faire habiter la carte : la validation des bâtiments
Idées :

- Bâtir une carte valide
- Les détails de la carte sont bien logés

2023-03-24 11:46 UTC, Guts commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +### Faire habiter la carte : la validation des bâtiments
```suggestion
### Bâtir une carte valide : la validation des bâtiments
```

2023-03-24 11:49 UTC, Guts commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +Des bénévoles de tous niveaux choisissent une tâche qu’ils et elles complètent en ajoutant les informations sur OpenStreetMap. Quand tous les carrés sont terminés, la zone est cartographiée, et les d
Vu avec @KazeNoOni : c'est en effet détaillé plus tard.

2023-03-24 11:54 UTC, Guts commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +image: "Image d'illustration de l'article qui sert ensuite dans la mise en avant : réseaux sociaux, flux RSS..."
note pour moi-même : c'est pas clair sur cette page, pô clair

2023-03-24 12:02 UTC, Guts commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +----
```suggestion
Quant aux statistiques elles sont formelles : on passe beaucoup moins de temps à valider qu’à cartographier. Nous sommes parfaitement complémentaires pour obtenir notre résultat : [une carte de qualité](https://hal.science/hal-02157229) destinée aux personnes sur le terrain et [aux multiples utilisations](https://www.openstreetmap.org/user/pedrito1414/diary/401009). Vous vous joignez au mouvement ?

[Rejoindre l'aventure pour cartographier :map:](https://tasks.hotosm.org/explore){: .md-button }
{: align=middle }

----
```

2023-03-24 12:04 UTC, Guts commented
@KazeNoOni mémo :

- image l'en-tête en PNG, 400x800 qui synthétise l'objet de l'article
- une description en 160 caractères de l'article

2023-03-27 13:51 UTC, Guts commented on content/articles/2023/2023-03-24_validation-data-HOT-OSM.md
> +image: "![image](https://user-images.githubusercontent.com/17273438/227956441-f7bb991f-a3e3-480e-98b2-cc6c49435ae9.png)"
```suggestion
image: https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/hot_qualite_contributions/hot_validation_qualite_donnees.png
```

Utilise l'image créée par @KazeNoOni et téléversée sur CDN

2023-03-27 15:04 UTC, Guts approved these changes

2023-03-27 15:07 UTC, merged