Create 2023-05-22_carto-vandalisme_dans_OSM.md
geotribu/website pull request #926
Opened 2023-05-13 07:34 UTC by quythytruong

# Amorcer une nouvelle revue de presse

- [ ] nommer cette _Pull Request_ de façon claire et lisible. Exemple : `GeoRDP du JJ MM AAAA`
- [ ] partir du modèle disponible (copier/coller) [sur Github](https://github.com/geotribu/website/blob/master/content/rdp/templates/template_rdp.md?plain=1) ou [sur le pad](https://geotripad.herokuapp.com/DCBQirjYSp6sqxPd5JYqLg?both)
- [ ] changer la date dans les métadonnées :
    - [ ] `date` : au format `AAAA-MM-JJ HH-MM` - mais laisser l'heure sur 14h20 c'est historique
    - [ ] `title` : correspond à ce qui est affiché dans le menu de navigation, l'onglet du navigateur et le SEO. Bien **indiquer l'année** pour améliorer le référencement et en prévision d'une refonte du moteur de rendu.
- [ ] changer la date du titre principal (en début de contenu). Idem, **indiquer l'année**.

## Encourager les contributions

- [ ] informer l'équipe que la prochaine RDP a été initiée en publiant le lien de la PR sur [le canal `#revues-de-presse` de Slack](https://geotribu.slack.com/archives/C010DD7FMEX)
- [ ] tweeter le lien du fichier de la RDP. Voici ci-dessous un modèle dans lequel :

- remplacer `XXXXXXXXXX` par le lien vers le fichier de la GeoRDP dans la branche créée (par exemple : <https://github.com/geotribu/website/blob/rdp/2021-02-26/content/rdp/2021/rdp_2021-02-26.md?plain=1>)
- insérer cette image dans le tweet <https://cdn.geotribu.fr/img/internal/contribution/geotribu_contribuer_rdp_github_edit.png>

```txt
Ce vendredi c'est #GeoRDP !

💡 Une idée de news ? Une envie de parler de #carte ? d'outil #SIG ? de relayer un article, un tutoriel  sur la #géographie ou la #géomatique ?

C'est par ici 👉 XXXXXXXXXX 👈
(icône 🖍️)

Modèle de news ici : https://github.com/geotribu/website/blob/master/content/rdp/templates/template_rdp_news.md
```

Exemple de [tweet](https://twitter.com/geotribu/status/1364625815099613185) :

![tweet geordp](https://cdn.geotribu.fr/img/internal/contribution/geotribu_rdp_tweet_incitation.png)

----

## Check-list de publication

### Qualité

- [ ] les news sont bien réparties dans les bonnes sections
- [ ] les sections vides sont supprimées
- [ ] vérifier le rendu de la syntaxe markdown (cf. linter)
- [ ] chasse aux coquilles orthographiques et dyslexiques

### Images

- [ ] les images téléversées sur le CDN n'ont pas de caractère spécial dans leur nom de fichier (espace, accent, etc.) et n'excédent pas 1000px de largeur
- [ ] les images sont hébergées sur des sites sécurisés (HTTPS)
- [ ] chaque news a une vignette
- [ ] les images (sauf les vignettes) ont l'attribut `loading` défini sur `lazy` (cf. [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading) et [guide material-mkdocs](https://squidfunk.github.io/mkdocs-material/reference/images/#image-lazy-loading))
- [ ] accessibilité : chaque image a un texte de remplacement (entre les crochets) et un titre lisible par les outils d'assistance. Bref, qui respecte la [syntaxe générale](https://contribuer.geotribu.fr/guides/image/#syntaxe-generale)

### SEO

- [ ] `image` pointe vers l'URL d'une des images de la revue de presse
- [ ] `description` contient les mots-clés et grandes lignes du contenu (par exemple, la reprise de l'intro)

----

## Publier

1. S'assurer que la branche soit à jour par rapport à la branche principale. Le cas échéant, utiliser le bouton `Update branch` en bas.
2. S'assurer que les éléments de la check-list ci-dessus soient tous remplis
3. Fusionner (_merge_) en utilisant un _merge commit_ ou un _rebase_, mais **surtout pas un squash**.

----

## Diffuser

### Twitter

Une fois le déploiement effectué (~ 5 minutes), diffuser a minima sur Twitter :

- avec le hashtag `#GeoRDP`, en citant les contributeur/ices avec leur éventuel compte
- si possible en intégrant quelques hastags des personne, organisations ou logiciels cités dans la revue de presse
- de préférence via le compte `@geotribu` en utilisant Tweetdeck.

### LinkedIn

La diffusion sur LinkedIn est à faire avec un compte personnel. Exemple de structure :

```txt
🗞 La #GeoRDP est en ligne :

👥 Contributeur/ices : @XXXX

🌍 #Geotribu #veille #géomatique #YYYY @ZZZZ
```

2023-05-13 08:44 UTC, Guts commented
Salut @quythytruong et merci pour la proposition d'article 🙏 !

J'ai mis à jour la description de la PR de façon à y intégrer certains éléménts importants que nous t'invitons à parcourir.

Je fais quelques corrections rapides en mode suggestion histoire de corriger les erreurs rapportées par le linter ([visibles ici](https://results.pre-commit.ci/run/github/248722492/1683965124.TFyzLN47TGuJlGWI6FRXYg) notamment).

2023-05-13 09:01 UTC, Guts requested changes

2023-05-13 09:01 UTC, Guts commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +![](https://pad.oslandia.net/uploads/0b3e6ced-1972-4309-8057-e8a52f6492bd.png){: .img-center loading=lazy }
```suggestion
![Carto-vandalisme : échanges lunaires sur les changesets](https://pad.oslandia.net/uploads/0b3e6ced-1972-4309-8057-e8a52f6492bd.png){: .img-center loading=lazy }
```

2023-05-13 09:01 UTC, Guts commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +
```suggestion
> 
```

2023-05-13 10:42 UTC, Michael-cd30 reviewed
Super article vraiment !!!

2023-05-13 10:42 UTC, Michael-cd30 commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +* La ville de New-York a été renommée temporairement ["Jewtropolis"](https://time.com/5382801/new-york-city-jewtropolis-snapchat/), bien que l'auteur de ces contributions prétende avoir agi de la sor
Là encore j'ai toujours un doute mais si les énumérations commencent pas une majuscule c'est que chacune est une phrase distincte donc elles devraient se terminer par un point.

2023-05-13 10:42 UTC, Michael-cd30 commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +OpenStreetMap étant devenue une référence pour de nombreux secteurs de métier, les dégradations causées peuvent être très graves et nécessitent d'être détectées au plus vite.
métierS ?

2023-05-13 10:42 UTC, Michael-cd30 commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Un échange a eu lieu entre un autre contributeur OSM et l'auteur de ce changeset révèle une erreur de manipulation :
Pour être cohérent avec le précédent, mettre ici changeset en italique.

2023-05-13 10:42 UTC, Michael-cd30 commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +![Erreur de bonne foi au moment de la saisie](https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/osm_carto_vandalisme/osm_erreur_bonne_foi_batiments_denver.webp){: .img-center loading=lazy }
Je trouve que l'image n'est pas assez explicite concernant l'erreur, peut être rajouter un petit texte explicatif.
A lire la suite, je crois deviner que ça concerne l'ajout de bâtiments sur une zone alors qu'il était question d'un HOT sur une autre zone, c'est çà ?

2023-05-13 10:42 UTC, Michael-cd30 commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Bien que la communauté OSM soit fournie en contributeurs (ré-)actifs et alertes pour détecter les erreurs de contribution, les outils à leur disposition - comme [Osmose](https://osmose.openstreetmap.
"fournie en" me semble mal adapté pour parler de contributeurs...ça fait plus "objet" que "personne".
Proposition "soit riche de"

2023-05-13 10:42 UTC, Michael-cd30 commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +### Pourquoi c'est si dur
Ajout d'un ?

2023-05-13 10:42 UTC, Michael-cd30 commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Toutefois, la définition du [vandalisme par OSM](https://wiki.openstreetmap.org/wiki/Vandalism) est plus large que celle que nous nous étions fixée, puisque les blocages d'utilisateurs pouvaient conc
Encore un gros doute sur "Nous nous étions fixée" : selon moi auxiliaire être donc accord avec le sujet et pas le COD, j'écrirais "fixés"

2023-05-13 10:42 UTC, Michael-cd30 commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Toutefois, la définition du [vandalisme par OSM](https://wiki.openstreetmap.org/wiki/Vandalism) est plus large que celle que nous nous étions fixée, puisque les blocages d'utilisateurs pouvaient conc
Pourquoi mettre involontaires en italique ?

2023-05-13 10:42 UTC, Michael-cd30 commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +*Ci-dessus : parc ou forêt ? Cet objet OSM a été le lieu d'un débat, comme le montre [son historique](https://osmlab.github.io/osm-deep-history/#/way/87406131). Les tags ont oscillé à plusieurs repri
"a été le lieu de" ou "a donné lieu à" ?

2023-05-13 10:42 UTC, Michael-cd30 commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +### Comment on a fait
Ajout d'un ?

2023-05-13 10:42 UTC, Michael-cd30 commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Pour faire ce corpus de carto-vandalisme OSM, j'ai sélectionné quatre zones géographiques (deux en France, et deux en Allemagne) à partir desquelles j'ai introduit des contributions de carto-vandalis
les attributS

2023-05-13 10:42 UTC, Michael-cd30 commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Pour s'assurer de la cohérence des contributions (ici des bâtiments) avec le reste de l'environnement cartographique, j'ai aussi considéré des indicateurs topologiques qui vérifient l'inclusion ou l'
répétition de "des"

2023-05-13 10:42 UTC, Michael-cd30 commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +On observe entre 97% et 100% de bonne classification sur des contributions qui se situent dans la zone d'entraînement du système d'apprentissage. En revanche, le système produit entre 99% à 100% de m
Dingue, c'est vraiment le grand écart. Pour ma culture, mais je pourrai reposer la question en commentaire de l'article lorsqu'il sera public,  les résultats ne seraient-ils pas meilleurs en ne prenant en compte que les descripteurs liés au contributeur et non à la contribution ?

2023-05-13 10:42 UTC, Michael-cd30 commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +En parallèle de cette expérience, j'ai voulu interroger l'intérêt des descripteurs centrés sur les contributeurs. Une autre expérience similaire a été réalisée en entraînant un modèle sans ces variab
pertinentEs

2023-05-13 10:42 UTC, Michael-cd30 commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +* d'identifier et de définir le carto-vandalisme
enum encore, là je mettrais une virgule à la fin de la première et un point à la fin de la dernière.

2023-05-13 10:42 UTC, Michael-cd30 reviewed
Super article vraiment !!!

2023-05-13 13:50 UTC, quythytruong commented on content/team/qtru.md
> +Je suis ingénieure en géomatique issue de l'[ENSG](https://ensg.eu/).
Et voici ! 

![qtt_bw_cropped_redim](https://github.com/geotribu/website/assets/23528521/c8bc5523-6b34-4f6d-ae96-2311077b9e70)

2023-05-13 14:11 UTC, quythytruong commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +La qualité de ces nouveaux référentiels repose sur une forte participation de la communauté de contributeurs. Mais comment s'assurer que, dans ce nouvel espace commun, il n'y ait pas de dégradation s
"introduite**s**" qualifie les données qui sont bien au pluriel. 

Quant à "pas de dégradation", on peut l'écrire au singulier ou au pluriel (cf. cet [article](https://www.lalanguefrancaise.com/orthographe/pas-de-probleme-ou-pas-de-problemes)). Donc je vais laisser comme ça :)

2023-05-13 14:16 UTC, quythytruong commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +* La ville de New-York a été renommée temporairement ["Jewtropolis"](https://time.com/5382801/new-york-city-jewtropolis-snapchat/), bien que l'auteur de ces contributions prétende avoir agi de la sor
Tu as raison :

> Une liste à puce débutant par une phrase fermée signifie que la phrase introductive se termine par un point ou se termine sans ponctuation s’il s’agit d’un titre.
>
> Dans ce cas, les puces qui vont suivre sont considérées comme autant de phrases distinctes. Elles débutent logiquement par une majuscule et se terminent par un point.

Source [ici](https://redaction-seo.fr/la-ponctuation-de-la-liste-a-puce/).

Je fais la modification !

2023-05-13 14:24 UTC, Guts commented
Coucou 👋 @KazeNoOni, un article qui devrait t'intéresser. Si jamais tu veux le relire 😊.

@quythytruong d'ailleurs ça peut valoir le coup de faire référence à l'article de Delphine quelque part, vu que ça parle de validation des saisies OSM.

2023-05-13 14:26 UTC, quythytruong commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +OpenStreetMap étant devenue une référence pour de nombreux secteurs de métier, les dégradations causées peuvent être très graves et nécessitent d'être détectées au plus vite.
Houlà, bonne question ! J'ai dû bien chercher pour trouver la [réponse](https://vitrinelinguistique.oqlf.gouv.qc.ca/index.php?id=21596)
> Le complément est généralement au pluriel s’il se réfère à une réalité concrète ou que l’on peut compter

"métier" étant dénombrable, il faudrait donc l'accorder en nombre en effet.

2023-05-15 15:04 UTC, quythytruong commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Bien que la communauté OSM soit fournie en contributeurs (ré-)actifs et alertes pour détecter les erreurs de contribution, les outils à leur disposition - comme [Osmose](https://osmose.openstreetmap.
Tu as raison, et d'ailleurs ça m'a donné l'occasion de chercher la différence entre ["riche de" et "riche en"](https://www.question-orthographe.fr/question/quelle-est-la-difference-entre-riche-en-et-riche-de/)...

2023-05-15 15:06 UTC, quythytruong commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Toutefois, la définition du [vandalisme par OSM](https://wiki.openstreetmap.org/wiki/Vandalism) est plus large que celle que nous nous étions fixée, puisque les blocages d'utilisateurs pouvaient conc
C'est parce que "fixée" qualifie "la règle de consensus" qui est un groupe nominal féminin

2023-05-15 15:10 UTC, quythytruong commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Toutefois, la définition du [vandalisme par OSM](https://wiki.openstreetmap.org/wiki/Vandalism) est plus large que celle que nous nous étions fixée, puisque les blocages d'utilisateurs pouvaient conc
Pour insister sur cette composante intentionnelle qui est absente ici, et qui différencie bien la définition du carto-vandalisme selon OSM (toute erreur, volontaire ou non) et ma définition (toute erreur de saisie intentionnelle).

Je résous la conversation ici, mais on peut rouvrir le sujet si ce choix typographique est discutable.

2023-05-15 15:13 UTC, quythytruong commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +*Ci-dessus : parc ou forêt ? Cet objet OSM a été le lieu d'un débat, comme le montre [son historique](https://osmlab.github.io/osm-deep-history/#/way/87406131). Les tags ont oscillé à plusieurs repri
Tu as raison, "a donné lieu à" est plus opportun ici, je fais la modification.

2023-05-15 15:38 UTC, quythytruong commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +On observe entre 97% et 100% de bonne classification sur des contributions qui se situent dans la zone d'entraînement du système d'apprentissage. En revanche, le système produit entre 99% à 100% de m
C'est une très bonne question, et je n'ai pas tenté de lancer l'apprentissage uniquement sur les descripteurs liés aux utilisateurs. Mais l'expérience mériterait d'être testée !

Là encore, le jeu de données mérite d'être construit avec soin, car c'est dessus que le modèle va apprendre à distinguer un contributeur OSM bien intentionné d'un carto-vandale. Ca suppose que je connaisse moi-même le profil type d'un carto-vandale, or je ne suis pas sûre de savoir quels profils je devrais faire apprendre au système.

2023-05-17 09:56 UTC, quythytruong commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +image: "Image d'illustration de l'article qui sert ensuite dans la mise en avant : réseaux sociaux, flux RSS... 400x800 en PNG"
Et voici l'image d'en-tête, j'espère que c'est assez lisible, car je trouve que le rendu du preview est flou.

![carto-vandalism-is-a-crime-redim](https://github.com/geotribu/website/assets/23528521/199cf1e8-8164-47e5-aecc-473701150bf8)

2023-05-17 10:18 UTC, quythytruong commented
> Merci d'indiquer en commentaire tes comptes à utiliser pour être cité/e dans les messages

Alors j'ai compte LinkedIn, ça doit être quythytruong à en croire l'[URL vers mon profil](https://www.linkedin.com/in/quythytruong/).

En revanche, je n'ai pas de compte Mastodon ni Twitter (c'est pas trop mon truc les réseaux sociaux en réalité..!)

2023-05-17 12:43 UTC, lbartoletti commented
Top article @quythytruong !!

2023-05-17 12:43 UTC, lbartoletti approved these changes

2023-05-17 13:59 UTC, Guts commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +image: "Image d'illustration de l'article qui sert ensuite dans la mise en avant : réseaux sociaux, flux RSS... 400x800 en PNG"
```suggestion
image: https://cdn.geotribu.fr/img/articles-blog-rdp/articles/2023/osm_carto_vandalisme/osm_vandalisme_en-tete.png
```

2023-05-17 14:01 UTC, Guts commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +![robot](https://github.com/quythytruong/geotribu-website/assets/23528521/82718bea-4fff-46df-9aaa-e6f4cabbfe72){: .img-rdp-news-thumb }
```suggestion
![icône robot futurama](https://cdn.geotribu.fr/img/logos-icones/divers/robot_futurama.webp){: .img-rdp-news-thumb }
```

2023-05-17 20:31 UTC, quythytruong commented
@Guts voici les images compressées à intégrer dans l'article (les 3 premières seront sous forme de vignettes) :

![256px-OSM-Notes](https://github.com/geotribu/website/assets/23528521/fdc038ec-9cda-433f-a477-3be8f6c381dc)

![bwink_ppl_20_single_02](https://github.com/geotribu/website/assets/23528521/241018cd-9e7c-445a-8cea-0e5e6e652a0f)

![bad_manip](https://github.com/geotribu/website/assets/23528521/4e6bcc38-fab6-409b-bdaa-662c9f592b8a)

![andrea-de-santis-zwd435-ewb4-unsplash-redim](https://github.com/geotribu/website/assets/23528521/c22341f0-d552-4928-934b-e5df6c720df7)

Merci !! :pray:

2023-05-18 15:14 UTC, Guts commented
> @Guts voici les images compressées à intégrer dans l'article (les 3 premières seront sous forme de vignettes) :

Merci @quythytruong ! Je les ai redimensionnées pour coller aux dimensions recommandées pour les vignettes, téléversées et j'ai inséré les liens.

2023-05-20 19:55 UTC, KazeNoOni reviewed
Quel article passionnant ! Je trouve les idées proposées pour détecter le vandalisme très bonnes.

2023-05-20 19:55 UTC, KazeNoOni commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +En réaction à ces contributions douteuses, des contributeurs OSM ont écrit sur le fil de discussion du *changeset* de cette contribution, comme par exemple ce message d'un membre du *Data Working Gro
J'indiquerai ce qu'est le DWG dans OSM.

2023-05-20 19:55 UTC, KazeNoOni commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +
Suggestion : introduire dès maintenant la diversité de l'intentionnalité. Ce n'est pas le même état d'esprit quand on veut avoir un Pokémon eau près de chez soi (égoïsme) et dégrader OSM avec une visée commerciale (Google).

2023-05-20 19:55 UTC, KazeNoOni commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Toutefois, la définition du [vandalisme par OSM](https://wiki.openstreetmap.org/wiki/Vandalism) est plus large que celle que nous nous étions fixée, puisque les blocages d'utilisateurs pouvaient conc
J'expliquerai ce qu'est la règle de consensus.
(pour moi, on règle les conflits dans le changeset)

2023-05-20 19:55 UTC, KazeNoOni commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Les descripteurs, aussi appelés variables ou *features* en anglais, sont les indicateurs qui vont être calculés sur toutes les contributions OSM, et à partir desquelles le système d'apprentissage va
Je n'ai pas compris ce qu'est un descripteur (je ne suis pas du milieu de l'AA)

2023-05-20 19:55 UTC, KazeNoOni commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Avec un modèle de [forêts aléatoires](https://datascientest.com/random-forest-definition), j'utilise 80% des données du corpus pour l'entraîner. Les 20% restants sont utilisées pour vérifier comment
J'ajouterai une image de la documentation sur ces fameuses forêts aléatoires.

2023-05-20 19:55 UTC, KazeNoOni commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +L'erreur étant humaine, il peut bien sûr y avoir des contributions de données OSM erronnées mais non-intentionnelles. Par exemple, sur ce [*changeset*](https://www.openstreetmap.org/changeset/5659854
de données OSM erro**n**ées

2023-05-20 19:55 UTC, KazeNoOni commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Comme évoqué au début de cet article, la force de la communauté est primordiale pour assurer la qualité des données OSM. Or, des utilisateurs inexpérimentés méritent d'être formés afin de devenir des
erro**n**ées

2023-05-20 19:55 UTC, KazeNoOni commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Comme évoqué au début de cet article, la force de la communauté est primordiale pour assurer la qualité des données OSM. Or, des utilisateurs inexpérimentés méritent d'être formés afin de devenir des
malintentionnés

2023-05-22 20:16 UTC, quythytruong commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +En réaction à ces contributions douteuses, des contributeurs OSM ont écrit sur le fil de discussion du *changeset* de cette contribution, comme par exemple ce message d'un membre du *Data Working Gro
En fait j'en parle dans la suite. Mais effectivement, à ce stade de l'article, on peut se demander ce qu'est le DWG. Le plus simple, c'est que je ne précise pas que le message provienne d'un contributeur du DWG. Ca ne retire en rien l'intérêt de son message.

2023-05-23 18:38 UTC, quythytruong commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +
J'ai ajouté un petit paragraphe sur les différentes motivations qui expliquent les actes de carto-vandalisme, en mettant un lien vers un article scientifique à ce sujet.

2023-05-23 18:47 UTC, quythytruong commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Toutefois, la définition du [vandalisme par OSM](https://wiki.openstreetmap.org/wiki/Vandalism) est plus large que celle que nous nous étions fixée, puisque les blocages d'utilisateurs pouvaient conc
J'ai ajouté un lien vers https://wiki.openstreetmap.org/wiki/FR:Disputes pour inviter le lecteur à aller voir directement les règles d'OSM à ce sujet.

> pour moi, on règle les conflits dans le changeset

Je ne suis pas sûre de comprendre ce que tu veux dire :thinking:

2023-05-23 19:12 UTC, quythytruong commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Les descripteurs, aussi appelés variables ou *features* en anglais, sont les indicateurs qui vont être calculés sur toutes les contributions OSM, et à partir desquelles le système d'apprentissage va
Un descripteur est un indicateur chiffré que l'on va calculer sur chacune des contributions OSM. Le système va donc apprendre à détecter le carto-vandalisme à partir des valeurs de chaque indicateur choisi. D'où l'intérêt de choisir des descripteurs qui servent de critères pour discriminer les contributions relevant du carto-vandalisme ou non.

Est-ce que ça te semble plus clair @KazeNoOni ? :)

2023-05-23 19:22 UTC, quythytruong commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Avec un modèle de [forêts aléatoires](https://datascientest.com/random-forest-definition), j'utilise 80% des données du corpus pour l'entraîner. Les 20% restants sont utilisées pour vérifier comment
Je propose ce schéma :
![random_forest_diagram_minified](https://github.com/geotribu/website/assets/23528521/b45fd624-c713-46a5-af07-9d6f15010ace)

J'espère qu'il est assez parlant.

@Guts peux-tu l'insérer s'il te plaît ? C'est du SVG que j'ai compressé, mais je te laisse le redimensionner, si tu veux bien :)

2023-05-24 07:14 UTC, Guts commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Avec un modèle de [forêts aléatoires](https://datascientest.com/random-forest-definition), j'utilise 80% des données du corpus pour l'entraîner. Les 20% restants sont utilisées pour vérifier comment
Fait.

2023-05-24 07:14 UTC, Guts approved these changes

2023-05-24 07:22 UTC, Guts commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Les descripteurs, aussi appelés variables ou *features* en anglais, sont les indicateurs qui vont être calculés sur toutes les contributions OSM, et à partir desquelles le système d'apprentissage va
J'aime bien aussi cette définition. Soit la fusionner avec le paragraphe actuel soit tu peux l'ajouter en abbréviation de façnn à ce que ça s'affiche en infobulle au survol du mot. [Exemple](https://contribuer.geotribu.fr/articles/workflow/) :

![image](https://github.com/geotribu/website/assets/1596222/28640a65-ee94-45e9-be63-7570cffaad9d)

2023-05-24 07:55 UTC, quythytruong commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +Les descripteurs, aussi appelés variables ou *features* en anglais, sont les indicateurs qui vont être calculés sur toutes les contributions OSM, et à partir desquelles le système d'apprentissage va
J'ai fusionné le paragraphe avec la définition que j'ai mise dans nos échanges. Mais je retiens la syntaxe de l'info-bulle, ça pourra me servir plus tard ;)

2023-05-24 08:00 UTC, quythytruong commented
Merci pour vos relectures @Guts, @Michael-cd30, @lbartoletti et @KazeNoOni ! :pray:

2023-05-24 08:12 UTC, Guts requested changes

2023-05-24 08:12 UTC, Guts commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +date: "2023-05-22 10:20"
```suggestion
date: "2023-05-24 10:20"
```

2023-05-24 08:12 UTC, Guts commented on content/articles/2023/2023-05-22_carto-vandalisme_dans_OSM.md
> +:calendar: Date de publication initiale : 22 mai 2023
```suggestion
:calendar: Date de publication initiale : 24 mai 2023
```

2023-05-24 08:25 UTC, Guts approved these changes

2023-05-24 08:28 UTC, merged

2023-05-26 18:54 UTC, Michael-cd30 commented
Vous n'avez pas prévu d'annoncer la publication de l'article sur les RS ? Ou alors je suis passé au travers.

2023-05-26 21:06 UTC, Guts commented
> Vous n'avez pas prévu d'annoncer la publication de l'article sur les RS ? Ou alors je suis passé au travers.

Si mais pas eu le temps 😥... Je suis un peu seul sur ce front ces derniers temps alors si tu veux m'aider, je te file volontiers les accès !

2023-05-27 09:25 UTC, Michael-cd30 commented
> > Vous n'avez pas prévu d'annoncer la publication de l'article sur les RS ? Ou alors je suis passé au travers.
> 
> Si mais pas eu le temps 😥... Je suis un peu seul sur ce front ces derniers temps alors si tu veux m'aider, je te file volontiers les accès !

Si tu veux. Par contre je pense que là tout le monde est en weekend...et en plus par chez nous à la féria. Donc je dirais qu'il faut attendre mardi pour faire l'annonce.

2023-05-27 11:58 UTC, Guts commented
@Michael-cd30 on est bien d'accord sur le timing.

2023-06-01 08:16 UTC, Guts commented
https://twitter.com/geotribu/status/1664183988770963457

2023-06-01 08:19 UTC, Guts commented
ah @Michael-cd30 je n'avais pas vu ton tweet déso

2023-06-01 09:26 UTC, Michael-cd30 commented
> ah @Michael-cd30 je n'avais pas vu ton tweet déso

Pas de problème, comme il y avait la RDP et que celle-ci référençait l'article, je me suis permis une "mise en avant" mais c'est mieux que la com' viennent du compte geotribu.