Create 2023-10-02_Nouvelle_etape_pour_Panoramax
geotribu/website pull request #989
Opened 2023-10-02 12:12 UTC by mferrey

C’était il y a un an… l’IGN répondait à la proposition d’OpenStreetMap France et se lançait dans une phase d’investigation pour la création d’un street-view libre. Aujourd’hui, où en est-on ?

2023-10-02 20:24 UTC, Michael-cd30 reviewed
Cool de voir arriver sur GéoTribu un article qui présente Panoramax.

La trame me semble ok. Par contre, la notion de "nouvelle étape" évoquée dans le titre ne me semble pas bien marquée dans le contenu.

Sinon j'ai noté quelques petites remarques.

Merci !

2023-10-02 20:24 UTC, Michael-cd30 commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +En quelques mois, ce sont plus de 8 millions de photos qui ont ainsi été versé sur ces deux instances.
accord de versé avec photos ou 8 millions donc versées ou versés

2023-10-02 20:24 UTC, Michael-cd30 commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +La visionneuse de référence actuelle est issue de Geovisio, un développement initié entre autre par Géovélo et largement amélioré ces derniers mois pour Panoramax.
ajout d'un hyperlien vers géovélo

2023-10-02 20:24 UTC, Michael-cd30 commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Le premier outil de version proposé par la startup Panoramax a visé les versements en masse de prises de vues existantes. C'est un outil en ligne de commande (écrit en python) qui permet de verser de
version = versement ?
Le cas échéant, je propose de n'écrire que "le premier outil proposé" pour éviter la répétition de versement dans la phrase

2023-10-02 20:24 UTC, Michael-cd30 commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Celui-ci se fait à l'aide d'un modèle de machine-learning qui a été entraîné pour l'occasion, collaborativement. Quelques milliers de photos on été annotées par une vingtaine de contributeurs à l'aid
typo : "onT été annotées" et j'accorderais plutôt avec milliers donc annotés

2023-10-02 20:24 UTC, Michael-cd30 commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Celui-ci se fait à l'aide d'un modèle de machine-learning qui a été entraîné pour l'occasion, collaborativement. Quelques milliers de photos on été annotées par une vingtaine de contributeurs à l'aid
Ajout d'un hyperlien vers label-studio ?

2023-10-02 20:24 UTC, Michael-cd30 commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Celui-ci se fait à l'aide d'un modèle de machine-learning qui a été entraîné pour l'occasion, collaborativement. Quelques milliers de photos on été annotées par une vingtaine de contributeurs à l'aid
Je serais d'avis de couper la dernière phrase en deux.
Quelques milliers de photos on été annotées par une vingtaine de contributeurs à l'aide du logiciel libre label-studio.
Celles-ci ont été utilisées pour entraîner un modèle avec YOLOv8.

2023-10-02 20:24 UTC, Michael-cd30 commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Le floutage a donné de suite des bons résultats sur les photos "planes" mais était un peu décevant sur les photosphères (360°) en partie à cause de leur dimensions. Un changement de paramètre permet
- typo : entraîné
- je trouve étrange l'emploi de "permet" je dirais "donne"
- répétition du mot résultat dans la phrase, remplacer le dernier par "taux de détection" ou "qualité de détection" ?

2023-10-02 20:24 UTC, Michael-cd30 commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Les annotations et le modèle couvrent un troisième type d'objet: les panneaux de signalisation. Ceci a permis de démarrer une expérimentation pour les détecter et les classer automatiquement.
ajouter un espace avant le :

2023-10-02 20:24 UTC, Michael-cd30 commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +## Quelles sont les perspectives de réutilisation?
ajouter un espace avant le ?

2023-10-02 20:24 UTC, Michael-cd30 commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +
Par cohérence, commencer toutes (ou aucunes) les énums par une majuscule

2023-10-03 07:50 UTC, Guts commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +C'était il y a un an... l'IGN répondait à la proposition d'OpenStreetMap France et se lançait dans une phase d'investigation pour la création d'un Street-View libre nommé Panoramax. Aujourd'hui, où e
Une petite vignette avec le logo c'est tjs cympa non ?

```suggestion

![logo Panoramax](https://cdn.geotribu.fr/img/logos-icones/entreprises_association/panoramax.jpg "logo Panoramax"){: .img-rdp-news-thumb }

C'était il y a un an... l'IGN répondait à la proposition d'OpenStreetMap France et se lançait dans une phase d'investigation pour la création d'un Street-View libre nommé Panoramax. Aujourd'hui, où en est-on ?
```

2023-10-03 07:54 UTC, Gab-OPenIG commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +* Une multiplicité d’acteurs tant pour les prises de vues que pour les réutilisations
Mais on peut dire prise**s** de vue quand même vu qu'il y en a 8 millions ?

2023-10-03 07:54 UTC, Gab-OPenIG commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +* 2 instances publiques (IGN + OSM-FR)
- https://panoramax.openstreetmap.fr/#focus=map&map=2.01/12.45/31.69&speed=250
- https://panoramax.ign.fr/#focus=map&map=5.7/47/3&speed=250

2023-10-03 08:11 UTC, Gab-OPenIG commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Le premier outil de version proposé par la startup Panoramax a visé les versements en masse de prises de vues existantes. C'est un outil en ligne de commande (écrit en python) qui permet de verser de
On "apprend" ici que c'est une startup ... j'imagine qu'il s'agît d'une startup d'état (intrapreneur.e.s ?) Si c'est utile  mettre un lien vers la startup, sinon, on peut aussi en rester au projet de géo-commun ?

2023-10-03 08:19 UTC, Gab-OPenIG commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Une API permet de verser des images, de les cataloguer, puis de les rechercher pour une diffusion à destination de différents outils (visionneuse mais pas uniquement). Elle s'appuie sur un espace de
Lien vers l'API / sa documentation / canal du forum ??

2023-10-03 08:19 UTC, Gab-OPenIG commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +La visionneuse de référence actuelle est issue de Geovisio, un développement initié entre autre par Géovélo et largement amélioré ces derniers mois pour Panoramax.
J'aurai pas dit mieux

- https://geovisio.fr/
- https://geovelo.app/fr/

2023-10-03 08:19 UTC, Gab-OPenIG commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Le premier outil de version proposé par la startup Panoramax a visé les versements en masse de prises de vues existantes. C'est un outil en ligne de commande (écrit en python) qui permet de verser de
Ajouter des liens vers les outils de versement ? Premier et second ?

2023-10-03 08:20 UTC, Gab-OPenIG commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Les versements ne sont pas anonymes, un compte utilisateur est nécessaire, pour l'instance OpenStreetMap France, c'est tout simplement le compte OSM qui est utilisé pour s'identifier.
Quelle authentification pour l'instance IGN ?

2023-10-03 08:22 UTC, Gab-OPenIG commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Celui-ci se fait à l'aide d'un modèle de machine-learning qui a été entraîné collaborativement. Pour cela, quelques milliers de photos ont été annotées par une vingtaine de contributeurs à l'aide du
Ajout des liens vers label-studio et YOLOv8 ?

2023-10-03 08:25 UTC, Michael-cd30 commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +* Une multiplicité d’acteurs tant pour les prises de vues que pour les réutilisations
Oui oui, la remarque poste sur le mot "vue"

2023-10-03 08:40 UTC, Gab-OPenIG commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Le floutage a donné de suite de bons résultats sur les photos "planes" mais était un peu décevant sur les photosphères (360°) en partie à cause de leurs dimensions. Un changement de paramètre permet
Peut être expliquer / illustrer brièvement les défauts corrigés ou le paramètre ?

2023-10-03 08:51 UTC, Gab-OPenIG commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +* Usages non routiers : référentiel des rivières (ex. dans le Lot Dordou), chemins de randonnée.
ex. dans le _bassin_ Lot-Dordou ou plutôt : ex. dans le [Lot Lozérien](https://lot-dourdou.fr/nos-cours-deau-en-vues-immersives/) mis en place par le [SMLD](https://lot-dourdou.fr/) 

C'est le nom du syndicat mais c'est aussi comme dire dans la Seine-Marne ou dans l'Adour-Garonne.

2023-10-03 08:53 UTC, Gab-OPenIG commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +* Enseignes publicitaires : détection par les collectivités locales
Ce serait chouette d'avoir les cas d'usage : cela inciterait encore plus à contribuer.

2023-10-03 19:39 UTC, igeofr commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +    - vues immersives
```suggestion
    - Geovisio
    - IGN
    - OpenStreetMap
    - Panoramax
    - vues immersives
```

2023-10-03 19:39 UTC, igeofr commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +C'était il y a un an... l'IGN répondait à la proposition d'OpenStreetMap France et se lançait dans une phase d'investigation pour la création d'un Street-View libre nommé Panoramax. Aujourd'hui, où e
```suggestion
C'était il y a un an... l'[IGN](https://ign.fr) répondait à la proposition d'[OpenStreetMap France](https://www.openstreetmap.fr) et se lançait dans une phase d'investigation pour la création d'un Street-View libre nommé [Panoramax](https://panoramax.fr). Aujourd'hui, où en est-on ?
```

2023-10-03 19:39 UTC, igeofr commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +* 2 instances publiques (IGN + OSM-FR)
```suggestion
* 2 instances publiques ([IGN](https://panoramax.ign.fr) + [OSM-FR](https://panoramax.openstreetmap.fr))
```

2023-10-03 19:39 UTC, igeofr commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +* Plus de 20.000 séquences
Est-ce qu'on a un tableau de bord public qui permet de suivre le versement en temps réel?

2023-10-03 19:39 UTC, igeofr commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +* Un début d’intégration QGIS (avec Oslandia)
```suggestion
* Un début d’intégration [QGIS](https://www.qgis.org/) (avec [Oslandia](https://oslandia.com))
```

2023-10-03 19:39 UTC, igeofr commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +La version bêta actuelle propose les premières briques essentielles que sont l'API et la visionneuse ainsi que deux outils de versement de photos sans oublier le moteur de floutage.
De mémoire, je crois qu'il y a une doc de l'API. Si c'est le cas, je trouverai ça intéressant de le rajouter.

2023-10-03 19:39 UTC, igeofr commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Les versements ne sont pas anonymes, un compte utilisateur est nécessaire, pour l'instance OpenStreetMap France, c'est tout simplement le compte OSM qui est utilisé pour s'identifier.
> Quelle authentification pour l'instance IGN ?

Il faut créer un compte dédié mais ça vaut le coup de le préciser.

2023-10-03 19:39 UTC, igeofr commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Et beaucoup d'autres encore à inventer. À suivre !
```suggestion
Et beaucoup d'autres encore à inventer. À suivre !

[Forum des Géocommuns - Panoramax :fontawesome-solid-comment:](https://forum.geocommuns.fr/c/panoramax/6){: .md-button }
{: align=middle }
```

Permet d'ajouter un bouton qui renvoie vers le forum.

2023-10-03 19:39 UTC, igeofr commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +image: "Image d'illustration de l'article qui sert ensuite dans la mise en avant : réseaux sociaux, flux RSS... 400x800 en PNG"
```suggestion
icon: material/panorama-variant
image: "Image d'illustration de l'article qui sert ensuite dans la mise en avant : réseaux sociaux, flux RSS... 400x800 en PNG"
```

2023-10-03 19:39 UTC, igeofr commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +En quelques mois, ce sont plus de 8 millions de photos qui ont ainsi été versées sur ces deux instances.
```suggestion
En quelques mois, ce sont plus de 8 millions de photos qui ont ainsi été versées sur ces deux instances.

[Instance IGN :fontawesome-solid-image:](https://panoramax.ign.fr/){: .md-button }
[Instance OpenStreetMap :fontawesome-solid-image:](https://panoramax.openstreetmap.fr){: .md-button }
{: align=middle }
```

Permet d'ajouter des boutons.

2023-10-11 12:09 UTC, igeofr commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +La version bêta actuelle propose les premières briques essentielles que sont l'API et la visionneuse ainsi que deux outils de versement de photos sans oublier le moteur de floutage.
Lien vers la doc de l'API : https://panoramax.ign.fr/api/docs/swagger

2023-10-11 14:19 UTC, mferrey commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +* Une multiplicité d’acteurs tant pour les prises de vues que pour les réutilisations
bien vu ;-)

2023-10-11 15:37 UTC, mferrey commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +* Plus de 20.000 séquences
pas encore

2023-10-11 15:43 UTC, mferrey reviewed
revue partielle de l'article suite à vos commentaires

2023-10-11 15:56 UTC, mferrey commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Celui-ci se fait à l'aide d'un modèle de machine-learning qui a été entraîné pour l'occasion, collaborativement. Quelques milliers de photos on été annotées par une vingtaine de contributeurs à l'aid
pas joli joli c'est vrai

2023-10-11 16:10 UTC, mferrey commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Les versements ne sont pas anonymes, un compte utilisateur est nécessaire, pour l'instance OpenStreetMap France, c'est tout simplement le compte OSM qui est utilisé pour s'identifier.
ok

2023-10-11 16:36 UTC, mferrey commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Le floutage a donné de suite de bons résultats sur les photos "planes" mais était un peu décevant sur les photosphères (360°) en partie à cause de leurs dimensions. Un changement de paramètre permet
ce serait bien de donner des détails dans un article complémentaire sur le floutage

2023-10-11 16:44 UTC, mferrey commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +* Usages non routiers : référentiel des rivières (ex. dans le Lot Dordou), chemins de randonnée.
ok merci

2023-10-11 16:44 UTC, mferrey commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +* Enseignes publicitaires : détection par les collectivités locales
trop tôt pour le moment...

2023-10-11 16:46 UTC, mferrey commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +La version bêta actuelle propose les premières briques essentielles que sont l'API et la visionneuse ainsi que deux outils de versement de photos sans oublier le moteur de floutage.
top

2023-10-11 16:53 UTC, mferrey commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Une API permet de verser des images, de les cataloguer, puis de les rechercher pour une diffusion à destination de différents outils (visionneuse mais pas uniquement). Elle s'appuie sur un espace de
fait :-)

2023-10-11 17:03 UTC, mferrey reviewed
syntaxe liens corrigée

2023-10-11 17:11 UTC, mferrey reviewed
coquille espace ? corrigée et 2e lien vers la doc de l'api

2023-10-11 20:15 UTC, Michael-cd30 reviewed
3 bricoles

2023-10-11 20:15 UTC, Michael-cd30 commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +# Panoramax, quel bilan tirer de la phase de construction?
Il faudrait ajouter un espace avant le ? ... oui je sais je suis pénible avec ça.

2023-10-11 20:15 UTC, Michael-cd30 commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +:calendar: Date de publication initiale : 3 octobre 2023
Date de publication à modifier...on a hâte de la voir en ligne !

2023-10-11 20:15 UTC, Michael-cd30 commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +Le premier outil proposé par [la start-up d'état de Panoramax](<https://beta.gouv.fr/startups/vues-immersives-libres.html>) a visé les versements en masse de prises de vue existantes. C'est [un outil
start-up d'État

2023-10-16 09:45 UTC, mferrey reviewed
3 derniers commentaires résolus

2023-10-16 10:42 UTC, Guts commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +license: default
@mferrey @cquest êtes-vous OK avec la licence par défaut ?

https://contribuer.geotribu.fr/guides/licensing/#licence-par-defaut

2023-10-16 10:44 UTC, Guts commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +image: "Image d'illustration de l'article qui sert ensuite dans la mise en avant : réseaux sociaux, flux RSS... 400x800 en PNG"
Il manque l'image d'en-tête : https://contribuer.geotribu.fr/guides/metadata_yaml_frontmatter/. Laquelle voulez-vous utiliser ?

A noter que si le champ est laissé vide, une image est générée automatiquement.

2023-10-16 10:45 UTC, Guts commented on content/articles/2023/2023-10-02_panoramax-bilan-et-nouvelle-etape.md
> +--8<-- "content/team/mfer.md"
```suggestion
## Auteurs

--8<-- "content/team/mfer.md"  
--8<-- "content/team/cque.md"
```

2023-10-16 10:46 UTC, Guts requested changes
Allez @mferrey , on y est presque !

Il faut encore :

- renommer le fichier (faisable depuis l'interface d'édition de GitHub)
- répondre aux questions sur la diffusion dans la description

2023-10-16 14:13 UTC, mferrey commented
@Guts merci pour ton retour. Il me faudrait plus de précisions sur ta question "répondre aux questions sur la diffusion dans la description" (pour le titre, c'est OK)

2023-10-16 14:55 UTC, Guts commented on content/articles/2023/2023-10-02_panoramax-bilan-phase-construction.md
> +    - OpenStreetMap
```suggestion
    - Mapillary
    - OpenStreetMap
```

2023-10-16 15:05 UTC, mferrey commented
![image](https://github.com/geotribu/website/assets/45847618/7a776835-d372-4a43-9111-84c4b7ad4225)

2023-10-16 15:14 UTC, merged